/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  JinRyuu.JRMCore.entity.EntityEnergyAtt
 *  JinRyuu.JRMCore.entity.EntityPrjtls_1
 *  JinRyuu.JRMCore.entity.RenderEnergyAttackKi
 *  JinRyuu.JRMCore.entity.RenderPrjtls_1
 *  cpw.mods.fml.client.registry.ClientRegistry
 *  cpw.mods.fml.client.registry.RenderingRegistry
 *  cpw.mods.fml.common.registry.EntityRegistry
 *  cpw.mods.fml.common.registry.GameRegistry
 *  cpw.mods.fml.relauncher.Side
 *  cpw.mods.fml.relauncher.SideOnly
 *  net.minecraft.client.model.ModelBase
 *  net.minecraft.client.renderer.entity.Render
 *  net.minecraft.client.renderer.tileentity.TileEntitySpecialRenderer
 *  net.minecraft.entity.Entity
 *  net.minecraft.entity.EnumCreatureType
 *  net.minecraft.world.biome.BiomeGenBase
 */
package JinRyuu.DragonBC.common.Npcs;

import JinRyuu.DragonBC.common.DBCConfig;
import JinRyuu.DragonBC.common.Entitys.EntityEnergyFM;
import JinRyuu.DragonBC.common.Entitys.EntityInstantTransmission;
import JinRyuu.DragonBC.common.Entitys.EntityMajinAbsorption;
import JinRyuu.DragonBC.common.Entitys.RenderEnergyFM;
import JinRyuu.DragonBC.common.Entitys.RenderInstantTransmission;
import JinRyuu.DragonBC.common.Entitys.RenderMajinAbsorption;
import JinRyuu.DragonBC.common.Npcs.EntityAngelAwamo;
import JinRyuu.DragonBC.common.Npcs.EntityAngelCamparri;
import JinRyuu.DragonBC.common.Npcs.EntityAngelCognac;
import JinRyuu.DragonBC.common.Npcs.EntityAngelCukatail;
import JinRyuu.DragonBC.common.Npcs.EntityAngelKorn;
import JinRyuu.DragonBC.common.Npcs.EntityAngelKusu;
import JinRyuu.DragonBC.common.Npcs.EntityAngelMarcarita;
import JinRyuu.DragonBC.common.Npcs.EntityAngelMartinu;
import JinRyuu.DragonBC.common.Npcs.EntityAngelMohito;
import JinRyuu.DragonBC.common.Npcs.EntityAngelSour;
import JinRyuu.DragonBC.common.Npcs.EntityAniraza;
import JinRyuu.DragonBC.common.Npcs.EntityAura;
import JinRyuu.DragonBC.common.Npcs.EntityAura2;
import JinRyuu.DragonBC.common.Npcs.EntityAuraLightning;
import JinRyuu.DragonBC.common.Npcs.EntityAuraPur;
import JinRyuu.DragonBC.common.Npcs.EntityAuraRed;
import JinRyuu.DragonBC.common.Npcs.EntityAuraRing;
import JinRyuu.DragonBC.common.Npcs.EntityAuraRingPur;
import JinRyuu.DragonBC.common.Npcs.EntityAuraRingRed;
import JinRyuu.DragonBC.common.Npcs.EntityAuraRingSup;
import JinRyuu.DragonBC.common.Npcs.EntityAuraSup;
import JinRyuu.DragonBC.common.Npcs.EntityBarta;
import JinRyuu.DragonBC.common.Npcs.EntityBasil;
import JinRyuu.DragonBC.common.Npcs.EntityBeerus;
import JinRyuu.DragonBC.common.Npcs.EntityBeerusMonaka;
import JinRyuu.DragonBC.common.Npcs.EntityBeerusMonaka2;
import JinRyuu.DragonBC.common.Npcs.EntityBeerusMonaka3;
import JinRyuu.DragonBC.common.Npcs.EntityBergamo;
import JinRyuu.DragonBC.common.Npcs.EntityBerryblue;
import JinRyuu.DragonBC.common.Npcs.EntityBiarra;
import JinRyuu.DragonBC.common.Npcs.EntityBorareta;
import JinRyuu.DragonBC.common.Npcs.EntityBotamo;
import JinRyuu.DragonBC.common.Npcs.EntityBrianne;
import JinRyuu.DragonBC.common.Npcs.EntityBuuBuffed;
import JinRyuu.DragonBC.common.Npcs.EntityBuuEvil;
import JinRyuu.DragonBC.common.Npcs.EntityBuuFat;
import JinRyuu.DragonBC.common.Npcs.EntityBuuFusion;
import JinRyuu.DragonBC.common.Npcs.EntityBuuKid;
import JinRyuu.DragonBC.common.Npcs.EntityBuuPiccolo;
import JinRyuu.DragonBC.common.Npcs.EntityBuuSuper;
import JinRyuu.DragonBC.common.Npcs.EntityBuuUltimate;
import JinRyuu.DragonBC.common.Npcs.EntityCabba;
import JinRyuu.DragonBC.common.Npcs.EntityCabbaSSJ;
import JinRyuu.DragonBC.common.Npcs.EntityCaulifla;
import JinRyuu.DragonBC.common.Npcs.EntityCaulifla2;
import JinRyuu.DragonBC.common.Npcs.EntityCell1;
import JinRyuu.DragonBC.common.Npcs.EntityCell2;
import JinRyuu.DragonBC.common.Npcs.EntityCell3;
import JinRyuu.DragonBC.common.Npcs.EntityCell4;
import JinRyuu.DragonBC.common.Npcs.EntityCellJr;
import JinRyuu.DragonBC.common.Npcs.EntityChampa;
import JinRyuu.DragonBC.common.Npcs.EntityCocotte;
import JinRyuu.DragonBC.common.Npcs.EntityCyborg16;
import JinRyuu.DragonBC.common.Npcs.EntityCyborg17;
import JinRyuu.DragonBC.common.Npcs.EntityCyborg18;
import JinRyuu.DragonBC.common.Npcs.EntityCyborg19;
import JinRyuu.DragonBC.common.Npcs.EntityCyborg20;
import JinRyuu.DragonBC.common.Npcs.EntityDarbura;
import JinRyuu.DragonBC.common.Npcs.EntityDercori;
import JinRyuu.DragonBC.common.Npcs.EntityDino01;
import JinRyuu.DragonBC.common.Npcs.EntityDino02;
import JinRyuu.DragonBC.common.Npcs.EntityDino03;
import JinRyuu.DragonBC.common.Npcs.EntityDodoria;
import JinRyuu.DragonBC.common.Npcs.EntityDragon;
import JinRyuu.DragonBC.common.Npcs.EntityDragon2;
import JinRyuu.DragonBC.common.Npcs.EntityDyspo;
import JinRyuu.DragonBC.common.Npcs.EntityFreeza1;
import JinRyuu.DragonBC.common.Npcs.EntityFreeza2;
import JinRyuu.DragonBC.common.Npcs.EntityFreeza3;
import JinRyuu.DragonBC.common.Npcs.EntityFreeza4;
import JinRyuu.DragonBC.common.Npcs.EntityFreeza5;
import JinRyuu.DragonBC.common.Npcs.EntityFreeza6;
import JinRyuu.DragonBC.common.Npcs.EntityFreeza7;
import JinRyuu.DragonBC.common.Npcs.EntityFreezaFather;
import JinRyuu.DragonBC.common.Npcs.EntityFreezaMecha;
import JinRyuu.DragonBC.common.Npcs.EntityFreezaSoldier1;
import JinRyuu.DragonBC.common.Npcs.EntityFreezaSoldier2;
import JinRyuu.DragonBC.common.Npcs.EntityFreezaSoldier3;
import JinRyuu.DragonBC.common.Npcs.EntityFrost1;
import JinRyuu.DragonBC.common.Npcs.EntityFrost2;
import JinRyuu.DragonBC.common.Npcs.EntityFrost3;
import JinRyuu.DragonBC.common.Npcs.EntityFrost4;
import JinRyuu.DragonBC.common.Npcs.EntityFrost5;
import JinRyuu.DragonBC.common.Npcs.EntityFrost6;
import JinRyuu.DragonBC.common.Npcs.EntityGanos;
import JinRyuu.DragonBC.common.Npcs.EntityGanos2;
import JinRyuu.DragonBC.common.Npcs.EntityGinyu;
import JinRyuu.DragonBC.common.Npcs.EntityGodArak;
import JinRyuu.DragonBC.common.Npcs.EntityGodBelmod;
import JinRyuu.DragonBC.common.Npcs.EntityGodGiin;
import JinRyuu.DragonBC.common.Npcs.EntityGodHeles;
import JinRyuu.DragonBC.common.Npcs.EntityGodIwan;
import JinRyuu.DragonBC.common.Npcs.EntityGodLiquiir;
import JinRyuu.DragonBC.common.Npcs.EntityGodMosco;
import JinRyuu.DragonBC.common.Npcs.EntityGodQuitela;
import JinRyuu.DragonBC.common.Npcs.EntityGodRumsshi;
import JinRyuu.DragonBC.common.Npcs.EntityGodSidra;
import JinRyuu.DragonBC.common.Npcs.EntityGohan;
import JinRyuu.DragonBC.common.Npcs.EntityGohan2;
import JinRyuu.DragonBC.common.Npcs.EntityGohan_orange;
import JinRyuu.DragonBC.common.Npcs.EntityGohan_orange2;
import JinRyuu.DragonBC.common.Npcs.EntityGoku;
import JinRyuu.DragonBC.common.Npcs.EntityGoku2;
import JinRyuu.DragonBC.common.Npcs.EntityGoku3;
import JinRyuu.DragonBC.common.Npcs.EntityGoku4;
import JinRyuu.DragonBC.common.Npcs.EntityGokuBlack;
import JinRyuu.DragonBC.common.Npcs.EntityGokuBlackRose;
import JinRyuu.DragonBC.common.Npcs.EntityGuldo;
import JinRyuu.DragonBC.common.Npcs.EntityHell01;
import JinRyuu.DragonBC.common.Npcs.EntityHell02;
import JinRyuu.DragonBC.common.Npcs.EntityHit;
import JinRyuu.DragonBC.common.Npcs.EntityHop;
import JinRyuu.DragonBC.common.Npcs.EntityJeice;
import JinRyuu.DragonBC.common.Npcs.EntityJiren;
import JinRyuu.DragonBC.common.Npcs.EntityJiren2;
import JinRyuu.DragonBC.common.Npcs.EntityKahseral;
import JinRyuu.DragonBC.common.Npcs.EntityKakunsa;
import JinRyuu.DragonBC.common.Npcs.EntityKale;
import JinRyuu.DragonBC.common.Npcs.EntityKale2;
import JinRyuu.DragonBC.common.Npcs.EntityKatopesla;
import JinRyuu.DragonBC.common.Npcs.EntityKatopesla2;
import JinRyuu.DragonBC.common.Npcs.EntityKatopesla3;
import JinRyuu.DragonBC.common.Npcs.EntityKatopesla4;
import JinRyuu.DragonBC.common.Npcs.EntityKefla;
import JinRyuu.DragonBC.common.Npcs.EntityKefla2;
import JinRyuu.DragonBC.common.Npcs.EntityKiwi;
import JinRyuu.DragonBC.common.Npcs.EntityKoichiarator;
import JinRyuu.DragonBC.common.Npcs.EntityKoitsukai;
import JinRyuu.DragonBC.common.Npcs.EntityKrillin;
import JinRyuu.DragonBC.common.Npcs.EntityKunshi;
import JinRyuu.DragonBC.common.Npcs.EntityLavender;
import JinRyuu.DragonBC.common.Npcs.EntityMagetta;
import JinRyuu.DragonBC.common.Npcs.EntityMajora;
import JinRyuu.DragonBC.common.Npcs.EntityMasterBabidi;
import JinRyuu.DragonBC.common.Npcs.EntityMasterCell;
import JinRyuu.DragonBC.common.Npcs.EntityMasterEnma;
import JinRyuu.DragonBC.common.Npcs.EntityMasterFreeza;
import JinRyuu.DragonBC.common.Npcs.EntityMasterGohan;
import JinRyuu.DragonBC.common.Npcs.EntityMasterGoku;
import JinRyuu.DragonBC.common.Npcs.EntityMasterGuru;
import JinRyuu.DragonBC.common.Npcs.EntityMasterJin;
import JinRyuu.DragonBC.common.Npcs.EntityMasterKaio;
import JinRyuu.DragonBC.common.Npcs.EntityMasterKami;
import JinRyuu.DragonBC.common.Npcs.EntityMasterKarin;
import JinRyuu.DragonBC.common.Npcs.EntityMasterPiccolo;
import JinRyuu.DragonBC.common.Npcs.EntityMasterRoshi;
import JinRyuu.DragonBC.common.Npcs.EntityMasterTrunksFuture;
import JinRyuu.DragonBC.common.Npcs.EntityMasterVegeta;
import JinRyuu.DragonBC.common.Npcs.EntityMasterWhis;
import JinRyuu.DragonBC.common.Npcs.EntityMonaka;
import JinRyuu.DragonBC.common.Npcs.EntityMurichim;
import JinRyuu.DragonBC.common.Npcs.EntityNamekFrog;
import JinRyuu.DragonBC.common.Npcs.EntityNamekian01;
import JinRyuu.DragonBC.common.Npcs.EntityNamekian03;
import JinRyuu.DragonBC.common.Npcs.EntityNapapa;
import JinRyuu.DragonBC.common.Npcs.EntityNarirama;
import JinRyuu.DragonBC.common.Npcs.EntityObni;
import JinRyuu.DragonBC.common.Npcs.EntityPanchia;
import JinRyuu.DragonBC.common.Npcs.EntityPaparoni;
import JinRyuu.DragonBC.common.Npcs.EntityPiccolo;
import JinRyuu.DragonBC.common.Npcs.EntityPiccolo2;
import JinRyuu.DragonBC.common.Npcs.EntityPorunga;
import JinRyuu.DragonBC.common.Npcs.EntityPorunga2;
import JinRyuu.DragonBC.common.Npcs.EntityPuipui;
import JinRyuu.DragonBC.common.Npcs.EntityRRMecha;
import JinRyuu.DragonBC.common.Npcs.EntityRecoome;
import JinRyuu.DragonBC.common.Npcs.EntityRoasie;
import JinRyuu.DragonBC.common.Npcs.EntityRoshi_super;
import JinRyuu.DragonBC.common.Npcs.EntityRylibeu;
import JinRyuu.DragonBC.common.Npcs.EntitySabertooth;
import JinRyuu.DragonBC.common.Npcs.EntitySaibaiman;
import JinRyuu.DragonBC.common.Npcs.EntitySaiyan01;
import JinRyuu.DragonBC.common.Npcs.EntitySaiyan02;
import JinRyuu.DragonBC.common.Npcs.EntitySaiyanNappa;
import JinRyuu.DragonBC.common.Npcs.EntitySaiyanRaditz;
import JinRyuu.DragonBC.common.Npcs.EntitySaiyanVegeta;
import JinRyuu.DragonBC.common.Npcs.EntityShisami;
import JinRyuu.DragonBC.common.Npcs.EntityShosa;
import JinRyuu.DragonBC.common.Npcs.EntitySorbet;
import JinRyuu.DragonBC.common.Npcs.EntitySorrel;
import JinRyuu.DragonBC.common.Npcs.EntityTagoma;
import JinRyuu.DragonBC.common.Npcs.EntityToppo;
import JinRyuu.DragonBC.common.Npcs.EntityToppo2;
import JinRyuu.DragonBC.common.Npcs.EntityTrunks;
import JinRyuu.DragonBC.common.Npcs.EntityTrunks2;
import JinRyuu.DragonBC.common.Npcs.EntityTrunks_dbs;
import JinRyuu.DragonBC.common.Npcs.EntityTrunks_dbs2;
import JinRyuu.DragonBC.common.Npcs.EntityVados;
import JinRyuu.DragonBC.common.Npcs.EntityVegeta;
import JinRyuu.DragonBC.common.Npcs.EntityVegeta2;
import JinRyuu.DragonBC.common.Npcs.EntityVegeta3;
import JinRyuu.DragonBC.common.Npcs.EntityVegeta4;
import JinRyuu.DragonBC.common.Npcs.EntityVegetaCopy;
import JinRyuu.DragonBC.common.Npcs.EntityVegetaCopyBlue;
import JinRyuu.DragonBC.common.Npcs.EntityWhis;
import JinRyuu.DragonBC.common.Npcs.EntityYakon;
import JinRyuu.DragonBC.common.Npcs.EntityZamasu;
import JinRyuu.DragonBC.common.Npcs.EntityZamasu_Fused;
import JinRyuu.DragonBC.common.Npcs.EntityZamasu_Fused2;
import JinRyuu.DragonBC.common.Npcs.EntityZamasu_Fused3;
import JinRyuu.DragonBC.common.Npcs.EntityZarbon;
import JinRyuu.DragonBC.common.Npcs.EntityZarbon2;
import JinRyuu.DragonBC.common.Npcs.EntityZeno;
import JinRyuu.DragonBC.common.Npcs.ModelAngelAwamo;
import JinRyuu.DragonBC.common.Npcs.ModelAngelCamparri;
import JinRyuu.DragonBC.common.Npcs.ModelAngelCognac;
import JinRyuu.DragonBC.common.Npcs.ModelAngelCukatail;
import JinRyuu.DragonBC.common.Npcs.ModelAngelKorn;
import JinRyuu.DragonBC.common.Npcs.ModelAngelKusu;
import JinRyuu.DragonBC.common.Npcs.ModelAngelMarcarita;
import JinRyuu.DragonBC.common.Npcs.ModelAngelMartinu;
import JinRyuu.DragonBC.common.Npcs.ModelAngelMohito;
import JinRyuu.DragonBC.common.Npcs.ModelAngelSour;
import JinRyuu.DragonBC.common.Npcs.ModelAniraza;
import JinRyuu.DragonBC.common.Npcs.ModelBabidi;
import JinRyuu.DragonBC.common.Npcs.ModelBasil;
import JinRyuu.DragonBC.common.Npcs.ModelBeerus;
import JinRyuu.DragonBC.common.Npcs.ModelBeerusMonaka;
import JinRyuu.DragonBC.common.Npcs.ModelBeerusMonaka2;
import JinRyuu.DragonBC.common.Npcs.ModelBeerusMonaka3;
import JinRyuu.DragonBC.common.Npcs.ModelBergamo;
import JinRyuu.DragonBC.common.Npcs.ModelBerryblue;
import JinRyuu.DragonBC.common.Npcs.ModelBiarra;
import JinRyuu.DragonBC.common.Npcs.ModelBorareta;
import JinRyuu.DragonBC.common.Npcs.ModelBotamo;
import JinRyuu.DragonBC.common.Npcs.ModelBrianne;
import JinRyuu.DragonBC.common.Npcs.ModelBuuEvil;
import JinRyuu.DragonBC.common.Npcs.ModelBuuFat;
import JinRyuu.DragonBC.common.Npcs.ModelBuuKid;
import JinRyuu.DragonBC.common.Npcs.ModelBuuSuper;
import JinRyuu.DragonBC.common.Npcs.ModelBuuSuper_Buffed;
import JinRyuu.DragonBC.common.Npcs.ModelBuuSuper_Fusion;
import JinRyuu.DragonBC.common.Npcs.ModelBuuSuper_Piccolo;
import JinRyuu.DragonBC.common.Npcs.ModelBuuSuper_Ultimate;
import JinRyuu.DragonBC.common.Npcs.ModelCabba;
import JinRyuu.DragonBC.common.Npcs.ModelCaulifla;
import JinRyuu.DragonBC.common.Npcs.ModelCauliflaSSJ;
import JinRyuu.DragonBC.common.Npcs.ModelChampa;
import JinRyuu.DragonBC.common.Npcs.ModelCocotte;
import JinRyuu.DragonBC.common.Npcs.ModelDBCZed;
import JinRyuu.DragonBC.common.Npcs.ModelDercori;
import JinRyuu.DragonBC.common.Npcs.ModelDino01;
import JinRyuu.DragonBC.common.Npcs.ModelDino02;
import JinRyuu.DragonBC.common.Npcs.ModelDino03;
import JinRyuu.DragonBC.common.Npcs.ModelDragon;
import JinRyuu.DragonBC.common.Npcs.ModelDyspo;
import JinRyuu.DragonBC.common.Npcs.ModelEnma;
import JinRyuu.DragonBC.common.Npcs.ModelFr4;
import JinRyuu.DragonBC.common.Npcs.ModelFr6;
import JinRyuu.DragonBC.common.Npcs.ModelFrog;
import JinRyuu.DragonBC.common.Npcs.ModelGanos;
import JinRyuu.DragonBC.common.Npcs.ModelGanos2;
import JinRyuu.DragonBC.common.Npcs.ModelGodArak;
import JinRyuu.DragonBC.common.Npcs.ModelGodBelmod;
import JinRyuu.DragonBC.common.Npcs.ModelGodGiin;
import JinRyuu.DragonBC.common.Npcs.ModelGodHeles;
import JinRyuu.DragonBC.common.Npcs.ModelGodIwan;
import JinRyuu.DragonBC.common.Npcs.ModelGodLiquiir;
import JinRyuu.DragonBC.common.Npcs.ModelGodMosco;
import JinRyuu.DragonBC.common.Npcs.ModelGodQuitela;
import JinRyuu.DragonBC.common.Npcs.ModelGodRumsshi;
import JinRyuu.DragonBC.common.Npcs.ModelGodSidra;
import JinRyuu.DragonBC.common.Npcs.ModelGuru;
import JinRyuu.DragonBC.common.Npcs.ModelHit;
import JinRyuu.DragonBC.common.Npcs.ModelHop;
import JinRyuu.DragonBC.common.Npcs.ModelJiren;
import JinRyuu.DragonBC.common.Npcs.ModelJiren_Full_Power;
import JinRyuu.DragonBC.common.Npcs.ModelKahseral;
import JinRyuu.DragonBC.common.Npcs.ModelKaio;
import JinRyuu.DragonBC.common.Npcs.ModelKakunsa;
import JinRyuu.DragonBC.common.Npcs.ModelKale;
import JinRyuu.DragonBC.common.Npcs.ModelKaleSSJ;
import JinRyuu.DragonBC.common.Npcs.ModelKarin;
import JinRyuu.DragonBC.common.Npcs.ModelKatopesla;
import JinRyuu.DragonBC.common.Npcs.ModelKefla;
import JinRyuu.DragonBC.common.Npcs.ModelKeflaSSJ;
import JinRyuu.DragonBC.common.Npcs.ModelKoichiarator;
import JinRyuu.DragonBC.common.Npcs.ModelKoitsukai;
import JinRyuu.DragonBC.common.Npcs.ModelKrillin;
import JinRyuu.DragonBC.common.Npcs.ModelKunshi;
import JinRyuu.DragonBC.common.Npcs.ModelLavender;
import JinRyuu.DragonBC.common.Npcs.ModelMagetta;
import JinRyuu.DragonBC.common.Npcs.ModelMajora;
import JinRyuu.DragonBC.common.Npcs.ModelMonaka;
import JinRyuu.DragonBC.common.Npcs.ModelMurichim;
import JinRyuu.DragonBC.common.Npcs.ModelNPCNormal;
import JinRyuu.DragonBC.common.Npcs.ModelNapapa;
import JinRyuu.DragonBC.common.Npcs.ModelNarirama;
import JinRyuu.DragonBC.common.Npcs.ModelObni;
import JinRyuu.DragonBC.common.Npcs.ModelPanchia;
import JinRyuu.DragonBC.common.Npcs.ModelPaparoni;
import JinRyuu.DragonBC.common.Npcs.ModelRRMecha;
import JinRyuu.DragonBC.common.Npcs.ModelRaditz;
import JinRyuu.DragonBC.common.Npcs.ModelRaditz2;
import JinRyuu.DragonBC.common.Npcs.ModelRoasie;
import JinRyuu.DragonBC.common.Npcs.ModelRoshi;
import JinRyuu.DragonBC.common.Npcs.ModelRoshi_super;
import JinRyuu.DragonBC.common.Npcs.ModelRylibeu;
import JinRyuu.DragonBC.common.Npcs.ModelSabertooth;
import JinRyuu.DragonBC.common.Npcs.ModelSaibaiman;
import JinRyuu.DragonBC.common.Npcs.ModelShisami;
import JinRyuu.DragonBC.common.Npcs.ModelShosa;
import JinRyuu.DragonBC.common.Npcs.ModelSorbet;
import JinRyuu.DragonBC.common.Npcs.ModelSorrel;
import JinRyuu.DragonBC.common.Npcs.ModelTagoma;
import JinRyuu.DragonBC.common.Npcs.ModelToppo;
import JinRyuu.DragonBC.common.Npcs.ModelToppo_GoD;
import JinRyuu.DragonBC.common.Npcs.ModelVados;
import JinRyuu.DragonBC.common.Npcs.ModelVegeta;
import JinRyuu.DragonBC.common.Npcs.ModelWhis;
import JinRyuu.DragonBC.common.Npcs.ModelYakon;
import JinRyuu.DragonBC.common.Npcs.ModelZamasu;
import JinRyuu.DragonBC.common.Npcs.ModelZamasu_Fused;
import JinRyuu.DragonBC.common.Npcs.ModelZamasu_Fused2;
import JinRyuu.DragonBC.common.Npcs.ModelZeno;
import JinRyuu.DragonBC.common.Npcs.RenderAura;
import JinRyuu.DragonBC.common.Npcs.RenderAura2;
import JinRyuu.DragonBC.common.Npcs.RenderAuraLightning;
import JinRyuu.DragonBC.common.Npcs.RenderAuraPur;
import JinRyuu.DragonBC.common.Npcs.RenderAuraRed;
import JinRyuu.DragonBC.common.Npcs.RenderAuraRing;
import JinRyuu.DragonBC.common.Npcs.RenderAuraRingPur;
import JinRyuu.DragonBC.common.Npcs.RenderAuraRingRed;
import JinRyuu.DragonBC.common.Npcs.RenderAuraRingSup;
import JinRyuu.DragonBC.common.Npcs.RenderAuraSup;
import JinRyuu.DragonBC.common.Npcs.RenderDBC;
import JinRyuu.DragonBC.common.Npcs.RenderPorunga;
import JinRyuu.DragonBC.common.Npcs.RenderPorunga2;
import JinRyuu.DragonBC.common.Npcs.db.EntityBearThief;
import JinRyuu.DragonBC.common.Npcs.db.EntityBora;
import JinRyuu.DragonBC.common.Npcs.db.EntityDBMasterRoshi;
import JinRyuu.DragonBC.common.Npcs.db.EntityDBMasterRoshi2;
import JinRyuu.DragonBC.common.Npcs.db.EntityDBMasterRoshi3;
import JinRyuu.DragonBC.common.Npcs.db.EntityOolong;
import JinRyuu.DragonBC.common.Npcs.db.EntityPuar;
import JinRyuu.DragonBC.common.Npcs.db.EntityTigerBandit;
import JinRyuu.DragonBC.common.Npcs.db.EntityUpa;
import JinRyuu.DragonBC.common.Npcs.db.EntityYajirobe;
import JinRyuu.DragonBC.common.Npcs.db.EntityYamcha;
import JinRyuu.DragonBC.common.Npcs.db.EntityYamcha2;
import JinRyuu.DragonBC.common.Npcs.db.EntityYamcha3;
import JinRyuu.DragonBC.common.Npcs.db.EntityYamcha4;
import JinRyuu.DragonBC.common.Npcs.db.EntityYamcha5;
import JinRyuu.DragonBC.common.Npcs.db.ModelBearThief;
import JinRyuu.DragonBC.common.Npcs.db.ModelBora;
import JinRyuu.DragonBC.common.Npcs.db.ModelMasterRoshi;
import JinRyuu.DragonBC.common.Npcs.db.ModelMasterRoshi2;
import JinRyuu.DragonBC.common.Npcs.db.ModelMasterRoshi3;
import JinRyuu.DragonBC.common.Npcs.db.ModelOolong;
import JinRyuu.DragonBC.common.Npcs.db.ModelPuar;
import JinRyuu.DragonBC.common.Npcs.db.ModelTigerBandit;
import JinRyuu.DragonBC.common.Npcs.db.ModelUpa;
import JinRyuu.DragonBC.common.Npcs.db.ModelYajirobe;
import JinRyuu.DragonBC.common.Npcs.db.ModelYamcha;
import JinRyuu.DragonBC.common.Npcs.db.ModelYamcha2;
import JinRyuu.DragonBC.common.Npcs.dbbaba.EntityDevil;
import JinRyuu.DragonBC.common.Npcs.dbbaba.EntityFortunetellerBaba;
import JinRyuu.DragonBC.common.Npcs.dbbaba.EntityGrandpaGohan;
import JinRyuu.DragonBC.common.Npcs.dbbaba.EntityGrandpaGohan2;
import JinRyuu.DragonBC.common.Npcs.dbbaba.EntityInvisibleMan;
import JinRyuu.DragonBC.common.Npcs.dbbaba.EntityMummy;
import JinRyuu.DragonBC.common.Npcs.dbbaba.EntityVampire;
import JinRyuu.DragonBC.common.Npcs.dbbaba.ModelDevil;
import JinRyuu.DragonBC.common.Npcs.dbbaba.ModelFortunetellerBaba;
import JinRyuu.DragonBC.common.Npcs.dbbaba.ModelGrandpaGohan;
import JinRyuu.DragonBC.common.Npcs.dbbaba.ModelInvisibleMan;
import JinRyuu.DragonBC.common.Npcs.dbbaba.ModelMummy;
import JinRyuu.DragonBC.common.Npcs.dbbaba.ModelVampire;
import JinRyuu.DragonBC.common.Npcs.dbkingpiccolo.EntityCymbal;
import JinRyuu.DragonBC.common.Npcs.dbkingpiccolo.EntityDrum;
import JinRyuu.DragonBC.common.Npcs.dbkingpiccolo.EntityKingPiccolo;
import JinRyuu.DragonBC.common.Npcs.dbkingpiccolo.EntityKingPiccolo2;
import JinRyuu.DragonBC.common.Npcs.dbkingpiccolo.EntityPiano;
import JinRyuu.DragonBC.common.Npcs.dbkingpiccolo.EntityTambourine;
import JinRyuu.DragonBC.common.Npcs.dbkingpiccolo.ModelCymbal;
import JinRyuu.DragonBC.common.Npcs.dbkingpiccolo.ModelDrum;
import JinRyuu.DragonBC.common.Npcs.dbkingpiccolo.ModelKingPiccolo;
import JinRyuu.DragonBC.common.Npcs.dbkingpiccolo.ModelKingPiccolo2;
import JinRyuu.DragonBC.common.Npcs.dbkingpiccolo.ModelPiano;
import JinRyuu.DragonBC.common.Npcs.dbkingpiccolo.ModelTambourine;
import JinRyuu.DragonBC.common.Npcs.dbpilaf.EntityMai;
import JinRyuu.DragonBC.common.Npcs.dbpilaf.EntityMaiMecha;
import JinRyuu.DragonBC.common.Npcs.dbpilaf.EntityPilaf;
import JinRyuu.DragonBC.common.Npcs.dbpilaf.EntityPilafMecha;
import JinRyuu.DragonBC.common.Npcs.dbpilaf.EntityPilafMechaCombined;
import JinRyuu.DragonBC.common.Npcs.dbpilaf.EntityShu;
import JinRyuu.DragonBC.common.Npcs.dbpilaf.EntityShuMecha;
import JinRyuu.DragonBC.common.Npcs.dbpilaf.ModelMai;
import JinRyuu.DragonBC.common.Npcs.dbpilaf.ModelMaiMecha;
import JinRyuu.DragonBC.common.Npcs.dbpilaf.ModelPilaf;
import JinRyuu.DragonBC.common.Npcs.dbpilaf.ModelPilafMecha;
import JinRyuu.DragonBC.common.Npcs.dbpilaf.ModelPilafMechaCombined;
import JinRyuu.DragonBC.common.Npcs.dbpilaf.ModelShu;
import JinRyuu.DragonBC.common.Npcs.dbpilaf.ModelShuMecha;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityAndroid8;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityBuyon;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityColonelSilver;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityColonelViolet;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityCommanderRed;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityGeneralBlue;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityGeneralBlue2;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityGeneralWhite;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityGeneralWhite2;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityLaunch;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityLaunch2;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityMajorMetallitron;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityMajorMetallitron1;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityMajorMetallitron2;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityMajorMetallitron3;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityMercenaryTao;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityMercenaryTao2;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityMercenaryTao3;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityNinjaMurasaki;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityOfficerBlack;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityOfficerBlack2;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityOfficerBlack3;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityRedRibbonSoldier;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityRedRibbonSoldier2;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityRedRibbonSoldier3;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityRedRibbonSoldierB;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityRedRibbonSoldierB2;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.EntityRedRibbonSoldierB3;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.ModelAndroid8;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.ModelBuyon;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.ModelColonelSilver;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.ModelColonelViolet;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.ModelCommanderRed;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.ModelGeneralBlue;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.ModelGeneralWhite;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.ModelLaunch;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.ModelMajorMetallitron;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.ModelMercenaryTao;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.ModelMercenaryTao2;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.ModelNinjaMurasaki;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.ModelOfficerBlack;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.ModelOfficerBlack2;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.ModelRedRibbonSoldierBazooka;
import JinRyuu.DragonBC.common.Npcs.dbredribbon.ModelRedRibbonSoldierGunner;
import JinRyuu.DragonBC.common.Npcs.dbsbroly.EntityCheelai;
import JinRyuu.DragonBC.common.Npcs.dbsbroly.EntityCheelai2;
import JinRyuu.DragonBC.common.Npcs.dbsbroly.EntityDBSBroly1;
import JinRyuu.DragonBC.common.Npcs.dbsbroly.EntityDBSBroly2;
import JinRyuu.DragonBC.common.Npcs.dbsbroly.EntityDBSBroly3;
import JinRyuu.DragonBC.common.Npcs.dbsbroly.EntityDBSBroly4;
import JinRyuu.DragonBC.common.Npcs.dbsbroly.EntityDBSBrolyBuff;
import JinRyuu.DragonBC.common.Npcs.dbsbroly.EntityDBSBrolyBuffSSJ;
import JinRyuu.DragonBC.common.Npcs.dbsbroly.EntityDBSBrolyLegendary;
import JinRyuu.DragonBC.common.Npcs.dbsbroly.EntityDBSParagus;
import JinRyuu.DragonBC.common.Npcs.dbsbroly.EntityDBSParagus2;
import JinRyuu.DragonBC.common.Npcs.dbsbroly.EntityLemo;
import JinRyuu.DragonBC.common.Npcs.dbsbroly.ModelCheelai;
import JinRyuu.DragonBC.common.Npcs.dbsbroly.ModelDBSBrolyBuff;
import JinRyuu.DragonBC.common.Npcs.dbsbroly.ModelDBSBrolyLegendary;
import JinRyuu.DragonBC.common.Npcs.dbsbroly.ModelDBSBrolyNormal;
import JinRyuu.DragonBC.common.Npcs.dbsbroly.ModelDBSParagus;
import JinRyuu.DragonBC.common.Npcs.dbsbroly.ModelDBSParagus2;
import JinRyuu.DragonBC.common.Npcs.dbsbroly.ModelLemo;
import JinRyuu.DragonBC.common.Npcs.dbtournament.EntityBacterian;
import JinRyuu.DragonBC.common.Npcs.dbtournament.EntityChiaotzu;
import JinRyuu.DragonBC.common.Npcs.dbtournament.EntityChiaotzu2;
import JinRyuu.DragonBC.common.Npcs.dbtournament.EntityChiaotzu3;
import JinRyuu.DragonBC.common.Npcs.dbtournament.EntityChiaotzu4;
import JinRyuu.DragonBC.common.Npcs.dbtournament.EntityGiran;
import JinRyuu.DragonBC.common.Npcs.dbtournament.EntityJackieChun;
import JinRyuu.DragonBC.common.Npcs.dbtournament.EntityJackieChun2;
import JinRyuu.DragonBC.common.Npcs.dbtournament.EntityJackieChun3;
import JinRyuu.DragonBC.common.Npcs.dbtournament.EntityKingChappa;
import JinRyuu.DragonBC.common.Npcs.dbtournament.EntityManWolf;
import JinRyuu.DragonBC.common.Npcs.dbtournament.EntityMasterShen;
import JinRyuu.DragonBC.common.Npcs.dbtournament.EntityNam;
import JinRyuu.DragonBC.common.Npcs.dbtournament.EntityPamput;
import JinRyuu.DragonBC.common.Npcs.dbtournament.EntityTien;
import JinRyuu.DragonBC.common.Npcs.dbtournament.EntityTien2;
import JinRyuu.DragonBC.common.Npcs.dbtournament.EntityTien3;
import JinRyuu.DragonBC.common.Npcs.dbtournament.EntityTien4;
import JinRyuu.DragonBC.common.Npcs.dbtournament.EntityTien5;
import JinRyuu.DragonBC.common.Npcs.dbtournament.EntityTien6;
import JinRyuu.DragonBC.common.Npcs.dbtournament.EntityTien7;
import JinRyuu.DragonBC.common.Npcs.dbtournament.EntityTournamentAnnouncer;
import JinRyuu.DragonBC.common.Npcs.dbtournament.ModelBacterian;
import JinRyuu.DragonBC.common.Npcs.dbtournament.ModelChiaotzu;
import JinRyuu.DragonBC.common.Npcs.dbtournament.ModelChiaotzu2;
import JinRyuu.DragonBC.common.Npcs.dbtournament.ModelGiran;
import JinRyuu.DragonBC.common.Npcs.dbtournament.ModelJackieChun;
import JinRyuu.DragonBC.common.Npcs.dbtournament.ModelJackieChun2;
import JinRyuu.DragonBC.common.Npcs.dbtournament.ModelJackieChun3;
import JinRyuu.DragonBC.common.Npcs.dbtournament.ModelKingChappa;
import JinRyuu.DragonBC.common.Npcs.dbtournament.ModelManWolf;
import JinRyuu.DragonBC.common.Npcs.dbtournament.ModelMasterShen;
import JinRyuu.DragonBC.common.Npcs.dbtournament.ModelNam;
import JinRyuu.DragonBC.common.Npcs.dbtournament.ModelPamput;
import JinRyuu.DragonBC.common.Npcs.dbtournament.ModelTien;
import JinRyuu.DragonBC.common.Npcs.dbtournament.ModelTien2;
import JinRyuu.DragonBC.common.Npcs.dbtournament.ModelTournamentAnnouncer;
import JinRyuu.DragonBC.common.Npcs.dbz.EntityOfficeOgre;
import JinRyuu.DragonBC.common.Npcs.dbz.EntityOfficeOgre2;
import JinRyuu.DragonBC.common.Npcs.dbz.EntityOfficeOgre3;
import JinRyuu.DragonBC.common.Npcs.dbz.EntityOfficeOgre4;
import JinRyuu.DragonBC.common.Npcs.dbz.EntityOfficeOgre5;
import JinRyuu.DragonBC.common.Npcs.dbz.EntitySpirit;
import JinRyuu.DragonBC.common.Npcs.dbz.ModelOfficeOgre;
import JinRyuu.DragonBC.common.Npcs.dbz.ModelOfficeOgre2;
import JinRyuu.DragonBC.common.Npcs.dbz.ModelSpirit;
import JinRyuu.DragonBC.common.Render.ArtGravDevRender;
import JinRyuu.DragonBC.common.Render.ArtGravDevTileEntity;
import JinRyuu.DragonBC.common.Render.DragonBlock01Render;
import JinRyuu.DragonBC.common.Render.DragonBlock01TileEntity;
import JinRyuu.DragonBC.common.Render.DragonBlockNS01Render;
import JinRyuu.DragonBC.common.Render.DragonBlockNS01TileEntity;
import JinRyuu.DragonBC.common.Render.DragonBlockNamek01Render;
import JinRyuu.DragonBC.common.Render.DragonBlockNamek01TileEntity;
import JinRyuu.DragonBC.common.Render.DragonBlockS01Render;
import JinRyuu.DragonBC.common.Render.DragonBlockS01TileEntity;
import JinRyuu.DragonBC.common.Render.KintounBlackEntity;
import JinRyuu.DragonBC.common.Render.KintounEntity;
import JinRyuu.DragonBC.common.Render.KintounRender;
import JinRyuu.DragonBC.common.Render.MedPodDoor1Render;
import JinRyuu.DragonBC.common.Render.MedPodDoor1TileEntity;
import JinRyuu.DragonBC.common.Render.SaibaiHatchedRender;
import JinRyuu.DragonBC.common.Render.SaibaiHatchedTileEntity;
import JinRyuu.DragonBC.common.Render.SpacePod01Entity;
import JinRyuu.DragonBC.common.Render.SpacePod01Render;
import JinRyuu.DragonBC.common.Render.SpacePod01RenderPod;
import JinRyuu.DragonBC.common.Render.SpacePod01TileEntity;
import JinRyuu.DragonBC.common.Render.block01dbcEntity;
import JinRyuu.DragonBC.common.Render.block01dbcRender;
import JinRyuu.DragonBC.common.Render.namekian_throneRender;
import JinRyuu.DragonBC.common.Render.namekian_throneTileEntity;
import JinRyuu.DragonBC.common.Render.ppRender;
import JinRyuu.DragonBC.common.Render.ppTileEntity;
import JinRyuu.DragonBC.common.mod_DragonBC;
import JinRyuu.JRMCore.entity.EntityEnergyAtt;
import JinRyuu.JRMCore.entity.EntityPrjtls_1;
import JinRyuu.JRMCore.entity.RenderEnergyAttackKi;
import JinRyuu.JRMCore.entity.RenderPrjtls_1;
import cpw.mods.fml.client.registry.ClientRegistry;
import cpw.mods.fml.client.registry.RenderingRegistry;
import cpw.mods.fml.common.registry.EntityRegistry;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.renderer.entity.Render;
import net.minecraft.client.renderer.tileentity.TileEntitySpecialRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EnumCreatureType;
import net.minecraft.world.biome.BiomeGenBase;

public final class EntitiesDBC {
    public static int renderId = 100;
    public static int entityID = 0;

    public static int nextEntityID() {
        return ++entityID;
    }

    public static void addEntityClient(Class<? extends Entity> entityClass, Render renderer) {
        RenderingRegistry.registerEntityRenderingHandler(entityClass, (Render)renderer);
    }

    public static void addEntityServer(Class<? extends Entity> entityClass, String entityName) {
        EntitiesDBC.addEntityServer(entityClass, entityName, 80, 5);
    }

    public static void addEntityServer(Class<? extends Entity> entityClass, String entityName, int updateFrequency) {
        EntitiesDBC.addEntityServer(entityClass, entityName, 80, updateFrequency, true);
    }

    public static void addEntityServer(Class<? extends Entity> entityClass, String entityName, int trackingRange, int updateFrequency) {
        EntitiesDBC.addEntityServer(entityClass, entityName, trackingRange, updateFrequency, true);
    }

    public static void addEntityServer(Class<? extends Entity> entityClass, String entityName, int trackingRange, int updateFrequency, boolean sendsVelocityUpdates) {
        EntityRegistry.registerModEntity(entityClass, (String)entityName, (int)EntitiesDBC.nextEntityID(), (Object)mod_DragonBC.instance, (int)trackingRange, (int)updateFrequency, (boolean)sendsVelocityUpdates);
    }

    @SideOnly(value=Side.CLIENT)
    public static void client() {
        EntitiesDBC.addEntityClient(EntityEnergyAtt.class, (Render)new RenderEnergyAttackKi());
        EntitiesDBC.addEntityClient(EntityEnergyFM.class, (Render)new RenderEnergyFM());
        EntitiesDBC.addEntityClient(EntityPrjtls_1.class, (Render)new RenderPrjtls_1());
        EntitiesDBC.addEntityClient(SpacePod01Entity.class, new SpacePod01RenderPod());
        EntitiesDBC.addEntityClient(KintounEntity.class, new KintounRender(0));
        EntitiesDBC.addEntityClient(KintounBlackEntity.class, new KintounRender(1));
        EntitiesDBC.addEntityClient(EntityAuraRed.class, (Render)new RenderAuraRed());
        EntitiesDBC.addEntityClient(EntityAuraSup.class, (Render)new RenderAuraSup());
        EntitiesDBC.addEntityClient(EntityAuraPur.class, (Render)new RenderAuraPur());
        EntitiesDBC.addEntityClient(EntityPorunga.class, (Render)new RenderPorunga());
        EntitiesDBC.addEntityClient(EntityPorunga2.class, (Render)new RenderPorunga2());
        EntitiesDBC.addEntityClient(EntityDragon2.class, (Render)new RenderDBC(new ModelDragon(), 0.5f));
        EntitiesDBC.addEntityClient(EntityDragon.class, (Render)new RenderDBC(new ModelDragon(), 0.5f));
        EntitiesDBC.addEntityClient(EntityAura.class, (Render)new RenderAura());
        EntitiesDBC.addEntityClient(EntityAuraRing.class, (Render)new RenderAuraRing());
        EntitiesDBC.addEntityClient(EntityAuraRingSup.class, (Render)new RenderAuraRingSup());
        EntitiesDBC.addEntityClient(EntityAuraRingPur.class, (Render)new RenderAuraRingPur());
        EntitiesDBC.addEntityClient(EntityAuraRingRed.class, (Render)new RenderAuraRingRed());
        EntitiesDBC.addEntityClient(EntityAuraLightning.class, (Render)new RenderAuraLightning());
        EntitiesDBC.addEntityClient(EntityAura2.class, (Render)new RenderAura2());
        EntitiesDBC.addEntityClient(EntityHell01.class, (Render)new RenderDBC((ModelBase)new ModelNPCNormal(), 0.5f));
        EntitiesDBC.addEntityClient(EntityHell02.class, (Render)new RenderDBC((ModelBase)new ModelNPCNormal(), 0.5f));
        EntitiesDBC.addEntityClient(EntityMasterEnma.class, (Render)new RenderDBC(new ModelEnma(), 0.5f));
        EntitiesDBC.addEntityClient(EntityMasterKami.class, (Render)new RenderDBC((ModelBase)new ModelNPCNormal(), 0.5f));
        EntitiesDBC.addEntityClient(EntityMasterKaio.class, (Render)new RenderDBC(new ModelKaio(), 0.5f));
        EntitiesDBC.addEntityClient(EntityMasterKarin.class, (Render)new RenderDBC((ModelBase)new ModelKarin(), 0.5f));
        EntitiesDBC.addEntityClient(EntityMasterRoshi.class, (Render)new RenderDBC((ModelBase)new ModelRoshi(1.0f), 0.5f));
        EntitiesDBC.addEntityClient(EntityMasterCell.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityMasterGoku.class, (Render)new RenderDBC((ModelBase)new ModelDBCZed(0), 0.5f));
        EntitiesDBC.addEntityClient(EntityMasterGohan.class, (Render)new RenderDBC((ModelBase)new ModelDBCZed(1), 0.5f));
        EntitiesDBC.addEntityClient(EntityMasterTrunksFuture.class, (Render)new RenderDBC((ModelBase)new ModelDBCZed(2), 0.5f));
        EntitiesDBC.addEntityClient(EntityMasterFreeza.class, (Render)new RenderDBC((ModelBase)new ModelFr4(), 0.5f));
        EntitiesDBC.addEntityClient(EntityMasterJin.class, (Render)new RenderDBC((ModelBase)new ModelDBCZed(2), 0.5f));
        EntitiesDBC.addEntityClient(EntityMasterGuru.class, (Render)new RenderDBC(new ModelGuru(), 0.5f));
        EntitiesDBC.addEntityClient(EntityMasterWhis.class, (Render)new RenderDBC(new ModelWhis(), 0.5f));
        EntitiesDBC.addEntityClient(EntityNamekian01.class, (Render)new RenderDBC((ModelBase)new ModelNPCNormal(), 0.5f));
        EntitiesDBC.addEntityClient(EntityNamekian03.class, (Render)new RenderDBC((ModelBase)new ModelNPCNormal(), 0.5f));
        EntitiesDBC.addEntityClient(EntitySaiyan01.class, (Render)new RenderDBC((ModelBase)new ModelNPCNormal(), 0.5f));
        EntitiesDBC.addEntityClient(EntitySaiyan02.class, (Render)new RenderDBC((ModelBase)new ModelNPCNormal(), 0.5f));
        EntitiesDBC.addEntityClient(EntitySaibaiman.class, (Render)new RenderDBC((ModelBase)new ModelSaibaiman(), 0.5f));
        EntitiesDBC.addEntityClient(EntitySaiyanRaditz.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntitySaiyanNappa.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntitySaiyanVegeta.class, (Render)new RenderDBC((ModelBase)new ModelVegeta(), 0.5f));
        EntitiesDBC.addEntityClient(EntityDino01.class, (Render)new RenderDBC(new ModelDino01(), 0.5f));
        EntitiesDBC.addEntityClient(EntityDino02.class, (Render)new RenderDBC(new ModelDino02(), 0.5f));
        EntitiesDBC.addEntityClient(EntityDino03.class, (Render)new RenderDBC(new ModelDino03(), 0.5f));
        EntitiesDBC.addEntityClient(EntityRRMecha.class, (Render)new RenderDBC(new ModelRRMecha(), 0.5f));
        EntitiesDBC.addEntityClient(EntitySabertooth.class, (Render)new RenderDBC(new ModelSabertooth(), 0.5f));
        EntitiesDBC.addEntityClient(EntityKiwi.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityDodoria.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityZarbon.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityGuldo.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(0.6f, false, true), 0.5f));
        EntitiesDBC.addEntityClient(EntityRecoome.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityBarta.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityJeice.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityGinyu.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityFreezaSoldier1.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityFreezaSoldier2.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityFreezaSoldier3.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityFreeza1.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityFreeza2.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(1.25f), 0.5f));
        EntitiesDBC.addEntityClient(EntityFreeza3.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(1.25f), 0.5f));
        EntitiesDBC.addEntityClient(EntityFreeza4.class, (Render)new RenderDBC((ModelBase)new ModelFr4(), 0.5f));
        EntitiesDBC.addEntityClient(EntityFreeza5.class, (Render)new RenderDBC((ModelBase)new ModelFr4(), 0.5f));
        EntitiesDBC.addEntityClient(EntityFreeza6.class, (Render)new RenderDBC((ModelBase)new ModelFr6(), 0.5f));
        EntitiesDBC.addEntityClient(EntityPuipui.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityYakon.class, (Render)new RenderDBC((ModelBase)new ModelYakon(2.0f), 0.5f));
        EntitiesDBC.addEntityClient(EntityDarbura.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityBuuFat.class, (Render)new RenderDBC((ModelBase)new ModelBuuFat(), 0.5f));
        EntitiesDBC.addEntityClient(EntityBuuSuper.class, (Render)new RenderDBC(new ModelBuuSuper(), 0.5f));
        EntitiesDBC.addEntityClient(EntityMasterBabidi.class, (Render)new RenderDBC((ModelBase)new ModelBabidi(), 0.5f));
        EntitiesDBC.addEntityClient(EntityBeerus.class, (Render)new RenderDBC(new ModelBeerus(), 0.5f));
        EntitiesDBC.addEntityClient(EntityFreezaFather.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(2.0f), 0.5f));
        EntitiesDBC.addEntityClient(EntityFreezaMecha.class, (Render)new RenderDBC((ModelBase)new ModelFr4(), 0.5f));
        EntitiesDBC.addEntityClient(EntityCyborg16.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityCyborg17.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityCyborg18.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityCyborg19.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityCyborg20.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityCell1.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityCell2.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityCell3.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityCell4.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityMasterPiccolo.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityMasterVegeta.class, (Render)new RenderDBC((ModelBase)new ModelDBCZed(3), 0.5f));
        EntitiesDBC.addEntityClient(EntityFreeza7.class, (Render)new RenderDBC((ModelBase)new ModelFr4(), 0.5f));
        EntitiesDBC.addEntityClient(EntityZarbon2.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityNamekFrog.class, (Render)new RenderDBC(new ModelFrog(), 0.5f));
        EntitiesDBC.addEntityClient(EntityCellJr.class, (Render)new RenderDBC((ModelBase)new ModelRaditz2(0.8f, true), 0.5f));
        EntitiesDBC.addEntityClient(EntityBuuEvil.class, (Render)new RenderDBC(new ModelBuuEvil(), 0.5f));
        EntitiesDBC.addEntityClient(EntityBuuFusion.class, (Render)new RenderDBC(new ModelBuuSuper_Fusion(), 0.5f));
        EntitiesDBC.addEntityClient(EntityBuuPiccolo.class, (Render)new RenderDBC(new ModelBuuSuper_Piccolo(), 0.5f));
        EntitiesDBC.addEntityClient(EntityBuuUltimate.class, (Render)new RenderDBC(new ModelBuuSuper_Ultimate(), 0.5f));
        EntitiesDBC.addEntityClient(EntityBuuBuffed.class, (Render)new RenderDBC(new ModelBuuSuper_Buffed(), 0.5f));
        EntitiesDBC.addEntityClient(EntityBuuKid.class, (Render)new RenderDBC(new ModelBuuKid(), 0.5f));
        EntitiesDBC.addEntityClient(EntityBeerusMonaka.class, (Render)new RenderDBC(new ModelBeerusMonaka(), 0.5f));
        EntitiesDBC.addEntityClient(EntityBeerusMonaka2.class, (Render)new RenderDBC(new ModelBeerusMonaka2(), 0.5f));
        EntitiesDBC.addEntityClient(EntityBeerusMonaka3.class, (Render)new RenderDBC(new ModelBeerusMonaka3(), 0.5f));
        EntitiesDBC.addEntityClient(EntityBerryblue.class, (Render)new RenderDBC(new ModelBerryblue(), 0.5f));
        EntitiesDBC.addEntityClient(EntityBotamo.class, (Render)new RenderDBC(new ModelBotamo(), 0.5f));
        EntitiesDBC.addEntityClient(EntityChampa.class, (Render)new RenderDBC(new ModelChampa(), 0.5f));
        EntitiesDBC.addEntityClient(EntityFrost1.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityFrost2.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(1.25f), 0.5f));
        EntitiesDBC.addEntityClient(EntityFrost3.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(1.25f), 0.5f));
        EntitiesDBC.addEntityClient(EntityFrost4.class, (Render)new RenderDBC((ModelBase)new ModelFr4(), 0.5f));
        EntitiesDBC.addEntityClient(EntityFrost5.class, (Render)new RenderDBC((ModelBase)new ModelFr4(), 0.5f));
        EntitiesDBC.addEntityClient(EntityFrost6.class, (Render)new RenderDBC((ModelBase)new ModelFr6(), 0.5f));
        EntitiesDBC.addEntityClient(EntityHit.class, (Render)new RenderDBC(new ModelHit(), 0.5f));
        EntitiesDBC.addEntityClient(EntityKrillin.class, (Render)new RenderDBC(new ModelKrillin(), 0.5f));
        EntitiesDBC.addEntityClient(EntityMagetta.class, (Render)new RenderDBC(new ModelMagetta(), 0.5f));
        EntitiesDBC.addEntityClient(EntityMonaka.class, (Render)new RenderDBC(new ModelMonaka(), 0.5f));
        EntitiesDBC.addEntityClient(EntityRoshi_super.class, (Render)new RenderDBC(new ModelRoshi_super(), 0.5f));
        EntitiesDBC.addEntityClient(EntityShisami.class, (Render)new RenderDBC(new ModelShisami(), 0.5f));
        EntitiesDBC.addEntityClient(EntitySorbet.class, (Render)new RenderDBC(new ModelSorbet(), 0.5f));
        EntitiesDBC.addEntityClient(EntityTagoma.class, (Render)new RenderDBC(new ModelTagoma(), 0.5f));
        EntitiesDBC.addEntityClient(EntityVados.class, (Render)new RenderDBC(new ModelVados(), 0.5f));
        EntitiesDBC.addEntityClient(EntityWhis.class, (Render)new RenderDBC(new ModelWhis(), 0.5f));
        EntitiesDBC.addEntityClient(EntityGokuBlack.class, (Render)new RenderDBC((ModelBase)new ModelDBCZed(0), 0.5f));
        EntitiesDBC.addEntityClient(EntityGokuBlackRose.class, (Render)new RenderDBC((ModelBase)new ModelDBCZed(4), 0.5f));
        EntitiesDBC.addEntityClient(EntityVegetaCopy.class, (Render)new RenderDBC((ModelBase)new ModelDBCZed(3), 0.5f));
        EntitiesDBC.addEntityClient(EntityVegetaCopyBlue.class, (Render)new RenderDBC((ModelBase)new ModelDBCZed(3), 0.5f));
        EntitiesDBC.addEntityClient(EntityCabba.class, (Render)new RenderDBC(new ModelCabba(), 0.5f));
        EntitiesDBC.addEntityClient(EntityCabbaSSJ.class, (Render)new RenderDBC(new ModelCabba(), 0.5f));
        EntitiesDBC.addEntityClient(EntityZamasu.class, (Render)new RenderDBC(new ModelZamasu(), 0.5f));
        EntitiesDBC.addEntityClient(EntityZamasu_Fused.class, (Render)new RenderDBC(new ModelZamasu_Fused(), 0.5f));
        EntitiesDBC.addEntityClient(EntityZamasu_Fused2.class, (Render)new RenderDBC(new ModelZamasu_Fused2(), 0.5f));
        EntitiesDBC.addEntityClient(EntityZamasu_Fused3.class, (Render)new RenderDBC(new ModelZamasu_Fused2(1.35f), 0.5f));
        EntitiesDBC.addEntityClient(EntityZeno.class, (Render)new RenderDBC(new ModelZeno(), 0.5f));
        EntitiesDBC.addEntityClient(EntityGoku.class, (Render)new RenderDBC((ModelBase)new ModelDBCZed(0), 0.5f));
        EntitiesDBC.addEntityClient(EntityGoku2.class, (Render)new RenderDBC((ModelBase)new ModelDBCZed(4), 0.5f));
        EntitiesDBC.addEntityClient(EntityGoku3.class, (Render)new RenderDBC((ModelBase)new ModelDBCZed(0), 0.5f));
        EntitiesDBC.addEntityClient(EntityGoku4.class, (Render)new RenderDBC((ModelBase)new ModelDBCZed(4), 0.5f));
        EntitiesDBC.addEntityClient(EntityVegeta.class, (Render)new RenderDBC((ModelBase)new ModelDBCZed(3), 0.5f));
        EntitiesDBC.addEntityClient(EntityVegeta2.class, (Render)new RenderDBC((ModelBase)new ModelDBCZed(3), 0.5f));
        EntitiesDBC.addEntityClient(EntityVegeta3.class, (Render)new RenderDBC((ModelBase)new ModelDBCZed(3), 0.5f));
        EntitiesDBC.addEntityClient(EntityVegeta4.class, (Render)new RenderDBC((ModelBase)new ModelDBCZed(3), 0.5f));
        EntitiesDBC.addEntityClient(EntityGohan.class, (Render)new RenderDBC((ModelBase)new ModelDBCZed(1), 0.5f));
        EntitiesDBC.addEntityClient(EntityGohan2.class, (Render)new RenderDBC((ModelBase)new ModelDBCZed(1), 0.5f));
        EntitiesDBC.addEntityClient(EntityGohan_orange.class, (Render)new RenderDBC((ModelBase)new ModelDBCZed(1), 0.5f));
        EntitiesDBC.addEntityClient(EntityGohan_orange2.class, (Render)new RenderDBC((ModelBase)new ModelDBCZed(1), 0.5f));
        EntitiesDBC.addEntityClient(EntityTrunks.class, (Render)new RenderDBC((ModelBase)new ModelDBCZed(2), 0.5f));
        EntitiesDBC.addEntityClient(EntityTrunks2.class, (Render)new RenderDBC((ModelBase)new ModelDBCZed(5), 0.5f));
        EntitiesDBC.addEntityClient(EntityTrunks_dbs.class, (Render)new RenderDBC((ModelBase)new ModelDBCZed(2), 0.5f));
        EntitiesDBC.addEntityClient(EntityTrunks_dbs2.class, (Render)new RenderDBC((ModelBase)new ModelDBCZed(5), 0.5f));
        EntitiesDBC.addEntityClient(EntityAngelAwamo.class, (Render)new RenderDBC(new ModelAngelAwamo(), 0.5f));
        EntitiesDBC.addEntityClient(EntityAngelCamparri.class, (Render)new RenderDBC(new ModelAngelCamparri(), 0.5f));
        EntitiesDBC.addEntityClient(EntityAngelCognac.class, (Render)new RenderDBC(new ModelAngelCognac(), 0.5f));
        EntitiesDBC.addEntityClient(EntityAngelCukatail.class, (Render)new RenderDBC(new ModelAngelCukatail(), 0.5f));
        EntitiesDBC.addEntityClient(EntityAngelKorn.class, (Render)new RenderDBC(new ModelAngelKorn(), 0.5f));
        EntitiesDBC.addEntityClient(EntityAngelKusu.class, (Render)new RenderDBC(new ModelAngelKusu(), 0.5f));
        EntitiesDBC.addEntityClient(EntityAngelMarcarita.class, (Render)new RenderDBC(new ModelAngelMarcarita(), 0.5f));
        EntitiesDBC.addEntityClient(EntityAngelMartinu.class, (Render)new RenderDBC(new ModelAngelMartinu(), 0.5f));
        EntitiesDBC.addEntityClient(EntityAngelMohito.class, (Render)new RenderDBC(new ModelAngelMohito(), 0.5f));
        EntitiesDBC.addEntityClient(EntityAngelSour.class, (Render)new RenderDBC(new ModelAngelSour(), 0.5f));
        EntitiesDBC.addEntityClient(EntityGodArak.class, (Render)new RenderDBC(new ModelGodArak(), 0.5f));
        EntitiesDBC.addEntityClient(EntityGodBelmod.class, (Render)new RenderDBC(new ModelGodBelmod(), 0.5f));
        EntitiesDBC.addEntityClient(EntityGodGiin.class, (Render)new RenderDBC(new ModelGodGiin(), 0.5f));
        EntitiesDBC.addEntityClient(EntityGodHeles.class, (Render)new RenderDBC(new ModelGodHeles(), 0.5f));
        EntitiesDBC.addEntityClient(EntityGodIwan.class, (Render)new RenderDBC(new ModelGodIwan(), 0.5f));
        EntitiesDBC.addEntityClient(EntityGodLiquiir.class, (Render)new RenderDBC(new ModelGodLiquiir(), 0.5f));
        EntitiesDBC.addEntityClient(EntityGodMosco.class, (Render)new RenderDBC(new ModelGodMosco(), 0.5f));
        EntitiesDBC.addEntityClient(EntityGodQuitela.class, (Render)new RenderDBC(new ModelGodQuitela(), 0.5f));
        EntitiesDBC.addEntityClient(EntityGodRumsshi.class, (Render)new RenderDBC(new ModelGodRumsshi(), 0.5f));
        EntitiesDBC.addEntityClient(EntityGodSidra.class, (Render)new RenderDBC(new ModelGodSidra(), 0.5f));
        EntitiesDBC.addEntityClient(EntityBasil.class, (Render)new RenderDBC(new ModelBasil(), 0.5f));
        EntitiesDBC.addEntityClient(EntityBergamo.class, (Render)new RenderDBC(new ModelBergamo(), 0.5f));
        EntitiesDBC.addEntityClient(EntityLavender.class, (Render)new RenderDBC(new ModelLavender(), 0.5f));
        EntitiesDBC.addEntityClient(EntityBrianne.class, (Render)new RenderDBC(new ModelBrianne(), 0.5f));
        EntitiesDBC.addEntityClient(EntityCaulifla.class, (Render)new RenderDBC(new ModelCaulifla(), 0.5f));
        EntitiesDBC.addEntityClient(EntityCaulifla2.class, (Render)new RenderDBC(new ModelCauliflaSSJ(), 0.5f));
        EntitiesDBC.addEntityClient(EntityDyspo.class, (Render)new RenderDBC(new ModelDyspo(), 0.5f));
        EntitiesDBC.addEntityClient(EntityJiren.class, (Render)new RenderDBC(new ModelJiren(), 0.5f));
        EntitiesDBC.addEntityClient(EntityJiren2.class, (Render)new RenderDBC(new ModelJiren_Full_Power(), 0.5f));
        EntitiesDBC.addEntityClient(EntityKale.class, (Render)new RenderDBC(new ModelKale(), 0.5f));
        EntitiesDBC.addEntityClient(EntityKale2.class, (Render)new RenderDBC(new ModelKaleSSJ(), 0.5f));
        EntitiesDBC.addEntityClient(EntityKefla.class, (Render)new RenderDBC(new ModelKefla(), 0.5f));
        EntitiesDBC.addEntityClient(EntityKefla2.class, (Render)new RenderDBC(new ModelKeflaSSJ(), 0.5f));
        EntitiesDBC.addEntityClient(EntityToppo.class, (Render)new RenderDBC(new ModelToppo(), 0.5f));
        EntitiesDBC.addEntityClient(EntityToppo2.class, (Render)new RenderDBC(new ModelToppo_GoD(), 0.5f));
        EntitiesDBC.addEntityClient(EntityAniraza.class, (Render)new RenderDBC(new ModelAniraza(), 0.5f));
        EntitiesDBC.addEntityClient(EntityBiarra.class, (Render)new RenderDBC(new ModelBiarra(), 0.5f));
        EntitiesDBC.addEntityClient(EntityCocotte.class, (Render)new RenderDBC(new ModelCocotte(), 0.5f));
        EntitiesDBC.addEntityClient(EntityDercori.class, (Render)new RenderDBC(new ModelDercori(), 0.5f));
        EntitiesDBC.addEntityClient(EntityGanos.class, (Render)new RenderDBC(new ModelGanos(), 0.5f));
        EntitiesDBC.addEntityClient(EntityGanos2.class, (Render)new RenderDBC(new ModelGanos2(), 0.5f));
        EntitiesDBC.addEntityClient(EntityHop.class, (Render)new RenderDBC(new ModelHop(), 0.5f));
        EntitiesDBC.addEntityClient(EntityKahseral.class, (Render)new RenderDBC(new ModelKahseral(), 0.5f));
        EntitiesDBC.addEntityClient(EntityKakunsa.class, (Render)new RenderDBC(new ModelKakunsa(), 0.5f));
        EntitiesDBC.addEntityClient(EntityKunshi.class, (Render)new RenderDBC(new ModelKunshi(), 0.5f));
        EntitiesDBC.addEntityClient(EntityMajora.class, (Render)new RenderDBC(new ModelMajora(), 0.5f));
        EntitiesDBC.addEntityClient(EntityMurichim.class, (Render)new RenderDBC(new ModelMurichim(), 0.5f));
        EntitiesDBC.addEntityClient(EntityNapapa.class, (Render)new RenderDBC(new ModelNapapa(), 0.5f));
        EntitiesDBC.addEntityClient(EntityNarirama.class, (Render)new RenderDBC(new ModelNarirama(), 0.5f));
        EntitiesDBC.addEntityClient(EntityObni.class, (Render)new RenderDBC(new ModelObni(), 0.5f));
        EntitiesDBC.addEntityClient(EntityPaparoni.class, (Render)new RenderDBC(new ModelPaparoni(), 0.5f));
        EntitiesDBC.addEntityClient(EntityRoasie.class, (Render)new RenderDBC(new ModelRoasie(), 0.5f));
        EntitiesDBC.addEntityClient(EntityRylibeu.class, (Render)new RenderDBC(new ModelRylibeu(), 0.5f));
        EntitiesDBC.addEntityClient(EntityShosa.class, (Render)new RenderDBC(new ModelShosa(), 0.5f));
        EntitiesDBC.addEntityClient(EntitySorrel.class, (Render)new RenderDBC(new ModelSorrel(), 0.5f));
        EntitiesDBC.addEntityClient(EntityBorareta.class, (Render)new RenderDBC(new ModelBorareta(), 0.5f));
        EntitiesDBC.addEntityClient(EntityKoichiarator.class, (Render)new RenderDBC(new ModelKoichiarator(), 0.5f));
        EntitiesDBC.addEntityClient(EntityKoitsukai.class, (Render)new RenderDBC(new ModelKoitsukai(), 0.5f));
        EntitiesDBC.addEntityClient(EntityPanchia.class, (Render)new RenderDBC(new ModelPanchia(), 0.5f));
        EntitiesDBC.addEntityClient(EntityKatopesla.class, (Render)new RenderDBC(new ModelKatopesla(), 0.5f));
        EntitiesDBC.addEntityClient(EntityKatopesla2.class, (Render)new RenderDBC(new ModelKatopesla(), 0.5f));
        EntitiesDBC.addEntityClient(EntityKatopesla3.class, (Render)new RenderDBC(new ModelKatopesla(), 0.5f));
        EntitiesDBC.addEntityClient(EntityKatopesla4.class, (Render)new RenderDBC(new ModelKatopesla(), 0.5f));
        EntitiesDBC.addEntityClient(EntityDBSBroly1.class, (Render)new RenderDBC(new ModelDBSBrolyNormal(), 0.5f));
        EntitiesDBC.addEntityClient(EntityDBSBroly2.class, (Render)new RenderDBC(new ModelDBSBrolyNormal(), 0.5f));
        EntitiesDBC.addEntityClient(EntityDBSBroly3.class, (Render)new RenderDBC(new ModelDBSBrolyNormal(), 0.5f));
        EntitiesDBC.addEntityClient(EntityDBSBroly4.class, (Render)new RenderDBC(new ModelDBSBrolyNormal(), 0.5f));
        EntitiesDBC.addEntityClient(EntityDBSBrolyBuff.class, (Render)new RenderDBC(new ModelDBSBrolyBuff(), 0.5f));
        EntitiesDBC.addEntityClient(EntityDBSBrolyBuffSSJ.class, (Render)new RenderDBC(new ModelDBSBrolyBuff(), 0.5f));
        EntitiesDBC.addEntityClient(EntityDBSBrolyLegendary.class, (Render)new RenderDBC(new ModelDBSBrolyLegendary(), 0.5f));
        EntitiesDBC.addEntityClient(EntityDBSParagus.class, (Render)new RenderDBC(new ModelDBSParagus(), 0.5f));
        EntitiesDBC.addEntityClient(EntityDBSParagus2.class, (Render)new RenderDBC(new ModelDBSParagus2(), 0.5f));
        EntitiesDBC.addEntityClient(EntityCheelai.class, (Render)new RenderDBC(new ModelCheelai(), 0.5f));
        EntitiesDBC.addEntityClient(EntityCheelai2.class, (Render)new RenderDBC(new ModelCheelai(), 0.5f));
        EntitiesDBC.addEntityClient(EntityLemo.class, (Render)new RenderDBC(new ModelLemo(), 0.5f));
        EntitiesDBC.addEntityClient(EntityFortunetellerBaba.class, (Render)new RenderDBC(new ModelFortunetellerBaba(), 0.5f));
        EntitiesDBC.addEntityClient(EntityMummy.class, (Render)new RenderDBC(new ModelMummy(), 0.5f));
        EntitiesDBC.addEntityClient(EntityVampire.class, (Render)new RenderDBC(new ModelVampire(), 0.5f));
        EntitiesDBC.addEntityClient(EntityInvisibleMan.class, (Render)new RenderDBC(new ModelInvisibleMan(), 0.5f));
        EntitiesDBC.addEntityClient(EntityDevil.class, (Render)new RenderDBC(new ModelDevil(), 0.5f));
        EntitiesDBC.addEntityClient(EntityGrandpaGohan.class, (Render)new RenderDBC(new ModelGrandpaGohan(), 0.5f));
        EntitiesDBC.addEntityClient(EntityGrandpaGohan2.class, (Render)new RenderDBC(new ModelGrandpaGohan(), 0.5f));
        EntitiesDBC.addEntityClient(EntityCymbal.class, (Render)new RenderDBC(new ModelCymbal(), 0.5f));
        EntitiesDBC.addEntityClient(EntityDrum.class, (Render)new RenderDBC(new ModelDrum(), 0.5f));
        EntitiesDBC.addEntityClient(EntityKingPiccolo.class, (Render)new RenderDBC(new ModelKingPiccolo(), 0.5f));
        EntitiesDBC.addEntityClient(EntityKingPiccolo2.class, (Render)new RenderDBC(new ModelKingPiccolo2(), 0.5f));
        EntitiesDBC.addEntityClient(EntityPiano.class, (Render)new RenderDBC(new ModelPiano(), 0.5f));
        EntitiesDBC.addEntityClient(EntityTambourine.class, (Render)new RenderDBC(new ModelTambourine(), 0.5f));
        EntitiesDBC.addEntityClient(EntityDBMasterRoshi.class, (Render)new RenderDBC(new ModelMasterRoshi(), 0.5f));
        EntitiesDBC.addEntityClient(EntityDBMasterRoshi2.class, (Render)new RenderDBC(new ModelMasterRoshi2(), 0.5f));
        EntitiesDBC.addEntityClient(EntityDBMasterRoshi3.class, (Render)new RenderDBC(new ModelMasterRoshi3(), 0.5f));
        EntitiesDBC.addEntityClient(EntityBearThief.class, (Render)new RenderDBC(new ModelBearThief(), 0.5f));
        EntitiesDBC.addEntityClient(EntityTigerBandit.class, (Render)new RenderDBC(new ModelTigerBandit(), 0.5f));
        EntitiesDBC.addEntityClient(EntityPuar.class, (Render)new RenderDBC(new ModelPuar(), 0.5f));
        EntitiesDBC.addEntityClient(EntityYamcha.class, (Render)new RenderDBC(new ModelYamcha(), 0.5f));
        EntitiesDBC.addEntityClient(EntityYamcha2.class, (Render)new RenderDBC(new ModelYamcha2(), 0.5f));
        EntitiesDBC.addEntityClient(EntityYamcha3.class, (Render)new RenderDBC(new ModelYamcha2(), 0.5f));
        EntitiesDBC.addEntityClient(EntityYamcha4.class, (Render)new RenderDBC(new ModelYamcha2(), 0.5f));
        EntitiesDBC.addEntityClient(EntityYamcha5.class, (Render)new RenderDBC(new ModelYamcha(), 0.5f));
        EntitiesDBC.addEntityClient(EntityMai.class, (Render)new RenderDBC(new ModelMai(), 0.5f));
        EntitiesDBC.addEntityClient(EntityPilaf.class, (Render)new RenderDBC(new ModelPilaf(), 0.5f));
        EntitiesDBC.addEntityClient(EntityShu.class, (Render)new RenderDBC(new ModelShu(), 0.5f));
        EntitiesDBC.addEntityClient(EntityMaiMecha.class, (Render)new RenderDBC(new ModelMaiMecha(), 0.5f));
        EntitiesDBC.addEntityClient(EntityPilafMecha.class, (Render)new RenderDBC(new ModelPilafMecha(), 0.5f));
        EntitiesDBC.addEntityClient(EntityShuMecha.class, (Render)new RenderDBC(new ModelShuMecha(), 0.5f));
        EntitiesDBC.addEntityClient(EntityPilafMechaCombined.class, (Render)new RenderDBC(new ModelPilafMechaCombined(), 0.5f));
        EntitiesDBC.addEntityClient(EntityBacterian.class, (Render)new RenderDBC(new ModelBacterian(), 0.5f));
        EntitiesDBC.addEntityClient(EntityGiran.class, (Render)new RenderDBC(new ModelGiran(), 0.5f));
        EntitiesDBC.addEntityClient(EntityJackieChun.class, (Render)new RenderDBC(new ModelJackieChun(), 0.5f));
        EntitiesDBC.addEntityClient(EntityJackieChun2.class, (Render)new RenderDBC(new ModelJackieChun2(), 0.5f));
        EntitiesDBC.addEntityClient(EntityJackieChun3.class, (Render)new RenderDBC(new ModelJackieChun3(), 0.5f));
        EntitiesDBC.addEntityClient(EntityNam.class, (Render)new RenderDBC(new ModelNam(), 0.5f));
        EntitiesDBC.addEntityClient(EntityTournamentAnnouncer.class, (Render)new RenderDBC(new ModelTournamentAnnouncer(), 0.5f));
        EntitiesDBC.addEntityClient(EntityKingChappa.class, (Render)new RenderDBC(new ModelKingChappa(), 0.5f));
        EntitiesDBC.addEntityClient(EntityManWolf.class, (Render)new RenderDBC(new ModelManWolf(), 0.5f));
        EntitiesDBC.addEntityClient(EntityMasterShen.class, (Render)new RenderDBC(new ModelMasterShen(), 0.5f));
        EntitiesDBC.addEntityClient(EntityPamput.class, (Render)new RenderDBC(new ModelPamput(), 0.5f));
        EntitiesDBC.addEntityClient(EntityTien.class, (Render)new RenderDBC(new ModelTien(), 0.5f));
        EntitiesDBC.addEntityClient(EntityTien2.class, (Render)new RenderDBC(new ModelTien(), 0.5f));
        EntitiesDBC.addEntityClient(EntityTien3.class, (Render)new RenderDBC(new ModelTien(), 0.5f));
        EntitiesDBC.addEntityClient(EntityAndroid8.class, (Render)new RenderDBC(new ModelAndroid8(), 0.5f));
        EntitiesDBC.addEntityClient(EntityBuyon.class, (Render)new RenderDBC(new ModelBuyon(), 0.5f));
        EntitiesDBC.addEntityClient(EntityColonelSilver.class, (Render)new RenderDBC(new ModelColonelSilver(), 0.5f));
        EntitiesDBC.addEntityClient(EntityColonelViolet.class, (Render)new RenderDBC(new ModelColonelViolet(), 0.5f));
        EntitiesDBC.addEntityClient(EntityCommanderRed.class, (Render)new RenderDBC(new ModelCommanderRed(), 0.5f));
        EntitiesDBC.addEntityClient(EntityGeneralBlue.class, (Render)new RenderDBC(new ModelGeneralBlue(), 0.5f));
        EntitiesDBC.addEntityClient(EntityGeneralBlue2.class, (Render)new RenderDBC(new ModelGeneralBlue(), 0.5f));
        EntitiesDBC.addEntityClient(EntityGeneralWhite.class, (Render)new RenderDBC(new ModelGeneralWhite(), 0.5f));
        EntitiesDBC.addEntityClient(EntityGeneralWhite2.class, (Render)new RenderDBC(new ModelGeneralWhite(), 0.5f));
        EntitiesDBC.addEntityClient(EntityLaunch.class, (Render)new RenderDBC(new ModelLaunch(), 0.5f));
        EntitiesDBC.addEntityClient(EntityLaunch2.class, (Render)new RenderDBC(new ModelLaunch(), 0.5f));
        EntitiesDBC.addEntityClient(EntityMajorMetallitron.class, (Render)new RenderDBC(new ModelMajorMetallitron(), 0.5f));
        EntitiesDBC.addEntityClient(EntityMajorMetallitron1.class, (Render)new RenderDBC(new ModelMajorMetallitron(), 0.5f));
        EntitiesDBC.addEntityClient(EntityMajorMetallitron2.class, (Render)new RenderDBC(new ModelMajorMetallitron(), 0.5f));
        EntitiesDBC.addEntityClient(EntityMajorMetallitron3.class, (Render)new RenderDBC(new ModelMajorMetallitron(), 0.5f));
        EntitiesDBC.addEntityClient(EntityMercenaryTao.class, (Render)new RenderDBC(new ModelMercenaryTao(), 0.5f));
        EntitiesDBC.addEntityClient(EntityNinjaMurasaki.class, (Render)new RenderDBC(new ModelNinjaMurasaki(), 0.5f));
        EntitiesDBC.addEntityClient(EntityRedRibbonSoldier.class, (Render)new RenderDBC(new ModelRedRibbonSoldierGunner(), 0.5f));
        EntitiesDBC.addEntityClient(EntityRedRibbonSoldier2.class, (Render)new RenderDBC(new ModelRedRibbonSoldierGunner(), 0.5f));
        EntitiesDBC.addEntityClient(EntityRedRibbonSoldier3.class, (Render)new RenderDBC(new ModelRedRibbonSoldierBazooka(), 0.5f));
        EntitiesDBC.addEntityClient(EntityRedRibbonSoldierB.class, (Render)new RenderDBC(new ModelRedRibbonSoldierGunner(), 0.5f));
        EntitiesDBC.addEntityClient(EntityRedRibbonSoldierB2.class, (Render)new RenderDBC(new ModelRedRibbonSoldierGunner(), 0.5f));
        EntitiesDBC.addEntityClient(EntityRedRibbonSoldierB3.class, (Render)new RenderDBC(new ModelRedRibbonSoldierBazooka(), 0.5f));
        EntitiesDBC.addEntityClient(EntityBora.class, (Render)new RenderDBC(new ModelBora(), 0.5f));
        EntitiesDBC.addEntityClient(EntityUpa.class, (Render)new RenderDBC(new ModelUpa(), 0.5f));
        EntitiesDBC.addEntityClient(EntityOolong.class, (Render)new RenderDBC(new ModelOolong(), 0.5f));
        EntitiesDBC.addEntityClient(EntityYajirobe.class, (Render)new RenderDBC(new ModelYajirobe(), 0.5f));
        EntitiesDBC.addEntityClient(EntityMercenaryTao2.class, (Render)new RenderDBC(new ModelMercenaryTao2(), 0.5f));
        EntitiesDBC.addEntityClient(EntityMercenaryTao3.class, (Render)new RenderDBC(new ModelMercenaryTao2(), 0.5f));
        EntitiesDBC.addEntityClient(EntityOfficerBlack.class, (Render)new RenderDBC(new ModelOfficerBlack(), 0.5f));
        EntitiesDBC.addEntityClient(EntityOfficerBlack2.class, (Render)new RenderDBC(new ModelOfficerBlack(), 0.5f));
        EntitiesDBC.addEntityClient(EntityOfficerBlack3.class, (Render)new RenderDBC(new ModelOfficerBlack2(), 0.5f));
        EntitiesDBC.addEntityClient(EntityOfficeOgre.class, (Render)new RenderDBC(new ModelOfficeOgre(), 0.5f));
        EntitiesDBC.addEntityClient(EntityOfficeOgre2.class, (Render)new RenderDBC(new ModelOfficeOgre(), 0.5f));
        EntitiesDBC.addEntityClient(EntityOfficeOgre3.class, (Render)new RenderDBC(new ModelOfficeOgre(), 0.5f));
        EntitiesDBC.addEntityClient(EntityOfficeOgre4.class, (Render)new RenderDBC(new ModelOfficeOgre2(), 0.5f));
        EntitiesDBC.addEntityClient(EntityOfficeOgre5.class, (Render)new RenderDBC(new ModelOfficeOgre2(), 0.5f));
        EntitiesDBC.addEntityClient(EntitySpirit.class, (Render)new RenderDBC(new ModelSpirit(), 0.5f));
        EntitiesDBC.addEntityClient(EntityChiaotzu.class, (Render)new RenderDBC(new ModelChiaotzu(), 0.5f));
        EntitiesDBC.addEntityClient(EntityChiaotzu2.class, (Render)new RenderDBC(new ModelChiaotzu(), 0.5f));
        EntitiesDBC.addEntityClient(EntityChiaotzu3.class, (Render)new RenderDBC(new ModelChiaotzu2(), 0.5f));
        EntitiesDBC.addEntityClient(EntityChiaotzu4.class, (Render)new RenderDBC(new ModelChiaotzu(), 0.5f));
        EntitiesDBC.addEntityClient(EntityTien4.class, (Render)new RenderDBC(new ModelTien(), 0.5f));
        EntitiesDBC.addEntityClient(EntityTien5.class, (Render)new RenderDBC(new ModelTien2(), 0.5f));
        EntitiesDBC.addEntityClient(EntityTien6.class, (Render)new RenderDBC(new ModelTien2(), 0.5f));
        EntitiesDBC.addEntityClient(EntityTien7.class, (Render)new RenderDBC(new ModelTien(), 0.5f));
        EntitiesDBC.addEntityClient(EntityPiccolo.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(), 0.5f));
        EntitiesDBC.addEntityClient(EntityPiccolo2.class, (Render)new RenderDBC((ModelBase)new ModelRaditz(2.5f, false, true), 0.5f));
        ClientRegistry.registerTileEntity(namekian_throneTileEntity.class, (String)"namekian_throneTileEntityRender", (TileEntitySpecialRenderer)new namekian_throneRender());
        ClientRegistry.registerTileEntity(DragonBlockNS01TileEntity.class, (String)"DragonBlockNS01TileEntityRender", (TileEntitySpecialRenderer)new DragonBlockNS01Render());
        ClientRegistry.registerTileEntity(DragonBlockS01TileEntity.class, (String)"DragonBlockS01TileEntityRender", (TileEntitySpecialRenderer)new DragonBlockS01Render());
        ClientRegistry.registerTileEntity(DragonBlockNamek01TileEntity.class, (String)"DragonBlockNamek01TileEntityRender", (TileEntitySpecialRenderer)new DragonBlockNamek01Render());
        ClientRegistry.registerTileEntity(DragonBlock01TileEntity.class, (String)"DragonBlock01TileEntityRender", (TileEntitySpecialRenderer)new DragonBlock01Render());
        ClientRegistry.registerTileEntity(SpacePod01TileEntity.class, (String)"SpacePod01TileEntityRender", (TileEntitySpecialRenderer)new SpacePod01Render());
        ClientRegistry.registerTileEntity(SaibaiHatchedTileEntity.class, (String)"SaibaiHatchedEntityRender", (TileEntitySpecialRenderer)new SaibaiHatchedRender());
        ClientRegistry.registerTileEntity(MedPodDoor1TileEntity.class, (String)"MedPodDoor1EntityRender", (TileEntitySpecialRenderer)new MedPodDoor1Render());
        ClientRegistry.registerTileEntity(ArtGravDevTileEntity.class, (String)"ArtGravDevRender", (TileEntitySpecialRenderer)new ArtGravDevRender());
        ClientRegistry.registerTileEntity(ppTileEntity.class, (String)"ppRender", (TileEntitySpecialRenderer)new ppRender());
        EntitiesDBC.addEntityClient(block01dbcEntity.class, (Render)new block01dbcRender());
        EntitiesDBC.addEntityClient(EntityInstantTransmission.class, (Render)new RenderInstantTransmission());
        EntitiesDBC.addEntityClient(EntityMajinAbsorption.class, (Render)new RenderMajinAbsorption());
    }

    public static void common() {
        EntitiesDBC.addEntityServer(EntityPorunga.class, "Dragonp");
        EntitiesDBC.addEntityServer(EntityPorunga2.class, "Dragonp2");
        EntitiesDBC.addEntityServer(EntityDragon2.class, "Dragon2");
        EntitiesDBC.addEntityServer(EntityDragon.class, "Dragon");
        EntitiesDBC.addEntityServer(EntitySaiyanRaditz.class, "Raditz");
        EntitiesDBC.addEntityServer(EntitySaiyanNappa.class, "Nappa");
        EntitiesDBC.addEntityServer(EntitySaiyanVegeta.class, "Vegeta");
        EntitiesDBC.addEntityServer(EntitySaibaiman.class, "Saibaiman");
        EntitiesDBC.addEntityServer(EntitySaiyan01.class, "Saiyan01");
        EntitiesDBC.addEntityServer(EntitySaiyan02.class, "Saiyan02");
        EntitiesDBC.addEntityServer(EntityKiwi.class, "Kiwi");
        EntitiesDBC.addEntityServer(EntityDodoria.class, "Dodoria");
        EntitiesDBC.addEntityServer(EntityZarbon.class, "Zarbon");
        EntitiesDBC.addEntityServer(EntityGuldo.class, "Guldo");
        EntitiesDBC.addEntityServer(EntityRecoome.class, "Recoome");
        EntitiesDBC.addEntityServer(EntityBarta.class, "Barta");
        EntitiesDBC.addEntityServer(EntityJeice.class, "Jeice");
        EntitiesDBC.addEntityServer(EntityGinyu.class, "Ginyu");
        EntitiesDBC.addEntityServer(EntityFreezaSoldier1.class, "FreezaSoldier1");
        EntitiesDBC.addEntityServer(EntityFreezaSoldier2.class, "FreezaSoldier2");
        EntitiesDBC.addEntityServer(EntityFreezaSoldier3.class, "FreezaSoldier3");
        EntitiesDBC.addEntityServer(EntityFreeza1.class, "Freeza1");
        EntitiesDBC.addEntityServer(EntityFreeza2.class, "Freeza2");
        EntitiesDBC.addEntityServer(EntityFreeza3.class, "Freeza3");
        EntitiesDBC.addEntityServer(EntityFreeza4.class, "Freeza4");
        EntitiesDBC.addEntityServer(EntityFreeza5.class, "Freeza5");
        EntitiesDBC.addEntityServer(EntityFreeza6.class, "Freeza6");
        EntitiesDBC.addEntityServer(EntityFreezaFather.class, "KingCold");
        EntitiesDBC.addEntityServer(EntityFreezaMecha.class, "MechaFreeza");
        EntitiesDBC.addEntityServer(EntityCyborg16.class, "Cyborg16");
        EntitiesDBC.addEntityServer(EntityCyborg17.class, "Cyborg17");
        EntitiesDBC.addEntityServer(EntityCyborg18.class, "Cyborg18");
        EntitiesDBC.addEntityServer(EntityCyborg19.class, "Cyborg19");
        EntitiesDBC.addEntityServer(EntityCyborg20.class, "Cyborg20");
        EntitiesDBC.addEntityServer(EntityCell1.class, "Cell1");
        EntitiesDBC.addEntityServer(EntityCell2.class, "Cell2");
        EntitiesDBC.addEntityServer(EntityCell3.class, "Cell3");
        EntitiesDBC.addEntityServer(EntityCell4.class, "Cell4");
        EntitiesDBC.addEntityServer(SpacePod01Entity.class, "SpacePod");
        EntitiesDBC.addEntityServer(KintounEntity.class, "Kintoun");
        EntitiesDBC.addEntityServer(KintounBlackEntity.class, "KintounBlack");
        EntitiesDBC.addEntityServer(EntityHell01.class, "hell01");
        EntitiesDBC.addEntityServer(EntityHell02.class, "hell02");
        EntitiesDBC.addEntityServer(EntityMasterEnma.class, "enma");
        EntitiesDBC.addEntityServer(EntityNamekian01.class, "Namekian01");
        EntitiesDBC.addEntityServer(EntityNamekian03.class, "Namekian03");
        EntitiesDBC.addEntityServer(EntityMasterKami.class, "kami");
        EntitiesDBC.addEntityServer(EntityMasterKaio.class, "northkaio");
        EntitiesDBC.addEntityServer(EntityMasterKarin.class, "karin");
        EntitiesDBC.addEntityServer(EntityMasterRoshi.class, "roshi");
        EntitiesDBC.addEntityServer(EntityMasterCell.class, "cellmaster");
        EntitiesDBC.addEntityServer(EntityMasterGoku.class, "gokumaster");
        EntitiesDBC.addEntityServer(EntityMasterGohan.class, "gohanmaster");
        EntitiesDBC.addEntityServer(EntityMasterTrunksFuture.class, "trunksfuturemaster");
        EntitiesDBC.addEntityServer(EntityMasterFreeza.class, "Freezamaster");
        EntitiesDBC.addEntityServer(EntityMasterJin.class, "jin");
        EntitiesDBC.addEntityServer(EntityMasterGuru.class, "gurumaster");
        EntitiesDBC.addEntityServer(EntityMasterWhis.class, "whismaster");
        EntitiesDBC.addEntityServer(EntityDino01.class, "EntityDino01");
        EntitiesDBC.addEntityServer(EntityDino02.class, "EntityDino02");
        EntitiesDBC.addEntityServer(EntityDino03.class, "EntityDino03");
        EntitiesDBC.addEntityServer(EntityRRMecha.class, "EntityRRMecha");
        if (DBCConfig.spwnrt_rrmech1 > 0) {
            EntityRegistry.addSpawn(EntityRRMecha.class, (int)DBCConfig.spwnrt_rrmech1, (int)1, (int)1, (EnumCreatureType)EnumCreatureType.monster, (BiomeGenBase[])new BiomeGenBase[]{BiomeGenBase.extremeHills, BiomeGenBase.taiga, BiomeGenBase.coldTaiga, BiomeGenBase.coldTaigaHills, BiomeGenBase.icePlains, BiomeGenBase.taigaHills});
        }
        EntitiesDBC.addEntityServer(EntitySabertooth.class, "EntitySabertooth");
        if (DBCConfig.spwnrt_sabert > 0) {
            EntityRegistry.addSpawn(EntitySabertooth.class, (int)DBCConfig.spwnrt_sabert, (int)1, (int)1, (EnumCreatureType)EnumCreatureType.monster, (BiomeGenBase[])new BiomeGenBase[]{BiomeGenBase.plains, BiomeGenBase.forest, BiomeGenBase.forestHills, BiomeGenBase.birchForest, BiomeGenBase.birchForestHills});
        }
        EntitiesDBC.addEntityServer(EntityEnergyAtt.class, "EnergyAttack");
        EntitiesDBC.addEntityServer(EntityPrjtls_1.class, "DBCProjectile_1", 1);
        EntitiesDBC.addEntityServer(EntityPuipui.class, "Puipui");
        EntitiesDBC.addEntityServer(EntityYakon.class, "Yakon");
        EntitiesDBC.addEntityServer(EntityDarbura.class, "Darbura");
        EntitiesDBC.addEntityServer(EntityBuuFat.class, "BuuFat");
        EntitiesDBC.addEntityServer(EntityBuuSuper.class, "BuuSuper");
        EntitiesDBC.addEntityServer(EntityMasterBabidi.class, "masterbabidi");
        EntitiesDBC.addEntityServer(EntityBeerus.class, "Beerus");
        EntitiesDBC.addEntityServer(EntityMasterPiccolo.class, "masterpiccolo");
        EntitiesDBC.addEntityServer(EntityMasterVegeta.class, "mastervegeta");
        EntitiesDBC.addEntityServer(EntityZarbon2.class, "Zarbon2");
        EntitiesDBC.addEntityServer(EntityFreeza7.class, "FreezaGolden");
        EntitiesDBC.addEntityServer(EntityEnergyFM.class, "KiFakeMoon", 400, 5);
        EntitiesDBC.addEntityServer(EntityNamekFrog.class, "EntityNamekFrog");
        EntitiesDBC.addEntityServer(EntityCellJr.class, "CellJr");
        EntitiesDBC.addEntityServer(EntityBuuEvil.class, "BuuEvil");
        EntitiesDBC.addEntityServer(EntityBuuFusion.class, "BuuFusion");
        EntitiesDBC.addEntityServer(EntityBuuPiccolo.class, "BuuPiccolo");
        EntitiesDBC.addEntityServer(EntityBuuUltimate.class, "BuuUltimate");
        EntitiesDBC.addEntityServer(EntityBuuBuffed.class, "BuuBuffed");
        EntitiesDBC.addEntityServer(EntityBuuKid.class, "BuuKid");
        EntitiesDBC.addEntityServer(EntityBerryblue.class, "Berryblue");
        EntitiesDBC.addEntityServer(EntityBeerusMonaka.class, "BeerusMonaka");
        EntitiesDBC.addEntityServer(EntityBeerusMonaka2.class, "BeerusMonaka2");
        EntitiesDBC.addEntityServer(EntityBeerusMonaka3.class, "BeerusMonaka3");
        EntitiesDBC.addEntityServer(EntityBotamo.class, "Botamo");
        EntitiesDBC.addEntityServer(EntityChampa.class, "Champa");
        EntitiesDBC.addEntityServer(EntityFrost1.class, "Frost1");
        EntitiesDBC.addEntityServer(EntityFrost2.class, "Frost2");
        EntitiesDBC.addEntityServer(EntityFrost3.class, "Frost3");
        EntitiesDBC.addEntityServer(EntityFrost4.class, "Frost4");
        EntitiesDBC.addEntityServer(EntityFrost5.class, "Frost5");
        EntitiesDBC.addEntityServer(EntityFrost6.class, "Frost6");
        EntitiesDBC.addEntityServer(EntityHit.class, "Hit");
        EntitiesDBC.addEntityServer(EntityKrillin.class, "Krillin");
        EntitiesDBC.addEntityServer(EntityMagetta.class, "Magetta");
        EntitiesDBC.addEntityServer(EntityMonaka.class, "Monaka");
        EntitiesDBC.addEntityServer(EntityRoshi_super.class, "Roshi_super");
        EntitiesDBC.addEntityServer(EntityShisami.class, "Shisami");
        EntitiesDBC.addEntityServer(EntitySorbet.class, "Sorbet");
        EntitiesDBC.addEntityServer(EntityTagoma.class, "Tagoma");
        EntitiesDBC.addEntityServer(EntityVados.class, "Vados");
        EntitiesDBC.addEntityServer(EntityWhis.class, "Whis");
        EntitiesDBC.addEntityServer(EntityGokuBlack.class, "GokuBlack");
        EntitiesDBC.addEntityServer(EntityGokuBlackRose.class, "GokuBlackRose");
        EntitiesDBC.addEntityServer(EntityVegetaCopy.class, "VegetaCopy");
        EntitiesDBC.addEntityServer(EntityVegetaCopyBlue.class, "VegetaCopyBlue");
        EntitiesDBC.addEntityServer(EntityCabba.class, "Cabba");
        EntitiesDBC.addEntityServer(EntityCabbaSSJ.class, "CabbaSSJ");
        EntitiesDBC.addEntityServer(EntityZamasu.class, "Zamasu");
        EntitiesDBC.addEntityServer(EntityZamasu_Fused.class, "Zamasu_fused");
        EntitiesDBC.addEntityServer(EntityZamasu_Fused2.class, "Zamasu_fused2");
        EntitiesDBC.addEntityServer(EntityZamasu_Fused3.class, "Zamasu_fused3");
        EntitiesDBC.addEntityServer(EntityZeno.class, "Zeno");
        EntitiesDBC.addEntityServer(EntityGoku.class, "Goku_enemy");
        EntitiesDBC.addEntityServer(EntityGoku2.class, "Goku_enemy2");
        EntitiesDBC.addEntityServer(EntityGoku3.class, "Goku_enemy3");
        EntitiesDBC.addEntityServer(EntityGoku4.class, "Goku_enemy4");
        EntitiesDBC.addEntityServer(EntityVegeta.class, "Vegeta_enemy");
        EntitiesDBC.addEntityServer(EntityVegeta2.class, "Vegeta_enemy2");
        EntitiesDBC.addEntityServer(EntityVegeta3.class, "Vegeta_enemy3");
        EntitiesDBC.addEntityServer(EntityVegeta4.class, "Vegeta_enemy4");
        EntitiesDBC.addEntityServer(EntityGohan.class, "Gohan_enemy");
        EntitiesDBC.addEntityServer(EntityGohan2.class, "Gohan_enemy2");
        EntitiesDBC.addEntityServer(EntityGohan_orange.class, "Gohan_enemy2_1");
        EntitiesDBC.addEntityServer(EntityGohan_orange2.class, "Gohan_enemy2_2");
        EntitiesDBC.addEntityServer(EntityTrunks.class, "Trunks_enemy");
        EntitiesDBC.addEntityServer(EntityTrunks2.class, "Trunks_enemy2");
        EntitiesDBC.addEntityServer(EntityTrunks_dbs.class, "Trunks_enemy2_1");
        EntitiesDBC.addEntityServer(EntityTrunks_dbs2.class, "Trunks_enemy2_2");
        EntitiesDBC.addEntityServer(EntityAngelAwamo.class, "AngelAwamo");
        EntitiesDBC.addEntityServer(EntityAngelCamparri.class, "AngelCamparri");
        EntitiesDBC.addEntityServer(EntityAngelCognac.class, "AngelCognac");
        EntitiesDBC.addEntityServer(EntityAngelCukatail.class, "AngelCuktail");
        EntitiesDBC.addEntityServer(EntityAngelKorn.class, "AngelKorn");
        EntitiesDBC.addEntityServer(EntityAngelKusu.class, "AngelKusu");
        EntitiesDBC.addEntityServer(EntityAngelMarcarita.class, "AngelMarcarita");
        EntitiesDBC.addEntityServer(EntityAngelMartinu.class, "AngelMartinu");
        EntitiesDBC.addEntityServer(EntityAngelMohito.class, "AngelMohito");
        EntitiesDBC.addEntityServer(EntityAngelSour.class, "AngelSour");
        EntitiesDBC.addEntityServer(EntityGodArak.class, "GodArak");
        EntitiesDBC.addEntityServer(EntityGodBelmod.class, "GodBelmod");
        EntitiesDBC.addEntityServer(EntityGodGiin.class, "GodGiin");
        EntitiesDBC.addEntityServer(EntityGodHeles.class, "GodHeles");
        EntitiesDBC.addEntityServer(EntityGodIwan.class, "GodIwan");
        EntitiesDBC.addEntityServer(EntityGodLiquiir.class, "GodLiquiir");
        EntitiesDBC.addEntityServer(EntityGodMosco.class, "GodMosco");
        EntitiesDBC.addEntityServer(EntityGodQuitela.class, "GodQuitela");
        EntitiesDBC.addEntityServer(EntityGodRumsshi.class, "GodRumsshi");
        EntitiesDBC.addEntityServer(EntityGodSidra.class, "GodSidra");
        EntitiesDBC.addEntityServer(EntityBasil.class, "Basil");
        EntitiesDBC.addEntityServer(EntityBergamo.class, "Bergamo");
        EntitiesDBC.addEntityServer(EntityLavender.class, "Lavender");
        EntitiesDBC.addEntityServer(EntityBrianne.class, "Brianne");
        EntitiesDBC.addEntityServer(EntityCaulifla.class, "Caulifla");
        EntitiesDBC.addEntityServer(EntityCaulifla2.class, "Caulifla2");
        EntitiesDBC.addEntityServer(EntityDyspo.class, "Dyspo");
        EntitiesDBC.addEntityServer(EntityJiren.class, "Jiren");
        EntitiesDBC.addEntityServer(EntityJiren2.class, "Jiren2");
        EntitiesDBC.addEntityServer(EntityKale.class, "Kale");
        EntitiesDBC.addEntityServer(EntityKale2.class, "Kale2");
        EntitiesDBC.addEntityServer(EntityKefla.class, "Kefla");
        EntitiesDBC.addEntityServer(EntityKefla2.class, "Kefla2");
        EntitiesDBC.addEntityServer(EntityToppo.class, "Toppo");
        EntitiesDBC.addEntityServer(EntityToppo2.class, "Toppo2");
        EntitiesDBC.addEntityServer(EntityAniraza.class, "Aniraza");
        EntitiesDBC.addEntityServer(EntityBiarra.class, "Biarra");
        EntitiesDBC.addEntityServer(EntityCocotte.class, "Cocotte");
        EntitiesDBC.addEntityServer(EntityDercori.class, "Dercori");
        EntitiesDBC.addEntityServer(EntityGanos.class, "Ganos");
        EntitiesDBC.addEntityServer(EntityGanos2.class, "Ganos2");
        EntitiesDBC.addEntityServer(EntityHop.class, "Hop");
        EntitiesDBC.addEntityServer(EntityKahseral.class, "Kahseral");
        EntitiesDBC.addEntityServer(EntityKakunsa.class, "Kakunsa");
        EntitiesDBC.addEntityServer(EntityKunshi.class, "Kunshi");
        EntitiesDBC.addEntityServer(EntityMajora.class, "Majora");
        EntitiesDBC.addEntityServer(EntityMurichim.class, "Murichim");
        EntitiesDBC.addEntityServer(EntityNapapa.class, "Napapa");
        EntitiesDBC.addEntityServer(EntityNarirama.class, "Narirama");
        EntitiesDBC.addEntityServer(EntityObni.class, "Obni");
        EntitiesDBC.addEntityServer(EntityPaparoni.class, "Paparoni");
        EntitiesDBC.addEntityServer(EntityRoasie.class, "Roasie");
        EntitiesDBC.addEntityServer(EntityRylibeu.class, "Rylibeu");
        EntitiesDBC.addEntityServer(EntityShosa.class, "Shosa");
        EntitiesDBC.addEntityServer(EntitySorrel.class, "Sorrel");
        EntitiesDBC.addEntityServer(EntityBorareta.class, "Borareta");
        EntitiesDBC.addEntityServer(EntityKoichiarator.class, "Koichiarator");
        EntitiesDBC.addEntityServer(EntityKoitsukai.class, "Koitsukai");
        EntitiesDBC.addEntityServer(EntityPanchia.class, "Panchia");
        EntitiesDBC.addEntityServer(EntityKatopesla.class, "Katopesla");
        EntitiesDBC.addEntityServer(EntityKatopesla2.class, "Katopesla2");
        EntitiesDBC.addEntityServer(EntityKatopesla3.class, "Katopesla3");
        EntitiesDBC.addEntityServer(EntityKatopesla4.class, "Katopesla4");
        EntitiesDBC.addEntityServer(EntityDBSBroly1.class, "DBSBroly");
        EntitiesDBC.addEntityServer(EntityDBSBroly2.class, "DBSBroly2");
        EntitiesDBC.addEntityServer(EntityDBSBroly3.class, "DBSBroly3");
        EntitiesDBC.addEntityServer(EntityDBSBroly4.class, "DBSBroly4");
        EntitiesDBC.addEntityServer(EntityDBSBrolyBuff.class, "DBSBrolyBuff");
        EntitiesDBC.addEntityServer(EntityDBSBrolyBuffSSJ.class, "DBSBrolyBuffSSJ");
        EntitiesDBC.addEntityServer(EntityDBSBrolyLegendary.class, "DBSBrolyLegendary");
        EntitiesDBC.addEntityServer(EntityDBSParagus.class, "DBSParagus");
        EntitiesDBC.addEntityServer(EntityDBSParagus2.class, "DBSParagusOld");
        EntitiesDBC.addEntityServer(EntityCheelai.class, "Cheelai");
        EntitiesDBC.addEntityServer(EntityCheelai2.class, "Cheelai2");
        EntitiesDBC.addEntityServer(EntityLemo.class, "Lemo");
        EntitiesDBC.addEntityServer(EntityFortunetellerBaba.class, "FortunetellerBaba");
        EntitiesDBC.addEntityServer(EntityMummy.class, "BandagesTheMummy");
        EntitiesDBC.addEntityServer(EntityVampire.class, "FangsTheVampire");
        EntitiesDBC.addEntityServer(EntityInvisibleMan.class, "SeeThroughTheInvisibleMan");
        EntitiesDBC.addEntityServer(EntityDevil.class, "SpikeTheDevil");
        EntitiesDBC.addEntityServer(EntityGrandpaGohan.class, "GrandpaGohan");
        EntitiesDBC.addEntityServer(EntityGrandpaGohan2.class, "GrandpaGohan2");
        EntitiesDBC.addEntityServer(EntityCymbal.class, "Cymbal");
        EntitiesDBC.addEntityServer(EntityDrum.class, "Drum");
        EntitiesDBC.addEntityServer(EntityKingPiccolo.class, "KingPiccolo");
        EntitiesDBC.addEntityServer(EntityKingPiccolo2.class, "KingPiccolo2");
        EntitiesDBC.addEntityServer(EntityPiano.class, "Piano");
        EntitiesDBC.addEntityServer(EntityTambourine.class, "Tambourine");
        EntitiesDBC.addEntityServer(EntityDBMasterRoshi.class, "DBMasterRoshi");
        EntitiesDBC.addEntityServer(EntityDBMasterRoshi2.class, "DBMasterRoshi2");
        EntitiesDBC.addEntityServer(EntityDBMasterRoshi3.class, "DBMasterRoshi3");
        EntitiesDBC.addEntityServer(EntityBearThief.class, "BearThief");
        EntitiesDBC.addEntityServer(EntityTigerBandit.class, "TigerBandit");
        EntitiesDBC.addEntityServer(EntityPuar.class, "Puar");
        EntitiesDBC.addEntityServer(EntityYamcha.class, "Yamcha");
        EntitiesDBC.addEntityServer(EntityYamcha2.class, "Yamcha2");
        EntitiesDBC.addEntityServer(EntityYamcha3.class, "Yamcha3");
        EntitiesDBC.addEntityServer(EntityYamcha4.class, "Yamcha4");
        EntitiesDBC.addEntityServer(EntityYamcha5.class, "Yamcha5");
        EntitiesDBC.addEntityServer(EntityMai.class, "DBMai");
        EntitiesDBC.addEntityServer(EntityPilaf.class, "DBPilaf");
        EntitiesDBC.addEntityServer(EntityShu.class, "DBShu");
        EntitiesDBC.addEntityServer(EntityMaiMecha.class, "DBMaiMecha");
        EntitiesDBC.addEntityServer(EntityPilafMecha.class, "DBPilafMecha");
        EntitiesDBC.addEntityServer(EntityShuMecha.class, "DBShuMecha");
        EntitiesDBC.addEntityServer(EntityPilafMechaCombined.class, "DBPilafMechaCombined");
        EntitiesDBC.addEntityServer(EntityBacterian.class, "Bacterian");
        EntitiesDBC.addEntityServer(EntityGiran.class, "Giran");
        EntitiesDBC.addEntityServer(EntityJackieChun.class, "JackieChun");
        EntitiesDBC.addEntityServer(EntityJackieChun2.class, "JackieChun2");
        EntitiesDBC.addEntityServer(EntityJackieChun3.class, "JackieChun3");
        EntitiesDBC.addEntityServer(EntityNam.class, "Nam");
        EntitiesDBC.addEntityServer(EntityTournamentAnnouncer.class, "TournamentAnnouncer");
        EntitiesDBC.addEntityServer(EntityKingChappa.class, "KingChappa");
        EntitiesDBC.addEntityServer(EntityManWolf.class, "ManWolf");
        EntitiesDBC.addEntityServer(EntityMasterShen.class, "MasterShen");
        EntitiesDBC.addEntityServer(EntityPamput.class, "Pamput");
        EntitiesDBC.addEntityServer(EntityTien.class, "TienShinhan");
        EntitiesDBC.addEntityServer(EntityTien2.class, "TienShinhan2");
        EntitiesDBC.addEntityServer(EntityTien3.class, "TienShinhan3");
        EntitiesDBC.addEntityServer(EntityAndroid8.class, "Android8");
        EntitiesDBC.addEntityServer(EntityBuyon.class, "Buyon");
        EntitiesDBC.addEntityServer(EntityColonelSilver.class, "ColonelSilver");
        EntitiesDBC.addEntityServer(EntityColonelViolet.class, "ColonelViolet");
        EntitiesDBC.addEntityServer(EntityCommanderRed.class, "CommanderRed");
        EntitiesDBC.addEntityServer(EntityGeneralBlue.class, "GeneralBlue");
        EntitiesDBC.addEntityServer(EntityGeneralBlue2.class, "GeneralBlue2");
        EntitiesDBC.addEntityServer(EntityGeneralWhite.class, "GeneralWhite");
        EntitiesDBC.addEntityServer(EntityGeneralWhite2.class, "GeneralWhite2");
        EntitiesDBC.addEntityServer(EntityLaunch.class, "LaunchGood");
        EntitiesDBC.addEntityServer(EntityLaunch2.class, "LaunchBad");
        EntitiesDBC.addEntityServer(EntityMajorMetallitron.class, "MajorMetallitron");
        EntitiesDBC.addEntityServer(EntityMajorMetallitron1.class, "MajorMetallitron1");
        EntitiesDBC.addEntityServer(EntityMajorMetallitron2.class, "MajorMetallitron2");
        EntitiesDBC.addEntityServer(EntityMajorMetallitron3.class, "MajorMetallitron3");
        EntitiesDBC.addEntityServer(EntityMercenaryTao.class, "MercenaryTao");
        EntitiesDBC.addEntityServer(EntityNinjaMurasaki.class, "NinjaMurasaki");
        EntitiesDBC.addEntityServer(EntityRedRibbonSoldier.class, "RedRibbonSoldier");
        EntitiesDBC.addEntityServer(EntityRedRibbonSoldier2.class, "RedRibbonSoldier2");
        EntitiesDBC.addEntityServer(EntityRedRibbonSoldier3.class, "RedRibbonSoldier3");
        EntitiesDBC.addEntityServer(EntityRedRibbonSoldierB.class, "RedRibbonSoldierB");
        EntitiesDBC.addEntityServer(EntityRedRibbonSoldierB2.class, "RedRibbonSoldierB2");
        EntitiesDBC.addEntityServer(EntityRedRibbonSoldierB3.class, "RedRibbonSoldierB3");
        EntitiesDBC.addEntityServer(EntityBora.class, "DBBora");
        EntitiesDBC.addEntityServer(EntityUpa.class, "DBUpa");
        EntitiesDBC.addEntityServer(EntityOolong.class, "Oolong");
        EntitiesDBC.addEntityServer(EntityYajirobe.class, "Yajirobe");
        EntitiesDBC.addEntityServer(EntityMercenaryTao2.class, "MercenaryTao2");
        EntitiesDBC.addEntityServer(EntityMercenaryTao3.class, "MercenaryTao3");
        EntitiesDBC.addEntityServer(EntityOfficerBlack.class, "OfficerBlack");
        EntitiesDBC.addEntityServer(EntityOfficerBlack2.class, "OfficerBlack2");
        EntitiesDBC.addEntityServer(EntityOfficerBlack3.class, "OfficerBlack3");
        EntitiesDBC.addEntityServer(EntityOfficeOgre.class, "OfficeOgre");
        EntitiesDBC.addEntityServer(EntityOfficeOgre2.class, "OfficeOgre2");
        EntitiesDBC.addEntityServer(EntityOfficeOgre3.class, "OfficeOgre3");
        EntitiesDBC.addEntityServer(EntityOfficeOgre4.class, "OfficeOgre4");
        EntitiesDBC.addEntityServer(EntityOfficeOgre5.class, "OfficeOgre5");
        EntitiesDBC.addEntityServer(EntitySpirit.class, "DBZSpirit");
        EntitiesDBC.addEntityServer(EntityChiaotzu.class, "Chiaotzu");
        EntitiesDBC.addEntityServer(EntityChiaotzu2.class, "Chiaotzu2");
        EntitiesDBC.addEntityServer(EntityChiaotzu3.class, "Chiaotzu3");
        EntitiesDBC.addEntityServer(EntityChiaotzu4.class, "Chiaotzu4");
        EntitiesDBC.addEntityServer(EntityTien4.class, "TienShinhan4");
        EntitiesDBC.addEntityServer(EntityTien5.class, "TienShinhan5");
        EntitiesDBC.addEntityServer(EntityTien6.class, "TienShinhan6");
        EntitiesDBC.addEntityServer(EntityTien7.class, "TienShinhan7");
        EntitiesDBC.addEntityServer(EntityPiccolo.class, "Piccolo");
        EntitiesDBC.addEntityServer(EntityPiccolo2.class, "Piccolo2");
        if (DBCConfig.SpawnrateBearThief > 0) {
            EntityRegistry.addSpawn(EntityBearThief.class, (int)DBCConfig.SpawnrateBearThief, (int)1, (int)1, (EnumCreatureType)EnumCreatureType.monster, (BiomeGenBase[])new BiomeGenBase[]{BiomeGenBase.plains, BiomeGenBase.forest, BiomeGenBase.forestHills, BiomeGenBase.birchForest, BiomeGenBase.birchForestHills});
        }
        if (DBCConfig.SpawnrateTigerBandit > 0) {
            EntityRegistry.addSpawn(EntityTigerBandit.class, (int)DBCConfig.SpawnrateTigerBandit, (int)1, (int)1, (EnumCreatureType)EnumCreatureType.monster, (BiomeGenBase[])new BiomeGenBase[]{BiomeGenBase.plains, BiomeGenBase.forest, BiomeGenBase.forestHills, BiomeGenBase.birchForest, BiomeGenBase.birchForestHills});
        }
        if (DBCConfig.SpawnrateRRMajor > 0) {
            EntityRegistry.addSpawn(EntityMajorMetallitron.class, (int)DBCConfig.SpawnrateRRMajor, (int)1, (int)1, (EnumCreatureType)EnumCreatureType.monster, (BiomeGenBase[])new BiomeGenBase[]{BiomeGenBase.extremeHills, BiomeGenBase.taiga, BiomeGenBase.coldTaiga, BiomeGenBase.coldTaigaHills, BiomeGenBase.icePlains, BiomeGenBase.taigaHills});
        }
        if (DBCConfig.SpawnrateRRSoldiers > 0) {
            EntityRegistry.addSpawn(EntityRedRibbonSoldier.class, (int)DBCConfig.SpawnrateRRSoldiers, (int)1, (int)1, (EnumCreatureType)EnumCreatureType.monster, (BiomeGenBase[])new BiomeGenBase[]{BiomeGenBase.extremeHills, BiomeGenBase.taiga, BiomeGenBase.coldTaiga, BiomeGenBase.coldTaigaHills, BiomeGenBase.icePlains, BiomeGenBase.taigaHills});
            EntityRegistry.addSpawn(EntityRedRibbonSoldier2.class, (int)DBCConfig.SpawnrateRRSoldiers, (int)1, (int)1, (EnumCreatureType)EnumCreatureType.monster, (BiomeGenBase[])new BiomeGenBase[]{BiomeGenBase.extremeHills, BiomeGenBase.taiga, BiomeGenBase.coldTaiga, BiomeGenBase.coldTaigaHills, BiomeGenBase.icePlains, BiomeGenBase.taigaHills});
            EntityRegistry.addSpawn(EntityRedRibbonSoldier3.class, (int)DBCConfig.SpawnrateRRSoldiers, (int)1, (int)1, (EnumCreatureType)EnumCreatureType.monster, (BiomeGenBase[])new BiomeGenBase[]{BiomeGenBase.extremeHills, BiomeGenBase.taiga, BiomeGenBase.coldTaiga, BiomeGenBase.coldTaigaHills, BiomeGenBase.icePlains, BiomeGenBase.taigaHills});
            EntityRegistry.addSpawn(EntityRedRibbonSoldierB.class, (int)DBCConfig.SpawnrateRRSoldiers, (int)1, (int)1, (EnumCreatureType)EnumCreatureType.monster, (BiomeGenBase[])new BiomeGenBase[]{BiomeGenBase.extremeHills, BiomeGenBase.taiga, BiomeGenBase.coldTaiga, BiomeGenBase.coldTaigaHills, BiomeGenBase.icePlains, BiomeGenBase.taigaHills});
            EntityRegistry.addSpawn(EntityRedRibbonSoldierB2.class, (int)DBCConfig.SpawnrateRRSoldiers, (int)1, (int)1, (EnumCreatureType)EnumCreatureType.monster, (BiomeGenBase[])new BiomeGenBase[]{BiomeGenBase.extremeHills, BiomeGenBase.taiga, BiomeGenBase.coldTaiga, BiomeGenBase.coldTaigaHills, BiomeGenBase.icePlains, BiomeGenBase.taigaHills});
            EntityRegistry.addSpawn(EntityRedRibbonSoldierB3.class, (int)DBCConfig.SpawnrateRRSoldiers, (int)1, (int)1, (EnumCreatureType)EnumCreatureType.monster, (BiomeGenBase[])new BiomeGenBase[]{BiomeGenBase.extremeHills, BiomeGenBase.taiga, BiomeGenBase.coldTaiga, BiomeGenBase.coldTaigaHills, BiomeGenBase.icePlains, BiomeGenBase.taigaHills});
        }
        EntitiesDBC.addEntityServer(block01dbcEntity.class, "block01dbcEntity", 80, 1, false);
        GameRegistry.registerTileEntity(DragonBlockS01TileEntity.class, (String)"DragonBlockS01TileEntity");
        GameRegistry.registerTileEntity(DragonBlockNS01TileEntity.class, (String)"DragonBlockNS01TileEntity");
        GameRegistry.registerTileEntity(DragonBlockNamek01TileEntity.class, (String)"DragonBlockNamek01TileEntity");
        GameRegistry.registerTileEntity(DragonBlock01TileEntity.class, (String)"DragonBlock01TileEntity");
        GameRegistry.registerTileEntity(SpacePod01TileEntity.class, (String)"SpacePod01TileEntity");
        GameRegistry.registerTileEntity(SaibaiHatchedTileEntity.class, (String)"SaibaiHatchedTileEntity");
        GameRegistry.registerTileEntity(MedPodDoor1TileEntity.class, (String)"MedPodDoor1TileEntity");
        GameRegistry.registerTileEntity(ArtGravDevTileEntity.class, (String)"ArtGravDevTileEntity");
        GameRegistry.registerTileEntity(ppTileEntity.class, (String)"ppTileEntity");
        GameRegistry.registerTileEntity(namekian_throneTileEntity.class, (String)"namekian_throneTileEntity");
        EntitiesDBC.addEntityServer(EntityInstantTransmission.class, "KiInstantTransmission", 400, 5);
        EntitiesDBC.addEntityServer(EntityMajinAbsorption.class, "MajinAbsorption", 80, 1);
    }
}

