/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.client.model.ModelBase
 *  net.minecraft.client.model.ModelBiped
 *  net.minecraft.client.model.ModelRenderer
 *  net.minecraft.entity.Entity
 *  net.minecraft.util.MathHelper
 *  org.lwjgl.opengl.GL11
 */
package JinRyuu.DragonBC.common.Npcs;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;
import org.lwjgl.opengl.GL11;

public class ModelRaditz2
extends ModelBiped {
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer headhair;
    ModelRenderer leftarmshoulder;
    ModelRenderer rightarmshoulder;
    ModelRenderer cui1;
    ModelRenderer cui2;
    ModelRenderer spikes1;
    ModelRenderer spikes2;
    ModelRenderer spikes3;
    ModelRenderer spikes4;
    ModelRenderer spikes5;
    ModelRenderer spikes6;
    ModelRenderer spikes7;
    ModelRenderer spikes8;
    ModelRenderer ear1;
    ModelRenderer ear2;
    ModelRenderer horn2;
    ModelRenderer horn1;
    ModelRenderer appule;
    ModelRenderer Fhorn2;
    ModelRenderer Fhorn1;
    ModelRenderer Fhorn3;
    ModelRenderer Fhorn4;
    ModelRenderer F2horn1;
    ModelRenderer F2horn2;
    ModelRenderer tail1;
    ModelRenderer tail2;
    ModelRenderer body2;
    ModelRenderer rightarm2;
    ModelRenderer leftarm2;
    ModelRenderer rightleg2;
    ModelRenderer leftleg2;
    ModelRenderer celltail;
    ModelRenderer cellhead1;
    ModelRenderer cellhead2;
    ModelRenderer cellhead3;
    ModelRenderer cellhead4;
    ModelRenderer cell1head;
    ModelRenderer hair1;
    ModelRenderer hair2;
    ModelRenderer cape;
    ModelRenderer wing;
    ModelRenderer wing2;
    ModelRenderer c20;
    ModelRenderer c19;
    ModelRenderer puipui1;
    ModelRenderer puipui2;
    ModelRenderer puipui3;
    ModelRenderer puipui4;
    ModelRenderer Dear1;
    ModelRenderer Dear2;
    private float F = 1.0f;
    private boolean Y = false;
    private boolean Y2 = false;

    public ModelRaditz2(float f, boolean y) {
        this();
        this.F = f;
        this.Y = y;
    }

    public ModelRaditz2() {
        this.textureWidth = 128;
        this.textureHeight = 64;
        this.head = new ModelRenderer((ModelBase)this, 0, 0);
        this.head.addBox(-4.0f, -8.0f, -4.0f, 8, 8, 8);
        this.head.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.head.setTextureSize(128, 64);
        this.body = new ModelRenderer((ModelBase)this, 16, 16);
        this.body.addBox(-4.0f, 0.0f, -2.0f, 8, 12, 4);
        this.body.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.body.setTextureSize(128, 64);
        this.rightarm = new ModelRenderer((ModelBase)this, 40, 16);
        this.rightarm.addBox(-3.0f, -2.0f, -2.0f, 4, 12, 4);
        this.rightarm.setRotationPoint(-5.0f, 2.0f, 0.0f);
        this.rightarm.setTextureSize(128, 64);
        this.leftarm = new ModelRenderer((ModelBase)this, 40, 16);
        this.leftarm.mirror = true;
        this.leftarm.addBox(-1.0f, -2.0f, -2.0f, 4, 12, 4);
        this.leftarm.setRotationPoint(5.0f, 2.0f, 0.0f);
        this.leftarm.setTextureSize(128, 64);
        this.rightleg = new ModelRenderer((ModelBase)this, 0, 16);
        this.rightleg.addBox(-2.0f, 0.0f, -2.0f, 4, 12, 4);
        this.rightleg.setRotationPoint(-2.0f, 12.0f, 0.0f);
        this.rightleg.setTextureSize(128, 64);
        this.leftleg = new ModelRenderer((ModelBase)this, 0, 16);
        this.leftleg.mirror = true;
        this.leftleg.addBox(-2.0f, 0.0f, -2.0f, 4, 12, 4);
        this.leftleg.setRotationPoint(2.0f, 12.0f, 0.0f);
        this.leftleg.setTextureSize(128, 64);
        this.headhair = new ModelRenderer((ModelBase)this, 56, 0);
        this.headhair.addBox(-5.0f, -9.0f, -5.0f, 10, 20, 10);
        this.headhair.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.headhair.setTextureSize(128, 64);
        this.rightarmshoulder = new ModelRenderer((ModelBase)this, 40, 32);
        this.rightarmshoulder.addBox(-6.0f, -3.0f, -3.0f, 7, 4, 6);
        this.rightarmshoulder.setRotationPoint(-5.0f, 2.0f, 0.0f);
        this.rightarmshoulder.setTextureSize(128, 64);
        this.leftarmshoulder = new ModelRenderer((ModelBase)this, 40, 32);
        this.leftarmshoulder.mirror = true;
        this.leftarmshoulder.addBox(-1.0f, -3.0f, -3.0f, 7, 4, 6);
        this.leftarmshoulder.setRotationPoint(5.0f, 2.0f, 0.0f);
        this.leftarmshoulder.setTextureSize(128, 64);
        this.cui1 = new ModelRenderer((ModelBase)this, 0, 32);
        this.cui1.addBox(2.0f, -9.0f, -3.0f, 3, 3, 3);
        this.cui1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.cui1.setTextureSize(128, 64);
        this.cui1.mirror = true;
        this.setRotation(this.cui1, 0.0f, 0.0f, 0.0f);
        this.cui2 = new ModelRenderer((ModelBase)this, 0, 32);
        this.cui2.addBox(-5.0f, -9.0f, -3.0f, 3, 3, 3);
        this.cui2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.cui2.setTextureSize(128, 64);
        this.cui2.mirror = true;
        this.setRotation(this.cui2, 0.0f, 0.0f, 0.0f);
        this.spikes1 = new ModelRenderer((ModelBase)this, 18, 32);
        this.spikes1.addBox(0.0f, -10.0f, 0.0f, 1, 3, 1);
        this.spikes1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.spikes1.setTextureSize(128, 64);
        this.spikes1.mirror = true;
        this.setRotation(this.spikes1, 0.0f, 0.0f, 0.0f);
        this.spikes2 = new ModelRenderer((ModelBase)this, 18, 32);
        this.spikes2.addBox(3.0f, -10.0f, 1.0f, 1, 3, 1);
        this.spikes2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.spikes2.setTextureSize(128, 64);
        this.spikes2.mirror = true;
        this.setRotation(this.spikes2, 0.0f, 0.0f, 0.0f);
        this.spikes3 = new ModelRenderer((ModelBase)this, 18, 32);
        this.spikes3.addBox(2.0f, -10.0f, -3.0f, 1, 3, 1);
        this.spikes3.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.spikes3.setTextureSize(128, 64);
        this.spikes3.mirror = true;
        this.setRotation(this.spikes3, 0.0f, 0.0f, 0.0f);
        this.spikes4 = new ModelRenderer((ModelBase)this, 18, 32);
        this.spikes4.addBox(-2.0f, -10.0f, -2.0f, 1, 3, 1);
        this.spikes4.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.spikes4.setTextureSize(128, 64);
        this.spikes4.mirror = true;
        this.setRotation(this.spikes4, 0.0f, 0.0f, 0.0f);
        this.spikes5 = new ModelRenderer((ModelBase)this, 18, 32);
        this.spikes5.addBox(-3.0f, -10.0f, 2.0f, 1, 3, 1);
        this.spikes5.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.spikes5.setTextureSize(128, 64);
        this.spikes5.mirror = true;
        this.setRotation(this.spikes5, 0.0f, 0.0f, 0.0f);
        this.spikes6 = new ModelRenderer((ModelBase)this, 18, 32);
        this.spikes6.addBox(1.0f, -10.0f, 3.0f, 1, 3, 1);
        this.spikes6.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.spikes6.setTextureSize(128, 64);
        this.spikes6.mirror = true;
        this.setRotation(this.spikes6, 0.0f, 0.0f, 0.0f);
        this.spikes7 = new ModelRenderer((ModelBase)this, 18, 32);
        this.spikes7.addBox(-1.0f, -10.0f, -4.0f, 1, 3, 1);
        this.spikes7.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.spikes7.setTextureSize(128, 64);
        this.spikes7.mirror = true;
        this.setRotation(this.spikes7, 0.0f, 0.0f, 0.0f);
        this.spikes8 = new ModelRenderer((ModelBase)this, 18, 32);
        this.spikes8.addBox(-4.0f, -10.0f, -1.0f, 1, 3, 1);
        this.spikes8.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.spikes8.setTextureSize(128, 64);
        this.spikes8.mirror = true;
        this.setRotation(this.spikes8, 0.0f, 0.0f, 0.0f);
        this.ear1 = new ModelRenderer((ModelBase)this, 12, 32);
        this.ear1.addBox(-5.0f, -5.0f, -3.0f, 1, 3, 2);
        this.ear1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.ear1.setTextureSize(128, 64);
        this.ear1.mirror = true;
        this.setRotation(this.ear1, -0.4014257f, 0.0f, 0.0f);
        this.ear2 = new ModelRenderer((ModelBase)this, 12, 32);
        this.ear2.addBox(4.0f, -5.0f, -3.0f, 1, 3, 2);
        this.ear2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.ear2.setTextureSize(128, 64);
        this.ear2.mirror = true;
        this.setRotation(this.ear2, -0.4014257f, 0.0f, 0.0f);
        this.horn2 = new ModelRenderer((ModelBase)this, 0, 38);
        this.horn2.addBox(-2.5f, -11.0f, -3.5f, 2, 4, 2);
        this.horn2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.horn2.setTextureSize(128, 64);
        this.horn2.mirror = true;
        this.setRotation(this.horn2, 0.0f, 0.0f, -0.2094395f);
        this.horn1 = new ModelRenderer((ModelBase)this, 0, 38);
        this.horn1.addBox(0.5f, -11.0f, -3.5f, 2, 4, 2);
        this.horn1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.horn1.setTextureSize(128, 64);
        this.horn1.mirror = true;
        this.setRotation(this.horn1, 0.0f, 0.0f, 0.2094395f);
        this.appule = new ModelRenderer((ModelBase)this, 0, 48);
        this.appule.addBox(-4.0f, -8.0f, 4.0f, 8, 8, 8);
        this.appule.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.appule.setTextureSize(128, 64);
        this.appule.mirror = true;
        this.setRotation(this.appule, 0.0f, 0.0f, 0.0f);
        this.Fhorn2 = new ModelRenderer((ModelBase)this, 8, 38);
        this.Fhorn2.addBox(1.5f, -11.0f, -3.5f, 2, 4, 2);
        this.Fhorn2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.Fhorn2.setTextureSize(128, 64);
        this.Fhorn2.mirror = true;
        this.setRotation(this.Fhorn2, 0.0f, 0.0f, -0.7853982f);
        this.Fhorn1 = new ModelRenderer((ModelBase)this, 8, 38);
        this.Fhorn1.addBox(-3.5f, -11.0f, -3.5f, 2, 4, 2);
        this.Fhorn1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.Fhorn1.setTextureSize(128, 64);
        this.Fhorn1.mirror = true;
        this.setRotation(this.Fhorn1, 0.0f, 0.0f, 0.7853982f);
        this.Fhorn3 = new ModelRenderer((ModelBase)this, 8, 38);
        this.Fhorn3.addBox(2.5f, -14.0f, -3.5f, 2, 4, 2);
        this.Fhorn3.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.Fhorn3.setTextureSize(128, 64);
        this.Fhorn3.mirror = true;
        this.setRotation(this.Fhorn3, 0.0f, 0.0f, 0.2094395f);
        this.Fhorn4 = new ModelRenderer((ModelBase)this, 8, 38);
        this.Fhorn4.addBox(-4.5f, -14.0f, -3.5f, 2, 4, 2);
        this.Fhorn4.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.Fhorn4.setTextureSize(128, 64);
        this.Fhorn4.mirror = true;
        this.setRotation(this.Fhorn4, 0.0f, 0.0f, -0.2094395f);
        this.F2horn1 = new ModelRenderer((ModelBase)this, 16, 38);
        this.F2horn1.addBox(-3.5f, -11.0f, 6.5f, 2, 4, 2);
        this.F2horn1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.F2horn1.setTextureSize(128, 64);
        this.F2horn1.mirror = true;
        this.setRotation(this.F2horn1, 0.0f, 0.0f, 0.7853982f);
        this.F2horn2 = new ModelRenderer((ModelBase)this, 16, 38);
        this.F2horn2.addBox(1.5f, -11.0f, 6.5f, 2, 4, 2);
        this.F2horn2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.F2horn2.setTextureSize(128, 64);
        this.F2horn2.mirror = true;
        this.setRotation(this.F2horn2, 0.0f, 0.0f, -0.7853982f);
        this.tail1 = new ModelRenderer((ModelBase)this, 32, 48);
        this.tail1.addBox(-2.0f, 7.0f, 4.0f, 4, 4, 12);
        this.tail1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.tail1.setTextureSize(128, 64);
        this.tail1.mirror = true;
        this.setRotation(this.tail1, -0.3490659f, 0.0f, 0.0f);
        this.tail2 = new ModelRenderer((ModelBase)this, 32, 48);
        this.tail2.addBox(-2.0f, 15.0f, 2.0f, 4, 4, 12);
        this.tail2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.tail2.setTextureSize(128, 64);
        this.tail2.mirror = true;
        this.setRotation(this.tail2, 0.5235988f, 0.0f, 0.0f);
        this.celltail = new ModelRenderer((ModelBase)this, 32, 48);
        this.celltail.addBox(-0.5f, 16.5f, 14.0f, 1, 1, 4);
        this.celltail.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.celltail.setTextureSize(128, 64);
        this.cellhead1 = new ModelRenderer((ModelBase)this, 108, 50);
        this.cellhead1.addBox(-2.5f, -14.0f, -3.5f, 3, 7, 7);
        this.cellhead1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.cellhead1.setTextureSize(128, 64);
        this.setRotation(this.cellhead1, 0.0f, 0.0f, -0.2094395f);
        this.cellhead3 = new ModelRenderer((ModelBase)this, 108, 50);
        this.cellhead3.addBox(-2.5f, -10.0f, -3.5f, 3, 3, 7);
        this.cellhead3.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.cellhead3.setTextureSize(128, 64);
        this.setRotation(this.cellhead3, 0.0f, 0.0f, -0.2094395f);
        this.cellhead2 = new ModelRenderer((ModelBase)this, 108, 50);
        this.cellhead2.mirror = true;
        this.cellhead2.addBox(-0.5f, -14.0f, -3.5f, 3, 7, 7);
        this.cellhead2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.cellhead2.setTextureSize(128, 64);
        this.setRotation(this.cellhead2, 0.0f, 0.0f, 0.2094395f);
        this.cellhead4 = new ModelRenderer((ModelBase)this, 108, 50);
        this.cellhead4.mirror = true;
        this.cellhead4.addBox(-0.5f, -10.0f, -3.5f, 3, 3, 7);
        this.cellhead4.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.cellhead4.setTextureSize(128, 64);
        this.setRotation(this.cellhead4, 0.0f, 0.0f, 0.2094395f);
        this.cell1head = new ModelRenderer((ModelBase)this, 108, 44);
        this.cell1head.addBox(-5.0f, -10.0f, -6.5f, 10, 4, 2);
        this.cell1head.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.cell1head.setTextureSize(128, 64);
        this.setRotation(this.cell1head, -0.3490659f, 0.0f, 0.0f);
        this.hair1 = new ModelRenderer((ModelBase)this, 82, 47);
        this.hair1.addBox(2.0f, -8.0f, -4.5f, 4, 8, 9);
        this.hair1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.hair1.setTextureSize(128, 64);
        this.setRotation(this.hair1, 0.0f, 0.0174533f, -0.2617994f);
        this.hair2 = new ModelRenderer((ModelBase)this, 82, 47);
        this.hair2.mirror = true;
        this.hair2.addBox(-6.0f, -8.0f, -4.5f, 4, 8, 9);
        this.hair2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.hair2.setTextureSize(128, 64);
        this.setRotation(this.hair2, 0.0f, 0.0f, 0.2617994f);
        this.cape = new ModelRenderer((ModelBase)this, 100, 0);
        this.cape.addBox(-7.0f, 1.0f, 2.0f, 14, 20, 0);
        this.cape.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.cape.setTextureSize(128, 64);
        this.setRotation(this.cape, 0.1570796f, 0.0f, 0.0f);
        this.wing = new ModelRenderer((ModelBase)this, 114, 20);
        this.wing.addBox(-1.0f, 2.0f, 2.0f, 7, 20, 0);
        this.wing.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.wing.setTextureSize(128, 64);
        this.setRotation(this.wing, 0.1570796f, 0.0349066f, -0.2792527f);
        this.wing2 = new ModelRenderer((ModelBase)this, 114, 20);
        this.wing2.mirror = true;
        this.wing2.addBox(-6.0f, 2.0f, 2.0f, 7, 20, 0);
        this.wing2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.wing2.setTextureSize(128, 64);
        this.setRotation(this.wing2, 0.1570796f, -0.0349066f, 0.2792527f);
        this.c20 = new ModelRenderer((ModelBase)this, 76, 35);
        this.c20.addBox(-4.0f, -12.0f, -4.0f, 8, 4, 8);
        this.c20.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.c20.setTextureSize(128, 64);
        this.c20.mirror = true;
        this.setRotation(this.c20, 0.0f, 0.0f, 0.0f);
        this.c19 = new ModelRenderer((ModelBase)this, 106, 29);
        this.c19.addBox(-1.0f, -11.0f, -0.5f, 2, 4, 2);
        this.c19.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.c19.setTextureSize(128, 64);
        this.c19.mirror = true;
        this.setRotation(this.c19, 0.0f, 0.0f, 0.0f);
        this.puipui1 = new ModelRenderer((ModelBase)this, 53, 48);
        this.puipui1.addBox(0.5f, -8.0f, 2.5f, 2, 8, 2);
        this.puipui1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.puipui1.setTextureSize(128, 64);
        this.setRotation(this.puipui1, -1.047198f, 0.4363323f, 0.0f);
        this.puipui2 = new ModelRenderer((ModelBase)this, 53, 48);
        this.puipui2.addBox(-2.5f, -8.0f, 2.5f, 2, 8, 2);
        this.puipui2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.puipui2.setTextureSize(128, 64);
        this.setRotation(this.puipui2, -1.047198f, -0.4363323f, 0.0f);
        this.puipui3 = new ModelRenderer((ModelBase)this, 53, 48);
        this.puipui3.addBox(0.5f, -12.4f, -0.3f, 2, 4, 2);
        this.puipui3.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.puipui3.setTextureSize(128, 64);
        this.setRotation(this.puipui3, -1.396263f, 0.4380776f, 0.0f);
        this.puipui4 = new ModelRenderer((ModelBase)this, 53, 48);
        this.puipui4.addBox(-2.5f, -12.4f, -0.3f, 2, 4, 2);
        this.puipui4.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.puipui4.setTextureSize(128, 64);
        this.setRotation(this.puipui4, -1.396263f, -0.4380776f, 0.0f);
        this.Dear1 = new ModelRenderer((ModelBase)this, 22, 29);
        this.Dear1.addBox(-3.0f, -9.0f, -2.0f, 0, 6, 3);
        this.Dear1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.setRotation(this.Dear1, -0.6981317f, -1.047198f, 0.0f);
        this.Dear2 = new ModelRenderer((ModelBase)this, 22, 29);
        this.Dear2.addBox(3.0f, -9.0f, -2.0f, 0, 6, 3);
        this.Dear2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.Dear2.mirror = true;
        this.setRotation(this.Dear2, -0.6981317f, 1.047198f, 0.0f);
        this.body.addChild(this.puipui1);
        this.body.addChild(this.puipui2);
        this.body.addChild(this.puipui3);
        this.body.addChild(this.puipui4);
        this.head.addChild(this.Dear1);
        this.head.addChild(this.Dear2);
        this.head.addChild(this.hair2);
        this.head.addChild(this.hair1);
        this.head.addChild(this.cell1head);
        this.head.addChild(this.cellhead3);
        this.head.addChild(this.cellhead4);
        this.head.addChild(this.c20);
        this.head.addChild(this.c19);
        this.tail2.addChild(this.celltail);
        this.body.addChild(this.wing);
        this.body.addChild(this.wing2);
        this.body.addChild(this.cape);
        this.head.addChild(this.cui1);
        this.head.addChild(this.cui2);
        this.head.addChild(this.spikes1);
        this.head.addChild(this.spikes2);
        this.head.addChild(this.spikes3);
        this.head.addChild(this.spikes4);
        this.head.addChild(this.spikes5);
        this.head.addChild(this.spikes6);
        this.head.addChild(this.spikes7);
        this.head.addChild(this.spikes8);
        this.head.addChild(this.ear1);
        this.head.addChild(this.ear2);
        this.head.addChild(this.horn2);
        this.head.addChild(this.horn1);
        this.head.addChild(this.appule);
        this.head.addChild(this.Fhorn2);
        this.head.addChild(this.Fhorn1);
        this.head.addChild(this.Fhorn3);
        this.head.addChild(this.Fhorn4);
        this.head.addChild(this.F2horn1);
        this.head.addChild(this.F2horn2);
        this.body.addChild(this.tail1);
        this.body.addChild(this.tail2);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        GL11.glPushMatrix();
        GL11.glScalef((float)this.F, (float)this.F, (float)this.F);
        if (!this.Y2) {
            GL11.glTranslatef((float)0.0f, (float)((this.F - 1.0f) * -0.74f), (float)0.0f);
            if (this.Y) {
                GL11.glTranslatef((float)0.0f, (float)((this.F - 1.0f) * -0.74f * 3.65f), (float)0.0f);
            }
        } else {
            float ff1 = -2.45f;
            float ff2 = 0.6f;
            float diff = ff2 / this.F * ff1;
            GL11.glTranslatef((float)0.0f, (float)((this.F - 1.0f) * diff), (float)0.0f);
        }
        this.head.render(f5);
        if (this.Y) {
            GL11.glScalef((float)this.F, (float)this.F, (float)this.F);
        }
        this.body.render(f5);
        this.rightarm.render(f5);
        this.leftarm.render(f5);
        this.rightleg.render(f5);
        this.leftleg.render(f5);
        this.headhair.render(f5);
        this.leftarmshoulder.render(f5);
        this.rightarmshoulder.render(f5);
        GL11.glPopMatrix();
    }

    public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity) {
        this.head.rotateAngleY = par4 / 57.295776f;
        this.head.rotateAngleX = par5 / 57.295776f;
        this.headhair.rotateAngleY = this.head.rotateAngleY;
        this.headhair.rotateAngleX = this.head.rotateAngleX;
        this.rightarmshoulder.rotateAngleX = this.rightarm.rotateAngleX = MathHelper.cos((float)(par1 * 0.6662f + (float)Math.PI)) * 2.0f * par2 * 0.5f;
        this.leftarmshoulder.rotateAngleX = this.leftarm.rotateAngleX = MathHelper.cos((float)(par1 * 0.6662f)) * 2.0f * par2 * 0.5f;
        this.rightarmshoulder.rotateAngleZ = this.rightarm.rotateAngleZ = 0.0f;
        this.leftarmshoulder.rotateAngleZ = this.leftarm.rotateAngleZ = 0.0f;
        this.rightleg.rotateAngleX = MathHelper.cos((float)(par1 * 0.6662f)) * 1.4f * par2;
        this.leftleg.rotateAngleX = MathHelper.cos((float)(par1 * 0.6662f + (float)Math.PI)) * 1.4f * par2;
        this.rightleg.rotateAngleY = 0.0f;
        this.leftleg.rotateAngleY = 0.0f;
        if (this.isRiding) {
            this.rightarm.rotateAngleX += -0.62831855f;
            this.rightarmshoulder.rotateAngleX = this.rightarm.rotateAngleX;
            this.leftarm.rotateAngleX += -0.62831855f;
            this.leftarmshoulder.rotateAngleX = this.leftarm.rotateAngleX;
            this.rightleg.rotateAngleX = -1.2566371f;
            this.leftleg.rotateAngleX = -1.2566371f;
            this.rightleg.rotateAngleY = 0.31415927f;
            this.leftleg.rotateAngleY = -0.31415927f;
        }
        this.rightarmshoulder.rotateAngleY = this.rightarm.rotateAngleY = 0.0f;
        this.leftarmshoulder.rotateAngleY = this.leftarm.rotateAngleY = 0.0f;
        if (this.onGround > -9990.0f) {
            float var8 = this.onGround;
            this.body.rotateAngleY = MathHelper.sin((float)(MathHelper.sqrt_float((float)var8) * (float)Math.PI * 2.0f)) * 0.2f;
            this.rightarm.rotationPointZ = MathHelper.sin((float)this.body.rotateAngleY) * 5.0f;
            this.rightarm.rotationPointX = -MathHelper.cos((float)this.body.rotateAngleY) * 5.0f;
            this.leftarm.rotationPointZ = -MathHelper.sin((float)this.body.rotateAngleY) * 5.0f;
            this.leftarm.rotationPointX = MathHelper.cos((float)this.body.rotateAngleY) * 5.0f;
            this.rightarm.rotateAngleY += this.body.rotateAngleY;
            this.leftarm.rotateAngleY += this.body.rotateAngleY;
            this.leftarm.rotateAngleX += this.body.rotateAngleY;
            this.rightarmshoulder.rotationPointZ = MathHelper.sin((float)this.body.rotateAngleY) * 5.0f;
            this.rightarmshoulder.rotationPointX = -MathHelper.cos((float)this.body.rotateAngleY) * 5.0f;
            this.leftarmshoulder.rotationPointZ = -MathHelper.sin((float)this.body.rotateAngleY) * 5.0f;
            this.leftarmshoulder.rotationPointX = MathHelper.cos((float)this.body.rotateAngleY) * 5.0f;
            this.rightarmshoulder.rotateAngleY += this.body.rotateAngleY;
            this.leftarmshoulder.rotateAngleY += this.body.rotateAngleY;
            this.leftarmshoulder.rotateAngleX += this.body.rotateAngleY;
            var8 = 1.0f - this.onGround;
            var8 *= var8;
            var8 *= var8;
            var8 = 1.0f - var8;
            float var9 = MathHelper.sin((float)(var8 * (float)Math.PI));
            float var10 = MathHelper.sin((float)(this.onGround * (float)Math.PI)) * -(this.head.rotateAngleX - 0.7f) * 0.75f;
            this.rightarm.rotateAngleX = (float)((double)this.rightarm.rotateAngleX - ((double)var9 * 1.2 + (double)var10));
            this.rightarm.rotateAngleY += this.body.rotateAngleY * 2.0f;
            this.rightarm.rotateAngleZ = MathHelper.sin((float)(this.onGround * (float)Math.PI)) * -0.4f;
            this.rightarmshoulder.rotateAngleX = (float)((double)this.rightarm.rotateAngleX - ((double)var9 * 1.2 + (double)var10));
            this.rightarmshoulder.rotateAngleY += this.body.rotateAngleY * 2.0f;
            this.rightarmshoulder.rotateAngleZ = MathHelper.sin((float)(this.onGround * (float)Math.PI)) * -0.4f;
        }
        this.rightarm.rotateAngleZ += MathHelper.cos((float)(par3 * 0.09f)) * 0.05f + 0.05f;
        this.rightarmshoulder.rotateAngleZ = this.rightarm.rotateAngleZ;
        this.leftarm.rotateAngleZ -= MathHelper.cos((float)(par3 * 0.09f)) * 0.05f + 0.05f;
        this.leftarmshoulder.rotateAngleZ = this.leftarm.rotateAngleZ;
        this.rightarm.rotateAngleX += MathHelper.sin((float)(par3 * 0.067f)) * 0.05f;
        this.rightarmshoulder.rotateAngleX = this.rightarm.rotateAngleX;
        this.leftarm.rotateAngleX -= MathHelper.sin((float)(par3 * 0.067f)) * 0.05f;
        this.leftarmshoulder.rotateAngleX = this.leftarm.rotateAngleX;
    }
}

