/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  JinRyuu.JRMCore.JRMCoreComTickH
 *  JinRyuu.JRMCore.JRMCoreH
 *  cpw.mods.fml.common.FMLCommonHandler
 *  net.minecraft.block.Block
 *  net.minecraft.init.Blocks
 *  net.minecraft.server.MinecraftServer
 *  net.minecraft.world.World
 */
package JinRyuu.DragonBC.common.Villages;

import JinRyuu.DragonBC.common.Villages.bsP2;
import JinRyuu.DragonBC.common.Villages.builds;
import JinRyuu.DragonBC.common.Worlds.WorldGeneratorDB;
import JinRyuu.DragonBC.common.mod_DragonBC;
import JinRyuu.JRMCore.JRMCoreComTickH;
import JinRyuu.JRMCore.JRMCoreH;
import cpw.mods.fml.common.FMLCommonHandler;
import java.util.Random;
import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.server.MinecraftServer;
import net.minecraft.world.World;

public class bs
extends builds {
    protected World w;
    private int onSurface = 5;

    public bs() {
        SizeX = 29;
        SizeZ = 45;
        SizeY = 66 - this.onSurface;
    }

    @Override
    public boolean generate(World w, Random rand, int i, int j, int k) {
        this.w = w;
        SizeX = 29;
        SizeZ = 45;
        SizeY = 66 - this.onSurface;
        int gen = 3;
        WorldGeneratorDB.DBbuildsSpawn(gen, false);
        MinecraftServer server = FMLCommonHandler.instance().getMinecraftServerInstance();
        JRMCoreComTickH.bs = JRMCoreH.bsrwi((MinecraftServer)server);
        if (JRMCoreComTickH.bs.contains(WorldGeneratorDB.DBbuildsNams2(3)) && !this.respawn) {
            return false;
        }
        JRMCoreComTickH.bs = JRMCoreComTickH.bs + ";" + WorldGeneratorDB.DBbuildsNams2(3);
        JRMCoreH.bswwi((MinecraftServer)server, (String)JRMCoreComTickH.bs, (boolean)false);
        this.respawn = false;
        mod_DragonBC.logger.info(WorldGeneratorDB.DBbuildsNams(gen) + " spawned " + i + " " + k);
        return this.generateBuilding(w, rand, i, j, k);
    }

    /*
     * Opcode count of 20081 triggered aggressive code reduction.  Override with --aggressivesizethreshold.
     */
    @Override
    public boolean generateBuilding(World w, Random rand, int i, int j, int k) {
        if (!this.check) {
            for (int ix = 0; ix <= SizeX; ++ix) {
                for (int iz = 0; iz <= SizeZ; ++iz) {
                    int var = 0;
                    for (int iy = j + SizeY; iy < j + SizeY + 50; ++iy) {
                        ++var;
                        this.b(i + ix, iy, k + iz, Blocks.air);
                        if (iy >= j + SizeY + 10) continue;
                        for (int var2 = 0; var2 < var; ++var2) {
                            this.b(i + ix + var2, iy, k + iz + var2, Blocks.air);
                            if (w.getBlock(i + ix + var2, iy - 1, k + iz + var2) != Blocks.air) {
                                this.b(i + ix + var2, iy - 1, k + iz + var2, (Block)Blocks.grass);
                            }
                            this.b(i + ix - var2, iy, k + iz - var2, Blocks.air);
                            if (w.getBlock(i + ix - var2, iy - 1, k + iz - var2) != Blocks.air) {
                                this.b(i + ix - var2, iy - 1, k + iz - var2, (Block)Blocks.grass);
                            }
                            this.b(i + ix, iy, k + iz + var2, Blocks.air);
                            if (w.getBlock(i + ix, iy - 1, k + iz + var2) != Blocks.air) {
                                this.b(i + ix, iy - 1, k + iz + var2, (Block)Blocks.grass);
                            }
                            this.b(i + ix, iy, k + iz - var2, Blocks.air);
                            if (w.getBlock(i + ix, iy - 1, k + iz - var2) != Blocks.air) {
                                this.b(i + ix, iy - 1, k + iz - var2, (Block)Blocks.grass);
                            }
                            this.b(i + ix + var2, iy, k + iz, Blocks.air);
                            if (w.getBlock(i + ix + var2, iy - 1, k + iz) != Blocks.air) {
                                this.b(i + ix + var2, iy - 1, k + iz, (Block)Blocks.grass);
                            }
                            this.b(i + ix - var2, iy, k + iz, Blocks.air);
                            if (w.getBlock(i + ix - var2, iy - 1, k + iz) == Blocks.air) continue;
                            this.b(i + ix - var2, iy - 1, k + iz, (Block)Blocks.grass);
                        }
                    }
                }
            }
        }
        this.b(i + 0, j + 0, k + 8, this.c, 10);
        this.b(i + 0, j + 0, k + 9, this.c, 10);
        this.b(i + 0, j + 0, k + 10, this.c, 10);
        this.b(i + 0, j + 0, k + 11, this.c, 10);
        this.b(i + 0, j + 0, k + 12, this.c, 10);
        this.b(i + 0, j + 0, k + 13, this.c, 10);
        this.b(i + 0, j + 0, k + 14, this.c, 10);
        this.b(i + 0, j + 0, k + 15, this.c, 10);
        this.b(i + 0, j + 0, k + 16, this.c, 10);
        this.b(i + 0, j + 0, k + 17, this.c, 10);
        this.b(i + 0, j + 0, k + 18, this.c, 10);
        this.b(i + 0, j + 0, k + 19, this.c, 10);
        this.b(i + 0, j + 0, k + 20, this.c, 10);
        this.b(i + 0, j + 0, k + 21, this.c, 10);
        this.b(i + 0, j + 0, k + 22, this.c, 10);
        this.b(i + 0, j + 0, k + 23, this.c, 10);
        this.b(i + 0, j + 0, k + 24, this.c, 10);
        this.b(i + 0, j + 0, k + 25, this.c, 10);
        this.b(i + 0, j + 0, k + 26, this.c, 10);
        this.b(i + 0, j + 0, k + 27, this.c, 10);
        this.b(i + 0, j + 0, k + 28, this.c, 10);
        this.b(i + 0, j + 0, k + 29, this.c, 10);
        this.b(i + 0, j + 0, k + 30, this.c, 10);
        this.b(i + 0, j + 0, k + 31, this.c, 10);
        this.b(i + 0, j + 0, k + 32, this.c, 10);
        this.b(i + 0, j + 0, k + 33, this.c, 10);
        this.b(i + 0, j + 0, k + 34, this.c, 10);
        this.b(i + 0, j + 0, k + 35, this.c, 10);
        this.b(i + 0, j + 0, k + 36, this.c, 10);
        this.b(i + 0, j + 0, k + 37, this.c, 10);
        this.b(i + 0, j + 1, k + 8, this.air);
        this.b(i + 0, j + 1, k + 9, this.air);
        this.b(i + 0, j + 1, k + 10, this.air);
        this.b(i + 0, j + 1, k + 11, this.air);
        this.b(i + 0, j + 1, k + 12, this.air);
        this.b(i + 0, j + 1, k + 13, this.air);
        this.b(i + 0, j + 1, k + 14, this.air);
        this.b(i + 0, j + 1, k + 15, this.air);
        this.b(i + 0, j + 1, k + 16, this.air);
        this.b(i + 0, j + 1, k + 17, this.air);
        this.b(i + 0, j + 1, k + 18, this.air);
        this.b(i + 0, j + 1, k + 19, this.c, 11);
        this.b(i + 0, j + 1, k + 20, this.c, 11);
        this.b(i + 0, j + 1, k + 21, this.c, 11);
        this.b(i + 0, j + 1, k + 22, this.c, 11);
        this.b(i + 0, j + 1, k + 23, this.c, 11);
        this.b(i + 0, j + 1, k + 24, this.c, 11);
        this.b(i + 0, j + 1, k + 25, this.c, 11);
        this.b(i + 0, j + 1, k + 26, this.c, 11);
        this.b(i + 0, j + 1, k + 27, this.air);
        this.b(i + 0, j + 1, k + 28, this.air);
        this.b(i + 0, j + 1, k + 29, this.air);
        this.b(i + 0, j + 1, k + 30, this.air);
        this.b(i + 0, j + 1, k + 31, this.air);
        this.b(i + 0, j + 1, k + 32, this.air);
        this.b(i + 0, j + 1, k + 33, this.air);
        this.b(i + 0, j + 1, k + 34, this.air);
        this.b(i + 0, j + 1, k + 35, this.air);
        this.b(i + 0, j + 1, k + 36, this.air);
        this.b(i + 0, j + 1, k + 37, this.air);
        this.b(i + 0, j + 2, k + 8, this.air);
        this.b(i + 0, j + 2, k + 9, this.air);
        this.b(i + 0, j + 2, k + 10, this.air);
        this.b(i + 0, j + 2, k + 11, this.air);
        this.b(i + 0, j + 2, k + 12, this.air);
        this.b(i + 0, j + 2, k + 13, this.air);
        this.b(i + 0, j + 2, k + 14, this.air);
        this.b(i + 0, j + 2, k + 15, this.air);
        this.b(i + 0, j + 2, k + 16, this.air);
        this.b(i + 0, j + 2, k + 17, this.air);
        this.b(i + 0, j + 2, k + 18, this.air);
        this.b(i + 0, j + 2, k + 19, this.c, 11);
        this.b(i + 0, j + 2, k + 20, this.c, 11);
        this.b(i + 0, j + 2, k + 21, this.c, 11);
        this.b(i + 0, j + 2, k + 22, this.c, 11);
        this.b(i + 0, j + 2, k + 23, this.c, 11);
        this.b(i + 0, j + 2, k + 24, this.c, 11);
        this.b(i + 0, j + 2, k + 25, this.c, 11);
        this.b(i + 0, j + 2, k + 26, this.c, 11);
        this.b(i + 0, j + 2, k + 27, this.air);
        this.b(i + 0, j + 2, k + 28, this.air);
        this.b(i + 0, j + 2, k + 29, this.air);
        this.b(i + 0, j + 2, k + 30, this.air);
        this.b(i + 0, j + 2, k + 31, this.air);
        this.b(i + 0, j + 2, k + 32, this.air);
        this.b(i + 0, j + 2, k + 33, this.air);
        this.b(i + 0, j + 2, k + 34, this.air);
        this.b(i + 0, j + 2, k + 35, this.air);
        this.b(i + 0, j + 2, k + 36, this.air);
        this.b(i + 0, j + 2, k + 37, this.air);
        this.b(i + 0, j + 3, k + 8, this.air);
        this.b(i + 0, j + 3, k + 9, this.air);
        this.b(i + 0, j + 3, k + 10, this.air);
        this.b(i + 0, j + 3, k + 11, this.air);
        this.b(i + 0, j + 3, k + 12, this.air);
        this.b(i + 0, j + 3, k + 13, this.air);
        this.b(i + 0, j + 3, k + 14, this.air);
        this.b(i + 0, j + 3, k + 15, this.air);
        this.b(i + 0, j + 3, k + 16, this.air);
        this.b(i + 0, j + 3, k + 17, this.air);
        this.b(i + 0, j + 3, k + 18, this.air);
        this.b(i + 0, j + 3, k + 19, this.c, 11);
        this.b(i + 0, j + 3, k + 20, this.c, 11);
        this.b(i + 0, j + 3, k + 21, this.c, 11);
        this.b(i + 0, j + 3, k + 22, this.c, 11);
        this.b(i + 0, j + 3, k + 23, this.c, 11);
        this.b(i + 0, j + 3, k + 24, this.c, 11);
        this.b(i + 0, j + 3, k + 25, this.c, 11);
        this.b(i + 0, j + 3, k + 26, this.c, 11);
        this.b(i + 0, j + 3, k + 27, this.air);
        this.b(i + 0, j + 3, k + 28, this.air);
        this.b(i + 0, j + 3, k + 29, this.air);
        this.b(i + 0, j + 3, k + 30, this.air);
        this.b(i + 0, j + 3, k + 31, this.air);
        this.b(i + 0, j + 3, k + 32, this.air);
        this.b(i + 0, j + 3, k + 33, this.air);
        this.b(i + 0, j + 3, k + 34, this.air);
        this.b(i + 0, j + 3, k + 35, this.air);
        this.b(i + 0, j + 3, k + 36, this.air);
        this.b(i + 0, j + 3, k + 37, this.air);
        this.b(i + 0, j + 4, k + 8, this.air);
        this.b(i + 0, j + 4, k + 9, this.air);
        this.b(i + 0, j + 4, k + 10, this.air);
        this.b(i + 0, j + 4, k + 11, this.air);
        this.b(i + 0, j + 4, k + 12, this.air);
        this.b(i + 0, j + 4, k + 13, this.air);
        this.b(i + 0, j + 4, k + 14, this.air);
        this.b(i + 0, j + 4, k + 15, this.air);
        this.b(i + 0, j + 4, k + 16, this.air);
        this.b(i + 0, j + 4, k + 17, this.air);
        this.b(i + 0, j + 4, k + 18, this.air);
        this.b(i + 0, j + 4, k + 19, this.air);
        this.b(i + 0, j + 4, k + 20, this.c, 11);
        this.b(i + 0, j + 4, k + 21, this.c, 11);
        this.b(i + 0, j + 4, k + 22, this.c, 11);
        this.b(i + 0, j + 4, k + 23, this.c, 11);
        this.b(i + 0, j + 4, k + 24, this.c, 11);
        this.b(i + 0, j + 4, k + 25, this.c, 11);
        this.b(i + 0, j + 4, k + 26, this.air);
        this.b(i + 0, j + 4, k + 27, this.air);
        this.b(i + 0, j + 4, k + 28, this.air);
        this.b(i + 0, j + 4, k + 29, this.air);
        this.b(i + 0, j + 4, k + 30, this.air);
        this.b(i + 0, j + 4, k + 31, this.air);
        this.b(i + 0, j + 4, k + 32, this.air);
        this.b(i + 0, j + 4, k + 33, this.air);
        this.b(i + 0, j + 4, k + 34, this.air);
        this.b(i + 0, j + 4, k + 35, this.air);
        this.b(i + 0, j + 4, k + 36, this.air);
        this.b(i + 0, j + 4, k + 37, this.air);
        this.b(i + 0, j + 5, k + 8, this.air);
        this.b(i + 0, j + 5, k + 9, this.air);
        this.b(i + 0, j + 5, k + 10, this.air);
        this.b(i + 0, j + 5, k + 11, this.air);
        this.b(i + 0, j + 5, k + 12, this.air);
        this.b(i + 0, j + 5, k + 13, this.air);
        this.b(i + 0, j + 5, k + 14, this.air);
        this.b(i + 0, j + 5, k + 15, this.air);
        this.b(i + 0, j + 5, k + 16, this.air);
        this.b(i + 0, j + 5, k + 17, this.air);
        this.b(i + 0, j + 5, k + 18, this.air);
        this.b(i + 0, j + 5, k + 19, this.air);
        this.b(i + 0, j + 5, k + 20, this.air);
        this.b(i + 0, j + 5, k + 21, this.air);
        this.b(i + 0, j + 5, k + 22, this.c, 4);
        this.b(i + 0, j + 5, k + 23, this.c, 4);
        this.b(i + 0, j + 5, k + 24, this.air);
        this.b(i + 0, j + 5, k + 25, this.air);
        this.b(i + 0, j + 5, k + 26, this.air);
        this.b(i + 0, j + 5, k + 27, this.air);
        this.b(i + 0, j + 5, k + 28, this.air);
        this.b(i + 0, j + 5, k + 29, this.air);
        this.b(i + 0, j + 5, k + 30, this.air);
        this.b(i + 0, j + 5, k + 31, this.air);
        this.b(i + 0, j + 5, k + 32, this.air);
        this.b(i + 0, j + 5, k + 33, this.air);
        this.b(i + 0, j + 5, k + 34, this.air);
        this.b(i + 0, j + 5, k + 35, this.air);
        this.b(i + 0, j + 5, k + 36, this.air);
        this.b(i + 0, j + 5, k + 37, this.air);
        this.b(i + 0, j + 6, k + 8, this.air);
        this.b(i + 0, j + 6, k + 9, this.air);
        this.b(i + 0, j + 6, k + 10, this.air);
        this.b(i + 0, j + 6, k + 11, this.air);
        this.b(i + 0, j + 6, k + 12, this.air);
        this.b(i + 0, j + 6, k + 13, this.air);
        this.b(i + 0, j + 6, k + 14, this.air);
        this.b(i + 0, j + 6, k + 15, this.air);
        this.b(i + 0, j + 6, k + 16, this.air);
        this.b(i + 0, j + 6, k + 17, this.air);
        this.b(i + 0, j + 6, k + 18, this.air);
        this.b(i + 0, j + 6, k + 19, this.air);
        this.b(i + 0, j + 6, k + 20, this.air);
        this.b(i + 0, j + 6, k + 21, this.air);
        this.b(i + 0, j + 6, k + 22, this.air);
        this.b(i + 0, j + 6, k + 23, this.air);
        this.b(i + 0, j + 6, k + 24, this.air);
        this.b(i + 0, j + 6, k + 25, this.air);
        this.b(i + 0, j + 6, k + 26, this.air);
        this.b(i + 0, j + 6, k + 27, this.air);
        this.b(i + 0, j + 6, k + 28, this.air);
        this.b(i + 0, j + 6, k + 29, this.air);
        this.b(i + 0, j + 6, k + 30, this.air);
        this.b(i + 0, j + 6, k + 31, this.air);
        this.b(i + 0, j + 6, k + 32, this.air);
        this.b(i + 0, j + 6, k + 33, this.air);
        this.b(i + 0, j + 6, k + 34, this.air);
        this.b(i + 0, j + 6, k + 35, this.air);
        this.b(i + 0, j + 6, k + 36, this.air);
        this.b(i + 0, j + 6, k + 37, this.air);
        this.b(i + 0, j + 7, k + 8, this.air);
        this.b(i + 0, j + 7, k + 9, this.air);
        this.b(i + 0, j + 7, k + 10, this.air);
        this.b(i + 0, j + 7, k + 11, this.air);
        this.b(i + 0, j + 7, k + 12, this.air);
        this.b(i + 0, j + 7, k + 13, this.air);
        this.b(i + 0, j + 7, k + 14, this.air);
        this.b(i + 0, j + 7, k + 15, this.air);
        this.b(i + 0, j + 7, k + 16, this.air);
        this.b(i + 0, j + 7, k + 17, this.air);
        this.b(i + 0, j + 7, k + 18, this.air);
        this.b(i + 0, j + 7, k + 19, this.air);
        this.b(i + 0, j + 7, k + 20, this.air);
        this.b(i + 0, j + 7, k + 21, this.air);
        this.b(i + 0, j + 7, k + 22, this.air);
        this.b(i + 0, j + 7, k + 23, this.air);
        this.b(i + 0, j + 7, k + 24, this.air);
        this.b(i + 0, j + 7, k + 25, this.air);
        this.b(i + 0, j + 7, k + 26, this.air);
        this.b(i + 0, j + 7, k + 27, this.air);
        this.b(i + 0, j + 7, k + 28, this.air);
        this.b(i + 0, j + 7, k + 29, this.air);
        this.b(i + 0, j + 7, k + 30, this.air);
        this.b(i + 0, j + 7, k + 31, this.air);
        this.b(i + 0, j + 7, k + 32, this.air);
        this.b(i + 0, j + 7, k + 33, this.air);
        this.b(i + 0, j + 7, k + 34, this.air);
        this.b(i + 0, j + 7, k + 35, this.air);
        this.b(i + 0, j + 7, k + 36, this.air);
        this.b(i + 0, j + 7, k + 37, this.air);
        this.b(i + 0, j + 8, k + 8, this.air);
        this.b(i + 0, j + 8, k + 9, this.air);
        this.b(i + 0, j + 8, k + 10, this.air);
        this.b(i + 0, j + 8, k + 11, this.air);
        this.b(i + 0, j + 8, k + 12, this.air);
        this.b(i + 0, j + 8, k + 13, this.air);
        this.b(i + 0, j + 8, k + 14, this.air);
        this.b(i + 0, j + 8, k + 15, this.air);
        this.b(i + 0, j + 8, k + 16, this.air);
        this.b(i + 0, j + 8, k + 17, this.air);
        this.b(i + 0, j + 8, k + 18, this.air);
        this.b(i + 0, j + 8, k + 19, this.air);
        this.b(i + 0, j + 8, k + 20, this.air);
        this.b(i + 0, j + 8, k + 21, this.air);
        this.b(i + 0, j + 8, k + 22, this.air);
        this.b(i + 0, j + 8, k + 23, this.air);
        this.b(i + 0, j + 8, k + 24, this.air);
        this.b(i + 0, j + 8, k + 25, this.air);
        this.b(i + 0, j + 8, k + 26, this.air);
        this.b(i + 0, j + 8, k + 27, this.air);
        this.b(i + 0, j + 8, k + 28, this.air);
        this.b(i + 0, j + 8, k + 29, this.air);
        this.b(i + 0, j + 8, k + 30, this.air);
        this.b(i + 0, j + 8, k + 31, this.air);
        this.b(i + 0, j + 8, k + 32, this.air);
        this.b(i + 0, j + 8, k + 33, this.air);
        this.b(i + 0, j + 8, k + 34, this.air);
        this.b(i + 0, j + 8, k + 35, this.air);
        this.b(i + 0, j + 8, k + 36, this.air);
        this.b(i + 0, j + 8, k + 37, this.air);
        this.b(i + 0, j + 9, k + 8, this.air);
        this.b(i + 0, j + 9, k + 9, this.air);
        this.b(i + 0, j + 9, k + 10, this.air);
        this.b(i + 0, j + 9, k + 11, this.air);
        this.b(i + 0, j + 9, k + 12, this.air);
        this.b(i + 0, j + 9, k + 13, this.air);
        this.b(i + 0, j + 9, k + 14, this.air);
        this.b(i + 0, j + 9, k + 15, this.air);
        this.b(i + 0, j + 9, k + 16, this.air);
        this.b(i + 0, j + 9, k + 17, this.air);
        this.b(i + 0, j + 9, k + 18, this.air);
        this.b(i + 0, j + 9, k + 19, this.air);
        this.b(i + 0, j + 9, k + 20, this.air);
        this.b(i + 0, j + 9, k + 21, this.air);
        this.b(i + 0, j + 9, k + 22, this.air);
        this.b(i + 0, j + 9, k + 23, this.air);
        this.b(i + 0, j + 9, k + 24, this.air);
        this.b(i + 0, j + 9, k + 25, this.air);
        this.b(i + 0, j + 9, k + 26, this.air);
        this.b(i + 0, j + 9, k + 27, this.air);
        this.b(i + 0, j + 9, k + 28, this.air);
        this.b(i + 0, j + 9, k + 29, this.air);
        this.b(i + 0, j + 9, k + 30, this.air);
        this.b(i + 0, j + 9, k + 31, this.air);
        this.b(i + 0, j + 9, k + 32, this.air);
        this.b(i + 0, j + 9, k + 33, this.air);
        this.b(i + 0, j + 9, k + 34, this.air);
        this.b(i + 0, j + 9, k + 35, this.air);
        this.b(i + 0, j + 9, k + 36, this.air);
        this.b(i + 0, j + 9, k + 37, this.air);
        this.b(i + 0, j + 10, k + 8, this.air);
        this.b(i + 0, j + 10, k + 9, this.air);
        this.b(i + 0, j + 10, k + 10, this.air);
        this.b(i + 0, j + 10, k + 11, this.air);
        this.b(i + 0, j + 10, k + 12, this.air);
        this.b(i + 0, j + 10, k + 13, this.air);
        this.b(i + 0, j + 10, k + 14, this.air);
        this.b(i + 0, j + 10, k + 15, this.air);
        this.b(i + 0, j + 10, k + 16, this.air);
        this.b(i + 0, j + 10, k + 17, this.air);
        this.b(i + 0, j + 10, k + 18, this.air);
        this.b(i + 0, j + 10, k + 19, this.air);
        this.b(i + 0, j + 10, k + 20, this.air);
        this.b(i + 0, j + 10, k + 21, this.air);
        this.b(i + 0, j + 10, k + 22, this.air);
        this.b(i + 0, j + 10, k + 23, this.air);
        this.b(i + 0, j + 10, k + 24, this.air);
        this.b(i + 0, j + 10, k + 25, this.air);
        this.b(i + 0, j + 10, k + 26, this.air);
        this.b(i + 0, j + 10, k + 27, this.air);
        this.b(i + 0, j + 10, k + 28, this.air);
        this.b(i + 0, j + 10, k + 29, this.air);
        this.b(i + 0, j + 10, k + 30, this.air);
        this.b(i + 0, j + 10, k + 31, this.air);
        this.b(i + 0, j + 10, k + 32, this.air);
        this.b(i + 0, j + 10, k + 33, this.air);
        this.b(i + 0, j + 10, k + 34, this.air);
        this.b(i + 0, j + 10, k + 35, this.air);
        this.b(i + 0, j + 10, k + 36, this.air);
        this.b(i + 0, j + 10, k + 37, this.air);
        this.b(i + 0, j + 11, k + 8, this.air);
        this.b(i + 0, j + 11, k + 9, this.air);
        this.b(i + 0, j + 11, k + 10, this.air);
        this.b(i + 0, j + 11, k + 11, this.air);
        this.b(i + 0, j + 11, k + 12, this.air);
        this.b(i + 0, j + 11, k + 13, this.air);
        this.b(i + 0, j + 11, k + 14, this.air);
        this.b(i + 0, j + 11, k + 15, this.air);
        this.b(i + 0, j + 11, k + 16, this.air);
        this.b(i + 0, j + 11, k + 17, this.air);
        this.b(i + 0, j + 11, k + 18, this.air);
        this.b(i + 0, j + 11, k + 19, this.air);
        this.b(i + 0, j + 11, k + 20, this.air);
        this.b(i + 0, j + 11, k + 21, this.air);
        this.b(i + 0, j + 11, k + 22, this.air);
        this.b(i + 0, j + 11, k + 23, this.air);
        this.b(i + 0, j + 11, k + 24, this.air);
        this.b(i + 0, j + 11, k + 25, this.air);
        this.b(i + 0, j + 11, k + 26, this.air);
        this.b(i + 0, j + 11, k + 27, this.air);
        this.b(i + 0, j + 11, k + 28, this.air);
        this.b(i + 0, j + 11, k + 29, this.air);
        this.b(i + 0, j + 11, k + 30, this.air);
        this.b(i + 0, j + 11, k + 31, this.air);
        this.b(i + 0, j + 11, k + 32, this.air);
        this.b(i + 0, j + 11, k + 33, this.air);
        this.b(i + 0, j + 11, k + 34, this.air);
        this.b(i + 0, j + 11, k + 35, this.air);
        this.b(i + 0, j + 11, k + 36, this.air);
        this.b(i + 0, j + 11, k + 37, this.air);
        this.b(i + 0, j + 12, k + 8, this.air);
        this.b(i + 0, j + 12, k + 9, this.air);
        this.b(i + 0, j + 12, k + 10, this.air);
        this.b(i + 0, j + 12, k + 11, this.air);
        this.b(i + 0, j + 12, k + 12, this.air);
        this.b(i + 0, j + 12, k + 13, this.air);
        this.b(i + 0, j + 12, k + 14, this.air);
        this.b(i + 0, j + 12, k + 15, this.air);
        this.b(i + 0, j + 12, k + 16, this.air);
        this.b(i + 0, j + 12, k + 17, this.air);
        this.b(i + 0, j + 12, k + 18, this.air);
        this.b(i + 0, j + 12, k + 19, this.air);
        this.b(i + 0, j + 12, k + 20, this.air);
        this.b(i + 0, j + 12, k + 21, this.air);
        this.b(i + 0, j + 12, k + 22, this.air);
        this.b(i + 0, j + 12, k + 23, this.air);
        this.b(i + 0, j + 12, k + 24, this.air);
        this.b(i + 0, j + 12, k + 25, this.air);
        this.b(i + 0, j + 12, k + 26, this.air);
        this.b(i + 0, j + 12, k + 27, this.air);
        this.b(i + 0, j + 12, k + 28, this.air);
        this.b(i + 0, j + 12, k + 29, this.air);
        this.b(i + 0, j + 12, k + 30, this.air);
        this.b(i + 0, j + 12, k + 31, this.air);
        this.b(i + 0, j + 12, k + 32, this.air);
        this.b(i + 0, j + 12, k + 33, this.air);
        this.b(i + 0, j + 12, k + 34, this.air);
        this.b(i + 0, j + 12, k + 35, this.air);
        this.b(i + 0, j + 12, k + 36, this.air);
        this.b(i + 0, j + 12, k + 37, this.air);
        this.b(i + 0, j + 13, k + 8, this.c, 3);
        this.b(i + 0, j + 13, k + 9, this.c, 3);
        this.b(i + 0, j + 13, k + 10, this.c, 3);
        this.b(i + 0, j + 13, k + 11, this.c, 3);
        this.b(i + 0, j + 13, k + 12, this.c, 3);
        this.b(i + 0, j + 13, k + 13, this.c, 3);
        this.b(i + 0, j + 13, k + 14, this.c, 3);
        this.b(i + 0, j + 13, k + 15, this.c, 3);
        this.b(i + 0, j + 13, k + 16, this.c, 3);
        this.b(i + 0, j + 13, k + 17, this.c, 3);
        this.b(i + 0, j + 13, k + 18, this.c, 3);
        this.b(i + 0, j + 13, k + 19, this.c, 3);
        this.b(i + 0, j + 13, k + 20, this.c, 3);
        this.b(i + 0, j + 13, k + 21, this.c, 3);
        this.b(i + 0, j + 13, k + 22, this.c, 3);
        this.b(i + 0, j + 13, k + 23, this.c, 3);
        this.b(i + 0, j + 13, k + 24, this.c, 3);
        this.b(i + 0, j + 13, k + 25, this.c, 3);
        this.b(i + 0, j + 13, k + 26, this.c, 3);
        this.b(i + 0, j + 13, k + 27, this.c, 3);
        this.b(i + 0, j + 13, k + 28, this.c, 3);
        this.b(i + 0, j + 13, k + 29, this.c, 3);
        this.b(i + 0, j + 13, k + 30, this.c, 3);
        this.b(i + 0, j + 13, k + 31, this.c, 3);
        this.b(i + 0, j + 13, k + 32, this.c, 3);
        this.b(i + 0, j + 13, k + 33, this.c, 3);
        this.b(i + 0, j + 13, k + 34, this.c, 3);
        this.b(i + 0, j + 13, k + 35, this.c, 3);
        this.b(i + 0, j + 13, k + 36, this.c, 3);
        this.b(i + 0, j + 13, k + 37, this.c, 3);
        this.b(i + 0, j + 14, k + 8, this.air);
        this.b(i + 0, j + 14, k + 9, this.air);
        this.b(i + 0, j + 14, k + 10, this.air);
        this.b(i + 0, j + 14, k + 11, this.air);
        this.b(i + 0, j + 14, k + 12, this.air);
        this.b(i + 0, j + 14, k + 13, this.air);
        this.b(i + 0, j + 14, k + 14, this.air);
        this.b(i + 0, j + 14, k + 15, this.air);
        this.b(i + 0, j + 14, k + 16, this.air);
        this.b(i + 0, j + 14, k + 17, this.air);
        this.b(i + 0, j + 14, k + 18, this.air);
        this.b(i + 0, j + 14, k + 19, this.c, 11);
        this.b(i + 0, j + 14, k + 20, this.c, 11);
        this.b(i + 0, j + 14, k + 21, this.c, 11);
        this.b(i + 0, j + 14, k + 22, this.c, 11);
        this.b(i + 0, j + 14, k + 23, this.c, 11);
        this.b(i + 0, j + 14, k + 24, this.c, 11);
        this.b(i + 0, j + 14, k + 25, this.c, 11);
        this.b(i + 0, j + 14, k + 26, this.c, 11);
        this.b(i + 0, j + 14, k + 27, this.air);
        this.b(i + 0, j + 14, k + 28, this.air);
        this.b(i + 0, j + 14, k + 29, this.air);
        this.b(i + 0, j + 14, k + 30, this.air);
        this.b(i + 0, j + 14, k + 31, this.air);
        this.b(i + 0, j + 14, k + 32, this.air);
        this.b(i + 0, j + 14, k + 33, this.air);
        this.b(i + 0, j + 14, k + 34, this.air);
        this.b(i + 0, j + 14, k + 35, this.air);
        this.b(i + 0, j + 14, k + 36, this.air);
        this.b(i + 0, j + 14, k + 37, this.air);
        this.b(i + 0, j + 15, k + 8, this.air);
        this.b(i + 0, j + 15, k + 9, this.air);
        this.b(i + 0, j + 15, k + 10, this.air);
        this.b(i + 0, j + 15, k + 11, this.air);
        this.b(i + 0, j + 15, k + 12, this.air);
        this.b(i + 0, j + 15, k + 13, this.air);
        this.b(i + 0, j + 15, k + 14, this.air);
        this.b(i + 0, j + 15, k + 15, this.air);
        this.b(i + 0, j + 15, k + 16, this.air);
        this.b(i + 0, j + 15, k + 17, this.air);
        this.b(i + 0, j + 15, k + 18, this.air);
        this.b(i + 0, j + 15, k + 19, this.c, 11);
        this.b(i + 0, j + 15, k + 20, this.c, 11);
        this.b(i + 0, j + 15, k + 21, this.c, 11);
        this.b(i + 0, j + 15, k + 22, this.c, 11);
        this.b(i + 0, j + 15, k + 23, this.c, 11);
        this.b(i + 0, j + 15, k + 24, this.c, 11);
        this.b(i + 0, j + 15, k + 25, this.c, 11);
        this.b(i + 0, j + 15, k + 26, this.c, 11);
        this.b(i + 0, j + 15, k + 27, this.air);
        this.b(i + 0, j + 15, k + 28, this.air);
        this.b(i + 0, j + 15, k + 29, this.air);
        this.b(i + 0, j + 15, k + 30, this.air);
        this.b(i + 0, j + 15, k + 31, this.air);
        this.b(i + 0, j + 15, k + 32, this.air);
        this.b(i + 0, j + 15, k + 33, this.air);
        this.b(i + 0, j + 15, k + 34, this.air);
        this.b(i + 0, j + 15, k + 35, this.air);
        this.b(i + 0, j + 15, k + 36, this.air);
        this.b(i + 0, j + 15, k + 37, this.air);
        this.b(i + 0, j + 16, k + 8, this.air);
        this.b(i + 0, j + 16, k + 9, this.air);
        this.b(i + 0, j + 16, k + 10, this.air);
        this.b(i + 0, j + 16, k + 11, this.air);
        this.b(i + 0, j + 16, k + 12, this.air);
        this.b(i + 0, j + 16, k + 13, this.air);
        this.b(i + 0, j + 16, k + 14, this.air);
        this.b(i + 0, j + 16, k + 15, this.air);
        this.b(i + 0, j + 16, k + 16, this.air);
        this.b(i + 0, j + 16, k + 17, this.air);
        this.b(i + 0, j + 16, k + 18, this.air);
        this.b(i + 0, j + 16, k + 19, this.c, 11);
        this.b(i + 0, j + 16, k + 20, this.c, 11);
        this.b(i + 0, j + 16, k + 21, this.c, 11);
        this.b(i + 0, j + 16, k + 22, this.c, 11);
        this.b(i + 0, j + 16, k + 23, this.c, 11);
        this.b(i + 0, j + 16, k + 24, this.c, 11);
        this.b(i + 0, j + 16, k + 25, this.c, 11);
        this.b(i + 0, j + 16, k + 26, this.c, 11);
        this.b(i + 0, j + 16, k + 27, this.air);
        this.b(i + 0, j + 16, k + 28, this.air);
        this.b(i + 0, j + 16, k + 29, this.air);
        this.b(i + 0, j + 16, k + 30, this.air);
        this.b(i + 0, j + 16, k + 31, this.air);
        this.b(i + 0, j + 16, k + 32, this.air);
        this.b(i + 0, j + 16, k + 33, this.air);
        this.b(i + 0, j + 16, k + 34, this.air);
        this.b(i + 0, j + 16, k + 35, this.air);
        this.b(i + 0, j + 16, k + 36, this.air);
        this.b(i + 0, j + 16, k + 37, this.air);
        this.b(i + 0, j + 17, k + 8, this.air);
        this.b(i + 0, j + 17, k + 9, this.air);
        this.b(i + 0, j + 17, k + 10, this.air);
        this.b(i + 0, j + 17, k + 11, this.air);
        this.b(i + 0, j + 17, k + 12, this.air);
        this.b(i + 0, j + 17, k + 13, this.air);
        this.b(i + 0, j + 17, k + 14, this.air);
        this.b(i + 0, j + 17, k + 15, this.air);
        this.b(i + 0, j + 17, k + 16, this.air);
        this.b(i + 0, j + 17, k + 17, this.air);
        this.b(i + 0, j + 17, k + 18, this.air);
        this.b(i + 0, j + 17, k + 19, this.air);
        this.b(i + 0, j + 17, k + 20, this.c, 11);
        this.b(i + 0, j + 17, k + 21, this.c, 11);
        this.b(i + 0, j + 17, k + 22, this.c, 11);
        this.b(i + 0, j + 17, k + 23, this.c, 11);
        this.b(i + 0, j + 17, k + 24, this.c, 11);
        this.b(i + 0, j + 17, k + 25, this.c, 11);
        this.b(i + 0, j + 17, k + 26, this.air);
        this.b(i + 0, j + 17, k + 27, this.air);
        this.b(i + 0, j + 17, k + 28, this.air);
        this.b(i + 0, j + 17, k + 29, this.air);
        this.b(i + 0, j + 17, k + 30, this.air);
        this.b(i + 0, j + 17, k + 31, this.air);
        this.b(i + 0, j + 17, k + 32, this.air);
        this.b(i + 0, j + 17, k + 33, this.air);
        this.b(i + 0, j + 17, k + 34, this.air);
        this.b(i + 0, j + 17, k + 35, this.air);
        this.b(i + 0, j + 17, k + 36, this.air);
        this.b(i + 0, j + 17, k + 37, this.air);
        this.b(i + 0, j + 18, k + 8, this.air);
        this.b(i + 0, j + 18, k + 9, this.air);
        this.b(i + 0, j + 18, k + 10, this.air);
        this.b(i + 0, j + 18, k + 11, this.air);
        this.b(i + 0, j + 18, k + 12, this.air);
        this.b(i + 0, j + 18, k + 13, this.air);
        this.b(i + 0, j + 18, k + 14, this.air);
        this.b(i + 0, j + 18, k + 15, this.air);
        this.b(i + 0, j + 18, k + 16, this.air);
        this.b(i + 0, j + 18, k + 17, this.air);
        this.b(i + 0, j + 18, k + 18, this.air);
        this.b(i + 0, j + 18, k + 19, this.air);
        this.b(i + 0, j + 18, k + 20, this.air);
        this.b(i + 0, j + 18, k + 21, this.air);
        this.b(i + 0, j + 18, k + 22, this.c, 4);
        this.b(i + 0, j + 18, k + 23, this.c, 4);
        this.b(i + 0, j + 18, k + 24, this.air);
        this.b(i + 0, j + 18, k + 25, this.air);
        this.b(i + 0, j + 18, k + 26, this.air);
        this.b(i + 0, j + 18, k + 27, this.air);
        this.b(i + 0, j + 18, k + 28, this.air);
        this.b(i + 0, j + 18, k + 29, this.air);
        this.b(i + 0, j + 18, k + 30, this.air);
        this.b(i + 0, j + 18, k + 31, this.air);
        this.b(i + 0, j + 18, k + 32, this.air);
        this.b(i + 0, j + 18, k + 33, this.air);
        this.b(i + 0, j + 18, k + 34, this.air);
        this.b(i + 0, j + 18, k + 35, this.air);
        this.b(i + 0, j + 18, k + 36, this.air);
        this.b(i + 0, j + 18, k + 37, this.air);
        this.b(i + 0, j + 19, k + 8, this.air);
        this.b(i + 0, j + 19, k + 9, this.air);
        this.b(i + 0, j + 19, k + 10, this.air);
        this.b(i + 0, j + 19, k + 11, this.air);
        this.b(i + 0, j + 19, k + 12, this.air);
        this.b(i + 0, j + 19, k + 13, this.air);
        this.b(i + 0, j + 19, k + 14, this.air);
        this.b(i + 0, j + 19, k + 15, this.air);
        this.b(i + 0, j + 19, k + 16, this.air);
        this.b(i + 0, j + 19, k + 17, this.air);
        this.b(i + 0, j + 19, k + 18, this.air);
        this.b(i + 0, j + 19, k + 19, this.air);
        this.b(i + 0, j + 19, k + 20, this.air);
        this.b(i + 0, j + 19, k + 21, this.air);
        this.b(i + 0, j + 19, k + 22, this.air);
        this.b(i + 0, j + 19, k + 23, this.air);
        this.b(i + 0, j + 19, k + 24, this.air);
        this.b(i + 0, j + 19, k + 25, this.air);
        this.b(i + 0, j + 19, k + 26, this.air);
        this.b(i + 0, j + 19, k + 27, this.air);
        this.b(i + 0, j + 19, k + 28, this.air);
        this.b(i + 0, j + 19, k + 29, this.air);
        this.b(i + 0, j + 19, k + 30, this.air);
        this.b(i + 0, j + 19, k + 31, this.air);
        this.b(i + 0, j + 19, k + 32, this.air);
        this.b(i + 0, j + 19, k + 33, this.air);
        this.b(i + 0, j + 19, k + 34, this.air);
        this.b(i + 0, j + 19, k + 35, this.air);
        this.b(i + 0, j + 19, k + 36, this.air);
        this.b(i + 0, j + 19, k + 37, this.air);
        this.b(i + 0, j + 20, k + 8, this.air);
        this.b(i + 0, j + 20, k + 9, this.air);
        this.b(i + 0, j + 20, k + 10, this.air);
        this.b(i + 0, j + 20, k + 11, this.air);
        this.b(i + 0, j + 20, k + 12, this.air);
        this.b(i + 0, j + 20, k + 13, this.air);
        this.b(i + 0, j + 20, k + 14, this.air);
        this.b(i + 0, j + 20, k + 15, this.air);
        this.b(i + 0, j + 20, k + 16, this.air);
        this.b(i + 0, j + 20, k + 17, this.air);
        this.b(i + 0, j + 20, k + 18, this.air);
        this.b(i + 0, j + 20, k + 19, this.air);
        this.b(i + 0, j + 20, k + 20, this.air);
        this.b(i + 0, j + 20, k + 21, this.air);
        this.b(i + 0, j + 20, k + 22, this.air);
        this.b(i + 0, j + 20, k + 23, this.air);
        this.b(i + 0, j + 20, k + 24, this.air);
        this.b(i + 0, j + 20, k + 25, this.air);
        this.b(i + 0, j + 20, k + 26, this.air);
        this.b(i + 0, j + 20, k + 27, this.air);
        this.b(i + 0, j + 20, k + 28, this.air);
        this.b(i + 0, j + 20, k + 29, this.air);
        this.b(i + 0, j + 20, k + 30, this.air);
        this.b(i + 0, j + 20, k + 31, this.air);
        this.b(i + 0, j + 20, k + 32, this.air);
        this.b(i + 0, j + 20, k + 33, this.air);
        this.b(i + 0, j + 20, k + 34, this.air);
        this.b(i + 0, j + 20, k + 35, this.air);
        this.b(i + 0, j + 20, k + 36, this.air);
        this.b(i + 0, j + 20, k + 37, this.air);
        this.b(i + 0, j + 21, k + 8, this.air);
        this.b(i + 0, j + 21, k + 9, this.air);
        this.b(i + 0, j + 21, k + 10, this.air);
        this.b(i + 0, j + 21, k + 11, this.air);
        this.b(i + 0, j + 21, k + 12, this.air);
        this.b(i + 0, j + 21, k + 13, this.air);
        this.b(i + 0, j + 21, k + 14, this.air);
        this.b(i + 0, j + 21, k + 15, this.air);
        this.b(i + 0, j + 21, k + 16, this.air);
        this.b(i + 0, j + 21, k + 17, this.air);
        this.b(i + 0, j + 21, k + 18, this.air);
        this.b(i + 0, j + 21, k + 19, this.air);
        this.b(i + 0, j + 21, k + 20, this.air);
        this.b(i + 0, j + 21, k + 21, this.air);
        this.b(i + 0, j + 21, k + 22, this.air);
        this.b(i + 0, j + 21, k + 23, this.air);
        this.b(i + 0, j + 21, k + 24, this.air);
        this.b(i + 0, j + 21, k + 25, this.air);
        this.b(i + 0, j + 21, k + 26, this.air);
        this.b(i + 0, j + 21, k + 27, this.air);
        this.b(i + 0, j + 21, k + 28, this.air);
        this.b(i + 0, j + 21, k + 29, this.air);
        this.b(i + 0, j + 21, k + 30, this.air);
        this.b(i + 0, j + 21, k + 31, this.air);
        this.b(i + 0, j + 21, k + 32, this.air);
        this.b(i + 0, j + 21, k + 33, this.air);
        this.b(i + 0, j + 21, k + 34, this.air);
        this.b(i + 0, j + 21, k + 35, this.air);
        this.b(i + 0, j + 21, k + 36, this.air);
        this.b(i + 0, j + 21, k + 37, this.air);
        this.b(i + 0, j + 22, k + 8, this.air);
        this.b(i + 0, j + 22, k + 9, this.air);
        this.b(i + 0, j + 22, k + 10, this.air);
        this.b(i + 0, j + 22, k + 11, this.air);
        this.b(i + 0, j + 22, k + 12, this.air);
        this.b(i + 0, j + 22, k + 13, this.air);
        this.b(i + 0, j + 22, k + 14, this.air);
        this.b(i + 0, j + 22, k + 15, this.air);
        this.b(i + 0, j + 22, k + 16, this.air);
        this.b(i + 0, j + 22, k + 17, this.air);
        this.b(i + 0, j + 22, k + 18, this.air);
        this.b(i + 0, j + 22, k + 19, this.air);
        this.b(i + 0, j + 22, k + 20, this.air);
        this.b(i + 0, j + 22, k + 21, this.air);
        this.b(i + 0, j + 22, k + 22, this.air);
        this.b(i + 0, j + 22, k + 23, this.air);
        this.b(i + 0, j + 22, k + 24, this.air);
        this.b(i + 0, j + 22, k + 25, this.air);
        this.b(i + 0, j + 22, k + 26, this.air);
        this.b(i + 0, j + 22, k + 27, this.air);
        this.b(i + 0, j + 22, k + 28, this.air);
        this.b(i + 0, j + 22, k + 29, this.air);
        this.b(i + 0, j + 22, k + 30, this.air);
        this.b(i + 0, j + 22, k + 31, this.air);
        this.b(i + 0, j + 22, k + 32, this.air);
        this.b(i + 0, j + 22, k + 33, this.air);
        this.b(i + 0, j + 22, k + 34, this.air);
        this.b(i + 0, j + 22, k + 35, this.air);
        this.b(i + 0, j + 22, k + 36, this.air);
        this.b(i + 0, j + 22, k + 37, this.air);
        this.b(i + 0, j + 23, k + 8, this.air);
        this.b(i + 0, j + 23, k + 9, this.air);
        this.b(i + 0, j + 23, k + 10, this.air);
        this.b(i + 0, j + 23, k + 11, this.air);
        this.b(i + 0, j + 23, k + 12, this.air);
        this.b(i + 0, j + 23, k + 13, this.air);
        this.b(i + 0, j + 23, k + 14, this.air);
        this.b(i + 0, j + 23, k + 15, this.air);
        this.b(i + 0, j + 23, k + 16, this.air);
        this.b(i + 0, j + 23, k + 17, this.air);
        this.b(i + 0, j + 23, k + 18, this.air);
        this.b(i + 0, j + 23, k + 19, this.air);
        this.b(i + 0, j + 23, k + 20, this.air);
        this.b(i + 0, j + 23, k + 21, this.air);
        this.b(i + 0, j + 23, k + 22, this.air);
        this.b(i + 0, j + 23, k + 23, this.air);
        this.b(i + 0, j + 23, k + 24, this.air);
        this.b(i + 0, j + 23, k + 25, this.air);
        this.b(i + 0, j + 23, k + 26, this.air);
        this.b(i + 0, j + 23, k + 27, this.air);
        this.b(i + 0, j + 23, k + 28, this.air);
        this.b(i + 0, j + 23, k + 29, this.air);
        this.b(i + 0, j + 23, k + 30, this.air);
        this.b(i + 0, j + 23, k + 31, this.air);
        this.b(i + 0, j + 23, k + 32, this.air);
        this.b(i + 0, j + 23, k + 33, this.air);
        this.b(i + 0, j + 23, k + 34, this.air);
        this.b(i + 0, j + 23, k + 35, this.air);
        this.b(i + 0, j + 23, k + 36, this.air);
        this.b(i + 0, j + 23, k + 37, this.air);
        this.b(i + 0, j + 24, k + 8, this.air);
        this.b(i + 0, j + 24, k + 9, this.air);
        this.b(i + 0, j + 24, k + 10, this.air);
        this.b(i + 0, j + 24, k + 11, this.air);
        this.b(i + 0, j + 24, k + 12, this.air);
        this.b(i + 0, j + 24, k + 13, this.air);
        this.b(i + 0, j + 24, k + 14, this.air);
        this.b(i + 0, j + 24, k + 15, this.air);
        this.b(i + 0, j + 24, k + 16, this.air);
        this.b(i + 0, j + 24, k + 17, this.air);
        this.b(i + 0, j + 24, k + 18, this.air);
        this.b(i + 0, j + 24, k + 19, this.air);
        this.b(i + 0, j + 24, k + 20, this.air);
        this.b(i + 0, j + 24, k + 21, this.air);
        this.b(i + 0, j + 24, k + 22, this.air);
        this.b(i + 0, j + 24, k + 23, this.air);
        this.b(i + 0, j + 24, k + 24, this.air);
        this.b(i + 0, j + 24, k + 25, this.air);
        this.b(i + 0, j + 24, k + 26, this.air);
        this.b(i + 0, j + 24, k + 27, this.air);
        this.b(i + 0, j + 24, k + 28, this.air);
        this.b(i + 0, j + 24, k + 29, this.air);
        this.b(i + 0, j + 24, k + 30, this.air);
        this.b(i + 0, j + 24, k + 31, this.air);
        this.b(i + 0, j + 24, k + 32, this.air);
        this.b(i + 0, j + 24, k + 33, this.air);
        this.b(i + 0, j + 24, k + 34, this.air);
        this.b(i + 0, j + 24, k + 35, this.air);
        this.b(i + 0, j + 24, k + 36, this.air);
        this.b(i + 0, j + 24, k + 37, this.air);
        this.b(i + 0, j + 25, k + 8, this.air);
        this.b(i + 0, j + 25, k + 9, this.air);
        this.b(i + 0, j + 25, k + 10, this.air);
        this.b(i + 0, j + 25, k + 11, this.air);
        this.b(i + 0, j + 25, k + 12, this.air);
        this.b(i + 0, j + 25, k + 13, this.air);
        this.b(i + 0, j + 25, k + 14, this.air);
        this.b(i + 0, j + 25, k + 15, this.air);
        this.b(i + 0, j + 25, k + 16, this.air);
        this.b(i + 0, j + 25, k + 17, this.air);
        this.b(i + 0, j + 25, k + 18, this.air);
        this.b(i + 0, j + 25, k + 19, this.air);
        this.b(i + 0, j + 25, k + 20, this.air);
        this.b(i + 0, j + 25, k + 21, this.air);
        this.b(i + 0, j + 25, k + 22, this.air);
        this.b(i + 0, j + 25, k + 23, this.air);
        this.b(i + 0, j + 25, k + 24, this.air);
        this.b(i + 0, j + 25, k + 25, this.air);
        this.b(i + 0, j + 25, k + 26, this.air);
        this.b(i + 0, j + 25, k + 27, this.air);
        this.b(i + 0, j + 25, k + 28, this.air);
        this.b(i + 0, j + 25, k + 29, this.air);
        this.b(i + 0, j + 25, k + 30, this.air);
        this.b(i + 0, j + 25, k + 31, this.air);
        this.b(i + 0, j + 25, k + 32, this.air);
        this.b(i + 0, j + 25, k + 33, this.air);
        this.b(i + 0, j + 25, k + 34, this.air);
        this.b(i + 0, j + 25, k + 35, this.air);
        this.b(i + 0, j + 25, k + 36, this.air);
        this.b(i + 0, j + 25, k + 37, this.air);
        this.b(i + 0, j + 26, k + 8, this.c, 10);
        this.b(i + 0, j + 26, k + 9, this.c, 10);
        this.b(i + 0, j + 26, k + 10, this.c, 10);
        this.b(i + 0, j + 26, k + 11, this.c, 10);
        this.b(i + 0, j + 26, k + 12, this.c, 10);
        this.b(i + 0, j + 26, k + 13, this.c, 10);
        this.b(i + 0, j + 26, k + 14, this.c, 10);
        this.b(i + 0, j + 26, k + 15, this.c, 10);
        this.b(i + 0, j + 26, k + 16, this.c, 10);
        this.b(i + 0, j + 26, k + 17, this.c, 10);
        this.b(i + 0, j + 26, k + 18, this.c, 10);
        this.b(i + 0, j + 26, k + 19, this.c, 10);
        this.b(i + 0, j + 26, k + 20, this.c, 10);
        this.b(i + 0, j + 26, k + 21, this.c, 10);
        this.b(i + 0, j + 26, k + 22, this.c, 10);
        this.b(i + 0, j + 26, k + 23, this.c, 10);
        this.b(i + 0, j + 26, k + 24, this.c, 10);
        this.b(i + 0, j + 26, k + 25, this.c, 10);
        this.b(i + 0, j + 26, k + 26, this.c, 10);
        this.b(i + 0, j + 26, k + 27, this.c, 10);
        this.b(i + 0, j + 26, k + 28, this.c, 10);
        this.b(i + 0, j + 26, k + 29, this.c, 10);
        this.b(i + 0, j + 26, k + 30, this.c, 10);
        this.b(i + 0, j + 26, k + 31, this.c, 10);
        this.b(i + 0, j + 26, k + 32, this.c, 10);
        this.b(i + 0, j + 26, k + 33, this.c, 10);
        this.b(i + 0, j + 26, k + 34, this.c, 10);
        this.b(i + 0, j + 26, k + 35, this.c, 10);
        this.b(i + 0, j + 26, k + 36, this.c, 10);
        this.b(i + 0, j + 26, k + 37, this.c, 10);
        this.b(i + 0, j + 27, k + 8, this.air);
        this.b(i + 0, j + 27, k + 9, this.air);
        this.b(i + 0, j + 27, k + 10, this.air);
        this.b(i + 0, j + 27, k + 11, this.air);
        this.b(i + 0, j + 27, k + 12, this.air);
        this.b(i + 0, j + 27, k + 13, this.air);
        this.b(i + 0, j + 27, k + 14, this.air);
        this.b(i + 0, j + 27, k + 15, this.air);
        this.b(i + 0, j + 27, k + 16, this.air);
        this.b(i + 0, j + 27, k + 17, this.air);
        this.b(i + 0, j + 27, k + 18, this.air);
        this.b(i + 0, j + 27, k + 19, this.c, 11);
        this.b(i + 0, j + 27, k + 20, this.c, 11);
        this.b(i + 0, j + 27, k + 21, this.c, 11);
        this.b(i + 0, j + 27, k + 22, this.c, 11);
        this.b(i + 0, j + 27, k + 23, this.c, 11);
        this.b(i + 0, j + 27, k + 24, this.c, 11);
        this.b(i + 0, j + 27, k + 25, this.c, 11);
        this.b(i + 0, j + 27, k + 26, this.c, 11);
        this.b(i + 0, j + 27, k + 27, this.air);
        this.b(i + 0, j + 27, k + 28, this.air);
        this.b(i + 0, j + 27, k + 29, this.air);
        this.b(i + 0, j + 27, k + 30, this.air);
        this.b(i + 0, j + 27, k + 31, this.air);
        this.b(i + 0, j + 27, k + 32, this.air);
        this.b(i + 0, j + 27, k + 33, this.air);
        this.b(i + 0, j + 27, k + 34, this.air);
        this.b(i + 0, j + 27, k + 35, this.air);
        this.b(i + 0, j + 27, k + 36, this.air);
        this.b(i + 0, j + 27, k + 37, this.air);
        this.b(i + 0, j + 28, k + 8, this.air);
        this.b(i + 0, j + 28, k + 9, this.air);
        this.b(i + 0, j + 28, k + 10, this.air);
        this.b(i + 0, j + 28, k + 11, this.air);
        this.b(i + 0, j + 28, k + 12, this.air);
        this.b(i + 0, j + 28, k + 13, this.air);
        this.b(i + 0, j + 28, k + 14, this.air);
        this.b(i + 0, j + 28, k + 15, this.air);
        this.b(i + 0, j + 28, k + 16, this.air);
        this.b(i + 0, j + 28, k + 17, this.air);
        this.b(i + 0, j + 28, k + 18, this.air);
        this.b(i + 0, j + 28, k + 19, this.c, 11);
        this.b(i + 0, j + 28, k + 20, this.c, 11);
        this.b(i + 0, j + 28, k + 21, this.c, 11);
        this.b(i + 0, j + 28, k + 22, this.c, 11);
        this.b(i + 0, j + 28, k + 23, this.c, 11);
        this.b(i + 0, j + 28, k + 24, this.c, 11);
        this.b(i + 0, j + 28, k + 25, this.c, 11);
        this.b(i + 0, j + 28, k + 26, this.c, 11);
        this.b(i + 0, j + 28, k + 27, this.air);
        this.b(i + 0, j + 28, k + 28, this.air);
        this.b(i + 0, j + 28, k + 29, this.air);
        this.b(i + 0, j + 28, k + 30, this.air);
        this.b(i + 0, j + 28, k + 31, this.air);
        this.b(i + 0, j + 28, k + 32, this.air);
        this.b(i + 0, j + 28, k + 33, this.air);
        this.b(i + 0, j + 28, k + 34, this.air);
        this.b(i + 0, j + 28, k + 35, this.air);
        this.b(i + 0, j + 28, k + 36, this.air);
        this.b(i + 0, j + 28, k + 37, this.air);
        this.b(i + 0, j + 29, k + 8, this.air);
        this.b(i + 0, j + 29, k + 9, this.air);
        this.b(i + 0, j + 29, k + 10, this.air);
        this.b(i + 0, j + 29, k + 11, this.air);
        this.b(i + 0, j + 29, k + 12, this.air);
        this.b(i + 0, j + 29, k + 13, this.air);
        this.b(i + 0, j + 29, k + 14, this.air);
        this.b(i + 0, j + 29, k + 15, this.air);
        this.b(i + 0, j + 29, k + 16, this.air);
        this.b(i + 0, j + 29, k + 17, this.air);
        this.b(i + 0, j + 29, k + 18, this.air);
        this.b(i + 0, j + 29, k + 19, this.c, 11);
        this.b(i + 0, j + 29, k + 20, this.c, 11);
        this.b(i + 0, j + 29, k + 21, this.c, 11);
        this.b(i + 0, j + 29, k + 22, this.c, 11);
        this.b(i + 0, j + 29, k + 23, this.c, 11);
        this.b(i + 0, j + 29, k + 24, this.c, 11);
        this.b(i + 0, j + 29, k + 25, this.c, 11);
        this.b(i + 0, j + 29, k + 26, this.c, 11);
        this.b(i + 0, j + 29, k + 27, this.air);
        this.b(i + 0, j + 29, k + 28, this.air);
        this.b(i + 0, j + 29, k + 29, this.air);
        this.b(i + 0, j + 29, k + 30, this.air);
        this.b(i + 0, j + 29, k + 31, this.air);
        this.b(i + 0, j + 29, k + 32, this.air);
        this.b(i + 0, j + 29, k + 33, this.air);
        this.b(i + 0, j + 29, k + 34, this.air);
        this.b(i + 0, j + 29, k + 35, this.air);
        this.b(i + 0, j + 29, k + 36, this.air);
        this.b(i + 0, j + 29, k + 37, this.air);
        this.b(i + 0, j + 30, k + 8, this.air);
        this.b(i + 0, j + 30, k + 9, this.air);
        this.b(i + 0, j + 30, k + 10, this.air);
        this.b(i + 0, j + 30, k + 11, this.air);
        this.b(i + 0, j + 30, k + 12, this.air);
        this.b(i + 0, j + 30, k + 13, this.air);
        this.b(i + 0, j + 30, k + 14, this.air);
        this.b(i + 0, j + 30, k + 15, this.air);
        this.b(i + 0, j + 30, k + 16, this.air);
        this.b(i + 0, j + 30, k + 17, this.air);
        this.b(i + 0, j + 30, k + 18, this.air);
        this.b(i + 0, j + 30, k + 19, this.air);
        this.b(i + 0, j + 30, k + 20, this.c, 11);
        this.b(i + 0, j + 30, k + 21, this.c, 11);
        this.b(i + 0, j + 30, k + 22, this.c, 11);
        this.b(i + 0, j + 30, k + 23, this.c, 11);
        this.b(i + 0, j + 30, k + 24, this.c, 11);
        this.b(i + 0, j + 30, k + 25, this.c, 11);
        this.b(i + 0, j + 30, k + 26, this.air);
        this.b(i + 0, j + 30, k + 27, this.air);
        this.b(i + 0, j + 30, k + 28, this.air);
        this.b(i + 0, j + 30, k + 29, this.air);
        this.b(i + 0, j + 30, k + 30, this.air);
        this.b(i + 0, j + 30, k + 31, this.air);
        this.b(i + 0, j + 30, k + 32, this.air);
        this.b(i + 0, j + 30, k + 33, this.air);
        this.b(i + 0, j + 30, k + 34, this.air);
        this.b(i + 0, j + 30, k + 35, this.air);
        this.b(i + 0, j + 30, k + 36, this.air);
        this.b(i + 0, j + 30, k + 37, this.air);
        this.b(i + 0, j + 31, k + 8, this.air);
        this.b(i + 0, j + 31, k + 9, this.air);
        this.b(i + 0, j + 31, k + 10, this.air);
        this.b(i + 0, j + 31, k + 11, this.air);
        this.b(i + 0, j + 31, k + 12, this.air);
        this.b(i + 0, j + 31, k + 13, this.air);
        this.b(i + 0, j + 31, k + 14, this.air);
        this.b(i + 0, j + 31, k + 15, this.air);
        this.b(i + 0, j + 31, k + 16, this.air);
        this.b(i + 0, j + 31, k + 17, this.air);
        this.b(i + 0, j + 31, k + 18, this.air);
        this.b(i + 0, j + 31, k + 19, this.air);
        this.b(i + 0, j + 31, k + 20, this.air);
        this.b(i + 0, j + 31, k + 21, this.air);
        this.b(i + 0, j + 31, k + 22, this.c, 4);
        this.b(i + 0, j + 31, k + 23, this.c, 4);
        this.b(i + 0, j + 31, k + 24, this.air);
        this.b(i + 0, j + 31, k + 25, this.air);
        this.b(i + 0, j + 31, k + 26, this.air);
        this.b(i + 0, j + 31, k + 27, this.air);
        this.b(i + 0, j + 31, k + 28, this.air);
        this.b(i + 0, j + 31, k + 29, this.air);
        this.b(i + 0, j + 31, k + 30, this.air);
        this.b(i + 0, j + 31, k + 31, this.air);
        this.b(i + 0, j + 31, k + 32, this.air);
        this.b(i + 0, j + 31, k + 33, this.air);
        this.b(i + 0, j + 31, k + 34, this.air);
        this.b(i + 0, j + 31, k + 35, this.air);
        this.b(i + 0, j + 31, k + 36, this.air);
        this.b(i + 0, j + 31, k + 37, this.air);
        this.b(i + 0, j + 32, k + 8, this.air);
        this.b(i + 0, j + 32, k + 9, this.air);
        this.b(i + 0, j + 32, k + 10, this.air);
        this.b(i + 0, j + 32, k + 11, this.air);
        this.b(i + 0, j + 32, k + 12, this.air);
        this.b(i + 0, j + 32, k + 13, this.air);
        this.b(i + 0, j + 32, k + 14, this.air);
        this.b(i + 0, j + 32, k + 15, this.air);
        this.b(i + 0, j + 32, k + 16, this.air);
        this.b(i + 0, j + 32, k + 17, this.air);
        this.b(i + 0, j + 32, k + 18, this.air);
        this.b(i + 0, j + 32, k + 19, this.air);
        this.b(i + 0, j + 32, k + 20, this.air);
        this.b(i + 0, j + 32, k + 21, this.air);
        this.b(i + 0, j + 32, k + 22, this.air);
        this.b(i + 0, j + 32, k + 23, this.air);
        this.b(i + 0, j + 32, k + 24, this.air);
        this.b(i + 0, j + 32, k + 25, this.air);
        this.b(i + 0, j + 32, k + 26, this.air);
        this.b(i + 0, j + 32, k + 27, this.air);
        this.b(i + 0, j + 32, k + 28, this.air);
        this.b(i + 0, j + 32, k + 29, this.air);
        this.b(i + 0, j + 32, k + 30, this.air);
        this.b(i + 0, j + 32, k + 31, this.air);
        this.b(i + 0, j + 32, k + 32, this.air);
        this.b(i + 0, j + 32, k + 33, this.air);
        this.b(i + 0, j + 32, k + 34, this.air);
        this.b(i + 0, j + 32, k + 35, this.air);
        this.b(i + 0, j + 32, k + 36, this.air);
        this.b(i + 0, j + 32, k + 37, this.air);
        this.b(i + 0, j + 33, k + 8, this.air);
        this.b(i + 0, j + 33, k + 9, this.air);
        this.b(i + 0, j + 33, k + 10, this.air);
        this.b(i + 0, j + 33, k + 11, this.air);
        this.b(i + 0, j + 33, k + 12, this.air);
        this.b(i + 0, j + 33, k + 13, this.air);
        this.b(i + 0, j + 33, k + 14, this.air);
        this.b(i + 0, j + 33, k + 15, this.air);
        this.b(i + 0, j + 33, k + 16, this.air);
        this.b(i + 0, j + 33, k + 17, this.air);
        this.b(i + 0, j + 33, k + 18, this.air);
        this.b(i + 0, j + 33, k + 19, this.air);
        this.b(i + 0, j + 33, k + 20, this.air);
        this.b(i + 0, j + 33, k + 21, this.air);
        this.b(i + 0, j + 33, k + 22, this.air);
        this.b(i + 0, j + 33, k + 23, this.air);
        this.b(i + 0, j + 33, k + 24, this.air);
        this.b(i + 0, j + 33, k + 25, this.air);
        this.b(i + 0, j + 33, k + 26, this.air);
        this.b(i + 0, j + 33, k + 27, this.air);
        this.b(i + 0, j + 33, k + 28, this.air);
        this.b(i + 0, j + 33, k + 29, this.air);
        this.b(i + 0, j + 33, k + 30, this.air);
        this.b(i + 0, j + 33, k + 31, this.air);
        this.b(i + 0, j + 33, k + 32, this.air);
        this.b(i + 0, j + 33, k + 33, this.air);
        this.b(i + 0, j + 33, k + 34, this.air);
        this.b(i + 0, j + 33, k + 35, this.air);
        this.b(i + 0, j + 33, k + 36, this.air);
        this.b(i + 0, j + 33, k + 37, this.air);
        this.b(i + 0, j + 34, k + 8, this.air);
        this.b(i + 0, j + 34, k + 9, this.air);
        this.b(i + 0, j + 34, k + 10, this.air);
        this.b(i + 0, j + 34, k + 11, this.air);
        this.b(i + 0, j + 34, k + 12, this.air);
        this.b(i + 0, j + 34, k + 13, this.air);
        this.b(i + 0, j + 34, k + 14, this.air);
        this.b(i + 0, j + 34, k + 15, this.air);
        this.b(i + 0, j + 34, k + 16, this.air);
        this.b(i + 0, j + 34, k + 17, this.air);
        this.b(i + 0, j + 34, k + 18, this.air);
        this.b(i + 0, j + 34, k + 19, this.air);
        this.b(i + 0, j + 34, k + 20, this.air);
        this.b(i + 0, j + 34, k + 21, this.air);
        this.b(i + 0, j + 34, k + 22, this.air);
        this.b(i + 0, j + 34, k + 23, this.air);
        this.b(i + 0, j + 34, k + 24, this.air);
        this.b(i + 0, j + 34, k + 25, this.air);
        this.b(i + 0, j + 34, k + 26, this.air);
        this.b(i + 0, j + 34, k + 27, this.air);
        this.b(i + 0, j + 34, k + 28, this.air);
        this.b(i + 0, j + 34, k + 29, this.air);
        this.b(i + 0, j + 34, k + 30, this.air);
        this.b(i + 0, j + 34, k + 31, this.air);
        this.b(i + 0, j + 34, k + 32, this.air);
        this.b(i + 0, j + 34, k + 33, this.air);
        this.b(i + 0, j + 34, k + 34, this.air);
        this.b(i + 0, j + 34, k + 35, this.air);
        this.b(i + 0, j + 34, k + 36, this.air);
        this.b(i + 0, j + 34, k + 37, this.air);
        this.b(i + 0, j + 35, k + 8, this.air);
        this.b(i + 0, j + 35, k + 9, this.air);
        this.b(i + 0, j + 35, k + 10, this.air);
        this.b(i + 0, j + 35, k + 11, this.air);
        this.b(i + 0, j + 35, k + 12, this.air);
        this.b(i + 0, j + 35, k + 13, this.air);
        this.b(i + 0, j + 35, k + 14, this.air);
        this.b(i + 0, j + 35, k + 15, this.air);
        this.b(i + 0, j + 35, k + 16, this.air);
        this.b(i + 0, j + 35, k + 17, this.air);
        this.b(i + 0, j + 35, k + 18, this.air);
        this.b(i + 0, j + 35, k + 19, this.air);
        this.b(i + 0, j + 35, k + 20, this.air);
        this.b(i + 0, j + 35, k + 21, this.air);
        this.b(i + 0, j + 35, k + 22, this.air);
        this.b(i + 0, j + 35, k + 23, this.air);
        this.b(i + 0, j + 35, k + 24, this.air);
        this.b(i + 0, j + 35, k + 25, this.air);
        this.b(i + 0, j + 35, k + 26, this.air);
        this.b(i + 0, j + 35, k + 27, this.air);
        this.b(i + 0, j + 35, k + 28, this.air);
        this.b(i + 0, j + 35, k + 29, this.air);
        this.b(i + 0, j + 35, k + 30, this.air);
        this.b(i + 0, j + 35, k + 31, this.air);
        this.b(i + 0, j + 35, k + 32, this.air);
        this.b(i + 0, j + 35, k + 33, this.air);
        this.b(i + 0, j + 35, k + 34, this.air);
        this.b(i + 0, j + 35, k + 35, this.air);
        this.b(i + 0, j + 35, k + 36, this.air);
        this.b(i + 0, j + 35, k + 37, this.air);
        this.b(i + 0, j + 36, k + 8, this.air);
        this.b(i + 0, j + 36, k + 9, this.air);
        this.b(i + 0, j + 36, k + 10, this.air);
        this.b(i + 0, j + 36, k + 11, this.air);
        this.b(i + 0, j + 36, k + 12, this.air);
        this.b(i + 0, j + 36, k + 13, this.air);
        this.b(i + 0, j + 36, k + 14, this.air);
        this.b(i + 0, j + 36, k + 15, this.air);
        this.b(i + 0, j + 36, k + 16, this.air);
        this.b(i + 0, j + 36, k + 17, this.air);
        this.b(i + 0, j + 36, k + 18, this.air);
        this.b(i + 0, j + 36, k + 19, this.air);
        this.b(i + 0, j + 36, k + 20, this.air);
        this.b(i + 0, j + 36, k + 21, this.air);
        this.b(i + 0, j + 36, k + 22, this.air);
        this.b(i + 0, j + 36, k + 23, this.air);
        this.b(i + 0, j + 36, k + 24, this.air);
        this.b(i + 0, j + 36, k + 25, this.air);
        this.b(i + 0, j + 36, k + 26, this.air);
        this.b(i + 0, j + 36, k + 27, this.air);
        this.b(i + 0, j + 36, k + 28, this.air);
        this.b(i + 0, j + 36, k + 29, this.air);
        this.b(i + 0, j + 36, k + 30, this.air);
        this.b(i + 0, j + 36, k + 31, this.air);
        this.b(i + 0, j + 36, k + 32, this.air);
        this.b(i + 0, j + 36, k + 33, this.air);
        this.b(i + 0, j + 36, k + 34, this.air);
        this.b(i + 0, j + 36, k + 35, this.air);
        this.b(i + 0, j + 36, k + 36, this.air);
        this.b(i + 0, j + 36, k + 37, this.air);
        this.b(i + 0, j + 37, k + 8, this.air);
        this.b(i + 0, j + 37, k + 9, this.air);
        this.b(i + 0, j + 37, k + 10, this.air);
        this.b(i + 0, j + 37, k + 11, this.air);
        this.b(i + 0, j + 37, k + 12, this.air);
        this.b(i + 0, j + 37, k + 13, this.air);
        this.b(i + 0, j + 37, k + 14, this.air);
        this.b(i + 0, j + 37, k + 15, this.air);
        this.b(i + 0, j + 37, k + 16, this.air);
        this.b(i + 0, j + 37, k + 17, this.air);
        this.b(i + 0, j + 37, k + 18, this.air);
        this.b(i + 0, j + 37, k + 19, this.air);
        this.b(i + 0, j + 37, k + 20, this.air);
        this.b(i + 0, j + 37, k + 21, this.air);
        this.b(i + 0, j + 37, k + 22, this.air);
        this.b(i + 0, j + 37, k + 23, this.air);
        this.b(i + 0, j + 37, k + 24, this.air);
        this.b(i + 0, j + 37, k + 25, this.air);
        this.b(i + 0, j + 37, k + 26, this.air);
        this.b(i + 0, j + 37, k + 27, this.air);
        this.b(i + 0, j + 37, k + 28, this.air);
        this.b(i + 0, j + 37, k + 29, this.air);
        this.b(i + 0, j + 37, k + 30, this.air);
        this.b(i + 0, j + 37, k + 31, this.air);
        this.b(i + 0, j + 37, k + 32, this.air);
        this.b(i + 0, j + 37, k + 33, this.air);
        this.b(i + 0, j + 37, k + 34, this.air);
        this.b(i + 0, j + 37, k + 35, this.air);
        this.b(i + 0, j + 37, k + 36, this.air);
        this.b(i + 0, j + 37, k + 37, this.air);
        this.b(i + 0, j + 38, k + 8, this.air);
        this.b(i + 0, j + 38, k + 9, this.air);
        this.b(i + 0, j + 38, k + 10, this.air);
        this.b(i + 0, j + 38, k + 11, this.air);
        this.b(i + 0, j + 38, k + 12, this.air);
        this.b(i + 0, j + 38, k + 13, this.air);
        this.b(i + 0, j + 38, k + 14, this.air);
        this.b(i + 0, j + 38, k + 15, this.air);
        this.b(i + 0, j + 38, k + 16, this.air);
        this.b(i + 0, j + 38, k + 17, this.air);
        this.b(i + 0, j + 38, k + 18, this.air);
        this.b(i + 0, j + 38, k + 19, this.air);
        this.b(i + 0, j + 38, k + 20, this.air);
        this.b(i + 0, j + 38, k + 21, this.air);
        this.b(i + 0, j + 38, k + 22, this.air);
        this.b(i + 0, j + 38, k + 23, this.air);
        this.b(i + 0, j + 38, k + 24, this.air);
        this.b(i + 0, j + 38, k + 25, this.air);
        this.b(i + 0, j + 38, k + 26, this.air);
        this.b(i + 0, j + 38, k + 27, this.air);
        this.b(i + 0, j + 38, k + 28, this.air);
        this.b(i + 0, j + 38, k + 29, this.air);
        this.b(i + 0, j + 38, k + 30, this.air);
        this.b(i + 0, j + 38, k + 31, this.air);
        this.b(i + 0, j + 38, k + 32, this.air);
        this.b(i + 0, j + 38, k + 33, this.air);
        this.b(i + 0, j + 38, k + 34, this.air);
        this.b(i + 0, j + 38, k + 35, this.air);
        this.b(i + 0, j + 38, k + 36, this.air);
        this.b(i + 0, j + 38, k + 37, this.air);
        this.b(i + 0, j + 39, k + 8, this.c, 3);
        this.b(i + 0, j + 39, k + 9, this.c, 3);
        this.b(i + 0, j + 39, k + 10, this.c, 3);
        this.b(i + 0, j + 39, k + 11, this.c, 3);
        this.b(i + 0, j + 39, k + 12, this.c, 3);
        this.b(i + 0, j + 39, k + 13, this.c, 3);
        this.b(i + 0, j + 39, k + 14, this.c, 3);
        this.b(i + 0, j + 39, k + 15, this.c, 3);
        this.b(i + 0, j + 39, k + 16, this.c, 3);
        this.b(i + 0, j + 39, k + 17, this.c, 3);
        this.b(i + 0, j + 39, k + 18, this.c, 3);
        this.b(i + 0, j + 39, k + 19, this.c, 3);
        this.b(i + 0, j + 39, k + 20, this.c, 3);
        this.b(i + 0, j + 39, k + 21, this.c, 3);
        this.b(i + 0, j + 39, k + 22, this.c, 3);
        this.b(i + 0, j + 39, k + 23, this.c, 3);
        this.b(i + 0, j + 39, k + 24, this.c, 3);
        this.b(i + 0, j + 39, k + 25, this.c, 3);
        this.b(i + 0, j + 39, k + 26, this.c, 3);
        this.b(i + 0, j + 39, k + 27, this.c, 3);
        this.b(i + 0, j + 39, k + 28, this.c, 3);
        this.b(i + 0, j + 39, k + 29, this.c, 3);
        this.b(i + 0, j + 39, k + 30, this.c, 3);
        this.b(i + 0, j + 39, k + 31, this.c, 3);
        this.b(i + 0, j + 39, k + 32, this.c, 3);
        this.b(i + 0, j + 39, k + 33, this.c, 3);
        this.b(i + 0, j + 39, k + 34, this.c, 3);
        this.b(i + 0, j + 39, k + 35, this.c, 3);
        this.b(i + 0, j + 39, k + 36, this.c, 3);
        this.b(i + 0, j + 39, k + 37, this.c, 3);
        this.b(i + 0, j + 40, k + 8, this.air);
        this.b(i + 0, j + 40, k + 9, this.air);
        this.b(i + 0, j + 40, k + 10, this.air);
        this.b(i + 0, j + 40, k + 11, this.air);
        this.b(i + 0, j + 40, k + 12, this.air);
        this.b(i + 0, j + 40, k + 13, this.air);
        this.b(i + 0, j + 40, k + 14, this.air);
        this.b(i + 0, j + 40, k + 15, this.air);
        this.b(i + 0, j + 40, k + 16, this.air);
        this.b(i + 0, j + 40, k + 17, this.air);
        this.b(i + 0, j + 40, k + 18, this.air);
        this.b(i + 0, j + 40, k + 19, this.c, 11);
        this.b(i + 0, j + 40, k + 20, this.c, 11);
        this.b(i + 0, j + 40, k + 21, this.c, 11);
        this.b(i + 0, j + 40, k + 22, this.c, 11);
        this.b(i + 0, j + 40, k + 23, this.c, 11);
        this.b(i + 0, j + 40, k + 24, this.c, 11);
        this.b(i + 0, j + 40, k + 25, this.c, 11);
        this.b(i + 0, j + 40, k + 26, this.c, 11);
        this.b(i + 0, j + 40, k + 27, this.air);
        this.b(i + 0, j + 40, k + 28, this.air);
        this.b(i + 0, j + 40, k + 29, this.air);
        this.b(i + 0, j + 40, k + 30, this.air);
        this.b(i + 0, j + 40, k + 31, this.air);
        this.b(i + 0, j + 40, k + 32, this.air);
        this.b(i + 0, j + 40, k + 33, this.air);
        this.b(i + 0, j + 40, k + 34, this.air);
        this.b(i + 0, j + 40, k + 35, this.air);
        this.b(i + 0, j + 40, k + 36, this.air);
        this.b(i + 0, j + 40, k + 37, this.air);
        this.b(i + 0, j + 41, k + 8, this.air);
        this.b(i + 0, j + 41, k + 9, this.air);
        this.b(i + 0, j + 41, k + 10, this.air);
        this.b(i + 0, j + 41, k + 11, this.air);
        this.b(i + 0, j + 41, k + 12, this.air);
        this.b(i + 0, j + 41, k + 13, this.air);
        this.b(i + 0, j + 41, k + 14, this.air);
        this.b(i + 0, j + 41, k + 15, this.air);
        this.b(i + 0, j + 41, k + 16, this.air);
        this.b(i + 0, j + 41, k + 17, this.air);
        this.b(i + 0, j + 41, k + 18, this.air);
        this.b(i + 0, j + 41, k + 19, this.c, 11);
        this.b(i + 0, j + 41, k + 20, this.c, 11);
        this.b(i + 0, j + 41, k + 21, this.c, 11);
        this.b(i + 0, j + 41, k + 22, this.c, 11);
        this.b(i + 0, j + 41, k + 23, this.c, 11);
        this.b(i + 0, j + 41, k + 24, this.c, 11);
        this.b(i + 0, j + 41, k + 25, this.c, 11);
        this.b(i + 0, j + 41, k + 26, this.c, 11);
        this.b(i + 0, j + 41, k + 27, this.air);
        this.b(i + 0, j + 41, k + 28, this.air);
        this.b(i + 0, j + 41, k + 29, this.air);
        this.b(i + 0, j + 41, k + 30, this.air);
        this.b(i + 0, j + 41, k + 31, this.air);
        this.b(i + 0, j + 41, k + 32, this.air);
        this.b(i + 0, j + 41, k + 33, this.air);
        this.b(i + 0, j + 41, k + 34, this.air);
        this.b(i + 0, j + 41, k + 35, this.air);
        this.b(i + 0, j + 41, k + 36, this.air);
        this.b(i + 0, j + 41, k + 37, this.air);
        this.b(i + 0, j + 42, k + 8, this.air);
        this.b(i + 0, j + 42, k + 9, this.air);
        this.b(i + 0, j + 42, k + 10, this.air);
        this.b(i + 0, j + 42, k + 11, this.air);
        this.b(i + 0, j + 42, k + 12, this.air);
        this.b(i + 0, j + 42, k + 13, this.air);
        this.b(i + 0, j + 42, k + 14, this.air);
        this.b(i + 0, j + 42, k + 15, this.air);
        this.b(i + 0, j + 42, k + 16, this.air);
        this.b(i + 0, j + 42, k + 17, this.air);
        this.b(i + 0, j + 42, k + 18, this.air);
        this.b(i + 0, j + 42, k + 19, this.c, 11);
        this.b(i + 0, j + 42, k + 20, this.c, 11);
        this.b(i + 0, j + 42, k + 21, this.c, 11);
        this.b(i + 0, j + 42, k + 22, this.c, 11);
        this.b(i + 0, j + 42, k + 23, this.c, 11);
        this.b(i + 0, j + 42, k + 24, this.c, 11);
        this.b(i + 0, j + 42, k + 25, this.c, 11);
        this.b(i + 0, j + 42, k + 26, this.c, 11);
        this.b(i + 0, j + 42, k + 27, this.air);
        this.b(i + 0, j + 42, k + 28, this.air);
        this.b(i + 0, j + 42, k + 29, this.air);
        this.b(i + 0, j + 42, k + 30, this.air);
        this.b(i + 0, j + 42, k + 31, this.air);
        this.b(i + 0, j + 42, k + 32, this.air);
        this.b(i + 0, j + 42, k + 33, this.air);
        this.b(i + 0, j + 42, k + 34, this.air);
        this.b(i + 0, j + 42, k + 35, this.air);
        this.b(i + 0, j + 42, k + 36, this.air);
        this.b(i + 0, j + 42, k + 37, this.air);
        this.b(i + 0, j + 43, k + 8, this.air);
        this.b(i + 0, j + 43, k + 9, this.air);
        this.b(i + 0, j + 43, k + 10, this.air);
        this.b(i + 0, j + 43, k + 11, this.air);
        this.b(i + 0, j + 43, k + 12, this.air);
        this.b(i + 0, j + 43, k + 13, this.air);
        this.b(i + 0, j + 43, k + 14, this.air);
        this.b(i + 0, j + 43, k + 15, this.air);
        this.b(i + 0, j + 43, k + 16, this.air);
        this.b(i + 0, j + 43, k + 17, this.air);
        this.b(i + 0, j + 43, k + 18, this.air);
        this.b(i + 0, j + 43, k + 19, this.air);
        this.b(i + 0, j + 43, k + 20, this.c, 11);
        this.b(i + 0, j + 43, k + 21, this.c, 11);
        this.b(i + 0, j + 43, k + 22, this.c, 11);
        this.b(i + 0, j + 43, k + 23, this.c, 11);
        this.b(i + 0, j + 43, k + 24, this.c, 11);
        this.b(i + 0, j + 43, k + 25, this.c, 11);
        this.b(i + 0, j + 43, k + 26, this.air);
        this.b(i + 0, j + 43, k + 27, this.air);
        this.b(i + 0, j + 43, k + 28, this.air);
        this.b(i + 0, j + 43, k + 29, this.air);
        this.b(i + 0, j + 43, k + 30, this.air);
        this.b(i + 0, j + 43, k + 31, this.air);
        this.b(i + 0, j + 43, k + 32, this.air);
        this.b(i + 0, j + 43, k + 33, this.air);
        this.b(i + 0, j + 43, k + 34, this.air);
        this.b(i + 0, j + 43, k + 35, this.air);
        this.b(i + 0, j + 43, k + 36, this.air);
        this.b(i + 0, j + 43, k + 37, this.air);
        this.b(i + 0, j + 44, k + 8, this.air);
        this.b(i + 0, j + 44, k + 9, this.air);
        this.b(i + 0, j + 44, k + 10, this.air);
        this.b(i + 0, j + 44, k + 11, this.air);
        this.b(i + 0, j + 44, k + 12, this.air);
        this.b(i + 0, j + 44, k + 13, this.air);
        this.b(i + 0, j + 44, k + 14, this.air);
        this.b(i + 0, j + 44, k + 15, this.air);
        this.b(i + 0, j + 44, k + 16, this.air);
        this.b(i + 0, j + 44, k + 17, this.air);
        this.b(i + 0, j + 44, k + 18, this.air);
        this.b(i + 0, j + 44, k + 19, this.air);
        this.b(i + 0, j + 44, k + 20, this.air);
        this.b(i + 0, j + 44, k + 21, this.air);
        this.b(i + 0, j + 44, k + 22, this.c, 4);
        this.b(i + 0, j + 44, k + 23, this.c, 4);
        this.b(i + 0, j + 44, k + 24, this.air);
        this.b(i + 0, j + 44, k + 25, this.air);
        this.b(i + 0, j + 44, k + 26, this.air);
        this.b(i + 0, j + 44, k + 27, this.air);
        this.b(i + 0, j + 44, k + 28, this.air);
        this.b(i + 0, j + 44, k + 29, this.air);
        this.b(i + 0, j + 44, k + 30, this.air);
        this.b(i + 0, j + 44, k + 31, this.air);
        this.b(i + 0, j + 44, k + 32, this.air);
        this.b(i + 0, j + 44, k + 33, this.air);
        this.b(i + 0, j + 44, k + 34, this.air);
        this.b(i + 0, j + 44, k + 35, this.air);
        this.b(i + 0, j + 44, k + 36, this.air);
        this.b(i + 0, j + 44, k + 37, this.air);
        this.b(i + 0, j + 45, k + 8, this.air);
        this.b(i + 0, j + 45, k + 9, this.air);
        this.b(i + 0, j + 45, k + 10, this.air);
        this.b(i + 0, j + 45, k + 11, this.air);
        this.b(i + 0, j + 45, k + 12, this.air);
        this.b(i + 0, j + 45, k + 13, this.air);
        this.b(i + 0, j + 45, k + 14, this.air);
        this.b(i + 0, j + 45, k + 15, this.air);
        this.b(i + 0, j + 45, k + 16, this.air);
        this.b(i + 0, j + 45, k + 17, this.air);
        this.b(i + 0, j + 45, k + 18, this.air);
        this.b(i + 0, j + 45, k + 19, this.air);
        this.b(i + 0, j + 45, k + 20, this.air);
        this.b(i + 0, j + 45, k + 21, this.air);
        this.b(i + 0, j + 45, k + 22, this.air);
        this.b(i + 0, j + 45, k + 23, this.air);
        this.b(i + 0, j + 45, k + 24, this.air);
        this.b(i + 0, j + 45, k + 25, this.air);
        this.b(i + 0, j + 45, k + 26, this.air);
        this.b(i + 0, j + 45, k + 27, this.air);
        this.b(i + 0, j + 45, k + 28, this.air);
        this.b(i + 0, j + 45, k + 29, this.air);
        this.b(i + 0, j + 45, k + 30, this.air);
        this.b(i + 0, j + 45, k + 31, this.air);
        this.b(i + 0, j + 45, k + 32, this.air);
        this.b(i + 0, j + 45, k + 33, this.air);
        this.b(i + 0, j + 45, k + 34, this.air);
        this.b(i + 0, j + 45, k + 35, this.air);
        this.b(i + 0, j + 45, k + 36, this.air);
        this.b(i + 0, j + 45, k + 37, this.air);
        this.b(i + 0, j + 46, k + 8, this.air);
        this.b(i + 0, j + 46, k + 9, this.air);
        this.b(i + 0, j + 46, k + 10, this.air);
        this.b(i + 0, j + 46, k + 11, this.air);
        this.b(i + 0, j + 46, k + 12, this.air);
        this.b(i + 0, j + 46, k + 13, this.air);
        this.b(i + 0, j + 46, k + 14, this.air);
        this.b(i + 0, j + 46, k + 15, this.air);
        this.b(i + 0, j + 46, k + 16, this.air);
        this.b(i + 0, j + 46, k + 17, this.air);
        this.b(i + 0, j + 46, k + 18, this.air);
        this.b(i + 0, j + 46, k + 19, this.air);
        this.b(i + 0, j + 46, k + 20, this.air);
        this.b(i + 0, j + 46, k + 21, this.air);
        this.b(i + 0, j + 46, k + 22, this.air);
        this.b(i + 0, j + 46, k + 23, this.air);
        this.b(i + 0, j + 46, k + 24, this.air);
        this.b(i + 0, j + 46, k + 25, this.air);
        this.b(i + 0, j + 46, k + 26, this.air);
        this.b(i + 0, j + 46, k + 27, this.air);
        this.b(i + 0, j + 46, k + 28, this.air);
        this.b(i + 0, j + 46, k + 29, this.air);
        this.b(i + 0, j + 46, k + 30, this.air);
        this.b(i + 0, j + 46, k + 31, this.air);
        this.b(i + 0, j + 46, k + 32, this.air);
        this.b(i + 0, j + 46, k + 33, this.air);
        this.b(i + 0, j + 46, k + 34, this.air);
        this.b(i + 0, j + 46, k + 35, this.air);
        this.b(i + 0, j + 46, k + 36, this.air);
        this.b(i + 0, j + 46, k + 37, this.air);
        this.b(i + 0, j + 47, k + 8, this.air);
        this.b(i + 0, j + 47, k + 9, this.air);
        this.b(i + 0, j + 47, k + 10, this.air);
        this.b(i + 0, j + 47, k + 11, this.air);
        this.b(i + 0, j + 47, k + 12, this.air);
        this.b(i + 0, j + 47, k + 13, this.air);
        this.b(i + 0, j + 47, k + 14, this.air);
        this.b(i + 0, j + 47, k + 15, this.air);
        this.b(i + 0, j + 47, k + 16, this.air);
        this.b(i + 0, j + 47, k + 17, this.air);
        this.b(i + 0, j + 47, k + 18, this.air);
        this.b(i + 0, j + 47, k + 19, this.air);
        this.b(i + 0, j + 47, k + 20, this.air);
        this.b(i + 0, j + 47, k + 21, this.air);
        this.b(i + 0, j + 47, k + 22, this.air);
        this.b(i + 0, j + 47, k + 23, this.air);
        this.b(i + 0, j + 47, k + 24, this.air);
        this.b(i + 0, j + 47, k + 25, this.air);
        this.b(i + 0, j + 47, k + 26, this.air);
        this.b(i + 0, j + 47, k + 27, this.air);
        this.b(i + 0, j + 47, k + 28, this.air);
        this.b(i + 0, j + 47, k + 29, this.air);
        this.b(i + 0, j + 47, k + 30, this.air);
        this.b(i + 0, j + 47, k + 31, this.air);
        this.b(i + 0, j + 47, k + 32, this.air);
        this.b(i + 0, j + 47, k + 33, this.air);
        this.b(i + 0, j + 47, k + 34, this.air);
        this.b(i + 0, j + 47, k + 35, this.air);
        this.b(i + 0, j + 47, k + 36, this.air);
        this.b(i + 0, j + 47, k + 37, this.air);
        this.b(i + 0, j + 48, k + 8, this.air);
        this.b(i + 0, j + 48, k + 9, this.air);
        this.b(i + 0, j + 48, k + 10, this.air);
        this.b(i + 0, j + 48, k + 11, this.air);
        this.b(i + 0, j + 48, k + 12, this.air);
        this.b(i + 0, j + 48, k + 13, this.air);
        this.b(i + 0, j + 48, k + 14, this.air);
        this.b(i + 0, j + 48, k + 15, this.air);
        this.b(i + 0, j + 48, k + 16, this.air);
        this.b(i + 0, j + 48, k + 17, this.air);
        this.b(i + 0, j + 48, k + 18, this.air);
        this.b(i + 0, j + 48, k + 19, this.air);
        this.b(i + 0, j + 48, k + 20, this.air);
        this.b(i + 0, j + 48, k + 21, this.air);
        this.b(i + 0, j + 48, k + 22, this.air);
        this.b(i + 0, j + 48, k + 23, this.air);
        this.b(i + 0, j + 48, k + 24, this.air);
        this.b(i + 0, j + 48, k + 25, this.air);
        this.b(i + 0, j + 48, k + 26, this.air);
        this.b(i + 0, j + 48, k + 27, this.air);
        this.b(i + 0, j + 48, k + 28, this.air);
        this.b(i + 0, j + 48, k + 29, this.air);
        this.b(i + 0, j + 48, k + 30, this.air);
        this.b(i + 0, j + 48, k + 31, this.air);
        this.b(i + 0, j + 48, k + 32, this.air);
        this.b(i + 0, j + 48, k + 33, this.air);
        this.b(i + 0, j + 48, k + 34, this.air);
        this.b(i + 0, j + 48, k + 35, this.air);
        this.b(i + 0, j + 48, k + 36, this.air);
        this.b(i + 0, j + 48, k + 37, this.air);
        this.b(i + 0, j + 49, k + 8, this.air);
        this.b(i + 0, j + 49, k + 9, this.air);
        this.b(i + 0, j + 49, k + 10, this.air);
        this.b(i + 0, j + 49, k + 11, this.air);
        this.b(i + 0, j + 49, k + 12, this.air);
        this.b(i + 0, j + 49, k + 13, this.air);
        this.b(i + 0, j + 49, k + 14, this.air);
        this.b(i + 0, j + 49, k + 15, this.air);
        this.b(i + 0, j + 49, k + 16, this.air);
        this.b(i + 0, j + 49, k + 17, this.air);
        this.b(i + 0, j + 49, k + 18, this.air);
        this.b(i + 0, j + 49, k + 19, this.air);
        this.b(i + 0, j + 49, k + 20, this.air);
        this.b(i + 0, j + 49, k + 21, this.air);
        this.b(i + 0, j + 49, k + 22, this.air);
        this.b(i + 0, j + 49, k + 23, this.air);
        this.b(i + 0, j + 49, k + 24, this.air);
        this.b(i + 0, j + 49, k + 25, this.air);
        this.b(i + 0, j + 49, k + 26, this.air);
        this.b(i + 0, j + 49, k + 27, this.air);
        this.b(i + 0, j + 49, k + 28, this.air);
        this.b(i + 0, j + 49, k + 29, this.air);
        this.b(i + 0, j + 49, k + 30, this.air);
        this.b(i + 0, j + 49, k + 31, this.air);
        this.b(i + 0, j + 49, k + 32, this.air);
        this.b(i + 0, j + 49, k + 33, this.air);
        this.b(i + 0, j + 49, k + 34, this.air);
        this.b(i + 0, j + 49, k + 35, this.air);
        this.b(i + 0, j + 49, k + 36, this.air);
        this.b(i + 0, j + 49, k + 37, this.air);
        bsP2 p2 = new bsP2();
        p2.setWorld(w);
        p2.generate2(w, rand, i, j, k);
        return true;
    }
}

