/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  JinRyuu.JRMCore.JRMCoreSafe
 *  JinRyuu.JRMCore.blocks.BlocksJRMC
 *  net.minecraft.block.Block
 *  net.minecraft.block.material.Material
 *  net.minecraft.init.Blocks
 *  net.minecraft.world.World
 *  net.minecraft.world.gen.feature.WorldGenerator
 */
package JinRyuu.DragonBC.common.Villages;

import JinRyuu.DragonBC.common.Villages.KnTrP2;
import JinRyuu.DragonBC.common.mod_DragonBC;
import JinRyuu.JRMCore.JRMCoreSafe;
import JinRyuu.JRMCore.blocks.BlocksJRMC;
import java.util.Random;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.init.Blocks;
import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;

public class KnTr
extends WorldGenerator {
    public Block c = BlocksJRMC.BlockColoredStone;
    public Block d = BlocksJRMC.BlockFence;
    public Block b = BlocksJRMC.BlockFence;
    public Block l = Blocks.leaves;
    public Block s = BlocksJRMC.stoneSingleSlab;
    public Block g = Blocks.glass;
    public Block v = Blocks.log;
    public Block t = Blocks.dirt;
    public Block e = Blocks.glowstone;
    public Block o = BlocksJRMC.BlockStairs;

    protected void b(World par1World, int par2, int par3, int par4, Block par5) {
        this.setBlockAndNotifyAdequately(par1World, par2, par3, par4, par5, 0);
    }

    protected void b(World par1World, int par2, int par3, int par4, Block par5, int par6) {
        this.setBlockAndNotifyAdequately(par1World, par2, par3, par4, par5, par6);
    }

    /*
     * Opcode count of 22255 triggered aggressive code reduction.  Override with --aggressivesizethreshold.
     */
    public boolean generate(World w, Random rand, int i, int j, int k) {
        block1: {
            i = 68;
            j = 120;
            k = 30;
            JRMCoreSafe safe = new JRMCoreSafe(w);
            safe.isSpawn("false ", "dont", 0, safe.dataDir, "kn.dbc");
            safe.isSpawn("false", 0, safe.dataDir, "kn.dbc");
            int cfr_ignored_0 = w.provider.dimensionId;
            if (w.getBlock(i, j + 100, k).getMaterial() != Material.air) break block1;
            safe.saveSpawnList("spwn ", safe.dataDir, "kn.dbc");
            mod_DragonBC.logger.info("Korin's Tower Spawned");
            for (int z = 119; z > 61 && w.getBlock(i + 9, z, k + 12).getMaterial() == Material.air; --z) {
                this.b(w, i + 9, z, k + 12, this.c, 8);
            }
            this.b(w, i + 0, j + 7, k + 3, this.c, 8);
            this.b(w, i + 0, j + 7, k + 4, this.c, 8);
            this.b(w, i + 0, j + 7, k + 5, this.c, 8);
            this.b(w, i + 0, j + 7, k + 6, this.c, 8);
            this.b(w, i + 0, j + 7, k + 7, this.c, 8);
            this.b(w, i + 0, j + 7, k + 8, this.c, 8);
            this.b(w, i + 0, j + 7, k + 9, this.c, 8);
            this.b(w, i + 0, j + 7, k + 10, this.c, 8);
            this.b(w, i + 0, j + 7, k + 11, this.c, 8);
            this.b(w, i + 0, j + 7, k + 12, this.c, 8);
            this.b(w, i + 0, j + 7, k + 13, this.c, 8);
            this.b(w, i + 0, j + 7, k + 14, this.c, 8);
            this.b(w, i + 0, j + 7, k + 15, this.c, 8);
            this.b(w, i + 0, j + 7, k + 16, this.c, 8);
            this.b(w, i + 0, j + 7, k + 17, this.c, 8);
            this.b(w, i + 0, j + 7, k + 18, this.c, 8);
            this.b(w, i + 0, j + 7, k + 19, this.c, 8);
            this.b(w, i + 0, j + 7, k + 20, this.c, 8);
            this.b(w, i + 0, j + 7, k + 21, this.c, 8);
            this.b(w, i + 0, j + 8, k + 3, this.c, 8);
            this.b(w, i + 0, j + 8, k + 4, this.c, 8);
            this.b(w, i + 0, j + 8, k + 5, this.c, 8);
            this.b(w, i + 0, j + 8, k + 6, this.c, 8);
            this.b(w, i + 0, j + 8, k + 7, this.c, 8);
            this.b(w, i + 0, j + 8, k + 8, this.c, 8);
            this.b(w, i + 0, j + 8, k + 9, this.c, 8);
            this.b(w, i + 0, j + 8, k + 10, this.c, 8);
            this.b(w, i + 0, j + 8, k + 11, this.c, 8);
            this.b(w, i + 0, j + 8, k + 12, this.c, 8);
            this.b(w, i + 0, j + 8, k + 13, this.c, 8);
            this.b(w, i + 0, j + 8, k + 14, this.c, 8);
            this.b(w, i + 0, j + 8, k + 15, this.c, 8);
            this.b(w, i + 0, j + 8, k + 16, this.c, 8);
            this.b(w, i + 0, j + 8, k + 17, this.c, 8);
            this.b(w, i + 0, j + 8, k + 18, this.c, 8);
            this.b(w, i + 0, j + 8, k + 19, this.c, 8);
            this.b(w, i + 0, j + 8, k + 20, this.c, 8);
            this.b(w, i + 0, j + 8, k + 21, this.c, 8);
            this.b(w, i + 0, j + 9, k + 5, this.c, 8);
            this.b(w, i + 0, j + 9, k + 6, this.c, 8);
            this.b(w, i + 0, j + 9, k + 7, this.c, 8);
            this.b(w, i + 0, j + 9, k + 14, this.c, 8);
            this.b(w, i + 0, j + 9, k + 15, this.c, 8);
            this.b(w, i + 0, j + 9, k + 16, this.c, 8);
            this.b(w, i + 0, j + 9, k + 21, this.c, 8);
            this.b(w, i + 0, j + 10, k + 3, this.c, 8);
            this.b(w, i + 0, j + 10, k + 4, this.c, 8);
            this.b(w, i + 0, j + 10, k + 5, this.c, 8);
            this.b(w, i + 0, j + 10, k + 6, this.c, 8);
            this.b(w, i + 0, j + 10, k + 7, this.c, 8);
            this.b(w, i + 0, j + 10, k + 8, this.c, 8);
            this.b(w, i + 0, j + 10, k + 9, this.c, 8);
            this.b(w, i + 0, j + 10, k + 10, this.c, 8);
            this.b(w, i + 0, j + 10, k + 11, this.c, 8);
            this.b(w, i + 0, j + 10, k + 12, this.c, 8);
            this.b(w, i + 0, j + 10, k + 13, this.c, 8);
            this.b(w, i + 0, j + 10, k + 14, this.c, 8);
            this.b(w, i + 0, j + 10, k + 15, this.c, 8);
            this.b(w, i + 0, j + 10, k + 16, this.c, 8);
            this.b(w, i + 0, j + 10, k + 17, this.c, 8);
            this.b(w, i + 0, j + 10, k + 18, this.c, 8);
            this.b(w, i + 0, j + 10, k + 19, this.c, 8);
            this.b(w, i + 0, j + 10, k + 20, this.c, 8);
            this.b(w, i + 0, j + 10, k + 21, this.c, 8);
            this.b(w, i + 0, j + 11, k + 3, this.c, 8);
            this.b(w, i + 0, j + 11, k + 4, this.c, 8);
            this.b(w, i + 0, j + 11, k + 5, this.c, 8);
            this.b(w, i + 0, j + 11, k + 6, this.c, 8);
            this.b(w, i + 0, j + 11, k + 7, this.c, 8);
            this.b(w, i + 0, j + 11, k + 8, this.c, 8);
            this.b(w, i + 0, j + 11, k + 9, this.c, 8);
            this.b(w, i + 0, j + 11, k + 10, this.c, 8);
            this.b(w, i + 0, j + 11, k + 11, this.c, 8);
            this.b(w, i + 0, j + 11, k + 12, this.c, 8);
            this.b(w, i + 0, j + 11, k + 13, this.c, 8);
            this.b(w, i + 0, j + 11, k + 14, this.c, 8);
            this.b(w, i + 0, j + 11, k + 15, this.c, 8);
            this.b(w, i + 0, j + 11, k + 16, this.c, 8);
            this.b(w, i + 0, j + 11, k + 17, this.c, 8);
            this.b(w, i + 0, j + 11, k + 18, this.c, 8);
            this.b(w, i + 0, j + 11, k + 19, this.c, 8);
            this.b(w, i + 0, j + 11, k + 20, this.c, 8);
            this.b(w, i + 0, j + 11, k + 21, this.c, 8);
            this.b(w, i + 0, j + 12, k + 3, this.c, 8);
            this.b(w, i + 0, j + 12, k + 4, this.c, 8);
            this.b(w, i + 0, j + 12, k + 5, this.c, 8);
            this.b(w, i + 0, j + 12, k + 6, this.c, 8);
            this.b(w, i + 0, j + 12, k + 7, this.c, 8);
            this.b(w, i + 0, j + 12, k + 8, this.c, 8);
            this.b(w, i + 0, j + 12, k + 9, this.c, 8);
            this.b(w, i + 0, j + 12, k + 10, this.c, 8);
            this.b(w, i + 0, j + 12, k + 11, this.c, 8);
            this.b(w, i + 0, j + 12, k + 12, this.c, 8);
            this.b(w, i + 0, j + 12, k + 13, this.c, 8);
            this.b(w, i + 0, j + 12, k + 14, this.c, 8);
            this.b(w, i + 0, j + 12, k + 15, this.c, 8);
            this.b(w, i + 0, j + 12, k + 16, this.c, 8);
            this.b(w, i + 0, j + 12, k + 17, this.c, 8);
            this.b(w, i + 0, j + 12, k + 18, this.c, 8);
            this.b(w, i + 0, j + 12, k + 19, this.c, 8);
            this.b(w, i + 0, j + 12, k + 20, this.c, 8);
            this.b(w, i + 0, j + 12, k + 21, this.c, 8);
            this.b(w, i + 0, j + 13, k + 3, this.d);
            this.b(w, i + 0, j + 13, k + 4, this.d);
            this.b(w, i + 0, j + 13, k + 5, this.d);
            this.b(w, i + 0, j + 13, k + 6, this.d);
            this.b(w, i + 0, j + 13, k + 7, this.d);
            this.b(w, i + 0, j + 13, k + 8, this.d);
            this.b(w, i + 0, j + 13, k + 9, this.d);
            this.b(w, i + 0, j + 13, k + 10, this.d);
            this.b(w, i + 0, j + 13, k + 11, this.d);
            this.b(w, i + 0, j + 13, k + 12, this.d);
            this.b(w, i + 0, j + 13, k + 13, this.d);
            this.b(w, i + 0, j + 13, k + 14, this.d);
            this.b(w, i + 0, j + 13, k + 15, this.d);
            this.b(w, i + 0, j + 13, k + 16, this.d);
            this.b(w, i + 0, j + 13, k + 17, this.d);
            this.b(w, i + 0, j + 13, k + 18, this.d);
            this.b(w, i + 0, j + 13, k + 19, this.d);
            this.b(w, i + 0, j + 13, k + 20, this.d);
            this.b(w, i + 0, j + 13, k + 21, this.d);
            this.b(w, i + 0, j + 17, k + 3, this.c, 8);
            this.b(w, i + 0, j + 17, k + 4, this.c, 8);
            this.b(w, i + 0, j + 17, k + 5, this.c, 8);
            this.b(w, i + 0, j + 17, k + 6, this.c, 8);
            this.b(w, i + 0, j + 17, k + 7, this.c, 8);
            this.b(w, i + 0, j + 17, k + 8, this.c, 8);
            this.b(w, i + 0, j + 17, k + 9, this.c, 8);
            this.b(w, i + 0, j + 17, k + 10, this.c, 8);
            this.b(w, i + 0, j + 17, k + 11, this.c, 8);
            this.b(w, i + 0, j + 17, k + 12, this.c, 8);
            this.b(w, i + 0, j + 17, k + 13, this.c, 8);
            this.b(w, i + 0, j + 17, k + 14, this.c, 8);
            this.b(w, i + 0, j + 17, k + 15, this.c, 8);
            this.b(w, i + 0, j + 17, k + 16, this.c, 8);
            this.b(w, i + 0, j + 17, k + 17, this.c, 8);
            this.b(w, i + 0, j + 17, k + 18, this.c, 8);
            this.b(w, i + 0, j + 17, k + 19, this.c, 8);
            this.b(w, i + 0, j + 17, k + 20, this.c, 8);
            this.b(w, i + 0, j + 17, k + 21, this.c, 8);
            this.b(w, i + 0, j + 18, k + 3, this.c, 8);
            this.b(w, i + 0, j + 18, k + 4, this.c, 7);
            this.b(w, i + 0, j + 18, k + 5, this.c, 8);
            this.b(w, i + 0, j + 18, k + 6, this.c, 8);
            this.b(w, i + 0, j + 18, k + 7, this.c, 8);
            this.b(w, i + 0, j + 18, k + 8, this.c, 8);
            this.b(w, i + 0, j + 18, k + 9, this.c, 8);
            this.b(w, i + 0, j + 18, k + 10, this.c, 7);
            this.b(w, i + 0, j + 18, k + 11, this.c, 8);
            this.b(w, i + 0, j + 18, k + 12, this.c, 8);
            this.b(w, i + 0, j + 18, k + 13, this.c, 8);
            this.b(w, i + 0, j + 18, k + 14, this.c, 8);
            this.b(w, i + 0, j + 18, k + 15, this.c, 8);
            this.b(w, i + 0, j + 18, k + 16, this.c, 8);
            this.b(w, i + 0, j + 18, k + 17, this.c, 7);
            this.b(w, i + 0, j + 18, k + 18, this.c, 8);
            this.b(w, i + 0, j + 18, k + 19, this.c, 8);
            this.b(w, i + 0, j + 18, k + 20, this.c, 8);
            this.b(w, i + 0, j + 18, k + 21, this.c, 8);
            this.b(w, i + 0, j + 19, k + 3, this.c, 7);
            this.b(w, i + 0, j + 19, k + 4, this.c, 8);
            this.b(w, i + 0, j + 19, k + 5, this.c, 7);
            this.b(w, i + 0, j + 19, k + 6, this.c, 8);
            this.b(w, i + 0, j + 19, k + 7, this.c, 8);
            this.b(w, i + 0, j + 19, k + 8, this.c, 8);
            this.b(w, i + 0, j + 19, k + 9, this.c, 7);
            this.b(w, i + 0, j + 19, k + 10, this.c, 8);
            this.b(w, i + 0, j + 19, k + 11, this.c, 7);
            this.b(w, i + 0, j + 19, k + 12, this.c, 8);
            this.b(w, i + 0, j + 19, k + 13, this.c, 8);
            this.b(w, i + 0, j + 19, k + 14, this.c, 8);
            this.b(w, i + 0, j + 19, k + 15, this.c, 8);
            this.b(w, i + 0, j + 19, k + 16, this.c, 7);
            this.b(w, i + 0, j + 19, k + 17, this.c, 8);
            this.b(w, i + 0, j + 19, k + 18, this.c, 7);
            this.b(w, i + 0, j + 19, k + 19, this.c, 8);
            this.b(w, i + 0, j + 19, k + 20, this.c, 8);
            this.b(w, i + 0, j + 19, k + 21, this.c, 8);
            this.b(w, i + 0, j + 20, k + 3, this.c, 8);
            this.b(w, i + 0, j + 20, k + 4, this.c, 8);
            this.b(w, i + 0, j + 20, k + 5, this.c, 8);
            this.b(w, i + 0, j + 20, k + 6, this.c, 7);
            this.b(w, i + 0, j + 20, k + 7, this.c, 8);
            this.b(w, i + 0, j + 20, k + 8, this.c, 7);
            this.b(w, i + 0, j + 20, k + 9, this.c, 8);
            this.b(w, i + 0, j + 20, k + 10, this.c, 8);
            this.b(w, i + 0, j + 20, k + 11, this.c, 8);
            this.b(w, i + 0, j + 20, k + 12, this.c, 7);
            this.b(w, i + 0, j + 20, k + 13, this.c, 7);
            this.b(w, i + 0, j + 20, k + 14, this.c, 8);
            this.b(w, i + 0, j + 20, k + 15, this.c, 7);
            this.b(w, i + 0, j + 20, k + 16, this.c, 8);
            this.b(w, i + 0, j + 20, k + 17, this.c, 8);
            this.b(w, i + 0, j + 20, k + 18, this.c, 8);
            this.b(w, i + 0, j + 20, k + 19, this.c, 7);
            this.b(w, i + 0, j + 20, k + 20, this.c, 8);
            this.b(w, i + 0, j + 20, k + 21, this.c, 7);
            this.b(w, i + 0, j + 21, k + 3, this.c, 8);
            this.b(w, i + 0, j + 21, k + 4, this.c, 8);
            this.b(w, i + 0, j + 21, k + 5, this.c, 8);
            this.b(w, i + 0, j + 21, k + 6, this.c, 8);
            this.b(w, i + 0, j + 21, k + 7, this.c, 7);
            this.b(w, i + 0, j + 21, k + 8, this.c, 8);
            this.b(w, i + 0, j + 21, k + 9, this.c, 8);
            this.b(w, i + 0, j + 21, k + 10, this.c, 8);
            this.b(w, i + 0, j + 21, k + 11, this.c, 8);
            this.b(w, i + 0, j + 21, k + 12, this.c, 8);
            this.b(w, i + 0, j + 21, k + 13, this.c, 8);
            this.b(w, i + 0, j + 21, k + 14, this.c, 7);
            this.b(w, i + 0, j + 21, k + 15, this.c, 8);
            this.b(w, i + 0, j + 21, k + 16, this.c, 8);
            this.b(w, i + 0, j + 21, k + 17, this.c, 8);
            this.b(w, i + 0, j + 21, k + 18, this.c, 8);
            this.b(w, i + 0, j + 21, k + 19, this.c, 8);
            this.b(w, i + 0, j + 21, k + 20, this.c, 7);
            this.b(w, i + 0, j + 21, k + 21, this.c, 8);
            this.b(w, i + 1, j + 6, k + 4, this.c, 7);
            this.b(w, i + 1, j + 6, k + 5, this.c, 7);
            this.b(w, i + 1, j + 6, k + 6, this.c, 7);
            this.b(w, i + 1, j + 6, k + 7, this.c, 7);
            this.b(w, i + 1, j + 6, k + 8, this.c, 7);
            this.b(w, i + 1, j + 6, k + 9, this.c, 7);
            this.b(w, i + 1, j + 6, k + 10, this.c, 7);
            this.b(w, i + 1, j + 6, k + 11, this.c, 7);
            this.b(w, i + 1, j + 6, k + 12, this.c, 7);
            this.b(w, i + 1, j + 6, k + 13, this.c, 7);
            this.b(w, i + 1, j + 6, k + 14, this.c, 7);
            this.b(w, i + 1, j + 6, k + 15, this.c, 7);
            this.b(w, i + 1, j + 6, k + 16, this.c, 7);
            this.b(w, i + 1, j + 6, k + 17, this.c, 7);
            this.b(w, i + 1, j + 6, k + 18, this.c, 7);
            this.b(w, i + 1, j + 6, k + 19, this.c, 7);
            this.b(w, i + 1, j + 6, k + 20, this.c, 7);
            this.b(w, i + 1, j + 7, k + 3, this.c, 8);
            this.b(w, i + 1, j + 7, k + 4, this.c, 8);
            this.b(w, i + 1, j + 7, k + 5, this.c, 8);
            this.b(w, i + 1, j + 7, k + 6, this.c, 8);
            this.b(w, i + 1, j + 7, k + 7, this.c, 8);
            this.b(w, i + 1, j + 7, k + 8, this.c, 8);
            this.b(w, i + 1, j + 7, k + 9, this.c, 8);
            this.b(w, i + 1, j + 7, k + 10, this.c, 8);
            this.b(w, i + 1, j + 7, k + 11, this.c, 8);
            this.b(w, i + 1, j + 7, k + 12, this.c, 8);
            this.b(w, i + 1, j + 7, k + 13, this.c, 8);
            this.b(w, i + 1, j + 7, k + 14, this.c, 8);
            this.b(w, i + 1, j + 7, k + 15, this.c, 8);
            this.b(w, i + 1, j + 7, k + 16, this.c, 8);
            this.b(w, i + 1, j + 7, k + 17, this.c, 8);
            this.b(w, i + 1, j + 7, k + 18, this.c, 8);
            this.b(w, i + 1, j + 7, k + 19, this.c, 8);
            this.b(w, i + 1, j + 7, k + 20, this.c, 8);
            this.b(w, i + 1, j + 7, k + 21, this.c, 8);
            this.b(w, i + 1, j + 8, k + 3, this.c, 8);
            this.b(w, i + 1, j + 8, k + 21, this.c, 8);
            this.b(w, i + 1, j + 9, k + 21, this.c, 8);
            this.b(w, i + 1, j + 10, k + 3, this.c, 8);
            this.b(w, i + 1, j + 10, k + 21, this.c, 8);
            this.b(w, i + 1, j + 11, k + 3, this.c, 8);
            this.b(w, i + 1, j + 11, k + 21, this.c, 8);
            this.b(w, i + 1, j + 12, k + 3, this.c, 8);
            this.b(w, i + 1, j + 12, k + 4, this.c);
            this.b(w, i + 1, j + 12, k + 5, this.c);
            this.b(w, i + 1, j + 12, k + 6, this.c);
            this.b(w, i + 1, j + 12, k + 7, this.c);
            this.b(w, i + 1, j + 12, k + 8, this.c);
            this.b(w, i + 1, j + 12, k + 9, this.c);
            this.b(w, i + 1, j + 12, k + 10, this.c);
            this.b(w, i + 1, j + 12, k + 11, this.c);
            this.b(w, i + 1, j + 12, k + 12, this.c);
            this.b(w, i + 1, j + 12, k + 13, this.c);
            this.b(w, i + 1, j + 12, k + 14, this.c);
            this.b(w, i + 1, j + 12, k + 15, this.c);
            this.b(w, i + 1, j + 12, k + 16, this.c);
            this.b(w, i + 1, j + 12, k + 17, this.c);
            this.b(w, i + 1, j + 12, k + 18, this.c);
            this.b(w, i + 1, j + 12, k + 19, this.c);
            this.b(w, i + 1, j + 12, k + 20, this.c);
            this.b(w, i + 1, j + 12, k + 21, this.c, 8);
            this.b(w, i + 1, j + 13, k + 3, this.d);
            this.b(w, i + 1, j + 13, k + 4, this.b);
            this.b(w, i + 1, j + 13, k + 9, this.b);
            this.b(w, i + 1, j + 13, k + 15, this.b);
            this.b(w, i + 1, j + 13, k + 20, this.b);
            this.b(w, i + 1, j + 13, k + 21, this.d);
            this.b(w, i + 1, j + 14, k + 4, this.b);
            this.b(w, i + 1, j + 14, k + 9, this.b);
            this.b(w, i + 1, j + 14, k + 15, this.b);
            this.b(w, i + 1, j + 14, k + 20, this.b);
            this.b(w, i + 1, j + 15, k + 4, this.b);
            this.b(w, i + 1, j + 15, k + 9, this.b);
            this.b(w, i + 1, j + 15, k + 15, this.b);
            this.b(w, i + 1, j + 15, k + 20, this.b);
            this.b(w, i + 1, j + 16, k + 4, this.b);
            this.b(w, i + 1, j + 16, k + 9, this.b);
            this.b(w, i + 1, j + 16, k + 15, this.b);
            this.b(w, i + 1, j + 16, k + 20, this.b);
            this.b(w, i + 1, j + 17, k + 3, this.c, 8);
            this.b(w, i + 1, j + 17, k + 4, this.c, 8);
            this.b(w, i + 1, j + 17, k + 5, this.c, 8);
            this.b(w, i + 1, j + 17, k + 6, this.c, 8);
            this.b(w, i + 1, j + 17, k + 7, this.c, 8);
            this.b(w, i + 1, j + 17, k + 8, this.c, 8);
            this.b(w, i + 1, j + 17, k + 9, this.c, 8);
            this.b(w, i + 1, j + 17, k + 10, this.c, 8);
            this.b(w, i + 1, j + 17, k + 11, this.c, 8);
            this.b(w, i + 1, j + 17, k + 12, this.c, 8);
            this.b(w, i + 1, j + 17, k + 13, this.c, 8);
            this.b(w, i + 1, j + 17, k + 14, this.c, 8);
            this.b(w, i + 1, j + 17, k + 15, this.c, 8);
            this.b(w, i + 1, j + 17, k + 16, this.c, 8);
            this.b(w, i + 1, j + 17, k + 17, this.c, 8);
            this.b(w, i + 1, j + 17, k + 18, this.c, 8);
            this.b(w, i + 1, j + 17, k + 19, this.c, 8);
            this.b(w, i + 1, j + 17, k + 20, this.c, 8);
            this.b(w, i + 1, j + 17, k + 21, this.c, 8);
            this.b(w, i + 1, j + 18, k + 3, this.c, 8);
            this.b(w, i + 1, j + 18, k + 4, this.c, 7);
            this.b(w, i + 1, j + 18, k + 5, this.c, 8);
            this.b(w, i + 1, j + 18, k + 6, this.c, 8);
            this.b(w, i + 1, j + 18, k + 7, this.c, 8);
            this.b(w, i + 1, j + 18, k + 8, this.c, 8);
            this.b(w, i + 1, j + 18, k + 9, this.c, 8);
            this.b(w, i + 1, j + 18, k + 10, this.c, 7);
            this.b(w, i + 1, j + 18, k + 11, this.c, 8);
            this.b(w, i + 1, j + 18, k + 12, this.c, 8);
            this.b(w, i + 1, j + 18, k + 13, this.c, 8);
            this.b(w, i + 1, j + 18, k + 14, this.c, 8);
            this.b(w, i + 1, j + 18, k + 15, this.c, 8);
            this.b(w, i + 1, j + 18, k + 16, this.c, 8);
            this.b(w, i + 1, j + 18, k + 17, this.c, 7);
            this.b(w, i + 1, j + 18, k + 18, this.c, 8);
            this.b(w, i + 1, j + 18, k + 19, this.c, 8);
            this.b(w, i + 1, j + 18, k + 20, this.c, 8);
            this.b(w, i + 1, j + 18, k + 21, this.c, 8);
            this.b(w, i + 1, j + 19, k + 3, this.c, 8);
            this.b(w, i + 1, j + 19, k + 4, this.c, 8);
            this.b(w, i + 1, j + 19, k + 5, this.c, 7);
            this.b(w, i + 1, j + 19, k + 6, this.c, 8);
            this.b(w, i + 1, j + 19, k + 7, this.c, 8);
            this.b(w, i + 1, j + 19, k + 8, this.c, 8);
            this.b(w, i + 1, j + 19, k + 9, this.c, 7);
            this.b(w, i + 1, j + 19, k + 10, this.c, 8);
            this.b(w, i + 1, j + 19, k + 11, this.c, 7);
            this.b(w, i + 1, j + 19, k + 12, this.c, 8);
            this.b(w, i + 1, j + 19, k + 13, this.c, 8);
            this.b(w, i + 1, j + 19, k + 14, this.c, 8);
            this.b(w, i + 1, j + 19, k + 15, this.c, 8);
            this.b(w, i + 1, j + 19, k + 16, this.c, 7);
            this.b(w, i + 1, j + 19, k + 17, this.c, 8);
            this.b(w, i + 1, j + 19, k + 18, this.c, 7);
            this.b(w, i + 1, j + 19, k + 19, this.c, 8);
            this.b(w, i + 1, j + 19, k + 20, this.c, 8);
            this.b(w, i + 1, j + 19, k + 21, this.c, 7);
            this.b(w, i + 1, j + 20, k + 3, this.c, 7);
            this.b(w, i + 1, j + 20, k + 4, this.c, 8);
            this.b(w, i + 1, j + 20, k + 5, this.c, 8);
            this.b(w, i + 1, j + 20, k + 6, this.c, 7);
            this.b(w, i + 1, j + 20, k + 7, this.c, 8);
            this.b(w, i + 1, j + 20, k + 8, this.c, 7);
            this.b(w, i + 1, j + 20, k + 9, this.c, 8);
            this.b(w, i + 1, j + 20, k + 10, this.c, 8);
            this.b(w, i + 1, j + 20, k + 11, this.c, 8);
            this.b(w, i + 1, j + 20, k + 12, this.c, 7);
            this.b(w, i + 1, j + 20, k + 13, this.c, 7);
            this.b(w, i + 1, j + 20, k + 14, this.c, 8);
            this.b(w, i + 1, j + 20, k + 15, this.c, 7);
            this.b(w, i + 1, j + 20, k + 16, this.c, 8);
            this.b(w, i + 1, j + 20, k + 17, this.c, 8);
            this.b(w, i + 1, j + 20, k + 18, this.c, 8);
            this.b(w, i + 1, j + 20, k + 19, this.c, 7);
            this.b(w, i + 1, j + 20, k + 20, this.c, 8);
            this.b(w, i + 1, j + 20, k + 21, this.c, 8);
            this.b(w, i + 1, j + 21, k + 3, this.c, 8);
            this.b(w, i + 1, j + 21, k + 4, this.c, 8);
            this.b(w, i + 1, j + 21, k + 5, this.c, 8);
            this.b(w, i + 1, j + 21, k + 6, this.c, 8);
            this.b(w, i + 1, j + 21, k + 7, this.c, 7);
            this.b(w, i + 1, j + 21, k + 8, this.c, 8);
            this.b(w, i + 1, j + 21, k + 9, this.c, 8);
            this.b(w, i + 1, j + 21, k + 10, this.c, 8);
            this.b(w, i + 1, j + 21, k + 11, this.c, 8);
            this.b(w, i + 1, j + 21, k + 12, this.c, 8);
            this.b(w, i + 1, j + 21, k + 13, this.c, 8);
            this.b(w, i + 1, j + 21, k + 14, this.c, 7);
            this.b(w, i + 1, j + 21, k + 15, this.c, 8);
            this.b(w, i + 1, j + 21, k + 16, this.c, 8);
            this.b(w, i + 1, j + 21, k + 17, this.c, 8);
            this.b(w, i + 1, j + 21, k + 18, this.c, 8);
            this.b(w, i + 1, j + 21, k + 19, this.c, 8);
            this.b(w, i + 1, j + 21, k + 20, this.c, 7);
            this.b(w, i + 1, j + 21, k + 21, this.c, 8);
            this.b(w, i + 1, j + 22, k + 4, this.c, 8);
            this.b(w, i + 1, j + 22, k + 5, this.c, 8);
            this.b(w, i + 1, j + 22, k + 6, this.c, 8);
            this.b(w, i + 1, j + 22, k + 7, this.c, 8);
            this.b(w, i + 1, j + 22, k + 8, this.c, 8);
            this.b(w, i + 1, j + 22, k + 9, this.c, 8);
            this.b(w, i + 1, j + 22, k + 10, this.c, 8);
            this.b(w, i + 1, j + 22, k + 11, this.c, 8);
            this.b(w, i + 1, j + 22, k + 12, this.c, 8);
            this.b(w, i + 1, j + 22, k + 13, this.c, 8);
            this.b(w, i + 1, j + 22, k + 14, this.c, 8);
            this.b(w, i + 1, j + 22, k + 15, this.c, 8);
            this.b(w, i + 1, j + 22, k + 16, this.c, 8);
            this.b(w, i + 1, j + 22, k + 17, this.c, 8);
            this.b(w, i + 1, j + 22, k + 18, this.c, 8);
            this.b(w, i + 1, j + 22, k + 19, this.c, 8);
            this.b(w, i + 1, j + 22, k + 20, this.c, 8);
            this.b(w, i + 2, j + 5, k + 5, this.c, 8);
            this.b(w, i + 2, j + 5, k + 6, this.c, 8);
            this.b(w, i + 2, j + 5, k + 7, this.c, 8);
            this.b(w, i + 2, j + 5, k + 8, this.c, 8);
            this.b(w, i + 2, j + 5, k + 9, this.c, 8);
            this.b(w, i + 2, j + 5, k + 10, this.c, 8);
            this.b(w, i + 2, j + 5, k + 11, this.c, 8);
            this.b(w, i + 2, j + 5, k + 12, this.c, 8);
            this.b(w, i + 2, j + 5, k + 13, this.c, 8);
            this.b(w, i + 2, j + 5, k + 14, this.c, 8);
            this.b(w, i + 2, j + 5, k + 15, this.c, 8);
            this.b(w, i + 2, j + 5, k + 16, this.c, 8);
            this.b(w, i + 2, j + 5, k + 17, this.c, 8);
            this.b(w, i + 2, j + 5, k + 18, this.c, 8);
            this.b(w, i + 2, j + 5, k + 19, this.c, 8);
            this.b(w, i + 2, j + 6, k + 4, this.c, 7);
            this.b(w, i + 2, j + 6, k + 5, this.c);
            this.b(w, i + 2, j + 6, k + 6, this.c);
            this.b(w, i + 2, j + 6, k + 7, this.c);
            this.b(w, i + 2, j + 6, k + 8, this.c);
            this.b(w, i + 2, j + 6, k + 9, this.c);
            this.b(w, i + 2, j + 6, k + 10, this.c);
            this.b(w, i + 2, j + 6, k + 11, this.c);
            this.b(w, i + 2, j + 6, k + 12, this.c);
            this.b(w, i + 2, j + 6, k + 13, this.c);
            this.b(w, i + 2, j + 6, k + 14, this.c);
            this.b(w, i + 2, j + 6, k + 15, this.c);
            this.b(w, i + 2, j + 6, k + 16, this.c);
            this.b(w, i + 2, j + 6, k + 17, this.c);
            this.b(w, i + 2, j + 6, k + 18, this.c);
            this.b(w, i + 2, j + 6, k + 19, this.c);
            this.b(w, i + 2, j + 6, k + 20, this.c, 7);
            this.b(w, i + 2, j + 7, k + 3, this.c, 8);
            this.b(w, i + 2, j + 7, k + 4, this.c, 8);
            this.b(w, i + 2, j + 7, k + 20, this.c, 8);
            this.b(w, i + 2, j + 7, k + 21, this.c, 8);
            this.b(w, i + 2, j + 8, k + 3, this.c, 8);
            this.b(w, i + 2, j + 8, k + 21, this.c, 8);
            this.b(w, i + 2, j + 9, k + 21, this.c, 8);
            this.b(w, i + 2, j + 10, k + 3, this.c, 8);
            this.b(w, i + 2, j + 10, k + 21, this.c, 8);
            this.b(w, i + 2, j + 11, k + 3, this.c, 8);
            this.b(w, i + 2, j + 11, k + 21, this.c, 8);
            this.b(w, i + 2, j + 12, k + 3, this.c, 8);
            this.b(w, i + 2, j + 12, k + 4, this.c);
            this.b(w, i + 2, j + 12, k + 5, this.c);
            this.b(w, i + 2, j + 12, k + 6, this.c);
            this.b(w, i + 2, j + 12, k + 7, this.c);
            this.b(w, i + 2, j + 12, k + 8, this.c);
            this.b(w, i + 2, j + 12, k + 9, this.c);
            this.b(w, i + 2, j + 12, k + 10, this.c);
            this.b(w, i + 2, j + 12, k + 11, this.c);
            this.b(w, i + 2, j + 12, k + 12, this.c);
            this.b(w, i + 2, j + 12, k + 13, this.c);
            this.b(w, i + 2, j + 12, k + 14, this.c);
            this.b(w, i + 2, j + 12, k + 15, this.c);
            this.b(w, i + 2, j + 12, k + 16, this.c);
            this.b(w, i + 2, j + 12, k + 17, this.c);
            this.b(w, i + 2, j + 12, k + 18, this.c);
            this.b(w, i + 2, j + 12, k + 19, this.c);
            this.b(w, i + 2, j + 12, k + 20, this.c);
            this.b(w, i + 2, j + 12, k + 21, this.c, 8);
            this.b(w, i + 2, j + 13, k + 3, this.d);
            this.b(w, i + 2, j + 13, k + 21, this.d);
            this.b(w, i + 2, j + 17, k + 3, this.c, 8);
            this.b(w, i + 2, j + 17, k + 4, this.c, 8);
            this.b(w, i + 2, j + 17, k + 20, this.c, 8);
            this.b(w, i + 2, j + 17, k + 21, this.c, 8);
            this.b(w, i + 2, j + 18, k + 3, this.c, 8);
            this.b(w, i + 2, j + 18, k + 4, this.c, 8);
            this.b(w, i + 2, j + 18, k + 20, this.c, 8);
            this.b(w, i + 2, j + 18, k + 21, this.c, 7);
            this.b(w, i + 2, j + 19, k + 3, this.c, 8);
            this.b(w, i + 2, j + 19, k + 4, this.c, 7);
            this.b(w, i + 2, j + 19, k + 20, this.c, 8);
            this.b(w, i + 2, j + 19, k + 21, this.c, 8);
            this.b(w, i + 2, j + 20, k + 3, this.c, 8);
            this.b(w, i + 2, j + 20, k + 4, this.c, 8);
            this.b(w, i + 2, j + 20, k + 20, this.c, 7);
            this.b(w, i + 2, j + 20, k + 21, this.c, 8);
            this.b(w, i + 2, j + 21, k + 3, this.c, 7);
            this.b(w, i + 2, j + 21, k + 4, this.c, 8);
            this.b(w, i + 2, j + 21, k + 20, this.c, 8);
            this.b(w, i + 2, j + 21, k + 21, this.c, 8);
            this.b(w, i + 2, j + 22, k + 4, this.c, 8);
            this.b(w, i + 2, j + 22, k + 5, this.c, 8);
            this.b(w, i + 2, j + 22, k + 6, this.c, 8);
            this.b(w, i + 2, j + 22, k + 7, this.c, 8);
            this.b(w, i + 2, j + 22, k + 8, this.c, 8);
            this.b(w, i + 2, j + 22, k + 9, this.c, 8);
            this.b(w, i + 2, j + 22, k + 10, this.c, 8);
            this.b(w, i + 2, j + 22, k + 11, this.c, 8);
            this.b(w, i + 2, j + 22, k + 12, this.c, 8);
            this.b(w, i + 2, j + 22, k + 13, this.c, 8);
            this.b(w, i + 2, j + 22, k + 14, this.c, 8);
            this.b(w, i + 2, j + 22, k + 15, this.c, 8);
            this.b(w, i + 2, j + 22, k + 16, this.c, 8);
            this.b(w, i + 2, j + 22, k + 17, this.c, 8);
            this.b(w, i + 2, j + 22, k + 18, this.c, 8);
            this.b(w, i + 2, j + 22, k + 19, this.c, 8);
            this.b(w, i + 2, j + 22, k + 20, this.c, 8);
            this.b(w, i + 2, j + 23, k + 5, this.c, 8);
            this.b(w, i + 2, j + 23, k + 6, this.c, 8);
            this.b(w, i + 2, j + 23, k + 7, this.c, 8);
            this.b(w, i + 2, j + 23, k + 8, this.c, 8);
            this.b(w, i + 2, j + 23, k + 9, this.c, 8);
            this.b(w, i + 2, j + 23, k + 10, this.c, 8);
            this.b(w, i + 2, j + 23, k + 11, this.c, 8);
            this.b(w, i + 2, j + 23, k + 12, this.c, 8);
            this.b(w, i + 2, j + 23, k + 13, this.c, 8);
            this.b(w, i + 2, j + 23, k + 14, this.c, 8);
            this.b(w, i + 2, j + 23, k + 15, this.c, 8);
            this.b(w, i + 2, j + 23, k + 16, this.c, 8);
            this.b(w, i + 2, j + 23, k + 17, this.c, 8);
            this.b(w, i + 2, j + 23, k + 18, this.c, 8);
            this.b(w, i + 2, j + 23, k + 19, this.c, 8);
            this.b(w, i + 3, j + 4, k + 6, this.c, 8);
            this.b(w, i + 3, j + 4, k + 7, this.c, 8);
            this.b(w, i + 3, j + 4, k + 8, this.c, 8);
            this.b(w, i + 3, j + 4, k + 9, this.c, 8);
            this.b(w, i + 3, j + 4, k + 10, this.c, 8);
            this.b(w, i + 3, j + 4, k + 11, this.c, 8);
            this.b(w, i + 3, j + 4, k + 12, this.c, 8);
            this.b(w, i + 3, j + 4, k + 13, this.c, 8);
            this.b(w, i + 3, j + 4, k + 14, this.c, 8);
            this.b(w, i + 3, j + 4, k + 15, this.c, 8);
            this.b(w, i + 3, j + 4, k + 16, this.c, 8);
            this.b(w, i + 3, j + 4, k + 17, this.c, 8);
            this.b(w, i + 3, j + 4, k + 18, this.c, 8);
            this.b(w, i + 3, j + 5, k + 5, this.c, 8);
            this.b(w, i + 3, j + 5, k + 19, this.c, 8);
            this.b(w, i + 3, j + 6, k + 4, this.c, 7);
            this.b(w, i + 3, j + 6, k + 5, this.c);
            this.b(w, i + 3, j + 6, k + 6, this.c);
            this.b(w, i + 3, j + 6, k + 7, this.c);
            this.b(w, i + 3, j + 6, k + 8, this.c);
            this.b(w, i + 3, j + 6, k + 9, this.c);
            this.b(w, i + 3, j + 6, k + 10, this.c);
            this.b(w, i + 3, j + 6, k + 11, this.c);
            this.b(w, i + 3, j + 6, k + 12, this.c);
            this.b(w, i + 3, j + 6, k + 13, this.c);
            this.b(w, i + 3, j + 6, k + 14, this.c);
            this.b(w, i + 3, j + 6, k + 15, this.c);
            this.b(w, i + 3, j + 6, k + 16, this.c);
            this.b(w, i + 3, j + 6, k + 17, this.c);
            this.b(w, i + 3, j + 6, k + 18, this.c);
            this.b(w, i + 3, j + 6, k + 19, this.c);
            this.b(w, i + 3, j + 6, k + 20, this.c, 7);
            this.b(w, i + 3, j + 7, k + 3, this.c, 8);
            this.b(w, i + 3, j + 7, k + 4, this.c, 8);
            this.b(w, i + 3, j + 7, k + 20, this.c, 8);
            this.b(w, i + 3, j + 7, k + 21, this.c, 8);
            this.b(w, i + 3, j + 8, k + 3, this.c, 8);
            this.b(w, i + 3, j + 8, k + 21, this.c, 8);
            this.b(w, i + 3, j + 10, k + 3, this.c, 8);
            this.b(w, i + 3, j + 10, k + 21, this.c, 8);
            this.b(w, i + 3, j + 11, k + 3, this.c, 8);
            this.b(w, i + 3, j + 11, k + 21, this.c, 8);
            this.b(w, i + 3, j + 12, k + 3, this.c, 8);
            this.b(w, i + 3, j + 12, k + 4, this.c);
            this.b(w, i + 3, j + 12, k + 5, this.c);
            this.b(w, i + 3, j + 12, k + 6, this.c);
            this.b(w, i + 3, j + 12, k + 7, this.c);
            this.b(w, i + 3, j + 12, k + 8, this.c);
            this.b(w, i + 3, j + 12, k + 9, this.c);
            this.b(w, i + 3, j + 12, k + 10, this.c);
            this.b(w, i + 3, j + 12, k + 11, this.c);
            this.b(w, i + 3, j + 12, k + 12, this.c);
            this.b(w, i + 3, j + 12, k + 13, this.c);
            this.b(w, i + 3, j + 12, k + 14, this.c);
            this.b(w, i + 3, j + 12, k + 15, this.c);
            this.b(w, i + 3, j + 12, k + 16, this.c);
            this.b(w, i + 3, j + 12, k + 17, this.c);
            this.b(w, i + 3, j + 12, k + 18, this.c);
            this.b(w, i + 3, j + 12, k + 19, this.c);
            this.b(w, i + 3, j + 12, k + 20, this.c);
            this.b(w, i + 3, j + 12, k + 21, this.c, 8);
            this.b(w, i + 3, j + 13, k + 3, this.d);
            this.b(w, i + 3, j + 13, k + 21, this.d);
            this.b(w, i + 3, j + 17, k + 3, this.c, 8);
            this.b(w, i + 3, j + 17, k + 4, this.c, 8);
            this.b(w, i + 3, j + 17, k + 20, this.c, 8);
            this.b(w, i + 3, j + 17, k + 21, this.c, 8);
            this.b(w, i + 3, j + 18, k + 3, this.c, 8);
            this.b(w, i + 3, j + 18, k + 4, this.c, 8);
            this.b(w, i + 3, j + 18, k + 20, this.c, 8);
            this.b(w, i + 3, j + 18, k + 21, this.c, 8);
            this.b(w, i + 3, j + 19, k + 3, this.c, 8);
            this.b(w, i + 3, j + 19, k + 4, this.c, 8);
            this.b(w, i + 3, j + 19, k + 20, this.c, 7);
            this.b(w, i + 3, j + 19, k + 21, this.c, 7);
            this.b(w, i + 3, j + 20, k + 3, this.c, 7);
            this.b(w, i + 3, j + 20, k + 4, this.c, 7);
            this.b(w, i + 3, j + 20, k + 20, this.c, 8);
            this.b(w, i + 3, j + 20, k + 21, this.c, 8);
            this.b(w, i + 3, j + 21, k + 3, this.c, 8);
            this.b(w, i + 3, j + 21, k + 4, this.c, 8);
            this.b(w, i + 3, j + 21, k + 20, this.c, 8);
            this.b(w, i + 3, j + 21, k + 21, this.c, 8);
            this.b(w, i + 3, j + 22, k + 4, this.c, 8);
            this.b(w, i + 3, j + 22, k + 5, this.c, 8);
            this.b(w, i + 3, j + 22, k + 19, this.c, 8);
            this.b(w, i + 3, j + 22, k + 20, this.c, 8);
            this.b(w, i + 3, j + 23, k + 5, this.c, 8);
            this.b(w, i + 3, j + 23, k + 19, this.c, 8);
            this.b(w, i + 3, j + 24, k + 6, this.c, 8);
            this.b(w, i + 3, j + 24, k + 7, this.c, 8);
            this.b(w, i + 3, j + 24, k + 8, this.c, 8);
            this.b(w, i + 3, j + 24, k + 9, this.c, 8);
            this.b(w, i + 3, j + 24, k + 10, this.c, 8);
            this.b(w, i + 3, j + 24, k + 11, this.c, 8);
            this.b(w, i + 3, j + 24, k + 12, this.c, 8);
            this.b(w, i + 3, j + 24, k + 13, this.c, 8);
            this.b(w, i + 3, j + 24, k + 14, this.c, 8);
            this.b(w, i + 3, j + 24, k + 15, this.c, 8);
            this.b(w, i + 3, j + 24, k + 16, this.c, 8);
            this.b(w, i + 3, j + 24, k + 17, this.c, 8);
            this.b(w, i + 3, j + 24, k + 18, this.c, 8);
            this.b(w, i + 4, j + 3, k + 7, this.c, 7);
            this.b(w, i + 4, j + 3, k + 8, this.c, 7);
            this.b(w, i + 4, j + 3, k + 9, this.c, 7);
            this.b(w, i + 4, j + 3, k + 10, this.c, 7);
            this.b(w, i + 4, j + 3, k + 11, this.c, 7);
            this.b(w, i + 4, j + 3, k + 12, this.c, 7);
            this.b(w, i + 4, j + 3, k + 13, this.c, 7);
            this.b(w, i + 4, j + 3, k + 14, this.c, 7);
            this.b(w, i + 4, j + 3, k + 15, this.c, 7);
            this.b(w, i + 4, j + 3, k + 16, this.c, 7);
            this.b(w, i + 4, j + 3, k + 17, this.c, 7);
            this.b(w, i + 4, j + 4, k + 6, this.c, 8);
            this.b(w, i + 4, j + 4, k + 18, this.c, 8);
            this.b(w, i + 4, j + 5, k + 5, this.c, 8);
            this.b(w, i + 4, j + 5, k + 19, this.c, 8);
            this.b(w, i + 4, j + 6, k + 4, this.c, 7);
            this.b(w, i + 4, j + 6, k + 5, this.c);
            this.b(w, i + 4, j + 6, k + 6, this.c);
            this.b(w, i + 4, j + 6, k + 7, this.c);
            this.b(w, i + 4, j + 6, k + 8, this.c);
            this.b(w, i + 4, j + 6, k + 9, this.c);
            this.b(w, i + 4, j + 6, k + 10, this.c);
            this.b(w, i + 4, j + 6, k + 11, this.c);
            this.b(w, i + 4, j + 6, k + 12, this.c);
            this.b(w, i + 4, j + 6, k + 13, this.c);
            this.b(w, i + 4, j + 6, k + 14, this.c);
            this.b(w, i + 4, j + 6, k + 15, this.c);
            this.b(w, i + 4, j + 6, k + 16, this.c);
            this.b(w, i + 4, j + 6, k + 17, this.c);
            this.b(w, i + 4, j + 6, k + 18, this.c);
            this.b(w, i + 4, j + 6, k + 19, this.c);
            this.b(w, i + 4, j + 6, k + 20, this.c, 7);
            this.b(w, i + 4, j + 7, k + 3, this.c, 8);
            this.b(w, i + 4, j + 7, k + 4, this.c, 8);
            this.b(w, i + 4, j + 7, k + 20, this.c, 8);
            this.b(w, i + 4, j + 7, k + 21, this.c, 8);
            this.b(w, i + 4, j + 8, k + 3, this.c, 8);
            this.b(w, i + 4, j + 8, k + 21, this.c, 8);
            this.b(w, i + 4, j + 9, k + 3, this.c, 8);
            this.b(w, i + 4, j + 10, k + 3, this.c, 8);
            this.b(w, i + 4, j + 10, k + 21, this.c, 8);
            this.b(w, i + 4, j + 11, k + 3, this.c, 8);
            this.b(w, i + 4, j + 11, k + 21, this.c, 8);
            this.b(w, i + 4, j + 12, k + 3, this.c, 8);
            this.b(w, i + 4, j + 12, k + 4, this.c);
            this.b(w, i + 4, j + 12, k + 5, this.c);
            this.b(w, i + 4, j + 12, k + 6, this.c);
            this.b(w, i + 4, j + 12, k + 7, this.c);
            this.b(w, i + 4, j + 12, k + 8, this.c);
            this.b(w, i + 4, j + 12, k + 9, this.c);
            this.b(w, i + 4, j + 12, k + 10, this.c);
            this.b(w, i + 4, j + 12, k + 11, this.c);
            this.b(w, i + 4, j + 12, k + 12, this.c);
            this.b(w, i + 4, j + 12, k + 13, this.c);
            this.b(w, i + 4, j + 12, k + 14, this.c);
            this.b(w, i + 4, j + 12, k + 15, this.c);
            this.b(w, i + 4, j + 12, k + 16, this.c);
            this.b(w, i + 4, j + 12, k + 17, this.c);
            this.b(w, i + 4, j + 12, k + 18, this.c);
            this.b(w, i + 4, j + 12, k + 19, this.c);
            this.b(w, i + 4, j + 12, k + 20, this.c);
            this.b(w, i + 4, j + 12, k + 21, this.c, 8);
            this.b(w, i + 4, j + 13, k + 3, this.d);
            this.b(w, i + 4, j + 13, k + 21, this.d);
            this.b(w, i + 4, j + 17, k + 3, this.c, 8);
            this.b(w, i + 4, j + 17, k + 4, this.c, 8);
            this.b(w, i + 4, j + 17, k + 20, this.c, 8);
            this.b(w, i + 4, j + 17, k + 21, this.c, 8);
            this.b(w, i + 4, j + 18, k + 3, this.c, 8);
            this.b(w, i + 4, j + 18, k + 4, this.c, 8);
            this.b(w, i + 4, j + 18, k + 20, this.c, 7);
            this.b(w, i + 4, j + 18, k + 21, this.c, 8);
            this.b(w, i + 4, j + 19, k + 3, this.c, 7);
            this.b(w, i + 4, j + 19, k + 4, this.c, 8);
            this.b(w, i + 4, j + 19, k + 20, this.c, 8);
            this.b(w, i + 4, j + 19, k + 21, this.c, 8);
            this.b(w, i + 4, j + 20, k + 3, this.c, 8);
            this.b(w, i + 4, j + 20, k + 4, this.c, 8);
            this.b(w, i + 4, j + 20, k + 20, this.c, 8);
            this.b(w, i + 4, j + 20, k + 21, this.c, 7);
            this.b(w, i + 4, j + 21, k + 3, this.c, 8);
            this.b(w, i + 4, j + 21, k + 4, this.c, 7);
            this.b(w, i + 4, j + 21, k + 20, this.c, 8);
            this.b(w, i + 4, j + 21, k + 21, this.c, 8);
            this.b(w, i + 4, j + 22, k + 4, this.c, 8);
            this.b(w, i + 4, j + 22, k + 5, this.c, 8);
            this.b(w, i + 4, j + 22, k + 19, this.c, 8);
            this.b(w, i + 4, j + 22, k + 20, this.c, 8);
            this.b(w, i + 4, j + 23, k + 5, this.c, 8);
            this.b(w, i + 4, j + 23, k + 19, this.c, 8);
            this.b(w, i + 4, j + 24, k + 6, this.c, 8);
            this.b(w, i + 4, j + 24, k + 18, this.c, 8);
            this.b(w, i + 4, j + 25, k + 7, this.c, 8);
            this.b(w, i + 4, j + 25, k + 8, this.c, 8);
            this.b(w, i + 4, j + 25, k + 9, this.c, 8);
            this.b(w, i + 4, j + 25, k + 10, this.c, 8);
            this.b(w, i + 4, j + 25, k + 11, this.c, 8);
            this.b(w, i + 4, j + 25, k + 12, this.c, 8);
            this.b(w, i + 4, j + 25, k + 13, this.c, 8);
            this.b(w, i + 4, j + 25, k + 14, this.c, 8);
            this.b(w, i + 4, j + 25, k + 15, this.c, 8);
            this.b(w, i + 4, j + 25, k + 16, this.c, 8);
            this.b(w, i + 4, j + 25, k + 17, this.c, 8);
            this.b(w, i + 5, j + 2, k + 8, this.c, 8);
            this.b(w, i + 5, j + 2, k + 9, this.c, 8);
            this.b(w, i + 5, j + 2, k + 10, this.c, 8);
            this.b(w, i + 5, j + 2, k + 11, this.c, 8);
            this.b(w, i + 5, j + 2, k + 12, this.c, 8);
            this.b(w, i + 5, j + 2, k + 13, this.c, 8);
            this.b(w, i + 5, j + 2, k + 14, this.c, 8);
            this.b(w, i + 5, j + 2, k + 15, this.c, 8);
            this.b(w, i + 5, j + 2, k + 16, this.c, 8);
            this.b(w, i + 5, j + 3, k + 7, this.c, 7);
            this.b(w, i + 5, j + 3, k + 17, this.c, 7);
            this.b(w, i + 5, j + 4, k + 6, this.c, 8);
            this.b(w, i + 5, j + 4, k + 18, this.c, 8);
            this.b(w, i + 5, j + 5, k + 5, this.c, 8);
            this.b(w, i + 5, j + 5, k + 19, this.c, 8);
            this.b(w, i + 5, j + 6, k + 4, this.c, 7);
            this.b(w, i + 5, j + 6, k + 5, this.c);
            this.b(w, i + 5, j + 6, k + 6, this.c);
            this.b(w, i + 5, j + 6, k + 7, this.c);
            this.b(w, i + 5, j + 6, k + 8, this.c, 8);
            this.b(w, i + 5, j + 6, k + 9, this.c, 8);
            this.b(w, i + 5, j + 6, k + 10, this.c, 8);
            this.b(w, i + 5, j + 6, k + 11, this.c, 8);
            this.b(w, i + 5, j + 6, k + 12, this.c, 8);
            this.b(w, i + 5, j + 6, k + 13, this.c, 8);
            this.b(w, i + 5, j + 6, k + 14, this.c, 8);
            this.b(w, i + 5, j + 6, k + 15, this.c, 8);
            this.b(w, i + 5, j + 6, k + 16, this.c, 8);
            this.b(w, i + 5, j + 6, k + 17, this.c);
            this.b(w, i + 5, j + 6, k + 18, this.c);
            this.b(w, i + 5, j + 6, k + 19, this.c);
            this.b(w, i + 5, j + 6, k + 20, this.c, 7);
            this.b(w, i + 5, j + 7, k + 3, this.c, 8);
            this.b(w, i + 5, j + 7, k + 4, this.c, 8);
            this.b(w, i + 5, j + 7, k + 20, this.c, 8);
            this.b(w, i + 5, j + 7, k + 21, this.c, 8);
            this.b(w, i + 5, j + 8, k + 3, this.c, 8);
            this.b(w, i + 5, j + 8, k + 21, this.c, 8);
            this.b(w, i + 5, j + 9, k + 3, this.c, 8);
            this.b(w, i + 5, j + 10, k + 3, this.c, 8);
            this.b(w, i + 5, j + 10, k + 21, this.c, 8);
            this.b(w, i + 5, j + 11, k + 3, this.c, 8);
            this.b(w, i + 5, j + 11, k + 21, this.c, 8);
            this.b(w, i + 5, j + 12, k + 3, this.c, 8);
            this.b(w, i + 5, j + 12, k + 4, this.c);
            this.b(w, i + 5, j + 12, k + 5, this.c);
            this.b(w, i + 5, j + 12, k + 6, this.c);
            this.b(w, i + 5, j + 12, k + 7, this.c);
            this.b(w, i + 5, j + 12, k + 8, this.c);
            this.b(w, i + 5, j + 12, k + 9, this.c);
            this.b(w, i + 5, j + 12, k + 10, this.c);
            this.b(w, i + 5, j + 12, k + 11, this.c);
            this.b(w, i + 5, j + 12, k + 12, this.c);
            this.b(w, i + 5, j + 12, k + 13, this.c);
            this.b(w, i + 5, j + 12, k + 14, this.c);
            this.b(w, i + 5, j + 12, k + 15, this.c);
            this.b(w, i + 5, j + 12, k + 16, this.c);
            this.b(w, i + 5, j + 12, k + 17, this.c);
            this.b(w, i + 5, j + 12, k + 18, this.c);
            this.b(w, i + 5, j + 12, k + 19, this.c);
            this.b(w, i + 5, j + 12, k + 20, this.c);
            this.b(w, i + 5, j + 12, k + 21, this.c, 8);
            this.b(w, i + 5, j + 13, k + 3, this.d);
            this.b(w, i + 5, j + 13, k + 21, this.d);
            this.b(w, i + 5, j + 17, k + 3, this.c, 8);
            this.b(w, i + 5, j + 17, k + 4, this.c, 8);
            this.b(w, i + 5, j + 17, k + 20, this.c, 8);
            this.b(w, i + 5, j + 17, k + 21, this.c, 8);
            this.b(w, i + 5, j + 18, k + 3, this.c, 7);
            this.b(w, i + 5, j + 18, k + 4, this.c, 8);
            this.b(w, i + 5, j + 18, k + 20, this.c, 8);
            this.b(w, i + 5, j + 18, k + 21, this.c, 8);
            this.b(w, i + 5, j + 19, k + 3, this.c, 8);
            this.b(w, i + 5, j + 19, k + 4, this.c, 8);
            this.b(w, i + 5, j + 19, k + 20, this.c, 7);
            this.b(w, i + 5, j + 19, k + 21, this.c, 8);
            this.b(w, i + 5, j + 20, k + 3, this.c, 8);
            this.b(w, i + 5, j + 20, k + 4, this.c, 7);
            this.b(w, i + 5, j + 20, k + 20, this.c, 8);
            this.b(w, i + 5, j + 20, k + 21, this.c, 8);
            this.b(w, i + 5, j + 21, k + 3, this.c, 8);
            this.b(w, i + 5, j + 21, k + 4, this.c, 8);
            this.b(w, i + 5, j + 21, k + 20, this.c, 8);
            this.b(w, i + 5, j + 21, k + 21, this.c, 7);
            this.b(w, i + 5, j + 22, k + 4, this.c, 8);
            this.b(w, i + 5, j + 22, k + 5, this.c, 8);
            this.b(w, i + 5, j + 22, k + 19, this.c, 8);
            this.b(w, i + 5, j + 22, k + 20, this.c, 8);
            this.b(w, i + 5, j + 23, k + 5, this.c, 8);
            this.b(w, i + 5, j + 23, k + 19, this.c, 8);
            this.b(w, i + 5, j + 24, k + 6, this.c, 8);
            this.b(w, i + 5, j + 24, k + 18, this.c, 8);
            this.b(w, i + 5, j + 25, k + 7, this.c, 8);
            this.b(w, i + 5, j + 25, k + 17, this.c, 8);
            this.b(w, i + 5, j + 26, k + 8, this.c, 8);
            this.b(w, i + 5, j + 26, k + 9, this.c, 8);
            this.b(w, i + 5, j + 26, k + 10, this.c, 8);
            this.b(w, i + 5, j + 26, k + 11, this.c, 8);
            this.b(w, i + 5, j + 26, k + 12, this.c, 8);
            this.b(w, i + 5, j + 26, k + 13, this.c, 8);
            this.b(w, i + 5, j + 26, k + 14, this.c, 8);
            this.b(w, i + 5, j + 26, k + 15, this.c, 8);
            this.b(w, i + 5, j + 26, k + 16, this.c, 8);
            this.b(w, i + 6, j + 1, k + 9, this.c, 8);
            this.b(w, i + 6, j + 1, k + 10, this.c, 8);
            this.b(w, i + 6, j + 1, k + 11, this.c, 8);
            this.b(w, i + 6, j + 1, k + 12, this.c, 8);
            this.b(w, i + 6, j + 1, k + 13, this.c, 8);
            this.b(w, i + 6, j + 1, k + 14, this.c, 8);
            this.b(w, i + 6, j + 1, k + 15, this.c, 8);
            this.b(w, i + 6, j + 2, k + 8, this.c, 8);
            this.b(w, i + 6, j + 2, k + 10, this.c, 8);
            this.b(w, i + 6, j + 2, k + 11, this.c, 8);
            this.b(w, i + 6, j + 2, k + 13, this.c, 8);
            this.b(w, i + 6, j + 2, k + 14, this.c, 8);
            this.b(w, i + 6, j + 2, k + 16, this.c, 8);
            this.b(w, i + 6, j + 3, k + 7, this.c, 7);
            this.b(w, i + 6, j + 3, k + 10, this.c, 8);
            this.b(w, i + 6, j + 3, k + 11, this.c, 8);
            this.b(w, i + 6, j + 3, k + 13, this.c, 8);
            this.b(w, i + 6, j + 3, k + 14, this.c, 8);
            this.b(w, i + 6, j + 3, k + 17, this.c, 7);
            this.b(w, i + 6, j + 4, k + 6, this.c, 8);
            this.b(w, i + 6, j + 4, k + 10, this.c, 8);
            this.b(w, i + 6, j + 4, k + 11, this.c, 8);
            this.b(w, i + 6, j + 4, k + 13, this.c, 8);
            this.b(w, i + 6, j + 4, k + 14, this.c, 8);
            this.b(w, i + 6, j + 4, k + 18, this.c, 8);
            this.b(w, i + 6, j + 5, k + 5, this.c, 8);
            this.b(w, i + 6, j + 5, k + 10, this.c, 8);
            this.b(w, i + 6, j + 5, k + 11, this.c, 8);
            this.b(w, i + 6, j + 5, k + 13, this.c, 8);
            this.b(w, i + 6, j + 5, k + 14, this.c, 8);
            this.b(w, i + 6, j + 5, k + 19, this.c, 8);
            this.b(w, i + 6, j + 6, k + 0, this.c);
            this.b(w, i + 6, j + 6, k + 1, this.c);
            this.b(w, i + 6, j + 6, k + 2, this.c);
            this.b(w, i + 6, j + 6, k + 3, this.c);
            this.b(w, i + 6, j + 6, k + 4, this.c);
            this.b(w, i + 6, j + 6, k + 5, this.c);
            this.b(w, i + 6, j + 6, k + 6, this.c);
            this.b(w, i + 6, j + 6, k + 7, this.c);
            this.b(w, i + 6, j + 6, k + 8, this.c, 8);
            this.b(w, i + 6, j + 6, k + 9, this.c, 8);
            this.b(w, i + 6, j + 6, k + 10, this.c, 8);
            this.b(w, i + 6, j + 6, k + 11, this.c, 8);
            this.b(w, i + 6, j + 6, k + 12, this.c, 8);
            this.b(w, i + 6, j + 6, k + 13, this.c, 8);
            this.b(w, i + 6, j + 6, k + 14, this.c, 8);
            this.b(w, i + 6, j + 6, k + 15, this.c, 8);
            this.b(w, i + 6, j + 6, k + 16, this.c, 8);
            this.b(w, i + 6, j + 6, k + 17, this.c);
            this.b(w, i + 6, j + 6, k + 18, this.c);
            this.b(w, i + 6, j + 6, k + 19, this.c);
            this.b(w, i + 6, j + 6, k + 20, this.c, 7);
            this.b(w, i + 6, j + 7, k + 0, this.d);
            this.b(w, i + 6, j + 7, k + 1, this.d);
            this.b(w, i + 6, j + 7, k + 2, this.d);
            this.b(w, i + 6, j + 7, k + 3, this.c, 8);
            this.b(w, i + 6, j + 7, k + 4, this.c, 8);
            this.b(w, i + 6, j + 7, k + 9, this.c, 8);
            this.b(w, i + 6, j + 7, k + 10, this.c, 8);
            this.b(w, i + 6, j + 7, k + 11, this.c, 8);
            this.b(w, i + 6, j + 7, k + 12, this.c, 8);
            this.b(w, i + 6, j + 7, k + 13, this.c, 8);
            this.b(w, i + 6, j + 7, k + 14, this.c, 8);
            this.b(w, i + 6, j + 7, k + 15, this.c, 8);
            this.b(w, i + 6, j + 7, k + 20, this.c, 8);
            this.b(w, i + 6, j + 7, k + 21, this.c, 8);
            this.b(w, i + 6, j + 8, k + 3, this.c, 8);
            this.b(w, i + 6, j + 8, k + 21, this.c, 8);
            this.b(w, i + 6, j + 9, k + 3, this.c, 8);
            this.b(w, i + 6, j + 10, k + 3, this.c, 8);
            this.b(w, i + 6, j + 10, k + 21, this.c, 8);
            this.b(w, i + 6, j + 11, k + 3, this.c, 8);
            this.b(w, i + 6, j + 11, k + 21, this.c, 8);
            this.b(w, i + 6, j + 12, k + 3, this.c, 8);
            this.b(w, i + 6, j + 12, k + 4, this.c);
            this.b(w, i + 6, j + 12, k + 5, this.c);
            this.b(w, i + 6, j + 12, k + 6, this.c);
            this.b(w, i + 6, j + 12, k + 7, this.c);
            this.b(w, i + 6, j + 12, k + 8, this.c);
            this.b(w, i + 6, j + 12, k + 9, this.c);
            this.b(w, i + 6, j + 12, k + 10, this.c);
            this.b(w, i + 6, j + 12, k + 11, this.c);
            this.b(w, i + 6, j + 12, k + 12, this.c);
            this.b(w, i + 6, j + 12, k + 13, this.c);
            this.b(w, i + 6, j + 12, k + 14, this.c);
            this.b(w, i + 6, j + 12, k + 15, this.c);
            this.b(w, i + 6, j + 12, k + 16, this.c);
            this.b(w, i + 6, j + 12, k + 17, this.c);
            this.b(w, i + 6, j + 12, k + 18, this.c);
            this.b(w, i + 6, j + 12, k + 19, this.c);
            this.b(w, i + 6, j + 12, k + 20, this.c);
            this.b(w, i + 6, j + 12, k + 21, this.c, 8);
            this.b(w, i + 6, j + 13, k + 3, this.d);
            this.b(w, i + 6, j + 13, k + 4, this.b);
            this.b(w, i + 6, j + 13, k + 20, this.b);
            this.b(w, i + 6, j + 13, k + 21, this.d);
            this.b(w, i + 6, j + 14, k + 4, this.b);
            this.b(w, i + 6, j + 14, k + 20, this.b);
            this.b(w, i + 6, j + 15, k + 4, this.b);
            this.b(w, i + 6, j + 15, k + 20, this.b);
            this.b(w, i + 6, j + 16, k + 4, this.b);
            this.b(w, i + 6, j + 16, k + 20, this.b);
            this.b(w, i + 6, j + 17, k + 3, this.c, 8);
            this.b(w, i + 6, j + 17, k + 4, this.c, 8);
            this.b(w, i + 6, j + 17, k + 20, this.c, 8);
            this.b(w, i + 6, j + 17, k + 21, this.c, 8);
            this.b(w, i + 6, j + 18, k + 3, this.c, 8);
            this.b(w, i + 6, j + 18, k + 4, this.c, 8);
            this.b(w, i + 6, j + 18, k + 20, this.c, 8);
            this.b(w, i + 6, j + 18, k + 21, this.c, 8);
            this.b(w, i + 6, j + 19, k + 3, this.c, 7);
            this.b(w, i + 6, j + 19, k + 4, this.c, 7);
            this.b(w, i + 6, j + 19, k + 20, this.c, 8);
            this.b(w, i + 6, j + 19, k + 21, this.c, 8);
            this.b(w, i + 6, j + 20, k + 3, this.c, 8);
            this.b(w, i + 6, j + 20, k + 4, this.c, 8);
            this.b(w, i + 6, j + 20, k + 20, this.c, 7);
            this.b(w, i + 6, j + 20, k + 21, this.c, 7);
            this.b(w, i + 6, j + 21, k + 3, this.c, 8);
            this.b(w, i + 6, j + 21, k + 4, this.c, 8);
            this.b(w, i + 6, j + 21, k + 20, this.c, 8);
            this.b(w, i + 6, j + 21, k + 21, this.c, 8);
            this.b(w, i + 6, j + 22, k + 4, this.c, 8);
            this.b(w, i + 6, j + 22, k + 5, this.c, 8);
            this.b(w, i + 6, j + 22, k + 19, this.c, 8);
            this.b(w, i + 6, j + 22, k + 20, this.c, 8);
            this.b(w, i + 6, j + 23, k + 5, this.c, 8);
            this.b(w, i + 6, j + 23, k + 19, this.c, 8);
            this.b(w, i + 6, j + 24, k + 6, this.c, 8);
            this.b(w, i + 6, j + 24, k + 18, this.c, 8);
            this.b(w, i + 6, j + 25, k + 7, this.c, 8);
            this.b(w, i + 6, j + 25, k + 17, this.c, 8);
            this.b(w, i + 6, j + 26, k + 8, this.c, 8);
            this.b(w, i + 6, j + 26, k + 16, this.c, 8);
            this.b(w, i + 6, j + 27, k + 9, this.c, 8);
            this.b(w, i + 6, j + 27, k + 10, this.c, 8);
            this.b(w, i + 6, j + 27, k + 11, this.c, 8);
            this.b(w, i + 6, j + 27, k + 12, this.c, 8);
            this.b(w, i + 6, j + 27, k + 13, this.c, 8);
            this.b(w, i + 6, j + 27, k + 14, this.c, 8);
            this.b(w, i + 6, j + 27, k + 15, this.c, 8);
            this.b(w, i + 7, j + 1, k + 9, this.c, 8);
            this.b(w, i + 7, j + 1, k + 12, this.c, 8);
            this.b(w, i + 7, j + 1, k + 15, this.c, 8);
            this.b(w, i + 7, j + 2, k + 8, this.c, 8);
            this.b(w, i + 7, j + 2, k + 9, this.c, 8);
            this.b(w, i + 7, j + 2, k + 12, this.c, 8);
            this.b(w, i + 7, j + 2, k + 15, this.c, 8);
            this.b(w, i + 7, j + 2, k + 16, this.c, 8);
            this.b(w, i + 7, j + 3, k + 7, this.c, 7);
            this.b(w, i + 7, j + 3, k + 9, this.c, 8);
            this.b(w, i + 7, j + 3, k + 12, this.c, 8);
            this.b(w, i + 7, j + 3, k + 15, this.c, 8);
            this.b(w, i + 7, j + 3, k + 17, this.c, 7);
            this.b(w, i + 7, j + 4, k + 6, this.c, 8);
            this.b(w, i + 7, j + 4, k + 9, this.c, 8);
            this.b(w, i + 7, j + 4, k + 12, this.c, 8);
            this.b(w, i + 7, j + 4, k + 15, this.c, 8);
            this.b(w, i + 7, j + 4, k + 18, this.c, 8);
            this.b(w, i + 7, j + 5, k + 5, this.c, 8);
            this.b(w, i + 7, j + 5, k + 9, this.c, 8);
            this.b(w, i + 7, j + 5, k + 12, this.c, 8);
            this.b(w, i + 7, j + 5, k + 15, this.c, 8);
            this.b(w, i + 7, j + 5, k + 19, this.c, 8);
            this.b(w, i + 7, j + 6, k + 0, this.c);
            this.b(w, i + 7, j + 6, k + 1, this.c);
            this.b(w, i + 7, j + 6, k + 2, this.c);
            this.b(w, i + 7, j + 6, k + 3, this.c);
            this.b(w, i + 7, j + 6, k + 4, this.c);
            this.b(w, i + 7, j + 6, k + 5, this.c);
            this.b(w, i + 7, j + 6, k + 6, this.c);
            this.b(w, i + 7, j + 6, k + 7, this.c);
            this.b(w, i + 7, j + 6, k + 8, this.c, 8);
            this.b(w, i + 7, j + 6, k + 9, this.c, 8);
            this.b(w, i + 7, j + 6, k + 12, this.c, 8);
            this.b(w, i + 7, j + 6, k + 15, this.c, 8);
            this.b(w, i + 7, j + 6, k + 16, this.c, 8);
            this.b(w, i + 7, j + 6, k + 17, this.c);
            this.b(w, i + 7, j + 6, k + 18, this.c);
            this.b(w, i + 7, j + 6, k + 19, this.c);
            this.b(w, i + 7, j + 6, k + 20, this.c, 7);
            this.b(w, i + 7, j + 7, k + 0, this.d);
            this.b(w, i + 7, j + 7, k + 9, this.c, 8);
            this.b(w, i + 7, j + 7, k + 12, this.c, 8);
            this.b(w, i + 7, j + 7, k + 15, this.c, 8);
            this.b(w, i + 7, j + 7, k + 20, this.c, 8);
            this.b(w, i + 7, j + 7, k + 21, this.c, 8);
            this.b(w, i + 7, j + 8, k + 21, this.c, 8);
            this.b(w, i + 7, j + 10, k + 3, this.c, 8);
            this.b(w, i + 7, j + 10, k + 21, this.c, 8);
            this.b(w, i + 7, j + 11, k + 3, this.c, 8);
            this.b(w, i + 7, j + 11, k + 21, this.c, 8);
            this.b(w, i + 7, j + 12, k + 3, this.c, 8);
            this.b(w, i + 7, j + 12, k + 4, this.c);
            this.b(w, i + 7, j + 12, k + 5, this.c);
            this.b(w, i + 7, j + 12, k + 6, this.c);
            this.b(w, i + 7, j + 12, k + 7, this.c);
            this.b(w, i + 7, j + 12, k + 8, this.c);
            this.b(w, i + 7, j + 12, k + 9, this.c);
            this.b(w, i + 7, j + 12, k + 10, this.c);
            this.b(w, i + 7, j + 12, k + 11, this.c);
            this.b(w, i + 7, j + 12, k + 12, this.c);
            this.b(w, i + 7, j + 12, k + 13, this.c);
            this.b(w, i + 7, j + 12, k + 14, this.c);
            this.b(w, i + 7, j + 12, k + 15, this.c);
            this.b(w, i + 7, j + 12, k + 16, this.c);
            this.b(w, i + 7, j + 12, k + 17, this.c);
            this.b(w, i + 7, j + 12, k + 18, this.c);
            this.b(w, i + 7, j + 12, k + 19, this.c);
            this.b(w, i + 7, j + 12, k + 20, this.c);
            this.b(w, i + 7, j + 12, k + 21, this.c, 8);
            this.b(w, i + 7, j + 13, k + 3, this.d);
            this.b(w, i + 7, j + 13, k + 21, this.d);
            this.b(w, i + 7, j + 17, k + 3, this.c, 8);
            this.b(w, i + 7, j + 17, k + 4, this.c, 8);
            this.b(w, i + 7, j + 17, k + 20, this.c, 8);
            this.b(w, i + 7, j + 17, k + 21, this.c, 8);
            this.b(w, i + 7, j + 18, k + 3, this.c, 8);
            this.b(w, i + 7, j + 18, k + 4, this.c, 7);
            this.b(w, i + 7, j + 18, k + 20, this.c, 8);
            this.b(w, i + 7, j + 18, k + 21, this.c, 8);
            this.b(w, i + 7, j + 19, k + 3, this.c, 8);
            this.b(w, i + 7, j + 19, k + 4, this.c, 8);
            this.b(w, i + 7, j + 19, k + 20, this.c, 8);
            this.b(w, i + 7, j + 19, k + 21, this.c, 7);
            this.b(w, i + 7, j + 20, k + 3, this.c, 7);
            this.b(w, i + 7, j + 20, k + 4, this.c, 8);
            this.b(w, i + 7, j + 20, k + 20, this.c, 8);
            this.b(w, i + 7, j + 20, k + 21, this.c, 8);
            this.b(w, i + 7, j + 21, k + 3, this.c, 8);
            this.b(w, i + 7, j + 21, k + 4, this.c, 8);
            this.b(w, i + 7, j + 21, k + 20, this.c, 7);
            this.b(w, i + 7, j + 21, k + 21, this.c, 8);
            this.b(w, i + 7, j + 22, k + 4, this.c, 8);
            this.b(w, i + 7, j + 22, k + 5, this.c, 8);
            this.b(w, i + 7, j + 22, k + 19, this.c, 8);
            this.b(w, i + 7, j + 22, k + 20, this.c, 8);
            this.b(w, i + 7, j + 23, k + 5, this.c, 8);
            this.b(w, i + 7, j + 23, k + 19, this.c, 8);
            this.b(w, i + 7, j + 24, k + 6, this.c, 8);
            this.b(w, i + 7, j + 24, k + 18, this.c, 8);
            this.b(w, i + 7, j + 25, k + 7, this.c, 8);
            this.b(w, i + 7, j + 25, k + 17, this.c, 8);
            this.b(w, i + 7, j + 26, k + 8, this.c, 8);
            this.b(w, i + 7, j + 26, k + 16, this.c, 8);
            this.b(w, i + 7, j + 27, k + 9, this.c, 8);
            this.b(w, i + 7, j + 27, k + 10, this.c, 8);
            this.b(w, i + 7, j + 27, k + 11, this.c, 8);
            this.b(w, i + 7, j + 27, k + 12, this.c, 8);
            this.b(w, i + 7, j + 27, k + 13, this.c, 8);
            this.b(w, i + 7, j + 27, k + 14, this.c, 8);
            this.b(w, i + 7, j + 27, k + 15, this.c, 8);
            this.b(w, i + 8, j + 1, k + 9, this.c, 8);
            this.b(w, i + 8, j + 1, k + 12, this.c, 8);
            this.b(w, i + 8, j + 1, k + 15, this.c, 8);
            this.b(w, i + 8, j + 2, k + 8, this.c, 8);
            this.b(w, i + 8, j + 2, k + 9, this.c, 8);
            this.b(w, i + 8, j + 2, k + 12, this.c, 8);
            this.b(w, i + 8, j + 2, k + 15, this.c, 8);
            this.b(w, i + 8, j + 2, k + 16, this.c, 8);
            this.b(w, i + 8, j + 3, k + 7, this.c, 7);
            this.b(w, i + 8, j + 3, k + 9, this.c, 8);
            this.b(w, i + 8, j + 3, k + 12, this.c, 8);
            this.b(w, i + 8, j + 3, k + 15, this.c, 8);
            this.b(w, i + 8, j + 3, k + 17, this.c, 7);
            this.b(w, i + 8, j + 4, k + 6, this.c, 8);
            this.b(w, i + 8, j + 4, k + 9, this.c, 8);
            this.b(w, i + 8, j + 4, k + 12, this.c, 8);
            this.b(w, i + 8, j + 4, k + 15, this.c, 8);
            this.b(w, i + 8, j + 4, k + 18, this.c, 8);
            this.b(w, i + 8, j + 5, k + 5, this.c, 8);
            this.b(w, i + 8, j + 5, k + 9, this.c, 8);
            this.b(w, i + 8, j + 5, k + 12, this.c, 8);
            this.b(w, i + 8, j + 5, k + 15, this.c, 8);
            this.b(w, i + 8, j + 5, k + 19, this.c, 8);
            this.b(w, i + 8, j + 6, k + 0, this.c);
            this.b(w, i + 8, j + 6, k + 1, this.c);
            this.b(w, i + 8, j + 6, k + 2, this.c);
            this.b(w, i + 8, j + 6, k + 3, this.c);
            this.b(w, i + 8, j + 6, k + 4, this.c);
            this.b(w, i + 8, j + 6, k + 5, this.c);
            this.b(w, i + 8, j + 6, k + 6, this.c);
            this.b(w, i + 8, j + 6, k + 7, this.c);
            this.b(w, i + 8, j + 6, k + 8, this.c, 8);
            this.b(w, i + 8, j + 6, k + 9, this.c, 8);
            this.b(w, i + 8, j + 6, k + 12, this.c, 8);
            this.b(w, i + 8, j + 6, k + 15, this.c, 8);
            this.b(w, i + 8, j + 6, k + 16, this.c, 8);
            this.b(w, i + 8, j + 6, k + 17, this.c);
            this.b(w, i + 8, j + 6, k + 18, this.c);
            this.b(w, i + 8, j + 6, k + 19, this.c);
            this.b(w, i + 8, j + 6, k + 20, this.c, 7);
            this.b(w, i + 8, j + 7, k + 0, this.d);
            this.b(w, i + 8, j + 7, k + 9, this.c, 8);
            this.b(w, i + 8, j + 7, k + 12, this.c, 8);
            this.b(w, i + 8, j + 7, k + 15, this.c, 8);
            this.b(w, i + 8, j + 7, k + 20, this.c, 8);
            this.b(w, i + 8, j + 7, k + 21, this.c, 8);
            this.b(w, i + 8, j + 8, k + 21, this.c, 8);
            this.b(w, i + 8, j + 9, k + 21, this.c, 8);
            this.b(w, i + 8, j + 10, k + 3, this.c, 8);
            this.b(w, i + 8, j + 10, k + 21, this.c, 8);
            this.b(w, i + 8, j + 11, k + 3, this.c, 8);
            this.b(w, i + 8, j + 11, k + 21, this.c, 8);
            this.b(w, i + 8, j + 12, k + 3, this.c, 8);
            this.b(w, i + 8, j + 12, k + 4, this.c);
            this.b(w, i + 8, j + 12, k + 5, this.c);
            this.b(w, i + 8, j + 12, k + 6, this.c);
            this.b(w, i + 8, j + 12, k + 7, this.c);
            this.b(w, i + 8, j + 12, k + 8, this.c);
            this.b(w, i + 8, j + 12, k + 9, this.c);
            this.b(w, i + 8, j + 12, k + 10, this.c);
            this.b(w, i + 8, j + 12, k + 11, this.c);
            this.b(w, i + 8, j + 12, k + 12, this.c);
            this.b(w, i + 8, j + 12, k + 13, this.c);
            this.b(w, i + 8, j + 12, k + 14, this.c);
            this.b(w, i + 8, j + 12, k + 15, this.c);
            this.b(w, i + 8, j + 12, k + 16, this.c);
            this.b(w, i + 8, j + 12, k + 17, this.c);
            this.b(w, i + 8, j + 12, k + 18, this.c);
            this.b(w, i + 8, j + 12, k + 19, this.c);
            this.b(w, i + 8, j + 12, k + 20, this.c);
            this.b(w, i + 8, j + 12, k + 21, this.c, 8);
            this.b(w, i + 8, j + 13, k + 3, this.d);
            this.b(w, i + 8, j + 13, k + 21, this.d);
            this.b(w, i + 8, j + 17, k + 3, this.c, 8);
            this.b(w, i + 8, j + 17, k + 4, this.c, 8);
            this.b(w, i + 8, j + 17, k + 20, this.c, 8);
            this.b(w, i + 8, j + 17, k + 21, this.c, 8);
            this.b(w, i + 8, j + 18, k + 3, this.c, 8);
            this.b(w, i + 8, j + 18, k + 4, this.c, 8);
            this.b(w, i + 8, j + 18, k + 20, this.c, 8);
            this.b(w, i + 8, j + 18, k + 21, this.c, 7);
            this.b(w, i + 8, j + 19, k + 3, this.c, 8);
            this.b(w, i + 8, j + 19, k + 4, this.c, 7);
            this.b(w, i + 8, j + 19, k + 20, this.c, 8);
            this.b(w, i + 8, j + 19, k + 21, this.c, 8);
            this.b(w, i + 8, j + 20, k + 3, this.c, 8);
            this.b(w, i + 8, j + 20, k + 4, this.c, 8);
            this.b(w, i + 8, j + 20, k + 20, this.c, 7);
            this.b(w, i + 8, j + 20, k + 21, this.c, 8);
            this.b(w, i + 8, j + 21, k + 3, this.c, 7);
            this.b(w, i + 8, j + 21, k + 4, this.c, 8);
            this.b(w, i + 8, j + 21, k + 20, this.c, 8);
            this.b(w, i + 8, j + 21, k + 21, this.c, 8);
            this.b(w, i + 8, j + 22, k + 4, this.c, 8);
            this.b(w, i + 8, j + 22, k + 5, this.c, 8);
            this.b(w, i + 8, j + 22, k + 19, this.c, 8);
            this.b(w, i + 8, j + 22, k + 20, this.c, 8);
            this.b(w, i + 8, j + 23, k + 5, this.c, 8);
            this.b(w, i + 8, j + 23, k + 19, this.c, 8);
            this.b(w, i + 8, j + 24, k + 6, this.c, 8);
            this.b(w, i + 8, j + 24, k + 18, this.c, 8);
            this.b(w, i + 8, j + 25, k + 7, this.c, 8);
            this.b(w, i + 8, j + 25, k + 17, this.c, 8);
            this.b(w, i + 8, j + 26, k + 8, this.c, 8);
            this.b(w, i + 8, j + 26, k + 16, this.c, 8);
            this.b(w, i + 8, j + 27, k + 9, this.c, 8);
            this.b(w, i + 8, j + 27, k + 10, this.c, 8);
            this.b(w, i + 8, j + 27, k + 11, this.c, 8);
            this.b(w, i + 8, j + 27, k + 12, this.c, 8);
            this.b(w, i + 8, j + 27, k + 13, this.c, 8);
            this.b(w, i + 8, j + 27, k + 14, this.c, 8);
            this.b(w, i + 8, j + 27, k + 15, this.c, 8);
            this.b(w, i + 8, j + 28, k + 11, this.c, 4);
            this.b(w, i + 8, j + 28, k + 12, this.c, 4);
            this.b(w, i + 8, j + 28, k + 13, this.c, 4);
            this.b(w, i + 8, j + 29, k + 11, this.c, 4);
            this.b(w, i + 8, j + 29, k + 12, this.c, 4);
            this.b(w, i + 8, j + 29, k + 13, this.c, 4);
            this.b(w, i + 8, j + 30, k + 11, this.c, 4);
            this.b(w, i + 8, j + 30, k + 12, this.c, 4);
            this.b(w, i + 8, j + 30, k + 13, this.c, 4);
            this.b(w, i + 9, j + 0, k + 12, this.c, 8);
            this.b(w, i + 9, j + 1, k + 9, this.c, 8);
            this.b(w, i + 9, j + 1, k + 10, this.c, 8);
            this.b(w, i + 9, j + 1, k + 11, this.c, 8);
            this.b(w, i + 9, j + 1, k + 13, this.c, 8);
            this.b(w, i + 9, j + 1, k + 14, this.c, 8);
            this.b(w, i + 9, j + 1, k + 15, this.c, 8);
            this.b(w, i + 9, j + 2, k + 8, this.c, 8);
            this.b(w, i + 9, j + 2, k + 10, this.c, 8);
            this.b(w, i + 9, j + 2, k + 11, this.c, 8);
            this.b(w, i + 9, j + 2, k + 13, this.c, 8);
            this.b(w, i + 9, j + 2, k + 14, this.c, 8);
            this.b(w, i + 9, j + 2, k + 16, this.c, 8);
            this.b(w, i + 9, j + 3, k + 7, this.c, 7);
            this.b(w, i + 9, j + 3, k + 10, this.c, 8);
            this.b(w, i + 9, j + 3, k + 11, this.c, 8);
            this.b(w, i + 9, j + 3, k + 13, this.c, 8);
            this.b(w, i + 9, j + 3, k + 14, this.c, 8);
            this.b(w, i + 9, j + 3, k + 17, this.c, 7);
            this.b(w, i + 9, j + 4, k + 6, this.c, 8);
            this.b(w, i + 9, j + 4, k + 10, this.c, 8);
            this.b(w, i + 9, j + 4, k + 11, this.c, 8);
            this.b(w, i + 9, j + 4, k + 13, this.c, 8);
            this.b(w, i + 9, j + 4, k + 14, this.c, 8);
            this.b(w, i + 9, j + 4, k + 18, this.c, 8);
            this.b(w, i + 9, j + 5, k + 5, this.c, 8);
            this.b(w, i + 9, j + 5, k + 10, this.c, 8);
            this.b(w, i + 9, j + 5, k + 11, this.c, 8);
            this.b(w, i + 9, j + 5, k + 13, this.c, 8);
            this.b(w, i + 9, j + 5, k + 14, this.c, 8);
            this.b(w, i + 9, j + 5, k + 19, this.c, 8);
            this.b(w, i + 9, j + 6, k + 0, this.c);
            this.b(w, i + 9, j + 6, k + 1, this.c);
            this.b(w, i + 9, j + 6, k + 2, this.c);
            this.b(w, i + 9, j + 6, k + 3, this.c);
            this.b(w, i + 9, j + 6, k + 4, this.c);
            this.b(w, i + 9, j + 6, k + 5, this.c);
            this.b(w, i + 9, j + 6, k + 6, this.c);
            this.b(w, i + 9, j + 6, k + 7, this.c);
            this.b(w, i + 9, j + 6, k + 8, this.c, 8);
            this.b(w, i + 9, j + 6, k + 9, this.c, 8);
            this.b(w, i + 9, j + 6, k + 10, this.c, 8);
            this.b(w, i + 9, j + 6, k + 11, this.c, 8);
            this.b(w, i + 9, j + 6, k + 13, this.c, 8);
            this.b(w, i + 9, j + 6, k + 14, this.c, 8);
            this.b(w, i + 9, j + 6, k + 15, this.c, 8);
            this.b(w, i + 9, j + 6, k + 16, this.c, 8);
            this.b(w, i + 9, j + 6, k + 17, this.c);
            this.b(w, i + 9, j + 6, k + 18, this.c);
            this.b(w, i + 9, j + 6, k + 19, this.c);
            this.b(w, i + 9, j + 6, k + 20, this.c, 7);
            this.b(w, i + 9, j + 7, k + 0, this.d);
            this.b(w, i + 9, j + 7, k + 3, this.c, 8);
            this.b(w, i + 9, j + 7, k + 4, this.c, 8);
            this.b(w, i + 9, j + 7, k + 9, this.c, 8);
            this.b(w, i + 9, j + 7, k + 10, this.c, 8);
            this.b(w, i + 9, j + 7, k + 11, this.c, 8);
            this.b(w, i + 9, j + 7, k + 13, this.c, 8);
            this.b(w, i + 9, j + 7, k + 14, this.c, 8);
            this.b(w, i + 9, j + 7, k + 15, this.c, 8);
            this.b(w, i + 9, j + 7, k + 20, this.c, 8);
            this.b(w, i + 9, j + 7, k + 21, this.c, 8);
            this.b(w, i + 9, j + 8, k + 3, this.c, 8);
            this.b(w, i + 9, j + 8, k + 12, this.c, 8);
            this.b(w, i + 9, j + 8, k + 21, this.c, 8);
            this.b(w, i + 9, j + 9, k + 3, this.c, 8);
            this.b(w, i + 9, j + 9, k + 21, this.c, 8);
            this.b(w, i + 9, j + 10, k + 3, this.c, 8);
            this.b(w, i + 9, j + 10, k + 21, this.c, 8);
            this.b(w, i + 9, j + 11, k + 3, this.c, 8);
            this.b(w, i + 9, j + 11, k + 21, this.c, 8);
            this.b(w, i + 9, j + 12, k + 3, this.c, 8);
            this.b(w, i + 9, j + 12, k + 4, this.c);
            this.b(w, i + 9, j + 12, k + 5, this.c);
            this.b(w, i + 9, j + 12, k + 6, this.c);
            this.b(w, i + 9, j + 12, k + 7, this.c);
            this.b(w, i + 9, j + 12, k + 8, this.c);
            this.b(w, i + 9, j + 12, k + 9, this.c);
            this.b(w, i + 9, j + 12, k + 10, this.c);
            this.b(w, i + 9, j + 12, k + 11, this.c);
            this.b(w, i + 9, j + 12, k + 12, this.c);
            this.b(w, i + 9, j + 12, k + 13, this.c);
            this.b(w, i + 9, j + 12, k + 14, this.c);
            this.b(w, i + 9, j + 12, k + 15, this.c);
            this.b(w, i + 9, j + 12, k + 16, this.c);
            this.b(w, i + 9, j + 12, k + 17, this.c);
            this.b(w, i + 9, j + 12, k + 18, this.c);
            this.b(w, i + 9, j + 12, k + 19, this.c);
            this.b(w, i + 9, j + 12, k + 20, this.c);
            this.b(w, i + 9, j + 12, k + 21, this.c, 8);
            this.b(w, i + 9, j + 13, k + 3, this.d);
            this.b(w, i + 9, j + 13, k + 21, this.d);
            this.b(w, i + 9, j + 17, k + 3, this.c, 8);
            this.b(w, i + 9, j + 17, k + 4, this.c, 8);
            this.b(w, i + 9, j + 17, k + 20, this.c, 8);
            this.b(w, i + 9, j + 17, k + 21, this.c, 8);
            this.b(w, i + 9, j + 18, k + 3, this.c, 8);
            this.b(w, i + 9, j + 18, k + 4, this.c, 8);
            this.b(w, i + 9, j + 18, k + 20, this.c, 8);
            this.b(w, i + 9, j + 18, k + 21, this.c, 7);
            this.b(w, i + 9, j + 19, k + 3, this.c, 8);
            this.b(w, i + 9, j + 19, k + 4, this.c, 7);
            this.b(w, i + 9, j + 19, k + 20, this.c, 8);
            this.b(w, i + 9, j + 19, k + 21, this.c, 8);
            this.b(w, i + 9, j + 20, k + 3, this.c, 8);
            this.b(w, i + 9, j + 20, k + 4, this.c, 8);
            this.b(w, i + 9, j + 20, k + 20, this.c, 7);
            this.b(w, i + 9, j + 20, k + 21, this.c, 8);
            this.b(w, i + 9, j + 21, k + 3, this.c, 7);
            this.b(w, i + 9, j + 21, k + 4, this.c, 8);
            this.b(w, i + 9, j + 21, k + 20, this.c, 8);
            this.b(w, i + 9, j + 21, k + 21, this.c, 8);
            this.b(w, i + 9, j + 22, k + 4, this.c, 8);
            this.b(w, i + 9, j + 22, k + 5, this.c, 8);
            this.b(w, i + 9, j + 22, k + 19, this.c, 8);
            this.b(w, i + 9, j + 22, k + 20, this.c, 8);
            this.b(w, i + 9, j + 23, k + 5, this.c, 8);
            this.b(w, i + 9, j + 23, k + 19, this.c, 8);
            this.b(w, i + 9, j + 24, k + 6, this.c, 8);
            this.b(w, i + 9, j + 24, k + 18, this.c, 8);
            this.b(w, i + 9, j + 25, k + 7, this.c, 8);
            this.b(w, i + 9, j + 25, k + 17, this.c, 8);
            this.b(w, i + 9, j + 26, k + 8, this.c, 8);
            this.b(w, i + 9, j + 26, k + 16, this.c, 8);
            this.b(w, i + 9, j + 27, k + 9, this.c, 8);
            this.b(w, i + 9, j + 27, k + 10, this.c, 8);
            this.b(w, i + 9, j + 27, k + 11, this.c, 8);
            this.b(w, i + 9, j + 27, k + 12, this.c, 8);
            this.b(w, i + 9, j + 27, k + 13, this.c, 8);
            this.b(w, i + 9, j + 27, k + 14, this.c, 8);
            this.b(w, i + 9, j + 27, k + 15, this.c, 8);
            this.b(w, i + 9, j + 28, k + 11, this.c, 4);
            this.b(w, i + 9, j + 28, k + 13, this.c, 4);
            this.b(w, i + 9, j + 29, k + 11, this.c, 4);
            this.b(w, i + 9, j + 29, k + 13, this.c, 4);
            this.b(w, i + 9, j + 30, k + 11, this.c, 4);
            this.b(w, i + 9, j + 30, k + 12, this.c, 4);
            this.b(w, i + 9, j + 30, k + 13, this.c, 4);
            this.b(w, i + 9, j + 31, k + 12, this.c, 4);
            this.b(w, i + 10, j + 1, k + 9, this.c, 8);
            this.b(w, i + 10, j + 1, k + 12, this.c, 8);
            this.b(w, i + 10, j + 1, k + 15, this.c, 8);
            this.b(w, i + 10, j + 2, k + 8, this.c, 8);
            this.b(w, i + 10, j + 2, k + 9, this.c, 8);
            this.b(w, i + 10, j + 2, k + 12, this.c, 8);
            this.b(w, i + 10, j + 2, k + 15, this.c, 8);
            this.b(w, i + 10, j + 2, k + 16, this.c, 8);
            this.b(w, i + 10, j + 3, k + 7, this.c, 7);
            this.b(w, i + 10, j + 3, k + 9, this.c, 8);
            this.b(w, i + 10, j + 3, k + 12, this.c, 8);
            this.b(w, i + 10, j + 3, k + 15, this.c, 8);
            this.b(w, i + 10, j + 3, k + 17, this.c, 7);
            this.b(w, i + 10, j + 4, k + 6, this.c, 8);
            this.b(w, i + 10, j + 4, k + 9, this.c, 8);
            this.b(w, i + 10, j + 4, k + 12, this.c, 8);
            this.b(w, i + 10, j + 4, k + 15, this.c, 8);
            this.b(w, i + 10, j + 4, k + 18, this.c, 8);
            this.b(w, i + 10, j + 5, k + 5, this.c, 8);
            this.b(w, i + 10, j + 5, k + 9, this.c, 8);
            this.b(w, i + 10, j + 5, k + 12, this.c, 8);
            this.b(w, i + 10, j + 5, k + 15, this.c, 8);
            this.b(w, i + 10, j + 5, k + 19, this.c, 8);
            this.b(w, i + 10, j + 6, k + 0, this.c);
            this.b(w, i + 10, j + 6, k + 1, this.c);
            this.b(w, i + 10, j + 6, k + 2, this.c);
            this.b(w, i + 10, j + 6, k + 3, this.c);
            this.b(w, i + 10, j + 6, k + 4, this.c, 7);
            this.b(w, i + 10, j + 6, k + 5, this.c);
            this.b(w, i + 10, j + 6, k + 6, this.c);
            this.b(w, i + 10, j + 6, k + 7, this.c);
            this.b(w, i + 10, j + 6, k + 8, this.c, 8);
            this.b(w, i + 10, j + 6, k + 9, this.c, 8);
            this.b(w, i + 10, j + 6, k + 12, this.c, 8);
            this.b(w, i + 10, j + 6, k + 15, this.c, 8);
            this.b(w, i + 10, j + 6, k + 16, this.c, 8);
            this.b(w, i + 10, j + 6, k + 17, this.c);
            this.b(w, i + 10, j + 6, k + 18, this.c);
            this.b(w, i + 10, j + 6, k + 19, this.c);
            this.b(w, i + 10, j + 6, k + 20, this.c, 7);
            this.b(w, i + 10, j + 7, k + 0, this.d);
            this.b(w, i + 10, j + 7, k + 1, this.o);
            this.b(w, i + 10, j + 7, k + 2, this.o);
            this.b(w, i + 10, j + 7, k + 3, this.c, 8);
            this.b(w, i + 10, j + 7, k + 4, this.c, 8);
            this.b(w, i + 10, j + 7, k + 9, this.c, 8);
            this.b(w, i + 10, j + 7, k + 12, this.c, 8);
            this.b(w, i + 10, j + 7, k + 15, this.c, 8);
            this.b(w, i + 10, j + 7, k + 20, this.c, 8);
            this.b(w, i + 10, j + 7, k + 21, this.c, 8);
            this.b(w, i + 10, j + 8, k + 0, this.d);
            this.b(w, i + 10, j + 8, k + 3, this.c, 8);
            this.b(w, i + 10, j + 8, k + 21, this.c, 8);
            this.b(w, i + 10, j + 9, k + 3, this.c, 8);
            this.b(w, i + 10, j + 9, k + 21, this.c, 8);
            this.b(w, i + 10, j + 10, k + 3, this.c, 8);
            this.b(w, i + 10, j + 10, k + 21, this.c, 8);
            this.b(w, i + 10, j + 11, k + 3, this.c, 8);
            this.b(w, i + 10, j + 11, k + 21, this.c, 8);
            this.b(w, i + 10, j + 12, k + 3, this.c, 8);
            this.b(w, i + 10, j + 12, k + 4, this.c);
            this.b(w, i + 10, j + 12, k + 5, this.c);
            this.b(w, i + 10, j + 12, k + 6, this.c);
            this.b(w, i + 10, j + 12, k + 7, this.c);
            this.b(w, i + 10, j + 12, k + 8, this.c);
            this.b(w, i + 10, j + 12, k + 9, this.c);
            this.b(w, i + 10, j + 12, k + 10, this.c);
            this.b(w, i + 10, j + 12, k + 11, this.c);
            this.b(w, i + 10, j + 12, k + 12, this.c);
            this.b(w, i + 10, j + 12, k + 13, this.c);
            this.b(w, i + 10, j + 12, k + 14, this.c);
            this.b(w, i + 10, j + 12, k + 15, this.c);
            this.b(w, i + 10, j + 12, k + 16, this.c);
            this.b(w, i + 10, j + 12, k + 17, this.c);
            this.b(w, i + 10, j + 12, k + 18, this.c);
            this.b(w, i + 10, j + 12, k + 19, this.c);
            this.b(w, i + 10, j + 12, k + 20, this.c);
            this.b(w, i + 10, j + 12, k + 21, this.c, 8);
            this.b(w, i + 10, j + 13, k + 3, this.d);
            this.b(w, i + 10, j + 13, k + 21, this.d);
            this.b(w, i + 10, j + 17, k + 3, this.c, 8);
            this.b(w, i + 10, j + 17, k + 4, this.c, 8);
            this.b(w, i + 10, j + 17, k + 20, this.c, 8);
            this.b(w, i + 10, j + 17, k + 21, this.c, 8);
            this.b(w, i + 10, j + 18, k + 3, this.c, 8);
            this.b(w, i + 10, j + 18, k + 4, this.c, 8);
            this.b(w, i + 10, j + 18, k + 20, this.c, 8);
            this.b(w, i + 10, j + 18, k + 21, this.c, 8);
            this.b(w, i + 10, j + 19, k + 3, this.c, 8);
            this.b(w, i + 10, j + 19, k + 4, this.c, 8);
            this.b(w, i + 10, j + 19, k + 20, this.c, 7);
            this.b(w, i + 10, j + 19, k + 21, this.c, 7);
            this.b(w, i + 10, j + 20, k + 3, this.c, 7);
            this.b(w, i + 10, j + 20, k + 4, this.c, 7);
            this.b(w, i + 10, j + 20, k + 20, this.c, 8);
            this.b(w, i + 10, j + 20, k + 21, this.c, 8);
            this.b(w, i + 10, j + 21, k + 3, this.c, 8);
            this.b(w, i + 10, j + 21, k + 4, this.c, 8);
            this.b(w, i + 10, j + 21, k + 20, this.c, 8);
            this.b(w, i + 10, j + 21, k + 21, this.c, 8);
            this.b(w, i + 10, j + 22, k + 4, this.c, 8);
            this.b(w, i + 10, j + 22, k + 5, this.c, 8);
            this.b(w, i + 10, j + 22, k + 19, this.c, 8);
            this.b(w, i + 10, j + 22, k + 20, this.c, 8);
            this.b(w, i + 10, j + 23, k + 5, this.c, 8);
            this.b(w, i + 10, j + 23, k + 19, this.c, 8);
            this.b(w, i + 10, j + 24, k + 6, this.c, 8);
            this.b(w, i + 10, j + 24, k + 18, this.c, 8);
            this.b(w, i + 10, j + 25, k + 7, this.c, 8);
            this.b(w, i + 10, j + 25, k + 17, this.c, 8);
            this.b(w, i + 10, j + 26, k + 8, this.c, 8);
            this.b(w, i + 10, j + 26, k + 16, this.c, 8);
            this.b(w, i + 10, j + 27, k + 9, this.c, 8);
            this.b(w, i + 10, j + 27, k + 10, this.c, 8);
            this.b(w, i + 10, j + 27, k + 11, this.c, 8);
            this.b(w, i + 10, j + 27, k + 12, this.c, 8);
            this.b(w, i + 10, j + 27, k + 13, this.c, 8);
            this.b(w, i + 10, j + 27, k + 14, this.c, 8);
            this.b(w, i + 10, j + 27, k + 15, this.c, 8);
            this.b(w, i + 10, j + 28, k + 11, this.c, 4);
            this.b(w, i + 10, j + 28, k + 12, this.c, 4);
            this.b(w, i + 10, j + 28, k + 13, this.c, 4);
            this.b(w, i + 10, j + 29, k + 11, this.c, 4);
            this.b(w, i + 10, j + 29, k + 12, this.c, 4);
            this.b(w, i + 10, j + 29, k + 13, this.c, 4);
            this.b(w, i + 10, j + 30, k + 11, this.c, 4);
            this.b(w, i + 10, j + 30, k + 12, this.c, 4);
            this.b(w, i + 10, j + 30, k + 13, this.c, 4);
            this.b(w, i + 11, j + 1, k + 9, this.c, 8);
            this.b(w, i + 11, j + 1, k + 12, this.c, 8);
            this.b(w, i + 11, j + 1, k + 15, this.c, 8);
            this.b(w, i + 11, j + 2, k + 8, this.c, 8);
            this.b(w, i + 11, j + 2, k + 9, this.c, 8);
            this.b(w, i + 11, j + 2, k + 12, this.c, 8);
            this.b(w, i + 11, j + 2, k + 15, this.c, 8);
            this.b(w, i + 11, j + 2, k + 16, this.c, 8);
            this.b(w, i + 11, j + 3, k + 7, this.c, 7);
            this.b(w, i + 11, j + 3, k + 9, this.c, 8);
            this.b(w, i + 11, j + 3, k + 12, this.c, 8);
            this.b(w, i + 11, j + 3, k + 15, this.c, 8);
            this.b(w, i + 11, j + 3, k + 17, this.c, 7);
            this.b(w, i + 11, j + 4, k + 6, this.c, 8);
            this.b(w, i + 11, j + 4, k + 9, this.c, 8);
            this.b(w, i + 11, j + 4, k + 12, this.c, 8);
            this.b(w, i + 11, j + 4, k + 15, this.c, 8);
            this.b(w, i + 11, j + 4, k + 18, this.c, 8);
            this.b(w, i + 11, j + 5, k + 5, this.c, 8);
            this.b(w, i + 11, j + 5, k + 9, this.c, 8);
            this.b(w, i + 11, j + 5, k + 12, this.c, 8);
            this.b(w, i + 11, j + 5, k + 15, this.c, 8);
            this.b(w, i + 11, j + 5, k + 19, this.c, 8);
            this.b(w, i + 11, j + 6, k + 4, this.c, 7);
            this.b(w, i + 11, j + 6, k + 5, this.c);
            this.b(w, i + 11, j + 6, k + 6, this.c);
            this.b(w, i + 11, j + 6, k + 7, this.c);
            this.b(w, i + 11, j + 6, k + 8, this.c, 8);
            KnTrP2 p2 = new KnTrP2();
            p2.generate2(w, rand, i, j, k);
        }
        return true;
    }
}

