/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  JinRyuu.JRMCore.JRMCoreSafe
 *  JinRyuu.JRMCore.blocks.BlocksJRMC
 *  net.minecraft.block.Block
 *  net.minecraft.block.material.Material
 *  net.minecraft.init.Blocks
 *  net.minecraft.world.World
 *  net.minecraft.world.gen.feature.WorldGenerator
 */
package JinRyuu.DragonBC.common.Villages;

import JinRyuu.DragonBC.common.Villages.TiChaP2;
import JinRyuu.DragonBC.common.mod_DragonBC;
import JinRyuu.JRMCore.JRMCoreSafe;
import JinRyuu.JRMCore.blocks.BlocksJRMC;
import java.util.Random;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.init.Blocks;
import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;

public class TiCha
extends WorldGenerator {
    public Block c = BlocksJRMC.BlockColoredStone;
    public Block d = Blocks.planks;
    public Block l = Blocks.leaves;
    public Block s = BlocksJRMC.stoneSingleSlab;
    public Block g = Blocks.glass;
    public Block v = Blocks.log;
    public Block t = Blocks.dirt;
    public Block e = Blocks.glowstone;
    public Block o = BlocksJRMC.BlockColoredStone;
    public Block f = BlocksJRMC.BlockFence;

    protected void b(World par1World, int par2, int par3, int par4, Block par5) {
        this.setBlockAndNotifyAdequately(par1World, par2, par3, par4, par5, 0);
    }

    protected void b(World par1World, int par2, int par3, int par4, Block par5, int par6) {
        this.setBlockAndNotifyAdequately(par1World, par2, par3, par4, par5, par6);
    }

    /*
     * Opcode count of 22030 triggered aggressive code reduction.  Override with --aggressivesizethreshold.
     */
    public boolean generate(World w, Random rand, int i, int j, int k) {
        block0: {
            i = 0;
            j = 32;
            k = 0;
            JRMCoreSafe safe = new JRMCoreSafe(w);
            safe.isSpawn("false ", "dont", 0, safe.dataDir, "tc.dbc");
            safe.isSpawn("false", 0, safe.dataDir, "tc.dbc");
            int cfr_ignored_0 = w.provider.dimensionId;
            if (w.getBlock(i, j + 100, k).getMaterial() != Material.air) break block0;
            safe.saveSpawnList("spwn ", safe.dataDir, "tc.dbc");
            mod_DragonBC.logger.info("Time Chamber Spawned");
            this.b(w, i + 0, j + 0, k + 6, this.s);
            this.b(w, i + 0, j + 0, k + 7, this.s);
            this.b(w, i + 0, j + 0, k + 8, this.s);
            this.b(w, i + 0, j + 0, k + 9, this.s);
            this.b(w, i + 0, j + 0, k + 10, this.s);
            this.b(w, i + 0, j + 0, k + 11, this.s);
            this.b(w, i + 0, j + 0, k + 12, this.s);
            this.b(w, i + 0, j + 0, k + 13, this.s);
            this.b(w, i + 0, j + 0, k + 14, this.s);
            this.b(w, i + 0, j + 0, k + 15, this.s);
            this.b(w, i + 0, j + 0, k + 16, this.s);
            this.b(w, i + 0, j + 0, k + 17, this.s);
            this.b(w, i + 0, j + 0, k + 18, this.s);
            this.b(w, i + 0, j + 0, k + 19, this.s);
            this.b(w, i + 0, j + 0, k + 20, this.s);
            this.b(w, i + 0, j + 0, k + 21, this.s);
            this.b(w, i + 0, j + 0, k + 22, this.s);
            this.b(w, i + 0, j + 0, k + 23, this.s);
            this.b(w, i + 0, j + 0, k + 24, this.s);
            this.b(w, i + 0, j + 0, k + 25, this.s);
            this.b(w, i + 0, j + 0, k + 26, this.s);
            this.b(w, i + 0, j + 0, k + 27, this.s);
            this.b(w, i + 0, j + 0, k + 28, this.s);
            this.b(w, i + 0, j + 0, k + 29, this.s);
            this.b(w, i + 1, j + 0, k + 6, this.s);
            this.b(w, i + 1, j + 0, k + 7, this.c, 8);
            this.b(w, i + 1, j + 0, k + 8, this.c, 8);
            this.b(w, i + 1, j + 0, k + 9, this.c, 8);
            this.b(w, i + 1, j + 0, k + 10, this.c, 8);
            this.b(w, i + 1, j + 0, k + 11, this.c, 8);
            this.b(w, i + 1, j + 0, k + 12, this.c, 8);
            this.b(w, i + 1, j + 0, k + 13, this.c, 8);
            this.b(w, i + 1, j + 0, k + 14, this.c, 8);
            this.b(w, i + 1, j + 0, k + 15, this.c, 8);
            this.b(w, i + 1, j + 0, k + 16, this.c, 8);
            this.b(w, i + 1, j + 0, k + 17, this.c, 8);
            this.b(w, i + 1, j + 0, k + 18, this.c, 8);
            this.b(w, i + 1, j + 0, k + 19, this.c, 8);
            this.b(w, i + 1, j + 0, k + 20, this.c, 8);
            this.b(w, i + 1, j + 0, k + 21, this.c, 8);
            this.b(w, i + 1, j + 0, k + 22, this.c, 8);
            this.b(w, i + 1, j + 0, k + 23, this.c, 8);
            this.b(w, i + 1, j + 0, k + 24, this.c, 8);
            this.b(w, i + 1, j + 0, k + 25, this.c, 8);
            this.b(w, i + 1, j + 0, k + 26, this.c, 8);
            this.b(w, i + 1, j + 0, k + 27, this.c, 8);
            this.b(w, i + 1, j + 0, k + 28, this.c, 8);
            this.b(w, i + 1, j + 0, k + 29, this.s);
            this.b(w, i + 1, j + 13, k + 20, this.g);
            this.b(w, i + 1, j + 14, k + 19, this.g);
            this.b(w, i + 1, j + 14, k + 20, this.g);
            this.b(w, i + 1, j + 14, k + 21, this.g);
            this.b(w, i + 1, j + 15, k + 19, this.g);
            this.b(w, i + 1, j + 15, k + 20, this.g);
            this.b(w, i + 1, j + 15, k + 21, this.g);
            this.b(w, i + 1, j + 16, k + 19, this.g);
            this.b(w, i + 1, j + 16, k + 20, this.g);
            this.b(w, i + 1, j + 16, k + 21, this.g);
            this.b(w, i + 1, j + 17, k + 20, this.g);
            this.b(w, i + 2, j + 0, k + 6, this.s);
            this.b(w, i + 2, j + 0, k + 7, this.c, 8);
            this.b(w, i + 2, j + 0, k + 8, this.c, 8);
            this.b(w, i + 2, j + 0, k + 9, this.c, 8);
            this.b(w, i + 2, j + 0, k + 10, this.c, 8);
            this.b(w, i + 2, j + 0, k + 11, this.c, 8);
            this.b(w, i + 2, j + 0, k + 12, this.c, 8);
            this.b(w, i + 2, j + 0, k + 13, this.c, 8);
            this.b(w, i + 2, j + 0, k + 14, this.c, 8);
            this.b(w, i + 2, j + 0, k + 15, this.c, 8);
            this.b(w, i + 2, j + 0, k + 16, this.c, 8);
            this.b(w, i + 2, j + 0, k + 17, this.c, 8);
            this.b(w, i + 2, j + 0, k + 18, this.c, 8);
            this.b(w, i + 2, j + 0, k + 19, this.c, 8);
            this.b(w, i + 2, j + 0, k + 20, this.c, 8);
            this.b(w, i + 2, j + 0, k + 21, this.c, 8);
            this.b(w, i + 2, j + 0, k + 22, this.c, 8);
            this.b(w, i + 2, j + 0, k + 23, this.c, 8);
            this.b(w, i + 2, j + 0, k + 24, this.c, 8);
            this.b(w, i + 2, j + 0, k + 25, this.c, 8);
            this.b(w, i + 2, j + 0, k + 26, this.c, 8);
            this.b(w, i + 2, j + 0, k + 27, this.c, 8);
            this.b(w, i + 2, j + 0, k + 28, this.c, 8);
            this.b(w, i + 2, j + 0, k + 29, this.s);
            this.b(w, i + 2, j + 1, k + 20, this.c, 4);
            this.b(w, i + 2, j + 2, k + 19, this.c, 4);
            this.b(w, i + 2, j + 2, k + 20, this.c, 4);
            this.b(w, i + 2, j + 2, k + 21, this.c, 4);
            this.b(w, i + 2, j + 3, k + 20, this.c, 4);
            this.b(w, i + 2, j + 12, k + 20, this.c, 4);
            this.b(w, i + 2, j + 13, k + 19, this.g);
            this.b(w, i + 2, j + 13, k + 21, this.g);
            this.b(w, i + 2, j + 14, k + 18, this.g);
            this.b(w, i + 2, j + 14, k + 22, this.g);
            this.b(w, i + 2, j + 15, k + 18, this.g);
            this.b(w, i + 2, j + 15, k + 22, this.g);
            this.b(w, i + 2, j + 16, k + 18, this.g);
            this.b(w, i + 2, j + 16, k + 22, this.g);
            this.b(w, i + 2, j + 17, k + 19, this.g);
            this.b(w, i + 2, j + 17, k + 21, this.g);
            this.b(w, i + 2, j + 18, k + 20, this.c, 4);
            this.b(w, i + 3, j + 0, k + 6, this.s);
            this.b(w, i + 3, j + 0, k + 7, this.c, 8);
            this.b(w, i + 3, j + 0, k + 8, this.c, 8);
            this.b(w, i + 3, j + 0, k + 9, this.c, 8);
            this.b(w, i + 3, j + 0, k + 10, this.c, 8);
            this.b(w, i + 3, j + 0, k + 11, this.c, 8);
            this.b(w, i + 3, j + 0, k + 12, this.c, 8);
            this.b(w, i + 3, j + 0, k + 13, this.c, 8);
            this.b(w, i + 3, j + 0, k + 14, this.c, 8);
            this.b(w, i + 3, j + 0, k + 15, this.c, 8);
            this.b(w, i + 3, j + 0, k + 16, this.c, 8);
            this.b(w, i + 3, j + 0, k + 17, this.c, 8);
            this.b(w, i + 3, j + 0, k + 18, this.c, 8);
            this.b(w, i + 3, j + 0, k + 19, this.c, 8);
            this.b(w, i + 3, j + 0, k + 20, this.c, 8);
            this.b(w, i + 3, j + 0, k + 21, this.c, 8);
            this.b(w, i + 3, j + 0, k + 22, this.c, 8);
            this.b(w, i + 3, j + 0, k + 23, this.c, 8);
            this.b(w, i + 3, j + 0, k + 24, this.c, 8);
            this.b(w, i + 3, j + 0, k + 25, this.c, 8);
            this.b(w, i + 3, j + 0, k + 26, this.c, 8);
            this.b(w, i + 3, j + 0, k + 27, this.c, 8);
            this.b(w, i + 3, j + 0, k + 28, this.c, 8);
            this.b(w, i + 3, j + 0, k + 29, this.s);
            this.b(w, i + 3, j + 1, k + 19, this.c, 4);
            this.b(w, i + 3, j + 1, k + 21, this.c, 4);
            this.b(w, i + 3, j + 2, k + 19, this.c, 4);
            this.b(w, i + 3, j + 2, k + 21, this.c, 4);
            this.b(w, i + 3, j + 3, k + 19, this.c, 4);
            this.b(w, i + 3, j + 3, k + 21, this.c, 4);
            this.b(w, i + 3, j + 4, k + 20, this.c, 4);
            this.b(w, i + 3, j + 5, k + 20, this.c, 4);
            this.b(w, i + 3, j + 6, k + 20, this.c, 4);
            this.b(w, i + 3, j + 7, k + 20, this.c, 4);
            this.b(w, i + 3, j + 8, k + 20, this.c, 4);
            this.b(w, i + 3, j + 9, k + 20, this.c, 4);
            this.b(w, i + 3, j + 10, k + 20, this.c, 4);
            this.b(w, i + 3, j + 11, k + 20, this.c, 4);
            this.b(w, i + 3, j + 12, k + 19, this.c, 4);
            this.b(w, i + 3, j + 12, k + 20, this.c, 4);
            this.b(w, i + 3, j + 12, k + 21, this.c, 4);
            this.b(w, i + 3, j + 13, k + 18, this.g);
            this.b(w, i + 3, j + 13, k + 20, this.g);
            this.b(w, i + 3, j + 13, k + 22, this.g);
            this.b(w, i + 3, j + 14, k + 18, this.g);
            this.b(w, i + 3, j + 14, k + 20, this.g);
            this.b(w, i + 3, j + 14, k + 22, this.g);
            this.b(w, i + 3, j + 15, k + 18, this.g);
            this.b(w, i + 3, j + 15, k + 22, this.g);
            this.b(w, i + 3, j + 16, k + 18, this.g);
            this.b(w, i + 3, j + 16, k + 22, this.g);
            this.b(w, i + 3, j + 17, k + 18, this.g);
            this.b(w, i + 3, j + 17, k + 22, this.g);
            this.b(w, i + 3, j + 18, k + 19, this.c, 4);
            this.b(w, i + 3, j + 18, k + 20, this.c, 4);
            this.b(w, i + 3, j + 18, k + 21, this.c, 4);
            this.b(w, i + 4, j + 0, k + 6, this.s);
            this.b(w, i + 4, j + 0, k + 7, this.c, 8);
            this.b(w, i + 4, j + 0, k + 8, this.c, 8);
            this.b(w, i + 4, j + 0, k + 9, this.c, 8);
            this.b(w, i + 4, j + 0, k + 10, this.c, 8);
            this.b(w, i + 4, j + 0, k + 11, this.c, 8);
            this.b(w, i + 4, j + 0, k + 12, this.c, 8);
            this.b(w, i + 4, j + 0, k + 13, this.c, 8);
            this.b(w, i + 4, j + 0, k + 14, this.c, 8);
            this.b(w, i + 4, j + 0, k + 15, this.c, 8);
            this.b(w, i + 4, j + 0, k + 16, this.c, 8);
            this.b(w, i + 4, j + 0, k + 17, this.c, 8);
            this.b(w, i + 4, j + 0, k + 18, this.c, 8);
            this.b(w, i + 4, j + 0, k + 19, this.c, 8);
            this.b(w, i + 4, j + 0, k + 20, this.c, 8);
            this.b(w, i + 4, j + 0, k + 21, this.c, 8);
            this.b(w, i + 4, j + 0, k + 22, this.c, 8);
            this.b(w, i + 4, j + 0, k + 23, this.c, 8);
            this.b(w, i + 4, j + 0, k + 24, this.c, 8);
            this.b(w, i + 4, j + 0, k + 25, this.c, 8);
            this.b(w, i + 4, j + 0, k + 26, this.c, 8);
            this.b(w, i + 4, j + 0, k + 27, this.c, 8);
            this.b(w, i + 4, j + 0, k + 28, this.c, 8);
            this.b(w, i + 4, j + 0, k + 29, this.s);
            this.b(w, i + 4, j + 1, k + 20, this.c, 4);
            this.b(w, i + 4, j + 2, k + 19, this.c, 4);
            this.b(w, i + 4, j + 2, k + 20, this.c, 4);
            this.b(w, i + 4, j + 2, k + 21, this.c, 4);
            this.b(w, i + 4, j + 3, k + 20, this.c, 4);
            this.b(w, i + 4, j + 12, k + 20, this.c, 4);
            this.b(w, i + 4, j + 13, k + 19, this.g);
            this.b(w, i + 4, j + 13, k + 21, this.g);
            this.b(w, i + 4, j + 14, k + 18, this.g);
            this.b(w, i + 4, j + 14, k + 22, this.g);
            this.b(w, i + 4, j + 15, k + 18, this.g);
            this.b(w, i + 4, j + 15, k + 22, this.g);
            this.b(w, i + 4, j + 16, k + 18, this.g);
            this.b(w, i + 4, j + 16, k + 22, this.g);
            this.b(w, i + 4, j + 17, k + 19, this.g);
            this.b(w, i + 4, j + 17, k + 21, this.g);
            this.b(w, i + 4, j + 18, k + 20, this.c, 4);
            this.b(w, i + 5, j + 0, k + 6, this.s);
            this.b(w, i + 5, j + 0, k + 7, this.c, 8);
            this.b(w, i + 5, j + 0, k + 8, this.c, 8);
            this.b(w, i + 5, j + 0, k + 9, this.c, 8);
            this.b(w, i + 5, j + 0, k + 10, this.c, 8);
            this.b(w, i + 5, j + 0, k + 11, this.c, 8);
            this.b(w, i + 5, j + 0, k + 12, this.c, 8);
            this.b(w, i + 5, j + 0, k + 13, this.c, 8);
            this.b(w, i + 5, j + 0, k + 14, this.c, 8);
            this.b(w, i + 5, j + 0, k + 15, this.c, 8);
            this.b(w, i + 5, j + 0, k + 16, this.c, 8);
            this.b(w, i + 5, j + 0, k + 17, this.c, 8);
            this.b(w, i + 5, j + 0, k + 18, this.c, 8);
            this.b(w, i + 5, j + 0, k + 19, this.c, 8);
            this.b(w, i + 5, j + 0, k + 20, this.c, 8);
            this.b(w, i + 5, j + 0, k + 21, this.c, 8);
            this.b(w, i + 5, j + 0, k + 22, this.c, 8);
            this.b(w, i + 5, j + 0, k + 23, this.c, 8);
            this.b(w, i + 5, j + 0, k + 24, this.c, 8);
            this.b(w, i + 5, j + 0, k + 25, this.c, 8);
            this.b(w, i + 5, j + 0, k + 26, this.c, 8);
            this.b(w, i + 5, j + 0, k + 27, this.c, 8);
            this.b(w, i + 5, j + 0, k + 28, this.c, 8);
            this.b(w, i + 5, j + 0, k + 29, this.s);
            this.b(w, i + 5, j + 13, k + 20, this.g);
            this.b(w, i + 5, j + 14, k + 19, this.g);
            this.b(w, i + 5, j + 14, k + 20, this.g);
            this.b(w, i + 5, j + 14, k + 21, this.g);
            this.b(w, i + 5, j + 15, k + 19, this.g);
            this.b(w, i + 5, j + 15, k + 20, this.g);
            this.b(w, i + 5, j + 15, k + 21, this.g);
            this.b(w, i + 5, j + 16, k + 19, this.g);
            this.b(w, i + 5, j + 16, k + 20, this.g);
            this.b(w, i + 5, j + 16, k + 21, this.g);
            this.b(w, i + 5, j + 17, k + 20, this.g);
            this.b(w, i + 6, j + 0, k + 6, this.s);
            this.b(w, i + 6, j + 0, k + 7, this.c, 8);
            this.b(w, i + 6, j + 0, k + 8, this.c, 8);
            this.b(w, i + 6, j + 0, k + 9, this.c, 8);
            this.b(w, i + 6, j + 0, k + 10, this.c, 8);
            this.b(w, i + 6, j + 0, k + 11, this.c, 8);
            this.b(w, i + 6, j + 0, k + 12, this.c, 8);
            this.b(w, i + 6, j + 0, k + 13, this.c, 8);
            this.b(w, i + 6, j + 0, k + 14, this.c, 8);
            this.b(w, i + 6, j + 0, k + 15, this.c, 8);
            this.b(w, i + 6, j + 0, k + 16, this.c, 8);
            this.b(w, i + 6, j + 0, k + 17, this.c, 8);
            this.b(w, i + 6, j + 0, k + 18, this.c, 8);
            this.b(w, i + 6, j + 0, k + 19, this.c, 8);
            this.b(w, i + 6, j + 0, k + 20, this.c, 8);
            this.b(w, i + 6, j + 0, k + 21, this.c, 8);
            this.b(w, i + 6, j + 0, k + 22, this.c, 8);
            this.b(w, i + 6, j + 0, k + 23, this.c, 8);
            this.b(w, i + 6, j + 0, k + 24, this.c, 8);
            this.b(w, i + 6, j + 0, k + 25, this.c, 8);
            this.b(w, i + 6, j + 0, k + 26, this.c, 8);
            this.b(w, i + 6, j + 0, k + 27, this.c, 8);
            this.b(w, i + 6, j + 0, k + 28, this.c, 8);
            this.b(w, i + 6, j + 0, k + 29, this.s);
            this.b(w, i + 7, j + 0, k + 6, this.s);
            this.b(w, i + 7, j + 0, k + 7, this.c, 8);
            this.b(w, i + 7, j + 0, k + 8, this.c, 8);
            this.b(w, i + 7, j + 0, k + 9, this.c, 8);
            this.b(w, i + 7, j + 0, k + 10, this.c, 8);
            this.b(w, i + 7, j + 0, k + 11, this.c, 8);
            this.b(w, i + 7, j + 0, k + 12, this.c, 8);
            this.b(w, i + 7, j + 0, k + 13, this.c, 8);
            this.b(w, i + 7, j + 0, k + 14, this.c, 8);
            this.b(w, i + 7, j + 0, k + 15, this.c, 8);
            this.b(w, i + 7, j + 0, k + 16, this.c, 8);
            this.b(w, i + 7, j + 0, k + 17, this.c, 8);
            this.b(w, i + 7, j + 0, k + 18, this.c, 8);
            this.b(w, i + 7, j + 0, k + 19, this.c, 8);
            this.b(w, i + 7, j + 0, k + 20, this.c, 8);
            this.b(w, i + 7, j + 0, k + 21, this.c, 8);
            this.b(w, i + 7, j + 0, k + 22, this.c, 8);
            this.b(w, i + 7, j + 0, k + 23, this.c, 8);
            this.b(w, i + 7, j + 0, k + 24, this.c, 8);
            this.b(w, i + 7, j + 0, k + 25, this.c, 8);
            this.b(w, i + 7, j + 0, k + 26, this.c, 8);
            this.b(w, i + 7, j + 0, k + 27, this.c, 8);
            this.b(w, i + 7, j + 0, k + 28, this.c, 8);
            this.b(w, i + 7, j + 0, k + 29, this.s);
            this.b(w, i + 8, j + 0, k + 6, this.s);
            this.b(w, i + 8, j + 0, k + 7, this.c, 8);
            this.b(w, i + 8, j + 0, k + 8, this.c, 8);
            this.b(w, i + 8, j + 0, k + 9, this.c, 8);
            this.b(w, i + 8, j + 0, k + 10, this.c, 8);
            this.b(w, i + 8, j + 0, k + 11, this.c, 8);
            this.b(w, i + 8, j + 0, k + 12, this.c, 8);
            this.b(w, i + 8, j + 0, k + 13, this.c, 8);
            this.b(w, i + 8, j + 0, k + 14, this.c, 8);
            this.b(w, i + 8, j + 0, k + 15, this.c, 8);
            this.b(w, i + 8, j + 0, k + 16, this.c, 8);
            this.b(w, i + 8, j + 0, k + 17, this.c, 8);
            this.b(w, i + 8, j + 0, k + 18, this.c, 8);
            this.b(w, i + 8, j + 0, k + 19, this.c, 8);
            this.b(w, i + 8, j + 0, k + 20, this.c, 8);
            this.b(w, i + 8, j + 0, k + 21, this.c, 8);
            this.b(w, i + 8, j + 0, k + 22, this.c, 8);
            this.b(w, i + 8, j + 0, k + 23, this.c, 8);
            this.b(w, i + 8, j + 0, k + 24, this.c, 8);
            this.b(w, i + 8, j + 0, k + 25, this.c, 8);
            this.b(w, i + 8, j + 0, k + 26, this.c, 8);
            this.b(w, i + 8, j + 0, k + 27, this.c, 8);
            this.b(w, i + 8, j + 0, k + 28, this.c, 8);
            this.b(w, i + 8, j + 0, k + 29, this.s);
            this.b(w, i + 9, j + 0, k + 6, this.s);
            this.b(w, i + 9, j + 0, k + 7, this.c, 8);
            this.b(w, i + 9, j + 0, k + 8, this.c, 8);
            this.b(w, i + 9, j + 0, k + 9, this.c, 8);
            this.b(w, i + 9, j + 0, k + 10, this.c, 8);
            this.b(w, i + 9, j + 0, k + 11, this.c, 8);
            this.b(w, i + 9, j + 0, k + 12, this.c, 8);
            this.b(w, i + 9, j + 0, k + 13, this.c, 8);
            this.b(w, i + 9, j + 0, k + 14, this.c, 8);
            this.b(w, i + 9, j + 0, k + 15, this.c, 8);
            this.b(w, i + 9, j + 0, k + 16, this.c, 8);
            this.b(w, i + 9, j + 0, k + 17, this.c, 8);
            this.b(w, i + 9, j + 0, k + 18, this.c, 8);
            this.b(w, i + 9, j + 0, k + 19, this.c, 8);
            this.b(w, i + 9, j + 0, k + 20, this.c, 8);
            this.b(w, i + 9, j + 0, k + 21, this.c, 8);
            this.b(w, i + 9, j + 0, k + 22, this.c, 8);
            this.b(w, i + 9, j + 0, k + 23, this.c, 8);
            this.b(w, i + 9, j + 0, k + 24, this.c, 8);
            this.b(w, i + 9, j + 0, k + 25, this.c, 8);
            this.b(w, i + 9, j + 0, k + 26, this.c, 8);
            this.b(w, i + 9, j + 0, k + 27, this.c, 8);
            this.b(w, i + 9, j + 0, k + 28, this.c, 8);
            this.b(w, i + 9, j + 0, k + 29, this.s);
            this.b(w, i + 9, j + 1, k + 18, this.c, 4);
            this.b(w, i + 9, j + 1, k + 19, this.c, 4);
            this.b(w, i + 9, j + 1, k + 20, this.c, 4);
            this.b(w, i + 9, j + 1, k + 21, this.c, 4);
            this.b(w, i + 9, j + 1, k + 22, this.c, 4);
            this.b(w, i + 9, j + 2, k + 19, this.c, 4);
            this.b(w, i + 9, j + 2, k + 20, this.c, 4);
            this.b(w, i + 9, j + 2, k + 21, this.c, 4);
            this.b(w, i + 9, j + 3, k + 19, this.g);
            this.b(w, i + 9, j + 3, k + 20, this.g);
            this.b(w, i + 9, j + 3, k + 21, this.g);
            this.b(w, i + 9, j + 4, k + 19, this.g);
            this.b(w, i + 9, j + 4, k + 20, this.g);
            this.b(w, i + 9, j + 4, k + 21, this.g);
            this.b(w, i + 9, j + 5, k + 18, this.g);
            this.b(w, i + 9, j + 5, k + 19, this.g);
            this.b(w, i + 9, j + 5, k + 20, this.g);
            this.b(w, i + 9, j + 5, k + 21, this.g);
            this.b(w, i + 9, j + 5, k + 22, this.g);
            this.b(w, i + 9, j + 6, k + 19, this.g);
            this.b(w, i + 9, j + 6, k + 20, this.g);
            this.b(w, i + 9, j + 6, k + 21, this.g);
            this.b(w, i + 9, j + 7, k + 19, this.g);
            this.b(w, i + 9, j + 7, k + 20, this.g);
            this.b(w, i + 9, j + 7, k + 21, this.g);
            this.b(w, i + 9, j + 17, k + 19, this.g);
            this.b(w, i + 9, j + 17, k + 20, this.g);
            this.b(w, i + 9, j + 17, k + 21, this.g);
            this.b(w, i + 9, j + 18, k + 19, this.g);
            this.b(w, i + 9, j + 18, k + 20, this.g);
            this.b(w, i + 9, j + 18, k + 21, this.g);
            this.b(w, i + 9, j + 19, k + 18, this.g);
            this.b(w, i + 9, j + 19, k + 19, this.g);
            this.b(w, i + 9, j + 19, k + 20, this.g);
            this.b(w, i + 9, j + 19, k + 21, this.g);
            this.b(w, i + 9, j + 19, k + 22, this.g);
            this.b(w, i + 9, j + 20, k + 19, this.g);
            this.b(w, i + 9, j + 20, k + 20, this.g);
            this.b(w, i + 9, j + 20, k + 21, this.g);
            this.b(w, i + 9, j + 21, k + 19, this.g);
            this.b(w, i + 9, j + 21, k + 20, this.g);
            this.b(w, i + 9, j + 21, k + 21, this.g);
            this.b(w, i + 9, j + 22, k + 19, this.c, 4);
            this.b(w, i + 9, j + 22, k + 20, this.c, 4);
            this.b(w, i + 9, j + 22, k + 21, this.c, 4);
            this.b(w, i + 9, j + 23, k + 18, this.c, 4);
            this.b(w, i + 9, j + 23, k + 19, this.c, 4);
            this.b(w, i + 9, j + 23, k + 20, this.c, 4);
            this.b(w, i + 9, j + 23, k + 21, this.c, 4);
            this.b(w, i + 9, j + 23, k + 22, this.c, 4);
            this.b(w, i + 9, j + 24, k + 18, this.c, 4);
            this.b(w, i + 9, j + 24, k + 19, this.c, 4);
            this.b(w, i + 9, j + 24, k + 20, this.c, 4);
            this.b(w, i + 9, j + 24, k + 21, this.c, 4);
            this.b(w, i + 9, j + 24, k + 22, this.c, 4);
            this.b(w, i + 9, j + 25, k + 19, this.c, 4);
            this.b(w, i + 9, j + 25, k + 20, this.c, 4);
            this.b(w, i + 9, j + 25, k + 21, this.c, 4);
            this.b(w, i + 9, j + 26, k + 20, this.c, 4);
            this.b(w, i + 10, j + 0, k + 6, this.s);
            this.b(w, i + 10, j + 0, k + 7, this.c, 8);
            this.b(w, i + 10, j + 0, k + 8, this.c, 8);
            this.b(w, i + 10, j + 0, k + 9, this.c, 8);
            this.b(w, i + 10, j + 0, k + 10, this.c, 8);
            this.b(w, i + 10, j + 0, k + 11, this.c, 8);
            this.b(w, i + 10, j + 0, k + 12, this.c, 8);
            this.b(w, i + 10, j + 0, k + 13, this.c, 8);
            this.b(w, i + 10, j + 0, k + 14, this.c, 8);
            this.b(w, i + 10, j + 0, k + 15, this.c, 8);
            this.b(w, i + 10, j + 0, k + 16, this.c, 8);
            this.b(w, i + 10, j + 0, k + 17, this.c, 8);
            this.b(w, i + 10, j + 0, k + 18, this.c, 8);
            this.b(w, i + 10, j + 0, k + 19, this.c, 8);
            this.b(w, i + 10, j + 0, k + 20, this.c, 8);
            this.b(w, i + 10, j + 0, k + 21, this.c, 8);
            this.b(w, i + 10, j + 0, k + 22, this.c, 8);
            this.b(w, i + 10, j + 0, k + 23, this.c, 8);
            this.b(w, i + 10, j + 0, k + 24, this.c, 8);
            this.b(w, i + 10, j + 0, k + 25, this.c, 8);
            this.b(w, i + 10, j + 0, k + 26, this.c, 8);
            this.b(w, i + 10, j + 0, k + 27, this.c, 8);
            this.b(w, i + 10, j + 0, k + 28, this.c, 8);
            this.b(w, i + 10, j + 0, k + 29, this.s);
            this.b(w, i + 10, j + 1, k + 17, this.c, 4);
            this.b(w, i + 10, j + 1, k + 19, this.g);
            this.b(w, i + 10, j + 1, k + 20, this.g);
            this.b(w, i + 10, j + 1, k + 21, this.g);
            this.b(w, i + 10, j + 1, k + 23, this.c, 4);
            this.b(w, i + 10, j + 2, k + 17, this.c, 4);
            this.b(w, i + 10, j + 2, k + 18, this.c, 4);
            this.b(w, i + 10, j + 2, k + 19, this.g);
            this.b(w, i + 10, j + 2, k + 20, this.g);
            this.b(w, i + 10, j + 2, k + 21, this.g);
            this.b(w, i + 10, j + 2, k + 22, this.c, 4);
            this.b(w, i + 10, j + 2, k + 23, this.c, 4);
            this.b(w, i + 10, j + 3, k + 17, this.g);
            this.b(w, i + 10, j + 3, k + 18, this.g);
            this.b(w, i + 10, j + 3, k + 19, this.c, 5);
            this.b(w, i + 10, j + 3, k + 20, this.c, 5);
            this.b(w, i + 10, j + 3, k + 21, this.c, 5);
            this.b(w, i + 10, j + 3, k + 22, this.g);
            this.b(w, i + 10, j + 3, k + 23, this.g);
            this.b(w, i + 10, j + 4, k + 17, this.g);
            this.b(w, i + 10, j + 4, k + 18, this.g);
            this.b(w, i + 10, j + 4, k + 19, this.c, 5);
            this.b(w, i + 10, j + 4, k + 20, this.c, 5);
            this.b(w, i + 10, j + 4, k + 21, this.c, 5);
            this.b(w, i + 10, j + 4, k + 22, this.g);
            this.b(w, i + 10, j + 4, k + 23, this.g);
            this.b(w, i + 10, j + 5, k + 17, this.g);
            this.b(w, i + 10, j + 5, k + 18, this.c, 5);
            this.b(w, i + 10, j + 5, k + 19, this.c, 5);
            this.b(w, i + 10, j + 5, k + 20, this.c, 5);
            this.b(w, i + 10, j + 5, k + 21, this.c, 5);
            this.b(w, i + 10, j + 5, k + 22, this.c, 5);
            this.b(w, i + 10, j + 5, k + 23, this.g);
            this.b(w, i + 10, j + 6, k + 17, this.g);
            this.b(w, i + 10, j + 6, k + 18, this.g);
            this.b(w, i + 10, j + 6, k + 19, this.c, 5);
            this.b(w, i + 10, j + 6, k + 20, this.c, 5);
            this.b(w, i + 10, j + 6, k + 21, this.c, 5);
            this.b(w, i + 10, j + 6, k + 22, this.g);
            this.b(w, i + 10, j + 6, k + 23, this.g);
            this.b(w, i + 10, j + 7, k + 17, this.g);
            this.b(w, i + 10, j + 7, k + 18, this.g);
            this.b(w, i + 10, j + 7, k + 19, this.c, 5);
            this.b(w, i + 10, j + 7, k + 20, this.c, 5);
            this.b(w, i + 10, j + 7, k + 21, this.c, 5);
            this.b(w, i + 10, j + 7, k + 22, this.g);
            this.b(w, i + 10, j + 7, k + 23, this.g);
            this.b(w, i + 10, j + 8, k + 18, this.g);
            this.b(w, i + 10, j + 8, k + 19, this.g);
            this.b(w, i + 10, j + 8, k + 20, this.g);
            this.b(w, i + 10, j + 8, k + 21, this.g);
            this.b(w, i + 10, j + 8, k + 22, this.g);
            this.b(w, i + 10, j + 9, k + 19, this.g);
            this.b(w, i + 10, j + 9, k + 20, this.g);
            this.b(w, i + 10, j + 9, k + 21, this.g);
            this.b(w, i + 10, j + 15, k + 19, this.g);
            this.b(w, i + 10, j + 15, k + 20, this.g);
            this.b(w, i + 10, j + 15, k + 21, this.g);
            this.b(w, i + 10, j + 16, k + 18, this.g);
            this.b(w, i + 10, j + 16, k + 19, this.g);
            this.b(w, i + 10, j + 16, k + 20, this.g);
            this.b(w, i + 10, j + 16, k + 21, this.g);
            this.b(w, i + 10, j + 16, k + 22, this.g);
            this.b(w, i + 10, j + 17, k + 17, this.g);
            this.b(w, i + 10, j + 17, k + 18, this.g);
            this.b(w, i + 10, j + 17, k + 22, this.g);
            this.b(w, i + 10, j + 17, k + 23, this.g);
            this.b(w, i + 10, j + 18, k + 17, this.g);
            this.b(w, i + 10, j + 18, k + 18, this.g);
            this.b(w, i + 10, j + 18, k + 22, this.g);
            this.b(w, i + 10, j + 18, k + 23, this.g);
            this.b(w, i + 10, j + 19, k + 17, this.g);
            this.b(w, i + 10, j + 19, k + 23, this.g);
            this.b(w, i + 10, j + 20, k + 17, this.g);
            this.b(w, i + 10, j + 20, k + 18, this.g);
            this.b(w, i + 10, j + 20, k + 22, this.g);
            this.b(w, i + 10, j + 20, k + 23, this.g);
            this.b(w, i + 10, j + 21, k + 17, this.g);
            this.b(w, i + 10, j + 21, k + 18, this.g);
            this.b(w, i + 10, j + 21, k + 22, this.g);
            this.b(w, i + 10, j + 21, k + 23, this.g);
            this.b(w, i + 10, j + 22, k + 17, this.c, 4);
            this.b(w, i + 10, j + 22, k + 18, this.c, 4);
            this.b(w, i + 10, j + 22, k + 19, this.g);
            this.b(w, i + 10, j + 22, k + 20, this.g);
            this.b(w, i + 10, j + 22, k + 21, this.g);
            this.b(w, i + 10, j + 22, k + 22, this.c, 4);
            this.b(w, i + 10, j + 22, k + 23, this.c, 4);
            this.b(w, i + 10, j + 23, k + 17, this.c, 4);
            this.b(w, i + 10, j + 23, k + 19, this.g);
            this.b(w, i + 10, j + 23, k + 20, this.g);
            this.b(w, i + 10, j + 23, k + 21, this.g);
            this.b(w, i + 10, j + 23, k + 23, this.c, 4);
            this.b(w, i + 10, j + 24, k + 17, this.c, 4);
            this.b(w, i + 10, j + 24, k + 23, this.c, 4);
            this.b(w, i + 10, j + 25, k + 17, this.c, 4);
            this.b(w, i + 10, j + 25, k + 18, this.c, 4);
            this.b(w, i + 10, j + 25, k + 22, this.c, 4);
            this.b(w, i + 10, j + 25, k + 23, this.c, 4);
            this.b(w, i + 10, j + 26, k + 18, this.c, 4);
            this.b(w, i + 10, j + 26, k + 19, this.c, 4);
            this.b(w, i + 10, j + 26, k + 21, this.c, 4);
            this.b(w, i + 10, j + 26, k + 22, this.c, 4);
            this.b(w, i + 10, j + 27, k + 19, this.c, 4);
            this.b(w, i + 10, j + 27, k + 20, this.c, 4);
            this.b(w, i + 10, j + 27, k + 21, this.c, 4);
            this.b(w, i + 11, j + 0, k + 6, this.s);
            this.b(w, i + 11, j + 0, k + 7, this.c, 8);
            this.b(w, i + 11, j + 0, k + 8, this.c, 8);
            this.b(w, i + 11, j + 0, k + 9, this.c, 8);
            this.b(w, i + 11, j + 0, k + 10, this.c, 8);
            this.b(w, i + 11, j + 0, k + 11, this.c, 8);
            this.b(w, i + 11, j + 0, k + 12, this.c, 8);
            this.b(w, i + 11, j + 0, k + 13, this.c, 8);
            this.b(w, i + 11, j + 0, k + 14, this.c, 8);
            this.b(w, i + 11, j + 0, k + 15, this.c, 8);
            this.b(w, i + 11, j + 0, k + 16, this.c, 8);
            this.b(w, i + 11, j + 0, k + 17, this.c, 8);
            this.b(w, i + 11, j + 0, k + 18, this.c, 8);
            this.b(w, i + 11, j + 0, k + 19, this.c, 8);
            this.b(w, i + 11, j + 0, k + 20, this.c, 8);
            this.b(w, i + 11, j + 0, k + 21, this.c, 8);
            this.b(w, i + 11, j + 0, k + 22, this.c, 8);
            this.b(w, i + 11, j + 0, k + 23, this.c, 8);
            this.b(w, i + 11, j + 0, k + 24, this.c, 8);
            this.b(w, i + 11, j + 0, k + 25, this.c, 8);
            this.b(w, i + 11, j + 0, k + 26, this.c, 8);
            this.b(w, i + 11, j + 0, k + 27, this.c, 8);
            this.b(w, i + 11, j + 0, k + 28, this.c, 8);
            this.b(w, i + 11, j + 0, k + 29, this.s);
            this.b(w, i + 11, j + 1, k + 16, this.c, 4);
            this.b(w, i + 11, j + 1, k + 18, this.g);
            this.b(w, i + 11, j + 1, k + 22, this.g);
            this.b(w, i + 11, j + 1, k + 24, this.c, 4);
            this.b(w, i + 11, j + 2, k + 17, this.c, 4);
            this.b(w, i + 11, j + 2, k + 18, this.c, 5);
            this.b(w, i + 11, j + 2, k + 19, this.c, 5);
            this.b(w, i + 11, j + 2, k + 20, this.c, 5);
            this.b(w, i + 11, j + 2, k + 21, this.c, 5);
            this.b(w, i + 11, j + 2, k + 22, this.c, 5);
            this.b(w, i + 11, j + 2, k + 23, this.c, 4);
            this.b(w, i + 11, j + 3, k + 17, this.g);
            this.b(w, i + 11, j + 3, k + 18, this.c, 5);
            this.b(w, i + 11, j + 3, k + 19, this.c, 5);
            this.b(w, i + 11, j + 3, k + 20, this.c, 5);
            this.b(w, i + 11, j + 3, k + 21, this.c, 5);
            this.b(w, i + 11, j + 3, k + 22, this.c, 5);
            this.b(w, i + 11, j + 3, k + 23, this.g);
            this.b(w, i + 11, j + 4, k + 17, this.g);
            this.b(w, i + 11, j + 4, k + 18, this.c, 5);
            this.b(w, i + 11, j + 4, k + 19, this.c, 5);
            this.b(w, i + 11, j + 4, k + 20, this.c, 5);
            this.b(w, i + 11, j + 4, k + 21, this.c, 5);
            this.b(w, i + 11, j + 4, k + 22, this.c, 5);
            this.b(w, i + 11, j + 4, k + 23, this.g);
            this.b(w, i + 11, j + 5, k + 16, this.g);
            this.b(w, i + 11, j + 5, k + 17, this.c, 5);
            this.b(w, i + 11, j + 5, k + 18, this.c, 5);
            this.b(w, i + 11, j + 5, k + 19, this.c, 5);
            this.b(w, i + 11, j + 5, k + 20, this.c, 5);
            this.b(w, i + 11, j + 5, k + 21, this.c, 5);
            this.b(w, i + 11, j + 5, k + 22, this.c, 5);
            this.b(w, i + 11, j + 5, k + 23, this.c, 5);
            this.b(w, i + 11, j + 5, k + 24, this.g);
            this.b(w, i + 11, j + 6, k + 17, this.g);
            this.b(w, i + 11, j + 6, k + 18, this.c, 5);
            this.b(w, i + 11, j + 6, k + 19, this.c, 5);
            this.b(w, i + 11, j + 6, k + 20, this.c, 5);
            this.b(w, i + 11, j + 6, k + 21, this.c, 5);
            this.b(w, i + 11, j + 6, k + 22, this.c, 5);
            this.b(w, i + 11, j + 6, k + 23, this.g);
            this.b(w, i + 11, j + 7, k + 17, this.g);
            this.b(w, i + 11, j + 7, k + 18, this.c, 5);
            this.b(w, i + 11, j + 7, k + 19, this.c, 5);
            this.b(w, i + 11, j + 7, k + 20, this.c, 5);
            this.b(w, i + 11, j + 7, k + 21, this.c, 5);
            this.b(w, i + 11, j + 7, k + 22, this.c, 5);
            this.b(w, i + 11, j + 7, k + 23, this.g);
            this.b(w, i + 11, j + 8, k + 17, this.g);
            this.b(w, i + 11, j + 8, k + 18, this.c, 5);
            this.b(w, i + 11, j + 8, k + 19, this.c, 5);
            this.b(w, i + 11, j + 8, k + 20, this.c, 5);
            this.b(w, i + 11, j + 8, k + 21, this.c, 5);
            this.b(w, i + 11, j + 8, k + 22, this.c, 5);
            this.b(w, i + 11, j + 8, k + 23, this.g);
            this.b(w, i + 11, j + 9, k + 18, this.g);
            this.b(w, i + 11, j + 9, k + 19, this.c, 5);
            this.b(w, i + 11, j + 9, k + 20, this.c, 5);
            this.b(w, i + 11, j + 9, k + 21, this.c, 5);
            this.b(w, i + 11, j + 9, k + 22, this.g);
            this.b(w, i + 11, j + 10, k + 18, this.g);
            this.b(w, i + 11, j + 10, k + 19, this.g);
            this.b(w, i + 11, j + 10, k + 20, this.g);
            this.b(w, i + 11, j + 10, k + 21, this.g);
            this.b(w, i + 11, j + 10, k + 22, this.g);
            this.b(w, i + 11, j + 14, k + 18, this.g);
            this.b(w, i + 11, j + 14, k + 19, this.g);
            this.b(w, i + 11, j + 14, k + 20, this.g);
            this.b(w, i + 11, j + 14, k + 21, this.g);
            this.b(w, i + 11, j + 14, k + 22, this.g);
            this.b(w, i + 11, j + 15, k + 18, this.g);
            this.b(w, i + 11, j + 15, k + 19, this.c, 5);
            this.b(w, i + 11, j + 15, k + 20, this.c, 5);
            this.b(w, i + 11, j + 15, k + 21, this.c, 5);
            this.b(w, i + 11, j + 15, k + 22, this.g);
            this.b(w, i + 11, j + 16, k + 17, this.g);
            this.b(w, i + 11, j + 16, k + 23, this.g);
            this.b(w, i + 11, j + 17, k + 17, this.g);
            this.b(w, i + 11, j + 17, k + 23, this.g);
            this.b(w, i + 11, j + 18, k + 17, this.g);
            this.b(w, i + 11, j + 18, k + 23, this.g);
            this.b(w, i + 11, j + 19, k + 16, this.g);
            this.b(w, i + 11, j + 19, k + 24, this.g);
            this.b(w, i + 11, j + 20, k + 17, this.g);
            this.b(w, i + 11, j + 20, k + 23, this.g);
            this.b(w, i + 11, j + 21, k + 17, this.g);
            this.b(w, i + 11, j + 21, k + 23, this.g);
            this.b(w, i + 11, j + 22, k + 17, this.c, 4);
            this.b(w, i + 11, j + 22, k + 23, this.c, 4);
            this.b(w, i + 11, j + 23, k + 16, this.c, 4);
            this.b(w, i + 11, j + 23, k + 18, this.g);
            this.b(w, i + 11, j + 23, k + 22, this.g);
            this.b(w, i + 11, j + 23, k + 24, this.c, 4);
            this.b(w, i + 11, j + 24, k + 16, this.c, 4);
            this.b(w, i + 11, j + 24, k + 24, this.c, 4);
            this.b(w, i + 11, j + 25, k + 17, this.c, 4);
            this.b(w, i + 11, j + 25, k + 23, this.c, 4);
            this.b(w, i + 11, j + 26, k + 17, this.c, 4);
            this.b(w, i + 11, j + 26, k + 23, this.c, 4);
            this.b(w, i + 11, j + 27, k + 18, this.c, 4);
            this.b(w, i + 11, j + 27, k + 19, this.c, 4);
            this.b(w, i + 11, j + 27, k + 21, this.c, 4);
            this.b(w, i + 11, j + 27, k + 22, this.c, 4);
            this.b(w, i + 11, j + 28, k + 20, this.c, 4);
            this.b(w, i + 12, j + 0, k + 6, this.s);
            this.b(w, i + 12, j + 0, k + 7, this.c, 8);
            this.b(w, i + 12, j + 0, k + 8, this.c, 8);
            this.b(w, i + 12, j + 0, k + 9, this.c, 8);
            this.b(w, i + 12, j + 0, k + 10, this.c, 8);
            this.b(w, i + 12, j + 0, k + 11, this.c, 8);
            this.b(w, i + 12, j + 0, k + 12, this.c, 8);
            this.b(w, i + 12, j + 0, k + 13, this.c, 8);
            this.b(w, i + 12, j + 0, k + 14, this.c, 8);
            this.b(w, i + 12, j + 0, k + 15, this.c, 8);
            this.b(w, i + 12, j + 0, k + 16, this.c, 8);
            this.b(w, i + 12, j + 0, k + 17, this.c, 8);
            this.b(w, i + 12, j + 0, k + 18, this.c, 8);
            this.b(w, i + 12, j + 0, k + 19, this.c, 8);
            this.b(w, i + 12, j + 0, k + 20, this.c, 8);
            this.b(w, i + 12, j + 0, k + 21, this.c, 8);
            this.b(w, i + 12, j + 0, k + 22, this.c, 8);
            this.b(w, i + 12, j + 0, k + 23, this.c, 8);
            this.b(w, i + 12, j + 0, k + 24, this.c, 8);
            this.b(w, i + 12, j + 0, k + 25, this.c, 8);
            this.b(w, i + 12, j + 0, k + 26, this.c, 8);
            this.b(w, i + 12, j + 0, k + 27, this.c, 8);
            this.b(w, i + 12, j + 0, k + 28, this.c, 8);
            this.b(w, i + 12, j + 0, k + 29, this.s);
            this.b(w, i + 12, j + 1, k + 16, this.c, 4);
            this.b(w, i + 12, j + 1, k + 17, this.g);
            this.b(w, i + 12, j + 1, k + 23, this.g);
            this.b(w, i + 12, j + 1, k + 24, this.c, 4);
            this.b(w, i + 12, j + 2, k + 16, this.c, 4);
            this.b(w, i + 12, j + 2, k + 17, this.g);
            this.b(w, i + 12, j + 2, k + 18, this.c, 5);
            this.b(w, i + 12, j + 2, k + 19, this.c, 5);
            this.b(w, i + 12, j + 2, k + 20, this.c, 5);
            this.b(w, i + 12, j + 2, k + 21, this.c, 5);
            this.b(w, i + 12, j + 2, k + 22, this.c, 5);
            this.b(w, i + 12, j + 2, k + 23, this.g);
            this.b(w, i + 12, j + 2, k + 24, this.c, 4);
            this.b(w, i + 12, j + 3, k + 16, this.g);
            this.b(w, i + 12, j + 3, k + 17, this.c, 5);
            this.b(w, i + 12, j + 3, k + 18, this.c, 5);
            this.b(w, i + 12, j + 3, k + 19, this.c, 5);
            this.b(w, i + 12, j + 3, k + 20, this.c, 5);
            this.b(w, i + 12, j + 3, k + 21, this.c, 5);
            this.b(w, i + 12, j + 3, k + 22, this.c, 5);
            this.b(w, i + 12, j + 3, k + 23, this.c, 5);
            this.b(w, i + 12, j + 3, k + 24, this.g);
            this.b(w, i + 12, j + 4, k + 16, this.g);
            this.b(w, i + 12, j + 4, k + 17, this.c, 5);
            this.b(w, i + 12, j + 4, k + 18, this.c, 5);
            this.b(w, i + 12, j + 4, k + 19, this.c, 5);
            this.b(w, i + 12, j + 4, k + 20, this.c, 5);
            this.b(w, i + 12, j + 4, k + 21, this.c, 5);
            this.b(w, i + 12, j + 4, k + 22, this.c, 5);
            this.b(w, i + 12, j + 4, k + 23, this.c, 5);
            this.b(w, i + 12, j + 4, k + 24, this.g);
            this.b(w, i + 12, j + 5, k + 16, this.g);
            this.b(w, i + 12, j + 5, k + 17, this.c, 5);
            this.b(w, i + 12, j + 5, k + 18, this.c, 5);
            this.b(w, i + 12, j + 5, k + 19, this.c, 5);
            this.b(w, i + 12, j + 5, k + 20, this.c, 5);
            this.b(w, i + 12, j + 5, k + 21, this.c, 5);
            this.b(w, i + 12, j + 5, k + 22, this.c, 5);
            this.b(w, i + 12, j + 5, k + 23, this.c, 5);
            this.b(w, i + 12, j + 5, k + 24, this.g);
            this.b(w, i + 12, j + 6, k + 16, this.g);
            this.b(w, i + 12, j + 6, k + 17, this.c, 5);
            this.b(w, i + 12, j + 6, k + 18, this.c, 5);
            this.b(w, i + 12, j + 6, k + 19, this.c, 5);
            this.b(w, i + 12, j + 6, k + 20, this.c, 5);
            this.b(w, i + 12, j + 6, k + 21, this.c, 5);
            this.b(w, i + 12, j + 6, k + 22, this.c, 5);
            this.b(w, i + 12, j + 6, k + 23, this.c, 5);
            this.b(w, i + 12, j + 6, k + 24, this.g);
            this.b(w, i + 12, j + 7, k + 16, this.g);
            this.b(w, i + 12, j + 7, k + 17, this.c, 5);
            this.b(w, i + 12, j + 7, k + 18, this.c, 5);
            this.b(w, i + 12, j + 7, k + 19, this.c, 5);
            this.b(w, i + 12, j + 7, k + 20, this.c, 5);
            this.b(w, i + 12, j + 7, k + 21, this.c, 5);
            this.b(w, i + 12, j + 7, k + 22, this.c, 5);
            this.b(w, i + 12, j + 7, k + 23, this.c, 5);
            this.b(w, i + 12, j + 7, k + 24, this.g);
            this.b(w, i + 12, j + 8, k + 17, this.g);
            this.b(w, i + 12, j + 8, k + 18, this.c, 5);
            this.b(w, i + 12, j + 8, k + 19, this.c, 5);
            this.b(w, i + 12, j + 8, k + 20, this.c, 5);
            this.b(w, i + 12, j + 8, k + 21, this.c, 5);
            this.b(w, i + 12, j + 8, k + 22, this.c, 5);
            this.b(w, i + 12, j + 8, k + 23, this.g);
            this.b(w, i + 12, j + 9, k + 17, this.g);
            this.b(w, i + 12, j + 9, k + 18, this.c, 5);
            this.b(w, i + 12, j + 9, k + 19, this.c, 5);
            this.b(w, i + 12, j + 9, k + 20, this.c, 5);
            this.b(w, i + 12, j + 9, k + 21, this.c, 5);
            this.b(w, i + 12, j + 9, k + 22, this.c, 5);
            this.b(w, i + 12, j + 9, k + 23, this.g);
            this.b(w, i + 12, j + 10, k + 18, this.g);
            this.b(w, i + 12, j + 10, k + 22, this.g);
            this.b(w, i + 12, j + 11, k + 19, this.g);
            this.b(w, i + 12, j + 11, k + 20, this.g);
            this.b(w, i + 12, j + 11, k + 21, this.g);
            this.b(w, i + 12, j + 12, k + 19, this.g);
            this.b(w, i + 12, j + 12, k + 20, this.g);
            this.b(w, i + 12, j + 12, k + 21, this.g);
            this.b(w, i + 12, j + 13, k + 19, this.g);
            this.b(w, i + 12, j + 13, k + 20, this.g);
            this.b(w, i + 12, j + 13, k + 21, this.g);
            this.b(w, i + 12, j + 14, k + 18, this.g);
            this.b(w, i + 12, j + 14, k + 19, this.c, 5);
            this.b(w, i + 12, j + 14, k + 20, this.c, 5);
            this.b(w, i + 12, j + 14, k + 21, this.c, 5);
            this.b(w, i + 12, j + 14, k + 22, this.g);
            this.b(w, i + 12, j + 15, k + 17, this.g);
            this.b(w, i + 12, j + 15, k + 18, this.c, 5);
            this.b(w, i + 12, j + 15, k + 19, this.c, 5);
            this.b(w, i + 12, j + 15, k + 20, this.c, 5);
            this.b(w, i + 12, j + 15, k + 21, this.c, 5);
            this.b(w, i + 12, j + 15, k + 22, this.c, 5);
            this.b(w, i + 12, j + 15, k + 23, this.g);
            this.b(w, i + 12, j + 16, k + 17, this.g);
            this.b(w, i + 12, j + 16, k + 23, this.g);
            this.b(w, i + 12, j + 17, k + 16, this.g);
            this.b(w, i + 12, j + 17, k + 24, this.g);
            this.b(w, i + 12, j + 18, k + 16, this.g);
            this.b(w, i + 12, j + 18, k + 24, this.g);
            this.b(w, i + 12, j + 19, k + 16, this.g);
            this.b(w, i + 12, j + 19, k + 24, this.g);
            this.b(w, i + 12, j + 20, k + 16, this.g);
            this.b(w, i + 12, j + 20, k + 24, this.g);
            this.b(w, i + 12, j + 21, k + 16, this.g);
            this.b(w, i + 12, j + 21, k + 24, this.g);
            this.b(w, i + 12, j + 22, k + 16, this.c, 4);
            this.b(w, i + 12, j + 22, k + 17, this.g);
            this.b(w, i + 12, j + 22, k + 23, this.g);
            this.b(w, i + 12, j + 22, k + 24, this.c, 4);
            this.b(w, i + 12, j + 23, k + 16, this.c, 4);
            this.b(w, i + 12, j + 23, k + 17, this.g);
            this.b(w, i + 12, j + 23, k + 23, this.g);
            this.b(w, i + 12, j + 23, k + 24, this.c, 4);
            this.b(w, i + 12, j + 24, k + 16, this.c, 4);
            this.b(w, i + 12, j + 24, k + 24, this.c, 4);
            this.b(w, i + 12, j + 25, k + 16, this.c, 4);
            this.b(w, i + 12, j + 25, k + 24, this.c, 4);
            this.b(w, i + 12, j + 26, k + 17, this.c, 4);
            this.b(w, i + 12, j + 26, k + 23, this.c, 4);
            this.b(w, i + 12, j + 27, k + 17, this.c, 4);
            this.b(w, i + 12, j + 27, k + 18, this.c, 4);
            this.b(w, i + 12, j + 27, k + 22, this.c, 4);
            this.b(w, i + 12, j + 27, k + 23, this.c, 4);
            this.b(w, i + 12, j + 28, k + 19, this.c, 4);
            this.b(w, i + 12, j + 28, k + 20, this.c, 4);
            this.b(w, i + 12, j + 28, k + 21, this.c, 4);
            this.b(w, i + 13, j + 0, k + 6, this.s);
            this.b(w, i + 13, j + 0, k + 7, this.c, 8);
            this.b(w, i + 13, j + 0, k + 8, this.c, 8);
            this.b(w, i + 13, j + 0, k + 9, this.c, 8);
            this.b(w, i + 13, j + 0, k + 10, this.c, 8);
            this.b(w, i + 13, j + 0, k + 11, this.c, 8);
            this.b(w, i + 13, j + 0, k + 12, this.c, 8);
            this.b(w, i + 13, j + 0, k + 13, this.c, 8);
            this.b(w, i + 13, j + 0, k + 14, this.c, 8);
            this.b(w, i + 13, j + 0, k + 15, this.c, 8);
            this.b(w, i + 13, j + 0, k + 16, this.c, 8);
            this.b(w, i + 13, j + 0, k + 17, this.c, 8);
            this.b(w, i + 13, j + 0, k + 18, this.c, 8);
            this.b(w, i + 13, j + 0, k + 19, this.c, 8);
            this.b(w, i + 13, j + 0, k + 20, this.c, 8);
            this.b(w, i + 13, j + 0, k + 21, this.c, 8);
            this.b(w, i + 13, j + 0, k + 22, this.c, 8);
            this.b(w, i + 13, j + 0, k + 23, this.c, 8);
            this.b(w, i + 13, j + 0, k + 24, this.c, 8);
            this.b(w, i + 13, j + 0, k + 25, this.c, 8);
            this.b(w, i + 13, j + 0, k + 26, this.c, 8);
            this.b(w, i + 13, j + 0, k + 27, this.c, 8);
            this.b(w, i + 13, j + 0, k + 28, this.c, 8);
            this.b(w, i + 13, j + 0, k + 29, this.s);
            this.b(w, i + 13, j + 1, k + 16, this.c, 4);
            this.b(w, i + 13, j + 1, k + 17, this.g);
            this.b(w, i + 13, j + 1, k + 23, this.g);
            this.b(w, i + 13, j + 1, k + 24, this.c, 4);
            this.b(w, i + 13, j + 2, k + 16, this.c, 4);
            this.b(w, i + 13, j + 2, k + 17, this.g);
            this.b(w, i + 13, j + 2, k + 18, this.c, 5);
            this.b(w, i + 13, j + 2, k + 19, this.c, 5);
            this.b(w, i + 13, j + 2, k + 20, this.c, 5);
            this.b(w, i + 13, j + 2, k + 21, this.c, 5);
            this.b(w, i + 13, j + 2, k + 22, this.c, 5);
            this.b(w, i + 13, j + 2, k + 23, this.g);
            this.b(w, i + 13, j + 2, k + 24, this.c, 4);
            this.b(w, i + 13, j + 3, k + 16, this.g);
            this.b(w, i + 13, j + 3, k + 17, this.c, 5);
            this.b(w, i + 13, j + 3, k + 18, this.c, 5);
            this.b(w, i + 13, j + 3, k + 19, this.c, 5);
            this.b(w, i + 13, j + 3, k + 20, this.c, 5);
            this.b(w, i + 13, j + 3, k + 21, this.c, 5);
            this.b(w, i + 13, j + 3, k + 22, this.c, 5);
            this.b(w, i + 13, j + 3, k + 23, this.c, 5);
            this.b(w, i + 13, j + 3, k + 24, this.g);
            this.b(w, i + 13, j + 4, k + 16, this.g);
            this.b(w, i + 13, j + 4, k + 17, this.c, 5);
            this.b(w, i + 13, j + 4, k + 18, this.c, 5);
            this.b(w, i + 13, j + 4, k + 19, this.c, 5);
            this.b(w, i + 13, j + 4, k + 20, this.c, 5);
            this.b(w, i + 13, j + 4, k + 21, this.c, 5);
            this.b(w, i + 13, j + 4, k + 22, this.c, 5);
            this.b(w, i + 13, j + 4, k + 23, this.c, 5);
            this.b(w, i + 13, j + 4, k + 24, this.g);
            this.b(w, i + 13, j + 5, k + 16, this.g);
            this.b(w, i + 13, j + 5, k + 17, this.c, 5);
            this.b(w, i + 13, j + 5, k + 18, this.c, 5);
            this.b(w, i + 13, j + 5, k + 19, this.c, 5);
            this.b(w, i + 13, j + 5, k + 20, this.c, 5);
            this.b(w, i + 13, j + 5, k + 21, this.c, 5);
            this.b(w, i + 13, j + 5, k + 22, this.c, 5);
            this.b(w, i + 13, j + 5, k + 23, this.c, 5);
            this.b(w, i + 13, j + 5, k + 24, this.g);
            this.b(w, i + 13, j + 6, k + 16, this.g);
            this.b(w, i + 13, j + 6, k + 17, this.c, 5);
            this.b(w, i + 13, j + 6, k + 18, this.c, 5);
            this.b(w, i + 13, j + 6, k + 19, this.c, 5);
            this.b(w, i + 13, j + 6, k + 20, this.c, 5);
            this.b(w, i + 13, j + 6, k + 21, this.c, 5);
            this.b(w, i + 13, j + 6, k + 22, this.c, 5);
            this.b(w, i + 13, j + 6, k + 23, this.c, 5);
            this.b(w, i + 13, j + 6, k + 24, this.g);
            this.b(w, i + 13, j + 7, k + 16, this.g);
            this.b(w, i + 13, j + 7, k + 17, this.c, 5);
            this.b(w, i + 13, j + 7, k + 18, this.c, 5);
            this.b(w, i + 13, j + 7, k + 19, this.c, 5);
            this.b(w, i + 13, j + 7, k + 20, this.c, 5);
            this.b(w, i + 13, j + 7, k + 21, this.c, 5);
            this.b(w, i + 13, j + 7, k + 22, this.c, 5);
            this.b(w, i + 13, j + 7, k + 23, this.c, 5);
            this.b(w, i + 13, j + 7, k + 24, this.g);
            this.b(w, i + 13, j + 8, k + 17, this.g);
            this.b(w, i + 13, j + 8, k + 18, this.c, 5);
            this.b(w, i + 13, j + 8, k + 19, this.c, 5);
            this.b(w, i + 13, j + 8, k + 20, this.c, 5);
            this.b(w, i + 13, j + 8, k + 21, this.c, 5);
            this.b(w, i + 13, j + 8, k + 22, this.c, 5);
            this.b(w, i + 13, j + 8, k + 23, this.g);
            this.b(w, i + 13, j + 9, k + 17, this.g);
            this.b(w, i + 13, j + 9, k + 18, this.c, 5);
            this.b(w, i + 13, j + 9, k + 19, this.c, 5);
            this.b(w, i + 13, j + 9, k + 20, this.c, 5);
            this.b(w, i + 13, j + 9, k + 21, this.c, 5);
            this.b(w, i + 13, j + 9, k + 22, this.c, 5);
            this.b(w, i + 13, j + 9, k + 23, this.g);
            this.b(w, i + 13, j + 10, k + 18, this.g);
            this.b(w, i + 13, j + 10, k + 20, this.c, 5);
            this.b(w, i + 13, j + 10, k + 22, this.g);
            this.b(w, i + 13, j + 11, k + 19, this.g);
            this.b(w, i + 13, j + 11, k + 20, this.c, 5);
            this.b(w, i + 13, j + 11, k + 21, this.g);
            this.b(w, i + 13, j + 12, k + 19, this.g);
            this.b(w, i + 13, j + 12, k + 20, this.c, 5);
            this.b(w, i + 13, j + 12, k + 21, this.g);
            this.b(w, i + 13, j + 13, k + 19, this.g);
            this.b(w, i + 13, j + 13, k + 20, this.c, 5);
            this.b(w, i + 13, j + 13, k + 21, this.g);
            this.b(w, i + 13, j + 14, k + 18, this.g);
            this.b(w, i + 13, j + 14, k + 19, this.c, 5);
            this.b(w, i + 13, j + 14, k + 20, this.c, 5);
            this.b(w, i + 13, j + 14, k + 21, this.c, 5);
            this.b(w, i + 13, j + 14, k + 22, this.g);
            this.b(w, i + 13, j + 15, k + 17, this.g);
            this.b(w, i + 13, j + 15, k + 18, this.c, 5);
            this.b(w, i + 13, j + 15, k + 19, this.c, 5);
            this.b(w, i + 13, j + 15, k + 20, this.c, 5);
            this.b(w, i + 13, j + 15, k + 21, this.c, 5);
            this.b(w, i + 13, j + 15, k + 22, this.c, 5);
            this.b(w, i + 13, j + 15, k + 23, this.g);
            this.b(w, i + 13, j + 16, k + 17, this.g);
            this.b(w, i + 13, j + 16, k + 23, this.g);
            this.b(w, i + 13, j + 17, k + 16, this.g);
            this.b(w, i + 13, j + 17, k + 24, this.g);
            this.b(w, i + 13, j + 18, k + 16, this.g);
            this.b(w, i + 13, j + 18, k + 24, this.g);
            this.b(w, i + 13, j + 19, k + 16, this.g);
            this.b(w, i + 13, j + 19, k + 24, this.g);
            this.b(w, i + 13, j + 20, k + 16, this.g);
            this.b(w, i + 13, j + 20, k + 24, this.g);
            this.b(w, i + 13, j + 21, k + 16, this.g);
            this.b(w, i + 13, j + 21, k + 24, this.g);
            this.b(w, i + 13, j + 22, k + 16, this.c, 4);
            this.b(w, i + 13, j + 22, k + 17, this.g);
            this.b(w, i + 13, j + 22, k + 23, this.g);
            this.b(w, i + 13, j + 22, k + 24, this.c, 4);
            this.b(w, i + 13, j + 23, k + 16, this.c, 4);
            this.b(w, i + 13, j + 23, k + 17, this.g);
            this.b(w, i + 13, j + 23, k + 23, this.g);
            this.b(w, i + 13, j + 23, k + 24, this.c, 4);
            this.b(w, i + 13, j + 24, k + 16, this.c, 4);
            this.b(w, i + 13, j + 24, k + 24, this.c, 4);
            this.b(w, i + 13, j + 25, k + 16, this.c, 4);
            this.b(w, i + 13, j + 25, k + 24, this.c, 4);
            this.b(w, i + 13, j + 26, k + 16, this.c, 4);
            this.b(w, i + 13, j + 26, k + 24, this.c, 4);
            this.b(w, i + 13, j + 27, k + 17, this.c, 4);
            this.b(w, i + 13, j + 27, k + 23, this.c, 4);
            this.b(w, i + 13, j + 28, k + 18, this.c, 4);
            this.b(w, i + 13, j + 28, k + 19, this.c, 4);
            this.b(w, i + 13, j + 28, k + 20, this.c, 4);
            this.b(w, i + 13, j + 28, k + 21, this.c, 4);
            this.b(w, i + 13, j + 28, k + 22, this.c, 4);
            this.b(w, i + 13, j + 29, k + 20, this.c, 4);
            this.b(w, i + 13, j + 30, k + 20, this.c, 4);
            this.b(w, i + 14, j + 0, k + 6, this.s);
            this.b(w, i + 14, j + 0, k + 7, this.c, 8);
            this.b(w, i + 14, j + 0, k + 8, this.c, 8);
            this.b(w, i + 14, j + 0, k + 9, this.c, 8);
            this.b(w, i + 14, j + 0, k + 10, this.c, 8);
            this.b(w, i + 14, j + 0, k + 11, this.c, 8);
            this.b(w, i + 14, j + 0, k + 12, this.c, 8);
            this.b(w, i + 14, j + 0, k + 13, this.c, 8);
            this.b(w, i + 14, j + 0, k + 14, this.c, 8);
            this.b(w, i + 14, j + 0, k + 15, this.c, 8);
            this.b(w, i + 14, j + 0, k + 16, this.c, 8);
            this.b(w, i + 14, j + 0, k + 17, this.c, 8);
            this.b(w, i + 14, j + 0, k + 18, this.c, 8);
            this.b(w, i + 14, j + 0, k + 19, this.c, 8);
            this.b(w, i + 14, j + 0, k + 20, this.c, 8);
            this.b(w, i + 14, j + 0, k + 21, this.c, 8);
            this.b(w, i + 14, j + 0, k + 22, this.c, 8);
            this.b(w, i + 14, j + 0, k + 23, this.c, 8);
            this.b(w, i + 14, j + 0, k + 24, this.c, 8);
            this.b(w, i + 14, j + 0, k + 25, this.c, 8);
            this.b(w, i + 14, j + 0, k + 26, this.c, 8);
            this.b(w, i + 14, j + 0, k + 27, this.c, 8);
            this.b(w, i + 14, j + 0, k + 28, this.c, 8);
            this.b(w, i + 14, j + 0, k + 29, this.s);
            this.b(w, i + 14, j + 1, k + 16, this.c, 4);
            this.b(w, i + 14, j + 1, k + 17, this.g);
            this.b(w, i + 14, j + 1, k + 23, this.g);
            this.b(w, i + 14, j + 1, k + 24, this.c, 4);
            this.b(w, i + 14, j + 2, k + 16, this.c, 4);
            this.b(w, i + 14, j + 2, k + 17, this.g);
            this.b(w, i + 14, j + 2, k + 18, this.c, 5);
            this.b(w, i + 14, j + 2, k + 19, this.c, 5);
            this.b(w, i + 14, j + 2, k + 20, this.c, 5);
            this.b(w, i + 14, j + 2, k + 21, this.c, 5);
            this.b(w, i + 14, j + 2, k + 22, this.c, 5);
            this.b(w, i + 14, j + 2, k + 23, this.g);
            this.b(w, i + 14, j + 2, k + 24, this.c, 4);
            this.b(w, i + 14, j + 3, k + 16, this.g);
            this.b(w, i + 14, j + 3, k + 17, this.c, 5);
            this.b(w, i + 14, j + 3, k + 18, this.c, 5);
            this.b(w, i + 14, j + 3, k + 19, this.c, 5);
            this.b(w, i + 14, j + 3, k + 20, this.c, 5);
            this.b(w, i + 14, j + 3, k + 21, this.c, 5);
            this.b(w, i + 14, j + 3, k + 22, this.c, 5);
            this.b(w, i + 14, j + 3, k + 23, this.c, 5);
            this.b(w, i + 14, j + 3, k + 24, this.g);
            this.b(w, i + 14, j + 4, k + 16, this.g);
            this.b(w, i + 14, j + 4, k + 17, this.c, 5);
            this.b(w, i + 14, j + 4, k + 18, this.c, 5);
            this.b(w, i + 14, j + 4, k + 19, this.c, 5);
            this.b(w, i + 14, j + 4, k + 20, this.c, 5);
            this.b(w, i + 14, j + 4, k + 21, this.c, 5);
            this.b(w, i + 14, j + 4, k + 22, this.c, 5);
            this.b(w, i + 14, j + 4, k + 23, this.c, 5);
            this.b(w, i + 14, j + 4, k + 24, this.g);
            this.b(w, i + 14, j + 5, k + 16, this.g);
            this.b(w, i + 14, j + 5, k + 17, this.c, 5);
            this.b(w, i + 14, j + 5, k + 18, this.c, 5);
            this.b(w, i + 14, j + 5, k + 19, this.c, 5);
            this.b(w, i + 14, j + 5, k + 20, this.c, 5);
            this.b(w, i + 14, j + 5, k + 21, this.c, 5);
            this.b(w, i + 14, j + 5, k + 22, this.c, 5);
            this.b(w, i + 14, j + 5, k + 23, this.c, 5);
            this.b(w, i + 14, j + 5, k + 24, this.g);
            this.b(w, i + 14, j + 6, k + 16, this.g);
            this.b(w, i + 14, j + 6, k + 17, this.c, 5);
            this.b(w, i + 14, j + 6, k + 18, this.c, 5);
            this.b(w, i + 14, j + 6, k + 19, this.c, 5);
            this.b(w, i + 14, j + 6, k + 20, this.c, 5);
            this.b(w, i + 14, j + 6, k + 21, this.c, 5);
            this.b(w, i + 14, j + 6, k + 22, this.c, 5);
            this.b(w, i + 14, j + 6, k + 23, this.c, 5);
            this.b(w, i + 14, j + 6, k + 24, this.g);
            this.b(w, i + 14, j + 7, k + 16, this.g);
            this.b(w, i + 14, j + 7, k + 17, this.c, 5);
            this.b(w, i + 14, j + 7, k + 18, this.c, 5);
            this.b(w, i + 14, j + 7, k + 19, this.c, 5);
            this.b(w, i + 14, j + 7, k + 20, this.c, 5);
            this.b(w, i + 14, j + 7, k + 21, this.c, 5);
            this.b(w, i + 14, j + 7, k + 22, this.c, 5);
            this.b(w, i + 14, j + 7, k + 23, this.c, 5);
            this.b(w, i + 14, j + 7, k + 24, this.g);
            this.b(w, i + 14, j + 8, k + 17, this.g);
            this.b(w, i + 14, j + 8, k + 18, this.c, 5);
            this.b(w, i + 14, j + 8, k + 19, this.c, 5);
            this.b(w, i + 14, j + 8, k + 20, this.c, 5);
            this.b(w, i + 14, j + 8, k + 21, this.c, 5);
            this.b(w, i + 14, j + 8, k + 22, this.c, 5);
            this.b(w, i + 14, j + 8, k + 23, this.g);
            this.b(w, i + 14, j + 9, k + 17, this.g);
            this.b(w, i + 14, j + 9, k + 18, this.c, 5);
            this.b(w, i + 14, j + 9, k + 19, this.c, 5);
            this.b(w, i + 14, j + 9, k + 20, this.c, 5);
            this.b(w, i + 14, j + 9, k + 21, this.c, 5);
            this.b(w, i + 14, j + 9, k + 22, this.c, 5);
            this.b(w, i + 14, j + 9, k + 23, this.g);
            this.b(w, i + 14, j + 10, k + 18, this.g);
            this.b(w, i + 14, j + 10, k + 22, this.g);
            this.b(w, i + 14, j + 11, k + 19, this.g);
            this.b(w, i + 14, j + 11, k + 20, this.g);
            this.b(w, i + 14, j + 11, k + 21, this.g);
            this.b(w, i + 14, j + 12, k + 19, this.g);
            this.b(w, i + 14, j + 12, k + 20, this.g);
            this.b(w, i + 14, j + 12, k + 21, this.g);
            this.b(w, i + 14, j + 13, k + 19, this.g);
            this.b(w, i + 14, j + 13, k + 20, this.g);
            this.b(w, i + 14, j + 13, k + 21, this.g);
            this.b(w, i + 14, j + 14, k + 18, this.g);
            this.b(w, i + 14, j + 14, k + 19, this.c, 5);
            this.b(w, i + 14, j + 14, k + 20, this.c, 5);
            this.b(w, i + 14, j + 14, k + 21, this.c, 5);
            this.b(w, i + 14, j + 14, k + 22, this.g);
            this.b(w, i + 14, j + 15, k + 17, this.g);
            this.b(w, i + 14, j + 15, k + 18, this.c, 5);
            this.b(w, i + 14, j + 15, k + 19, this.c, 5);
            this.b(w, i + 14, j + 15, k + 20, this.c, 5);
            this.b(w, i + 14, j + 15, k + 21, this.c, 5);
            this.b(w, i + 14, j + 15, k + 22, this.c, 5);
            this.b(w, i + 14, j + 15, k + 23, this.g);
            this.b(w, i + 14, j + 16, k + 17, this.g);
            this.b(w, i + 14, j + 16, k + 23, this.g);
            this.b(w, i + 14, j + 17, k + 16, this.g);
            this.b(w, i + 14, j + 17, k + 24, this.g);
            this.b(w, i + 14, j + 18, k + 16, this.g);
            this.b(w, i + 14, j + 18, k + 24, this.g);
            this.b(w, i + 14, j + 19, k + 16, this.g);
            this.b(w, i + 14, j + 19, k + 24, this.g);
            this.b(w, i + 14, j + 20, k + 16, this.g);
            this.b(w, i + 14, j + 20, k + 24, this.g);
            this.b(w, i + 14, j + 21, k + 16, this.g);
            this.b(w, i + 14, j + 21, k + 24, this.g);
            this.b(w, i + 14, j + 22, k + 16, this.c, 4);
            this.b(w, i + 14, j + 22, k + 17, this.g);
            this.b(w, i + 14, j + 22, k + 23, this.g);
            this.b(w, i + 14, j + 22, k + 24, this.c, 4);
            this.b(w, i + 14, j + 23, k + 16, this.c, 4);
            this.b(w, i + 14, j + 23, k + 17, this.g);
            this.b(w, i + 14, j + 23, k + 23, this.g);
            this.b(w, i + 14, j + 23, k + 24, this.c, 4);
            this.b(w, i + 14, j + 24, k + 16, this.c, 4);
            this.b(w, i + 14, j + 24, k + 24, this.c, 4);
            this.b(w, i + 14, j + 25, k + 16, this.c, 4);
            this.b(w, i + 14, j + 25, k + 24, this.c, 4);
            this.b(w, i + 14, j + 26, k + 17, this.c, 4);
            this.b(w, i + 14, j + 26, k + 23, this.c, 4);
            this.b(w, i + 14, j + 27, k + 17, this.c, 4);
            this.b(w, i + 14, j + 27, k + 18, this.c, 4);
            this.b(w, i + 14, j + 27, k + 22, this.c, 4);
            this.b(w, i + 14, j + 27, k + 23, this.c, 4);
            this.b(w, i + 14, j + 28, k + 19, this.c, 4);
            this.b(w, i + 14, j + 28, k + 20, this.c, 4);
            this.b(w, i + 14, j + 28, k + 21, this.c, 4);
            this.b(w, i + 15, j + 0, k + 6, this.s);
            this.b(w, i + 15, j + 0, k + 7, this.c, 8);
            this.b(w, i + 15, j + 0, k + 8, this.c, 8);
            this.b(w, i + 15, j + 0, k + 9, this.c, 8);
            this.b(w, i + 15, j + 0, k + 10, this.c, 8);
            this.b(w, i + 15, j + 0, k + 11, this.c, 8);
            this.b(w, i + 15, j + 0, k + 12, this.c, 8);
            this.b(w, i + 15, j + 0, k + 13, this.c, 8);
            this.b(w, i + 15, j + 0, k + 14, this.c, 8);
            this.b(w, i + 15, j + 0, k + 15, this.c, 8);
            this.b(w, i + 15, j + 0, k + 16, this.c, 8);
            this.b(w, i + 15, j + 0, k + 17, this.c, 8);
            this.b(w, i + 15, j + 0, k + 18, this.c, 8);
            this.b(w, i + 15, j + 0, k + 19, this.c, 8);
            this.b(w, i + 15, j + 0, k + 20, this.c, 8);
            this.b(w, i + 15, j + 0, k + 21, this.c, 8);
            this.b(w, i + 15, j + 0, k + 22, this.c, 8);
            this.b(w, i + 15, j + 0, k + 23, this.c, 8);
            this.b(w, i + 15, j + 0, k + 24, this.c, 8);
            this.b(w, i + 15, j + 0, k + 25, this.c, 8);
            this.b(w, i + 15, j + 0, k + 26, this.c, 8);
            this.b(w, i + 15, j + 0, k + 27, this.c, 8);
            this.b(w, i + 15, j + 0, k + 28, this.c, 8);
            this.b(w, i + 15, j + 0, k + 29, this.s);
            this.b(w, i + 15, j + 1, k + 16, this.c, 4);
            this.b(w, i + 15, j + 1, k + 18, this.g);
            this.b(w, i + 15, j + 1, k + 22, this.g);
            this.b(w, i + 15, j + 1, k + 24, this.c, 4);
            this.b(w, i + 15, j + 2, k + 17, this.c, 4);
            this.b(w, i + 15, j + 2, k + 18, this.c, 5);
            this.b(w, i + 15, j + 2, k + 19, this.c, 5);
            this.b(w, i + 15, j + 2, k + 20, this.c, 5);
            this.b(w, i + 15, j + 2, k + 21, this.c, 5);
            this.b(w, i + 15, j + 2, k + 22, this.c, 5);
            this.b(w, i + 15, j + 2, k + 23, this.c, 4);
            this.b(w, i + 15, j + 3, k + 17, this.g);
            this.b(w, i + 15, j + 3, k + 18, this.c, 5);
            this.b(w, i + 15, j + 3, k + 19, this.c, 5);
            this.b(w, i + 15, j + 3, k + 20, this.c, 5);
            this.b(w, i + 15, j + 3, k + 21, this.c, 5);
            this.b(w, i + 15, j + 3, k + 22, this.c, 5);
            this.b(w, i + 15, j + 3, k + 23, this.g);
            this.b(w, i + 15, j + 4, k + 17, this.g);
            this.b(w, i + 15, j + 4, k + 18, this.c, 5);
            this.b(w, i + 15, j + 4, k + 19, this.c, 5);
            this.b(w, i + 15, j + 4, k + 20, this.c, 5);
            this.b(w, i + 15, j + 4, k + 21, this.c, 5);
            this.b(w, i + 15, j + 4, k + 22, this.c, 5);
            this.b(w, i + 15, j + 4, k + 23, this.g);
            this.b(w, i + 15, j + 5, k + 16, this.g);
            this.b(w, i + 15, j + 5, k + 17, this.c, 5);
            this.b(w, i + 15, j + 5, k + 18, this.c, 5);
            this.b(w, i + 15, j + 5, k + 19, this.c, 5);
            this.b(w, i + 15, j + 5, k + 20, this.c, 5);
            this.b(w, i + 15, j + 5, k + 21, this.c, 5);
            this.b(w, i + 15, j + 5, k + 22, this.c, 5);
            this.b(w, i + 15, j + 5, k + 23, this.c, 5);
            this.b(w, i + 15, j + 5, k + 24, this.g);
            this.b(w, i + 15, j + 6, k + 17, this.g);
            this.b(w, i + 15, j + 6, k + 18, this.c, 5);
            this.b(w, i + 15, j + 6, k + 19, this.c, 5);
            this.b(w, i + 15, j + 6, k + 20, this.c, 5);
            this.b(w, i + 15, j + 6, k + 21, this.c, 5);
            this.b(w, i + 15, j + 6, k + 22, this.c, 5);
            this.b(w, i + 15, j + 6, k + 23, this.g);
            this.b(w, i + 15, j + 7, k + 17, this.g);
            this.b(w, i + 15, j + 7, k + 18, this.c, 5);
            this.b(w, i + 15, j + 7, k + 19, this.c, 5);
            this.b(w, i + 15, j + 7, k + 20, this.c, 5);
            this.b(w, i + 15, j + 7, k + 21, this.c, 5);
            this.b(w, i + 15, j + 7, k + 22, this.c, 5);
            this.b(w, i + 15, j + 7, k + 23, this.g);
            this.b(w, i + 15, j + 8, k + 17, this.g);
            this.b(w, i + 15, j + 8, k + 18, this.c, 5);
            this.b(w, i + 15, j + 8, k + 19, this.c, 5);
            this.b(w, i + 15, j + 8, k + 20, this.c, 5);
            this.b(w, i + 15, j + 8, k + 21, this.c, 5);
            this.b(w, i + 15, j + 8, k + 22, this.c, 5);
            this.b(w, i + 15, j + 8, k + 23, this.g);
            this.b(w, i + 15, j + 9, k + 18, this.g);
            this.b(w, i + 15, j + 9, k + 19, this.c, 5);
            this.b(w, i + 15, j + 9, k + 20, this.c, 5);
            this.b(w, i + 15, j + 9, k + 21, this.c, 5);
            this.b(w, i + 15, j + 9, k + 22, this.g);
            this.b(w, i + 15, j + 10, k + 18, this.g);
            this.b(w, i + 15, j + 10, k + 19, this.g);
            this.b(w, i + 15, j + 10, k + 20, this.g);
            this.b(w, i + 15, j + 10, k + 21, this.g);
            this.b(w, i + 15, j + 10, k + 22, this.g);
            this.b(w, i + 15, j + 14, k + 18, this.g);
            this.b(w, i + 15, j + 14, k + 19, this.g);
            this.b(w, i + 15, j + 14, k + 20, this.g);
            this.b(w, i + 15, j + 14, k + 21, this.g);
            this.b(w, i + 15, j + 14, k + 22, this.g);
            this.b(w, i + 15, j + 15, k + 18, this.g);
            this.b(w, i + 15, j + 15, k + 19, this.c, 5);
            this.b(w, i + 15, j + 15, k + 20, this.c, 5);
            this.b(w, i + 15, j + 15, k + 21, this.c, 5);
            this.b(w, i + 15, j + 15, k + 22, this.g);
            this.b(w, i + 15, j + 16, k + 17, this.g);
            this.b(w, i + 15, j + 16, k + 23, this.g);
            this.b(w, i + 15, j + 17, k + 17, this.g);
            this.b(w, i + 15, j + 17, k + 23, this.g);
            this.b(w, i + 15, j + 18, k + 17, this.g);
            this.b(w, i + 15, j + 18, k + 23, this.g);
            this.b(w, i + 15, j + 19, k + 16, this.g);
            this.b(w, i + 15, j + 19, k + 24, this.g);
            this.b(w, i + 15, j + 20, k + 17, this.g);
            this.b(w, i + 15, j + 20, k + 23, this.g);
            this.b(w, i + 15, j + 21, k + 17, this.g);
            this.b(w, i + 15, j + 21, k + 23, this.g);
            this.b(w, i + 15, j + 22, k + 17, this.c, 4);
            this.b(w, i + 15, j + 22, k + 23, this.c, 4);
            this.b(w, i + 15, j + 23, k + 16, this.c, 4);
            this.b(w, i + 15, j + 23, k + 18, this.g);
            this.b(w, i + 15, j + 23, k + 22, this.g);
            this.b(w, i + 15, j + 23, k + 24, this.c, 4);
            this.b(w, i + 15, j + 24, k + 16, this.c, 4);
            this.b(w, i + 15, j + 24, k + 24, this.c, 4);
            this.b(w, i + 15, j + 25, k + 17, this.c, 4);
            this.b(w, i + 15, j + 25, k + 23, this.c, 4);
            this.b(w, i + 15, j + 26, k + 17, this.c, 4);
            this.b(w, i + 15, j + 26, k + 23, this.c, 4);
            this.b(w, i + 15, j + 27, k + 18, this.c, 4);
            this.b(w, i + 15, j + 27, k + 19, this.c, 4);
            this.b(w, i + 15, j + 27, k + 21, this.c, 4);
            this.b(w, i + 15, j + 27, k + 22, this.c, 4);
            this.b(w, i + 15, j + 28, k + 20, this.c, 4);
            this.b(w, i + 16, j + 0, k + 6, this.s);
            this.b(w, i + 16, j + 0, k + 7, this.c, 8);
            this.b(w, i + 16, j + 0, k + 8, this.c, 8);
            this.b(w, i + 16, j + 0, k + 9, this.c, 8);
            this.b(w, i + 16, j + 0, k + 10, this.c, 8);
            this.b(w, i + 16, j + 0, k + 11, this.c, 8);
            this.b(w, i + 16, j + 0, k + 12, this.c, 8);
            this.b(w, i + 16, j + 0, k + 13, this.c, 8);
            this.b(w, i + 16, j + 0, k + 14, this.c, 8);
            this.b(w, i + 16, j + 0, k + 15, this.c, 8);
            this.b(w, i + 16, j + 0, k + 16, this.c, 8);
            this.b(w, i + 16, j + 0, k + 17, this.c, 8);
            this.b(w, i + 16, j + 0, k + 18, this.c, 8);
            this.b(w, i + 16, j + 0, k + 19, this.c, 8);
            this.b(w, i + 16, j + 0, k + 20, this.c, 8);
            this.b(w, i + 16, j + 0, k + 21, this.c, 8);
            this.b(w, i + 16, j + 0, k + 22, this.c, 8);
            this.b(w, i + 16, j + 0, k + 23, this.c, 8);
            this.b(w, i + 16, j + 0, k + 24, this.c, 8);
            this.b(w, i + 16, j + 0, k + 25, this.c, 8);
            this.b(w, i + 16, j + 0, k + 26, this.c, 8);
            this.b(w, i + 16, j + 0, k + 27, this.c, 8);
            this.b(w, i + 16, j + 0, k + 28, this.c, 8);
            this.b(w, i + 16, j + 0, k + 29, this.s);
            this.b(w, i + 16, j + 1, k + 17, this.c, 4);
            this.b(w, i + 16, j + 1, k + 19, this.g);
            this.b(w, i + 16, j + 1, k + 20, this.g);
            this.b(w, i + 16, j + 1, k + 21, this.g);
            this.b(w, i + 16, j + 1, k + 23, this.c, 4);
            this.b(w, i + 16, j + 2, k + 17, this.c, 4);
            this.b(w, i + 16, j + 2, k + 18, this.c, 4);
            this.b(w, i + 16, j + 2, k + 19, this.g);
            this.b(w, i + 16, j + 2, k + 20, this.g);
            this.b(w, i + 16, j + 2, k + 21, this.g);
            this.b(w, i + 16, j + 2, k + 22, this.c, 4);
            this.b(w, i + 16, j + 2, k + 23, this.c, 4);
            this.b(w, i + 16, j + 3, k + 17, this.g);
            this.b(w, i + 16, j + 3, k + 18, this.g);
            this.b(w, i + 16, j + 3, k + 19, this.c, 5);
            this.b(w, i + 16, j + 3, k + 20, this.c, 5);
            this.b(w, i + 16, j + 3, k + 21, this.c, 5);
            this.b(w, i + 16, j + 3, k + 22, this.g);
            this.b(w, i + 16, j + 3, k + 23, this.g);
            this.b(w, i + 16, j + 4, k + 17, this.g);
            this.b(w, i + 16, j + 4, k + 18, this.g);
            this.b(w, i + 16, j + 4, k + 19, this.c, 5);
            this.b(w, i + 16, j + 4, k + 20, this.c, 5);
            this.b(w, i + 16, j + 4, k + 21, this.c, 5);
            this.b(w, i + 16, j + 4, k + 22, this.g);
            this.b(w, i + 16, j + 4, k + 23, this.g);
            this.b(w, i + 16, j + 5, k + 17, this.g);
            this.b(w, i + 16, j + 5, k + 18, this.c, 5);
            this.b(w, i + 16, j + 5, k + 19, this.c, 5);
            this.b(w, i + 16, j + 5, k + 20, this.c, 5);
            this.b(w, i + 16, j + 5, k + 21, this.c, 5);
            this.b(w, i + 16, j + 5, k + 22, this.c, 5);
            this.b(w, i + 16, j + 5, k + 23, this.g);
            this.b(w, i + 16, j + 6, k + 17, this.g);
            this.b(w, i + 16, j + 6, k + 18, this.g);
            this.b(w, i + 16, j + 6, k + 19, this.c, 5);
            this.b(w, i + 16, j + 6, k + 20, this.c, 5);
            this.b(w, i + 16, j + 6, k + 21, this.c, 5);
            this.b(w, i + 16, j + 6, k + 22, this.g);
            this.b(w, i + 16, j + 6, k + 23, this.g);
            this.b(w, i + 16, j + 7, k + 17, this.g);
            this.b(w, i + 16, j + 7, k + 18, this.g);
            this.b(w, i + 16, j + 7, k + 19, this.c, 5);
            this.b(w, i + 16, j + 7, k + 20, this.c, 5);
            this.b(w, i + 16, j + 7, k + 21, this.c, 5);
            this.b(w, i + 16, j + 7, k + 22, this.g);
            this.b(w, i + 16, j + 7, k + 23, this.g);
            this.b(w, i + 16, j + 8, k + 18, this.g);
            this.b(w, i + 16, j + 8, k + 19, this.g);
            this.b(w, i + 16, j + 8, k + 20, this.g);
            this.b(w, i + 16, j + 8, k + 21, this.g);
            this.b(w, i + 16, j + 8, k + 22, this.g);
            this.b(w, i + 16, j + 9, k + 19, this.g);
            this.b(w, i + 16, j + 9, k + 20, this.g);
            this.b(w, i + 16, j + 9, k + 21, this.g);
            this.b(w, i + 16, j + 15, k + 19, this.g);
            this.b(w, i + 16, j + 15, k + 20, this.g);
            this.b(w, i + 16, j + 15, k + 21, this.g);
            this.b(w, i + 16, j + 16, k + 18, this.g);
            this.b(w, i + 16, j + 16, k + 19, this.g);
            this.b(w, i + 16, j + 16, k + 20, this.g);
            this.b(w, i + 16, j + 16, k + 21, this.g);
            this.b(w, i + 16, j + 16, k + 22, this.g);
            this.b(w, i + 16, j + 17, k + 17, this.g);
            this.b(w, i + 16, j + 17, k + 18, this.g);
            this.b(w, i + 16, j + 17, k + 22, this.g);
            this.b(w, i + 16, j + 17, k + 23, this.g);
            this.b(w, i + 16, j + 18, k + 17, this.g);
            this.b(w, i + 16, j + 18, k + 18, this.g);
            this.b(w, i + 16, j + 18, k + 22, this.g);
            this.b(w, i + 16, j + 18, k + 23, this.g);
            this.b(w, i + 16, j + 19, k + 17, this.g);
            this.b(w, i + 16, j + 19, k + 23, this.g);
            this.b(w, i + 16, j + 20, k + 17, this.g);
            this.b(w, i + 16, j + 20, k + 18, this.g);
            this.b(w, i + 16, j + 20, k + 22, this.g);
            this.b(w, i + 16, j + 20, k + 23, this.g);
            this.b(w, i + 16, j + 21, k + 17, this.g);
            this.b(w, i + 16, j + 21, k + 18, this.g);
            this.b(w, i + 16, j + 21, k + 22, this.g);
            this.b(w, i + 16, j + 21, k + 23, this.g);
            this.b(w, i + 16, j + 22, k + 17, this.c, 4);
            this.b(w, i + 16, j + 22, k + 18, this.c, 4);
            this.b(w, i + 16, j + 22, k + 19, this.g);
            this.b(w, i + 16, j + 22, k + 20, this.g);
            this.b(w, i + 16, j + 22, k + 21, this.g);
            this.b(w, i + 16, j + 22, k + 22, this.c, 4);
            this.b(w, i + 16, j + 22, k + 23, this.c, 4);
            this.b(w, i + 16, j + 23, k + 17, this.c, 4);
            this.b(w, i + 16, j + 23, k + 19, this.g);
            this.b(w, i + 16, j + 23, k + 20, this.g);
            this.b(w, i + 16, j + 23, k + 21, this.g);
            this.b(w, i + 16, j + 23, k + 23, this.c, 4);
            this.b(w, i + 16, j + 24, k + 17, this.c, 4);
            this.b(w, i + 16, j + 24, k + 23, this.c, 4);
            this.b(w, i + 16, j + 25, k + 17, this.c, 4);
            this.b(w, i + 16, j + 25, k + 18, this.c, 4);
            this.b(w, i + 16, j + 25, k + 22, this.c, 4);
            this.b(w, i + 16, j + 25, k + 23, this.c, 4);
            this.b(w, i + 16, j + 26, k + 18, this.c, 4);
            this.b(w, i + 16, j + 26, k + 19, this.c, 4);
            this.b(w, i + 16, j + 26, k + 21, this.c, 4);
            this.b(w, i + 16, j + 26, k + 22, this.c, 4);
            this.b(w, i + 16, j + 27, k + 19, this.c, 4);
            this.b(w, i + 16, j + 27, k + 20, this.c, 4);
            this.b(w, i + 16, j + 27, k + 21, this.c, 4);
            this.b(w, i + 17, j + 0, k + 6, this.s);
            this.b(w, i + 17, j + 0, k + 7, this.c, 8);
            this.b(w, i + 17, j + 0, k + 8, this.c, 8);
            this.b(w, i + 17, j + 0, k + 9, this.c, 8);
            this.b(w, i + 17, j + 0, k + 10, this.c, 8);
            this.b(w, i + 17, j + 0, k + 11, this.c, 8);
            this.b(w, i + 17, j + 0, k + 12, this.c, 8);
            this.b(w, i + 17, j + 0, k + 13, this.c, 8);
            this.b(w, i + 17, j + 0, k + 14, this.c, 8);
            this.b(w, i + 17, j + 0, k + 15, this.c, 8);
            this.b(w, i + 17, j + 0, k + 16, this.c, 8);
            this.b(w, i + 17, j + 0, k + 17, this.c, 8);
            this.b(w, i + 17, j + 0, k + 18, this.c, 8);
            this.b(w, i + 17, j + 0, k + 19, this.c, 8);
            this.b(w, i + 17, j + 0, k + 20, this.c, 8);
            this.b(w, i + 17, j + 0, k + 21, this.c, 8);
            this.b(w, i + 17, j + 0, k + 22, this.c, 8);
            this.b(w, i + 17, j + 0, k + 23, this.c, 8);
            this.b(w, i + 17, j + 0, k + 24, this.c, 8);
            this.b(w, i + 17, j + 0, k + 25, this.c, 8);
            this.b(w, i + 17, j + 0, k + 26, this.c, 8);
            this.b(w, i + 17, j + 0, k + 27, this.c, 8);
            this.b(w, i + 17, j + 0, k + 28, this.c, 8);
            this.b(w, i + 17, j + 0, k + 29, this.s);
            this.b(w, i + 17, j + 1, k + 18, this.c, 4);
            this.b(w, i + 17, j + 1, k + 19, this.c, 4);
            this.b(w, i + 17, j + 1, k + 20, this.c, 4);
            this.b(w, i + 17, j + 1, k + 21, this.c, 4);
            this.b(w, i + 17, j + 1, k + 22, this.c, 4);
            this.b(w, i + 17, j + 2, k + 19, this.c, 4);
            this.b(w, i + 17, j + 2, k + 20, this.c, 4);
            this.b(w, i + 17, j + 2, k + 21, this.c, 4);
            this.b(w, i + 17, j + 3, k + 19, this.g);
            this.b(w, i + 17, j + 3, k + 20, this.g);
            this.b(w, i + 17, j + 3, k + 21, this.g);
            this.b(w, i + 17, j + 4, k + 19, this.g);
            this.b(w, i + 17, j + 4, k + 20, this.g);
            this.b(w, i + 17, j + 4, k + 21, this.g);
            this.b(w, i + 17, j + 5, k + 18, this.g);
            this.b(w, i + 17, j + 5, k + 19, this.g);
            this.b(w, i + 17, j + 5, k + 20, this.g);
            this.b(w, i + 17, j + 5, k + 21, this.g);
            this.b(w, i + 17, j + 5, k + 22, this.g);
            this.b(w, i + 17, j + 6, k + 19, this.g);
            this.b(w, i + 17, j + 6, k + 20, this.g);
            this.b(w, i + 17, j + 6, k + 21, this.g);
            this.b(w, i + 17, j + 7, k + 19, this.g);
            this.b(w, i + 17, j + 7, k + 20, this.g);
            this.b(w, i + 17, j + 7, k + 21, this.g);
            this.b(w, i + 17, j + 17, k + 19, this.g);
            this.b(w, i + 17, j + 17, k + 20, this.g);
            this.b(w, i + 17, j + 17, k + 21, this.g);
            this.b(w, i + 17, j + 18, k + 19, this.g);
            this.b(w, i + 17, j + 18, k + 20, this.g);
            this.b(w, i + 17, j + 18, k + 21, this.g);
            this.b(w, i + 17, j + 19, k + 18, this.g);
            this.b(w, i + 17, j + 19, k + 19, this.g);
            this.b(w, i + 17, j + 19, k + 20, this.g);
            this.b(w, i + 17, j + 19, k + 21, this.g);
            this.b(w, i + 17, j + 19, k + 22, this.g);
            this.b(w, i + 17, j + 20, k + 19, this.g);
            this.b(w, i + 17, j + 20, k + 20, this.g);
            this.b(w, i + 17, j + 20, k + 21, this.g);
            this.b(w, i + 17, j + 21, k + 19, this.g);
            this.b(w, i + 17, j + 21, k + 20, this.g);
            this.b(w, i + 17, j + 21, k + 21, this.g);
            this.b(w, i + 17, j + 22, k + 19, this.c, 4);
            this.b(w, i + 17, j + 22, k + 20, this.c, 4);
            this.b(w, i + 17, j + 22, k + 21, this.c, 4);
            this.b(w, i + 17, j + 23, k + 18, this.c, 4);
            this.b(w, i + 17, j + 23, k + 19, this.c, 4);
            this.b(w, i + 17, j + 23, k + 20, this.c, 4);
            this.b(w, i + 17, j + 23, k + 21, this.c, 4);
            this.b(w, i + 17, j + 23, k + 22, this.c, 4);
            this.b(w, i + 17, j + 24, k + 18, this.c, 4);
            this.b(w, i + 17, j + 24, k + 19, this.c, 4);
            this.b(w, i + 17, j + 24, k + 20, this.c, 4);
            this.b(w, i + 17, j + 24, k + 21, this.c, 4);
            this.b(w, i + 17, j + 24, k + 22, this.c, 4);
            this.b(w, i + 17, j + 25, k + 19, this.c, 4);
            this.b(w, i + 17, j + 25, k + 20, this.c, 4);
            this.b(w, i + 17, j + 25, k + 21, this.c, 4);
            this.b(w, i + 17, j + 26, k + 20, this.c, 4);
            this.b(w, i + 18, j + 0, k + 6, this.s);
            this.b(w, i + 18, j + 0, k + 7, this.c, 8);
            this.b(w, i + 18, j + 0, k + 8, this.c, 8);
            this.b(w, i + 18, j + 0, k + 9, this.c, 8);
            this.b(w, i + 18, j + 0, k + 10, this.c, 8);
            this.b(w, i + 18, j + 0, k + 11, this.c, 8);
            this.b(w, i + 18, j + 0, k + 12, this.c, 8);
            this.b(w, i + 18, j + 0, k + 13, this.c, 8);
            this.b(w, i + 18, j + 0, k + 14, this.c, 8);
            this.b(w, i + 18, j + 0, k + 15, this.c, 8);
            this.b(w, i + 18, j + 0, k + 16, this.c, 8);
            this.b(w, i + 18, j + 0, k + 17, this.c, 8);
            this.b(w, i + 18, j + 0, k + 18, this.c, 8);
            this.b(w, i + 18, j + 0, k + 19, this.c, 8);
            this.b(w, i + 18, j + 0, k + 20, this.c, 8);
            this.b(w, i + 18, j + 0, k + 21, this.c, 8);
            this.b(w, i + 18, j + 0, k + 22, this.c, 8);
            this.b(w, i + 18, j + 0, k + 23, this.c, 8);
            this.b(w, i + 18, j + 0, k + 24, this.c, 8);
            this.b(w, i + 18, j + 0, k + 25, this.c, 8);
            this.b(w, i + 18, j + 0, k + 26, this.c, 8);
            this.b(w, i + 18, j + 0, k + 27, this.c, 8);
            this.b(w, i + 18, j + 0, k + 28, this.c, 8);
            this.b(w, i + 18, j + 0, k + 29, this.s);
            this.b(w, i + 19, j + 0, k + 6, this.s);
            this.b(w, i + 19, j + 0, k + 7, this.c, 8);
            this.b(w, i + 19, j + 0, k + 8, this.c, 8);
            this.b(w, i + 19, j + 0, k + 9, this.c, 8);
            this.b(w, i + 19, j + 0, k + 10, this.c, 8);
            this.b(w, i + 19, j + 0, k + 11, this.c, 8);
            this.b(w, i + 19, j + 0, k + 12, this.c, 8);
            this.b(w, i + 19, j + 0, k + 13, this.c, 8);
            this.b(w, i + 19, j + 0, k + 14, this.c, 8);
            this.b(w, i + 19, j + 0, k + 15, this.c, 8);
            this.b(w, i + 19, j + 0, k + 16, this.c, 8);
            this.b(w, i + 19, j + 0, k + 17, this.c, 8);
            this.b(w, i + 19, j + 0, k + 18, this.c, 8);
            this.b(w, i + 19, j + 0, k + 19, this.c, 8);
            this.b(w, i + 19, j + 0, k + 20, this.c, 8);
            this.b(w, i + 19, j + 0, k + 21, this.c, 8);
            this.b(w, i + 19, j + 0, k + 22, this.c, 8);
            this.b(w, i + 19, j + 0, k + 23, this.c, 8);
            this.b(w, i + 19, j + 0, k + 24, this.c, 8);
            this.b(w, i + 19, j + 0, k + 25, this.c, 8);
            this.b(w, i + 19, j + 0, k + 26, this.c, 8);
            this.b(w, i + 19, j + 0, k + 27, this.c, 8);
            this.b(w, i + 19, j + 0, k + 28, this.c, 8);
            this.b(w, i + 19, j + 0, k + 29, this.s);
            this.b(w, i + 20, j + 0, k + 6, this.s);
            this.b(w, i + 20, j + 0, k + 7, this.c, 8);
            this.b(w, i + 20, j + 0, k + 8, this.c, 8);
            this.b(w, i + 20, j + 0, k + 9, this.c, 8);
            this.b(w, i + 20, j + 0, k + 10, this.c, 8);
            this.b(w, i + 20, j + 0, k + 11, this.c, 8);
            this.b(w, i + 20, j + 0, k + 12, this.c, 8);
            TiChaP2 p2 = new TiChaP2();
            p2.generate2(w, rand, i, j, k);
        }
        return true;
    }
}

