/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  JinRyuu.JRMCore.client.JGRenderHelper
 *  net.minecraft.client.model.ModelBase
 *  net.minecraft.client.model.ModelRenderer
 *  net.minecraft.entity.Entity
 *  net.minecraft.util.MathHelper
 *  org.lwjgl.opengl.GL11
 */
package JinRyuu.DragonBC.common.Npcs.dbpilaf;

import JinRyuu.JRMCore.client.JGRenderHelper;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;
import org.lwjgl.opengl.GL11;

public class ModelMaiMecha
extends ModelBase {
    public ModelRenderer Body;
    public ModelRenderer ArmR1;
    public ModelRenderer ArmL1;
    public ModelRenderer Leg1R;
    public ModelRenderer Leg1L;
    public ModelRenderer Extra1;
    public ModelRenderer BodyBack;
    public ModelRenderer BodyR;
    public ModelRenderer BodyL;
    public ModelRenderer Head1;
    public ModelRenderer Back;
    public ModelRenderer BodyBottom1;
    public ModelRenderer BodyBottomR;
    public ModelRenderer BodyBottomL;
    public ModelRenderer BodyBottom2;
    public ModelRenderer BodyBottomR2;
    public ModelRenderer BodyBottomL2;
    public ModelRenderer PlateR;
    public ModelRenderer ShoulderR;
    public ModelRenderer PlateL;
    public ModelRenderer ShoulderL;
    public ModelRenderer Head2;
    public ModelRenderer ArmR2;
    public ModelRenderer ArmR3;
    public ModelRenderer ArmR4;
    public ModelRenderer handR;
    public ModelRenderer fingerR3;
    public ModelRenderer fingerR1;
    public ModelRenderer fingerR4;
    public ModelRenderer fingerR2;
    public ModelRenderer ArmL2;
    public ModelRenderer ArmL3;
    public ModelRenderer ArmL4;
    public ModelRenderer handL;
    public ModelRenderer fingerL3;
    public ModelRenderer fingerL1;
    public ModelRenderer fingerL4;
    public ModelRenderer fingerL2;
    public ModelRenderer Leg2R;
    public ModelRenderer Leg3R;
    public ModelRenderer KneeR;
    public ModelRenderer FootR;
    public ModelRenderer Leg2L;
    public ModelRenderer Leg3L;
    public ModelRenderer KneeL;
    public ModelRenderer FootL;
    public ModelRenderer Extra2;
    public ModelRenderer Extra3;

    public ModelMaiMecha() {
        this.textureWidth = 256;
        this.textureHeight = 128;
        this.fingerR2 = new ModelRenderer((ModelBase)this, 100, 106);
        this.fingerR2.setRotationPoint(-0.3f, 3.4f, 0.0f);
        this.fingerR2.addBox(-1.0f, 0.0f, -1.0f, 2, 4, 2, 0.0f);
        this.setRotateAngle(this.fingerR2, 0.0f, 0.0f, -0.9599311f);
        this.ArmL1 = new ModelRenderer((ModelBase)this, 70, 80);
        this.ArmL1.mirror = true;
        this.ArmL1.setRotationPoint(16.6f, -13.0f, 0.0f);
        this.ArmL1.addBox(-2.7f, -1.5f, -1.5f, 3, 3, 3, 0.0f);
        this.fingerR4 = new ModelRenderer((ModelBase)this, 100, 106);
        this.fingerR4.setRotationPoint(0.3f, 3.4f, 0.0f);
        this.fingerR4.addBox(-1.0f, 0.0f, -1.0f, 2, 4, 2, 0.0f);
        this.setRotateAngle(this.fingerR4, 0.0f, 0.0f, 0.9599311f);
        this.BodyBottom2 = new ModelRenderer((ModelBase)this, 0, 65);
        this.BodyBottom2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.BodyBottom2.addBox(-11.0f, -4.1f, -7.8f, 22, 13, 0, 0.0f);
        this.BodyBottomL2 = new ModelRenderer((ModelBase)this, 31, 66);
        this.BodyBottomL2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.BodyBottomL2.addBox(10.2f, 8.8f, -7.7f, 5, 2, 14, 0.0f);
        this.fingerL4 = new ModelRenderer((ModelBase)this, 100, 106);
        this.fingerL4.setRotationPoint(0.3f, 3.4f, 0.0f);
        this.fingerL4.addBox(-1.0f, 0.0f, -1.0f, 2, 4, 2, 0.0f);
        this.setRotateAngle(this.fingerL4, 0.0f, 0.0f, 0.9599311f);
        this.FootL = new ModelRenderer((ModelBase)this, 1, 113);
        this.FootL.mirror = true;
        this.FootL.setRotationPoint(0.0f, 9.0f, 0.0f);
        this.FootL.addBox(-2.0f, -0.1f, -6.0f, 4, 2, 11, 0.0f);
        this.PlateR = new ModelRenderer((ModelBase)this, 130, 34);
        this.PlateR.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.PlateR.addBox(-14.0f, -9.7f, -8.5f, 6, 6, 2, 0.0f);
        this.handR = new ModelRenderer((ModelBase)this, 100, 100);
        this.handR.setRotationPoint(0.0f, 12.5f, 0.0f);
        this.handR.addBox(-1.0f, -0.5f, -1.6f, 2, 1, 3, 0.0f);
        this.ArmR2 = new ModelRenderer((ModelBase)this, 70, 87);
        this.ArmR2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.ArmR2.addBox(-1.3f, -0.4f, -1.1f, 2, 12, 3, 0.0f);
        this.setRotateAngle(this.ArmR2, 0.11082841f, 0.0f, 0.5009095f);
        this.BodyBack = new ModelRenderer((ModelBase)this, 118, 63);
        this.BodyBack.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.BodyBack.addBox(-7.0f, -15.7f, 9.6f, 14, 13, 1, 0.0f);
        this.handL = new ModelRenderer((ModelBase)this, 100, 100);
        this.handL.mirror = true;
        this.handL.setRotationPoint(-0.4f, 12.5f, 0.0f);
        this.handL.addBox(-1.0f, -0.5f, -1.6f, 2, 1, 3, 0.0f);
        this.BodyL = new ModelRenderer((ModelBase)this, 97, 32);
        this.BodyL.mirror = true;
        this.BodyL.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.BodyL.addBox(9.0f, -17.0f, -6.5f, 7, 15, 14, 0.0f);
        this.Head2 = new ModelRenderer((ModelBase)this, 126, 1);
        this.Head2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.Head2.addBox(-5.0f, -20.6f, -10.0f, 10, 16, 13, 0.0f);
        this.fingerL2 = new ModelRenderer((ModelBase)this, 100, 106);
        this.fingerL2.setRotationPoint(-0.3f, 3.4f, 0.0f);
        this.fingerL2.addBox(-1.0f, 0.0f, -1.0f, 2, 4, 2, 0.0f);
        this.setRotateAngle(this.fingerL2, 0.0f, 0.0f, -0.9599311f);
        this.Leg3L = new ModelRenderer((ModelBase)this, 1, 98);
        this.Leg3L.mirror = true;
        this.Leg3L.setRotationPoint(0.0f, 5.3f, -0.1f);
        this.Leg3L.addBox(-2.5f, -0.1f, -2.0f, 5, 9, 4, 0.0f);
        this.setRotateAngle(this.Leg3L, 0.6981317f, 0.0f, 0.0f);
        this.KneeL = new ModelRenderer((ModelBase)this, 20, 106);
        this.KneeL.mirror = true;
        this.KneeL.setRotationPoint(0.1f, 1.6f, 0.0f);
        this.KneeL.addBox(-1.0f, -2.7f, -3.0f, 2, 3, 2, 0.0f);
        this.BodyBottomL = new ModelRenderer((ModelBase)this, 56, 45);
        this.BodyBottomL.mirror = true;
        this.BodyBottomL.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.BodyBottomL.addBox(10.0f, -2.9f, -9.2f, 7, 12, 20, 0.0f);
        this.Extra3 = new ModelRenderer((ModelBase)this, 110, 7);
        this.Extra3.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.Extra3.addBox(-3.5f, -0.5f, -0.5f, 7, 1, 1, 0.0f);
        this.fingerR1 = new ModelRenderer((ModelBase)this, 100, 106);
        this.fingerR1.setRotationPoint(-0.7f, 0.0f, 0.0f);
        this.fingerR1.addBox(-1.0f, 0.0f, -1.0f, 2, 4, 2, 0.0f);
        this.setRotateAngle(this.fingerR1, 0.0f, 0.0f, 0.6981317f);
        this.fingerR3 = new ModelRenderer((ModelBase)this, 100, 106);
        this.fingerR3.setRotationPoint(0.8f, 0.0f, 0.0f);
        this.fingerR3.addBox(-1.0f, 0.0f, -1.0f, 2, 4, 2, 0.0f);
        this.setRotateAngle(this.fingerR3, 0.0f, 0.0f, -0.6981317f);
        this.ArmR3 = new ModelRenderer((ModelBase)this, 70, 105);
        this.ArmR3.setRotationPoint(0.0f, 10.8f, 0.1f);
        this.ArmR3.addBox(-2.7f, 0.0f, -2.1f, 5, 12, 5, 0.0f);
        this.setRotateAngle(this.ArmR3, -0.4553564f, 0.0f, 0.0f);
        this.BodyBottomR2 = new ModelRenderer((ModelBase)this, 31, 66);
        this.BodyBottomR2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.BodyBottomR2.addBox(-15.3f, 8.8f, -7.7f, 5, 2, 14, 0.0f);
        this.BodyBottom1 = new ModelRenderer((ModelBase)this, 0, 43);
        this.BodyBottom1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.BodyBottom1.addBox(-14.0f, -4.0f, 5.7f, 28, 14, 7, 0.0f);
        this.Head1 = new ModelRenderer((ModelBase)this, 72, 0);
        this.Head1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.Head1.addBox(-6.0f, -19.8f, -8.8f, 12, 16, 14, 0.0f);
        this.Extra2 = new ModelRenderer((ModelBase)this, 110, 9);
        this.Extra2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.Extra2.addBox(2.9f, -0.5f, 0.5f, 1, 1, 4, 0.0f);
        this.BodyBottomR = new ModelRenderer((ModelBase)this, 56, 45);
        this.BodyBottomR.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.BodyBottomR.addBox(-17.0f, -2.9f, -9.2f, 7, 12, 20, 0.0f);
        this.ArmL3 = new ModelRenderer((ModelBase)this, 70, 105);
        this.ArmL3.mirror = true;
        this.ArmL3.setRotationPoint(0.0f, 10.8f, 0.1f);
        this.ArmL3.addBox(-2.7f, 0.0f, -2.1f, 5, 12, 5, 0.0f);
        this.setRotateAngle(this.ArmL3, -0.4553564f, 0.0f, 0.0f);
        this.Leg2R = new ModelRenderer((ModelBase)this, 20, 88);
        this.Leg2R.setRotationPoint(0.0f, 1.6f, 0.0f);
        this.Leg2R.addBox(-1.5f, -0.1f, -1.0f, 3, 6, 2, 0.0f);
        this.setRotateAngle(this.Leg2R, -0.6981317f, 0.06981317f, 0.0f);
        this.PlateL = new ModelRenderer((ModelBase)this, 130, 34);
        this.PlateL.mirror = true;
        this.PlateL.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.PlateL.addBox(8.0f, -9.7f, -8.5f, 6, 6, 2, 0.0f);
        this.fingerL3 = new ModelRenderer((ModelBase)this, 100, 106);
        this.fingerL3.setRotationPoint(0.8f, 0.0f, 0.0f);
        this.fingerL3.addBox(-1.0f, 0.0f, -1.0f, 2, 4, 2, 0.0f);
        this.setRotateAngle(this.fingerL3, 0.0f, 0.0f, -0.6981317f);
        this.ArmR4 = new ModelRenderer((ModelBase)this, 81, 93);
        this.ArmR4.setRotationPoint(0.0f, 0.0f, 1.3f);
        this.ArmR4.addBox(-3.3f, -1.9f, -2.0f, 2, 6, 3, 0.0f);
        this.Leg3R = new ModelRenderer((ModelBase)this, 1, 98);
        this.Leg3R.setRotationPoint(0.0f, 5.3f, -0.1f);
        this.Leg3R.addBox(-2.5f, -0.1f, -2.0f, 5, 9, 4, 0.0f);
        this.setRotateAngle(this.Leg3R, 0.6981317f, 0.0f, 0.0f);
        this.fingerL1 = new ModelRenderer((ModelBase)this, 100, 106);
        this.fingerL1.setRotationPoint(-0.7f, 0.0f, 0.0f);
        this.fingerL1.addBox(-1.0f, 0.0f, -1.0f, 2, 4, 2, 0.0f);
        this.setRotateAngle(this.fingerL1, 0.0f, 0.0f, 0.6981317f);
        this.KneeR = new ModelRenderer((ModelBase)this, 20, 106);
        this.KneeR.setRotationPoint(0.1f, 1.6f, 0.0f);
        this.KneeR.addBox(-1.0f, -2.7f, -3.0f, 2, 3, 2, 0.0f);
        this.Leg2L = new ModelRenderer((ModelBase)this, 20, 88);
        this.Leg2L.mirror = true;
        this.Leg2L.setRotationPoint(0.0f, 1.6f, 0.0f);
        this.Leg2L.addBox(-1.5f, -0.1f, -1.0f, 3, 6, 2, 0.0f);
        this.setRotateAngle(this.Leg2L, -0.6981317f, -0.06981317f, 0.0f);
        this.BodyR = new ModelRenderer((ModelBase)this, 97, 32);
        this.BodyR.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.BodyR.addBox(-16.0f, -17.0f, -6.5f, 7, 15, 14, 0.0f);
        this.FootR = new ModelRenderer((ModelBase)this, 1, 113);
        this.FootR.setRotationPoint(0.0f, 9.0f, 0.0f);
        this.FootR.addBox(-2.0f, -0.1f, -6.0f, 4, 2, 11, 0.0f);
        this.Leg1R = new ModelRenderer((ModelBase)this, 3, 90);
        this.Leg1R.setRotationPoint(-8.0f, 7.4f, 1.5f);
        this.Leg1R.addBox(-2.0f, -1.5f, -1.5f, 4, 5, 3, 0.0f);
        this.ShoulderR = new ModelRenderer((ModelBase)this, 143, 36);
        this.ShoulderR.setRotationPoint(-15.0f, -15.2f, 0.5f);
        this.ShoulderR.addBox(-2.0f, -2.5f, -5.0f, 4, 11, 10, 0.0f);
        this.Body = new ModelRenderer((ModelBase)this, 0, 0);
        this.Body.setRotationPoint(0.0f, 1.0f, 0.0f);
        this.Body.addBox(-9.0f, -18.7f, -7.4f, 18, 24, 17, 0.0f);
        this.Leg1L = new ModelRenderer((ModelBase)this, 3, 90);
        this.Leg1L.mirror = true;
        this.Leg1L.setRotationPoint(8.0f, 7.4f, 1.5f);
        this.Leg1L.addBox(-2.0f, -1.5f, -1.5f, 4, 5, 3, 0.0f);
        this.Extra1 = new ModelRenderer((ModelBase)this, 110, 9);
        this.Extra1.setRotationPoint(-0.2f, 5.4f, -11.6f);
        this.Extra1.addBox(-3.8f, -0.5f, 0.5f, 1, 1, 4, 0.0f);
        this.setRotateAngle(this.Extra1, 0.5009095f, 0.0f, 0.0f);
        this.ArmL4 = new ModelRenderer((ModelBase)this, 81, 93);
        this.ArmL4.mirror = true;
        this.ArmL4.setRotationPoint(0.0f, 0.0f, 1.3f);
        this.ArmL4.addBox(0.7f, -1.9f, -1.9f, 2, 6, 3, 0.0f);
        this.ArmR1 = new ModelRenderer((ModelBase)this, 70, 80);
        this.ArmR1.setRotationPoint(-16.2f, -13.0f, 0.0f);
        this.ArmR1.addBox(-0.7f, -1.5f, -1.5f, 3, 3, 3, 0.0f);
        this.Back = new ModelRenderer((ModelBase)this, 149, 60);
        this.Back.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.Back.addBox(-4.5f, -17.4f, 9.5f, 9, 18, 5, 0.0f);
        this.ShoulderL = new ModelRenderer((ModelBase)this, 143, 36);
        this.ShoulderL.mirror = true;
        this.ShoulderL.setRotationPoint(15.0f, -15.2f, 0.5f);
        this.ShoulderL.addBox(-2.0f, -2.5f, -5.0f, 4, 11, 10, 0.0f);
        this.ArmL2 = new ModelRenderer((ModelBase)this, 70, 87);
        this.ArmL2.mirror = true;
        this.ArmL2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.ArmL2.addBox(-1.3f, -0.4f, -1.1f, 2, 12, 3, 0.0f);
        this.setRotateAngle(this.ArmL2, 0.11082841f, 0.0f, -0.5009095f);
        this.fingerR1.addChild(this.fingerR2);
        this.fingerR3.addChild(this.fingerR4);
        this.BodyBottom1.addChild(this.BodyBottom2);
        this.BodyBottomL.addChild(this.BodyBottomL2);
        this.fingerL3.addChild(this.fingerL4);
        this.Leg3L.addChild(this.FootL);
        this.BodyR.addChild(this.PlateR);
        this.ArmR4.addChild(this.handR);
        this.ArmR1.addChild(this.ArmR2);
        this.Body.addChild(this.BodyBack);
        this.ArmL4.addChild(this.handL);
        this.Body.addChild(this.BodyL);
        this.Head1.addChild(this.Head2);
        this.fingerL1.addChild(this.fingerL2);
        this.Leg2L.addChild(this.Leg3L);
        this.Leg3L.addChild(this.KneeL);
        this.BodyBottom1.addChild(this.BodyBottomL);
        this.Extra1.addChild(this.Extra3);
        this.handR.addChild(this.fingerR1);
        this.handR.addChild(this.fingerR3);
        this.ArmR2.addChild(this.ArmR3);
        this.BodyBottomR.addChild(this.BodyBottomR2);
        this.BodyBack.addChild(this.BodyBottom1);
        this.Body.addChild(this.Head1);
        this.Extra1.addChild(this.Extra2);
        this.BodyBottom1.addChild(this.BodyBottomR);
        this.ArmL2.addChild(this.ArmL3);
        this.Leg1R.addChild(this.Leg2R);
        this.BodyL.addChild(this.PlateL);
        this.handL.addChild(this.fingerL3);
        this.ArmR3.addChild(this.ArmR4);
        this.Leg2R.addChild(this.Leg3R);
        this.handL.addChild(this.fingerL1);
        this.Leg3R.addChild(this.KneeR);
        this.Leg1L.addChild(this.Leg2L);
        this.Body.addChild(this.BodyR);
        this.Leg3R.addChild(this.FootR);
        this.BodyR.addChild(this.ShoulderR);
        this.ArmL3.addChild(this.ArmL4);
        this.BodyBack.addChild(this.Back);
        this.BodyL.addChild(this.ShoulderL);
        this.ArmL1.addChild(this.ArmL2);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        GL11.glPushMatrix();
        float F = 1.6f;
        JGRenderHelper.modelScalePositionHelper((float)1.6f);
        this.Body.render(f5);
        this.ArmR1.render(f5);
        this.ArmL1.render(f5);
        this.Leg1L.render(f5);
        this.Leg1R.render(f5);
        this.Extra1.render(f5);
        GL11.glPopMatrix();
    }

    public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }

    public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity) {
        int calc = par7Entity.ticksExisted;
        if (calc > 100) {
            calc -= 100;
        }
        float r = 360.0f;
        float r2 = 180.0f;
        float n4 = par4;
        float n5 = par5;
        float ex = par7Entity.ticksExisted;
        float r3 = MathHelper.cos((float)(ex * 0.14f)) * 0.1f;
        float r4 = MathHelper.cos((float)(ex / 8.0f)) / 5.0f + 0.1f;
        r3 = MathHelper.cos((float)(ex * 0.14f)) * 0.1f;
        r4 = MathHelper.cos((float)(ex / 8.0f)) / 3.0f - 0.2f;
        this.Leg1R.rotateAngleX = -0.0f - MathHelper.cos((float)(par1 * 0.6662f)) * 1.2f * par2;
        this.Leg1L.rotateAngleX = -0.0f + MathHelper.cos((float)(par1 * 0.6662f)) * 1.2f * par2;
        this.ArmR1.rotateAngleX = -0.0f + MathHelper.cos((float)(par1 * 0.6662f)) * 1.2f * par2;
        this.ArmL1.rotateAngleX = -0.0f - MathHelper.cos((float)(par1 * 0.6662f)) * 1.2f * par2;
        this.Leg1R.rotateAngleY = 0.0f;
        this.Leg1L.rotateAngleY = 0.0f;
        this.ArmR1.rotateAngleY = 0.0f;
        this.ArmL1.rotateAngleY = 0.0f;
    }
}

