/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  JinRyuu.JRMCore.JRMCoreComTickH
 *  JinRyuu.JRMCore.JRMCoreH
 *  cpw.mods.fml.common.FMLCommonHandler
 *  net.minecraft.block.Block
 *  net.minecraft.init.Blocks
 *  net.minecraft.server.MinecraftServer
 *  net.minecraft.util.AxisAlignedBB
 *  net.minecraft.world.World
 */
package JinRyuu.DragonBC.common.Worlds.structures;

import JinRyuu.DragonBC.common.Blocks.BlocksDBC;
import JinRyuu.DragonBC.common.Villages.builds;
import JinRyuu.DragonBC.common.Worlds.WorldGeneratorDB;
import JinRyuu.DragonBC.common.mod_DragonBC;
import JinRyuu.JRMCore.JRMCoreComTickH;
import JinRyuu.JRMCore.JRMCoreH;
import cpw.mods.fml.common.FMLCommonHandler;
import java.util.List;
import java.util.Random;
import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.server.MinecraftServer;
import net.minecraft.util.AxisAlignedBB;
import net.minecraft.world.World;

public class StructureGuru
extends builds {
    final String name = "Guru Structure";
    public Block r = Blocks.wool;
    public Block db = BlocksDBC.BlockNamekStone;
    public Block g = Blocks.stained_glass;
    public final int glassID = 13;
    public final int woolID = 11;
    protected Block b73 = BlocksDBC.BlockNamekGrass;

    protected void b(World par1World, int par2, int par3, int par4, Block par5) {
        this.setBlockAndNotifyAdequately(par1World, par2, par3, par4, par5, 0);
    }

    protected void b(World par1World, int par2, int par3, int par4, Block par5, int par6) {
        this.setBlockAndNotifyAdequately(par1World, par2, par3, par4, par5, par6);
    }

    public StructureGuru() {
        SizeX = 30;
        SizeZ = 30;
    }

    @Override
    public boolean generate(World w, Random rand, int i, int j, int k) {
        this.w = w;
        SizeX = 30;
        SizeZ = 30;
        int gen = 4;
        WorldGeneratorDB.DBbuildsSpawn(gen, false);
        MinecraftServer server = FMLCommonHandler.instance().getMinecraftServerInstance();
        JRMCoreComTickH.bs = JRMCoreH.bsrwi((MinecraftServer)server);
        if (JRMCoreComTickH.bs.contains(WorldGeneratorDB.DBbuildsNams2(gen)) && !this.respawn) {
            return false;
        }
        JRMCoreComTickH.bs = JRMCoreComTickH.bs + ";" + WorldGeneratorDB.DBbuildsNams2(gen);
        JRMCoreH.bswwi((MinecraftServer)server, (String)JRMCoreComTickH.bs, (boolean)false);
        this.respawn = false;
        mod_DragonBC.logger.info(WorldGeneratorDB.DBbuildsNams(gen) + " spawned " + i + " " + k);
        return this.generateBuilding(w, rand, i, j, k);
    }

    @Override
    public boolean generateBuilding(World w, Random rand, int i, int j, int k) {
        if (!this.check) {
            for (int ix = 0; ix <= SizeX; ++ix) {
                for (int iz = 0; iz <= SizeZ; ++iz) {
                    int var = 0;
                    for (int iy = j; iy < j + 50; ++iy) {
                        ++var;
                        this.b(i + ix, iy, k + iz, Blocks.air);
                        if (iy >= j + 10) continue;
                        for (int var2 = 0; var2 < var; ++var2) {
                            this.b(i + ix + var2, iy, k + iz + var2, Blocks.air);
                            if (w.getBlock(i + ix + var2, iy - 1, k + iz + var2) != Blocks.air) {
                                this.b(i + ix + var2, iy - 1, k + iz + var2, this.b73);
                            }
                            this.b(i + ix - var2, iy, k + iz - var2, Blocks.air);
                            if (w.getBlock(i + ix - var2, iy - 1, k + iz - var2) != Blocks.air) {
                                this.b(i + ix - var2, iy - 1, k + iz - var2, this.b73);
                            }
                            this.b(i + ix, iy, k + iz + var2, Blocks.air);
                            if (w.getBlock(i + ix, iy - 1, k + iz + var2) != Blocks.air) {
                                this.b(i + ix, iy - 1, k + iz + var2, this.b73);
                            }
                            this.b(i + ix, iy, k + iz - var2, Blocks.air);
                            if (w.getBlock(i + ix, iy - 1, k + iz - var2) != Blocks.air) {
                                this.b(i + ix, iy - 1, k + iz - var2, this.b73);
                            }
                            this.b(i + ix + var2, iy, k + iz, Blocks.air);
                            if (w.getBlock(i + ix + var2, iy - 1, k + iz) != Blocks.air) {
                                this.b(i + ix + var2, iy - 1, k + iz, this.b73);
                            }
                            this.b(i + ix - var2, iy, k + iz, Blocks.air);
                            if (w.getBlock(i + ix - var2, iy - 1, k + iz) == Blocks.air) continue;
                            this.b(i + ix - var2, iy - 1, k + iz, this.b73);
                        }
                    }
                }
            }
        }
        this.b(w, i + 0, j + 0, k + 7, this.db);
        this.b(w, i + 0, j + 0, k + 8, this.db);
        this.b(w, i + 0, j + 0, k + 9, this.db);
        this.b(w, i + 0, j + 0, k + 10, this.db);
        this.b(w, i + 0, j + 0, k + 11, this.db);
        this.b(w, i + 0, j + 0, k + 12, this.db);
        this.b(w, i + 0, j + 0, k + 13, this.db);
        this.b(w, i + 0, j + 1, k + 7, this.db);
        this.b(w, i + 0, j + 1, k + 8, this.db);
        this.b(w, i + 0, j + 1, k + 9, this.db);
        this.b(w, i + 0, j + 1, k + 10, this.db);
        this.b(w, i + 0, j + 1, k + 11, this.db);
        this.b(w, i + 0, j + 1, k + 12, this.db);
        this.b(w, i + 0, j + 1, k + 13, this.db);
        this.b(w, i + 0, j + 2, k + 7, this.g, 13);
        this.b(w, i + 0, j + 2, k + 8, this.db);
        this.b(w, i + 0, j + 2, k + 9, this.db);
        this.b(w, i + 0, j + 2, k + 10, this.g, 13);
        this.b(w, i + 0, j + 2, k + 11, this.db);
        this.b(w, i + 0, j + 2, k + 12, this.db);
        this.b(w, i + 0, j + 2, k + 13, this.g, 13);
        this.b(w, i + 0, j + 3, k + 7, this.db);
        this.b(w, i + 0, j + 3, k + 8, this.db);
        this.b(w, i + 0, j + 3, k + 9, this.db);
        this.b(w, i + 0, j + 3, k + 10, this.db);
        this.b(w, i + 0, j + 3, k + 11, this.db);
        this.b(w, i + 0, j + 3, k + 12, this.db);
        this.b(w, i + 0, j + 3, k + 13, this.db);
        this.b(w, i + 1, j + 0, k + 6, this.db);
        this.b(w, i + 1, j + 0, k + 7, this.r, 11);
        this.b(w, i + 1, j + 0, k + 8, this.r, 11);
        this.b(w, i + 1, j + 0, k + 9, this.r, 11);
        this.b(w, i + 1, j + 0, k + 10, this.r, 11);
        this.b(w, i + 1, j + 0, k + 11, this.r, 11);
        this.b(w, i + 1, j + 0, k + 12, this.r, 11);
        this.b(w, i + 1, j + 0, k + 13, this.r, 11);
        this.b(w, i + 1, j + 0, k + 14, this.db);
        this.b(w, i + 1, j + 1, k + 6, this.db);
        this.b(w, i + 1, j + 1, k + 14, this.db);
        this.b(w, i + 1, j + 2, k + 6, this.g, 13);
        this.b(w, i + 1, j + 2, k + 14, this.g, 13);
        this.b(w, i + 1, j + 3, k + 6, this.db);
        this.b(w, i + 1, j + 3, k + 7, this.db);
        this.b(w, i + 1, j + 3, k + 8, this.db);
        this.b(w, i + 1, j + 3, k + 9, this.db);
        this.b(w, i + 1, j + 3, k + 10, this.db);
        this.b(w, i + 1, j + 3, k + 11, this.db);
        this.b(w, i + 1, j + 3, k + 12, this.db);
        this.b(w, i + 1, j + 3, k + 13, this.db);
        this.b(w, i + 1, j + 3, k + 14, this.db);
        this.b(w, i + 1, j + 4, k + 7, this.db);
        this.b(w, i + 1, j + 4, k + 8, this.db);
        this.b(w, i + 1, j + 4, k + 9, this.db);
        this.b(w, i + 1, j + 4, k + 10, this.db);
        this.b(w, i + 1, j + 4, k + 11, this.db);
        this.b(w, i + 1, j + 4, k + 12, this.db);
        this.b(w, i + 1, j + 4, k + 13, this.db);
        this.b(w, i + 2, j + 0, k + 5, this.db);
        this.b(w, i + 2, j + 0, k + 6, this.r, 11);
        this.b(w, i + 2, j + 0, k + 7, this.r, 11);
        this.b(w, i + 2, j + 0, k + 8, this.r, 11);
        this.b(w, i + 2, j + 0, k + 9, this.r, 11);
        this.b(w, i + 2, j + 0, k + 10, this.r, 11);
        this.b(w, i + 2, j + 0, k + 11, this.r, 11);
        this.b(w, i + 2, j + 0, k + 12, this.r, 11);
        this.b(w, i + 2, j + 0, k + 13, this.r, 11);
        this.b(w, i + 2, j + 0, k + 14, this.r, 11);
        this.b(w, i + 2, j + 0, k + 15, this.db);
        this.b(w, i + 2, j + 1, k + 5, this.db);
        this.b(w, i + 2, j + 1, k + 15, this.db);
        this.b(w, i + 2, j + 2, k + 5, this.db);
        this.b(w, i + 2, j + 2, k + 15, this.db);
        this.b(w, i + 2, j + 3, k + 5, this.db);
        this.b(w, i + 2, j + 3, k + 6, this.db);
        this.b(w, i + 2, j + 3, k + 14, this.db);
        this.b(w, i + 2, j + 3, k + 15, this.db);
        this.b(w, i + 2, j + 4, k + 6, this.db);
        this.b(w, i + 2, j + 4, k + 7, this.r, 11);
        this.b(w, i + 2, j + 4, k + 8, this.r, 11);
        this.b(w, i + 2, j + 4, k + 9, this.r, 11);
        this.b(w, i + 2, j + 4, k + 10, this.r, 11);
        this.b(w, i + 2, j + 4, k + 11, this.r, 11);
        this.b(w, i + 2, j + 4, k + 12, this.r, 11);
        this.b(w, i + 2, j + 4, k + 13, this.r, 11);
        this.b(w, i + 2, j + 4, k + 14, this.db);
        this.b(w, i + 2, j + 5, k + 7, this.db);
        this.b(w, i + 2, j + 5, k + 8, this.db);
        this.b(w, i + 2, j + 5, k + 9, this.db);
        this.b(w, i + 2, j + 5, k + 10, this.db);
        this.b(w, i + 2, j + 5, k + 11, this.db);
        this.b(w, i + 2, j + 5, k + 12, this.db);
        this.b(w, i + 2, j + 5, k + 13, this.db);
        this.b(w, i + 3, j + 0, k + 5, this.db);
        this.b(w, i + 3, j + 0, k + 6, this.r, 11);
        this.b(w, i + 3, j + 0, k + 7, this.r, 11);
        this.b(w, i + 3, j + 0, k + 8, this.r, 11);
        this.b(w, i + 3, j + 0, k + 9, this.r, 11);
        this.b(w, i + 3, j + 0, k + 10, this.r, 11);
        this.b(w, i + 3, j + 0, k + 11, this.r, 11);
        this.b(w, i + 3, j + 0, k + 12, this.r, 11);
        this.b(w, i + 3, j + 0, k + 13, this.r, 11);
        this.b(w, i + 3, j + 0, k + 14, this.r, 11);
        this.b(w, i + 3, j + 0, k + 15, this.db);
        this.b(w, i + 3, j + 1, k + 5, this.db);
        this.b(w, i + 3, j + 1, k + 15, this.db);
        this.b(w, i + 3, j + 2, k + 5, this.db);
        this.b(w, i + 3, j + 2, k + 15, this.db);
        this.b(w, i + 3, j + 3, k + 5, this.db);
        this.b(w, i + 3, j + 3, k + 14, this.db);
        this.b(w, i + 3, j + 3, k + 15, this.db);
        this.b(w, i + 3, j + 4, k + 5, this.db);
        this.b(w, i + 3, j + 4, k + 6, this.r, 11);
        this.b(w, i + 3, j + 4, k + 7, this.r, 11);
        this.b(w, i + 3, j + 4, k + 8, this.r, 11);
        this.b(w, i + 3, j + 4, k + 9, this.r, 11);
        this.b(w, i + 3, j + 4, k + 10, this.r, 11);
        this.b(w, i + 3, j + 4, k + 11, this.r, 11);
        this.b(w, i + 3, j + 4, k + 12, this.r, 11);
        this.b(w, i + 3, j + 4, k + 13, this.r, 11);
        this.b(w, i + 3, j + 4, k + 14, this.db);
        this.b(w, i + 3, j + 5, k + 6, this.db);
        this.b(w, i + 3, j + 5, k + 7, this.db);
        this.b(w, i + 3, j + 5, k + 8, this.db);
        this.b(w, i + 3, j + 5, k + 9, this.db);
        this.b(w, i + 3, j + 5, k + 10, this.db);
        this.b(w, i + 3, j + 5, k + 11, this.db);
        this.b(w, i + 3, j + 5, k + 12, this.db);
        this.b(w, i + 3, j + 5, k + 13, this.db);
        this.b(w, i + 4, j + 0, k + 2, this.db);
        this.b(w, i + 4, j + 0, k + 3, this.db);
        this.b(w, i + 4, j + 0, k + 4, this.db);
        this.b(w, i + 4, j + 0, k + 5, this.r, 11);
        this.b(w, i + 4, j + 0, k + 6, this.r, 11);
        this.b(w, i + 4, j + 0, k + 7, this.r, 11);
        this.b(w, i + 4, j + 0, k + 8, this.r, 11);
        this.b(w, i + 4, j + 0, k + 9, this.r, 11);
        this.b(w, i + 4, j + 0, k + 10, this.r, 11);
        this.b(w, i + 4, j + 0, k + 11, this.r, 11);
        this.b(w, i + 4, j + 0, k + 12, this.r, 11);
        this.b(w, i + 4, j + 0, k + 13, this.r, 11);
        this.b(w, i + 4, j + 0, k + 14, this.r, 11);
        this.b(w, i + 4, j + 0, k + 15, this.r, 11);
        this.b(w, i + 4, j + 0, k + 16, this.db);
        this.b(w, i + 4, j + 0, k + 17, this.db);
        this.b(w, i + 4, j + 1, k + 2, this.db);
        this.b(w, i + 4, j + 1, k + 3, this.db);
        this.b(w, i + 4, j + 1, k + 4, this.db);
        this.b(w, i + 4, j + 1, k + 16, this.db);
        this.b(w, i + 4, j + 1, k + 17, this.db);
        this.b(w, i + 4, j + 2, k + 2, this.db);
        this.b(w, i + 4, j + 2, k + 3, this.db);
        this.b(w, i + 4, j + 2, k + 4, this.db);
        this.b(w, i + 4, j + 2, k + 16, this.db);
        this.b(w, i + 4, j + 2, k + 17, this.g, 13);
        this.b(w, i + 4, j + 3, k + 3, this.db);
        this.b(w, i + 4, j + 3, k + 4, this.db);
        this.b(w, i + 4, j + 3, k + 5, this.db);
        this.b(w, i + 4, j + 3, k + 15, this.db);
        this.b(w, i + 4, j + 3, k + 16, this.db);
        this.b(w, i + 4, j + 3, k + 17, this.db);
        this.b(w, i + 4, j + 4, k + 4, this.db);
        this.b(w, i + 4, j + 4, k + 5, this.db);
        this.b(w, i + 4, j + 4, k + 6, this.r, 11);
        this.b(w, i + 4, j + 4, k + 7, this.r, 11);
        this.b(w, i + 4, j + 4, k + 8, this.r, 11);
        this.b(w, i + 4, j + 4, k + 9, this.r, 11);
        this.b(w, i + 4, j + 4, k + 10, this.r, 11);
        this.b(w, i + 4, j + 4, k + 11, this.r, 11);
        this.b(w, i + 4, j + 4, k + 12, this.r, 11);
        this.b(w, i + 4, j + 4, k + 13, this.r, 11);
        this.b(w, i + 4, j + 4, k + 14, this.r, 11);
        this.b(w, i + 4, j + 4, k + 15, this.db);
        this.b(w, i + 4, j + 5, k + 6, this.db);
        this.b(w, i + 4, j + 5, k + 7, this.db);
        this.b(w, i + 4, j + 5, k + 8, this.db);
        this.b(w, i + 4, j + 5, k + 9, this.db);
        this.b(w, i + 4, j + 5, k + 10, this.db);
        this.b(w, i + 4, j + 5, k + 11, this.db);
        this.b(w, i + 4, j + 5, k + 12, this.db);
        this.b(w, i + 4, j + 5, k + 13, this.db);
        this.b(w, i + 4, j + 5, k + 14, this.db);
        this.b(w, i + 4, j + 6, k + 8, this.db);
        this.b(w, i + 4, j + 6, k + 9, this.db);
        this.b(w, i + 4, j + 6, k + 10, this.db);
        this.b(w, i + 4, j + 6, k + 11, this.db);
        this.b(w, i + 4, j + 6, k + 12, this.db);
        this.b(w, i + 4, j + 7, k + 9, this.db);
        this.b(w, i + 4, j + 7, k + 10, this.db);
        this.b(w, i + 4, j + 7, k + 11, this.db);
        this.b(w, i + 4, j + 9, k + 11, this.db);
        this.b(w, i + 4, j + 10, k + 11, this.db);
        this.b(w, i + 4, j + 11, k + 11, this.db);
        this.b(w, i + 5, j + 0, k + 1, this.db);
        this.b(w, i + 5, j + 0, k + 2, this.r, 11);
        this.b(w, i + 5, j + 0, k + 3, this.r, 11);
        this.b(w, i + 5, j + 0, k + 4, this.r, 11);
        this.b(w, i + 5, j + 0, k + 5, this.r, 11);
        this.b(w, i + 5, j + 0, k + 6, this.r, 11);
        this.b(w, i + 5, j + 0, k + 7, this.r, 11);
        this.b(w, i + 5, j + 0, k + 8, this.r, 11);
        this.b(w, i + 5, j + 0, k + 9, this.r, 11);
        this.b(w, i + 5, j + 0, k + 10, this.r, 11);
        this.b(w, i + 5, j + 0, k + 11, this.r, 11);
        this.b(w, i + 5, j + 0, k + 12, this.r, 11);
        this.b(w, i + 5, j + 0, k + 13, this.r, 11);
        this.b(w, i + 5, j + 0, k + 14, this.r, 11);
        this.b(w, i + 5, j + 0, k + 15, this.r, 11);
        this.b(w, i + 5, j + 0, k + 16, this.r, 11);
        this.b(w, i + 5, j + 0, k + 17, this.r, 11);
        this.b(w, i + 5, j + 0, k + 18, this.db);
        this.b(w, i + 5, j + 1, k + 1, this.db);
        this.b(w, i + 5, j + 1, k + 18, this.db);
        this.b(w, i + 5, j + 2, k + 1, this.db);
        this.b(w, i + 5, j + 2, k + 18, this.g, 13);
        this.b(w, i + 5, j + 3, k + 2, this.db);
        this.b(w, i + 5, j + 3, k + 3, this.db);
        this.b(w, i + 5, j + 3, k + 16, this.db);
        this.b(w, i + 5, j + 3, k + 17, this.db);
        this.b(w, i + 5, j + 3, k + 18, this.db);
        this.b(w, i + 5, j + 4, k + 3, this.db);
        this.b(w, i + 5, j + 4, k + 4, this.r, 11);
        this.b(w, i + 5, j + 4, k + 5, this.r, 11);
        this.b(w, i + 5, j + 4, k + 6, this.r, 11);
        this.b(w, i + 5, j + 4, k + 7, this.r, 11);
        this.b(w, i + 5, j + 4, k + 8, this.r, 11);
        this.b(w, i + 5, j + 4, k + 9, this.r, 11);
        this.b(w, i + 5, j + 4, k + 10, this.r, 11);
        this.b(w, i + 5, j + 4, k + 11, this.r, 11);
        this.b(w, i + 5, j + 4, k + 12, this.r, 11);
        this.b(w, i + 5, j + 4, k + 13, this.r, 11);
        this.b(w, i + 5, j + 4, k + 14, this.r, 11);
        this.b(w, i + 5, j + 4, k + 15, this.r, 11);
        this.b(w, i + 5, j + 4, k + 16, this.db);
        this.b(w, i + 5, j + 5, k + 4, this.db);
        this.b(w, i + 5, j + 5, k + 5, this.db);
        this.b(w, i + 5, j + 5, k + 6, this.db);
        this.b(w, i + 5, j + 5, k + 7, this.db);
        this.b(w, i + 5, j + 5, k + 8, this.db);
        this.b(w, i + 5, j + 5, k + 12, this.db);
        this.b(w, i + 5, j + 5, k + 13, this.db);
        this.b(w, i + 5, j + 5, k + 14, this.db);
        this.b(w, i + 5, j + 5, k + 15, this.db);
        this.b(w, i + 5, j + 6, k + 8, this.db);
        this.b(w, i + 5, j + 6, k + 12, this.g, 13);
        this.b(w, i + 5, j + 7, k + 8, this.db);
        this.b(w, i + 5, j + 7, k + 12, this.db);
        this.b(w, i + 5, j + 8, k + 9, this.db);
        this.b(w, i + 5, j + 8, k + 10, this.db);
        this.b(w, i + 5, j + 8, k + 11, this.db);
        this.b(w, i + 5, j + 9, k + 11, this.db);
        this.b(w, i + 6, j + 0, k + 0, this.db);
        this.b(w, i + 6, j + 0, k + 1, this.r, 11);
        this.b(w, i + 6, j + 0, k + 2, this.r, 11);
        this.b(w, i + 6, j + 0, k + 3, this.r, 11);
        this.b(w, i + 6, j + 0, k + 4, this.r, 11);
        this.b(w, i + 6, j + 0, k + 5, this.r, 11);
        this.b(w, i + 6, j + 0, k + 6, this.r, 11);
        this.b(w, i + 6, j + 0, k + 7, this.r, 11);
        this.b(w, i + 6, j + 0, k + 8, this.r, 11);
        this.b(w, i + 6, j + 0, k + 9, this.r, 11);
        this.b(w, i + 6, j + 0, k + 10, this.r, 11);
        this.b(w, i + 6, j + 0, k + 11, this.r, 11);
        this.b(w, i + 6, j + 0, k + 12, this.r, 11);
        this.b(w, i + 6, j + 0, k + 13, this.r, 11);
        this.b(w, i + 6, j + 0, k + 14, this.r, 11);
        this.b(w, i + 6, j + 0, k + 15, this.r, 11);
        this.b(w, i + 6, j + 0, k + 16, this.r, 11);
        this.b(w, i + 6, j + 0, k + 17, this.r, 11);
        this.b(w, i + 6, j + 0, k + 18, this.r, 11);
        this.b(w, i + 6, j + 0, k + 19, this.db);
        this.b(w, i + 6, j + 1, k + 0, this.db);
        this.b(w, i + 6, j + 1, k + 19, this.db);
        this.b(w, i + 6, j + 2, k + 0, this.db);
        this.b(w, i + 6, j + 2, k + 19, this.db);
        this.b(w, i + 6, j + 3, k + 0, this.db);
        this.b(w, i + 6, j + 3, k + 1, this.db);
        this.b(w, i + 6, j + 3, k + 2, this.db);
        this.b(w, i + 6, j + 3, k + 18, this.db);
        this.b(w, i + 6, j + 4, k + 2, this.db);
        this.b(w, i + 6, j + 4, k + 3, this.r, 11);
        this.b(w, i + 6, j + 4, k + 4, this.r, 11);
        this.b(w, i + 6, j + 4, k + 5, this.r, 11);
        this.b(w, i + 6, j + 4, k + 6, this.r, 11);
        this.b(w, i + 6, j + 4, k + 7, this.r, 11);
        this.b(w, i + 6, j + 4, k + 8, this.r, 11);
        this.b(w, i + 6, j + 4, k + 9, this.r, 11);
        this.b(w, i + 6, j + 4, k + 10, this.r, 11);
        this.b(w, i + 6, j + 4, k + 11, this.r, 11);
        this.b(w, i + 6, j + 4, k + 12, this.r, 11);
        this.b(w, i + 6, j + 4, k + 13, this.r, 11);
        this.b(w, i + 6, j + 4, k + 14, this.r, 11);
        this.b(w, i + 6, j + 4, k + 15, this.r, 11);
        this.b(w, i + 6, j + 4, k + 16, this.r, 11);
        this.b(w, i + 6, j + 4, k + 17, this.db);
        this.b(w, i + 6, j + 5, k + 3, this.db);
        this.b(w, i + 6, j + 5, k + 4, this.db);
        this.b(w, i + 6, j + 5, k + 5, this.db);
        this.b(w, i + 6, j + 5, k + 6, this.db);
        this.b(w, i + 6, j + 5, k + 7, this.db);
        this.b(w, i + 6, j + 5, k + 13, this.db);
        this.b(w, i + 6, j + 5, k + 14, this.db);
        this.b(w, i + 6, j + 5, k + 15, this.db);
        this.b(w, i + 6, j + 5, k + 16, this.db);
        this.b(w, i + 6, j + 6, k + 7, this.db);
        this.b(w, i + 6, j + 6, k + 13, this.g, 13);
        this.b(w, i + 6, j + 6, k + 14, this.db);
        this.b(w, i + 6, j + 6, k + 15, this.db);
        this.b(w, i + 6, j + 7, k + 7, this.db);
        this.b(w, i + 6, j + 7, k + 12, this.db);
        this.b(w, i + 6, j + 7, k + 13, this.db);
        this.b(w, i + 6, j + 7, k + 14, this.db);
        this.b(w, i + 6, j + 8, k + 8, this.db);
        this.b(w, i + 6, j + 8, k + 9, this.db);
        this.b(w, i + 6, j + 8, k + 10, this.db);
        this.b(w, i + 6, j + 8, k + 11, this.db);
        this.b(w, i + 6, j + 8, k + 12, this.db);
        this.b(w, i + 6, j + 8, k + 13, this.db);
        this.b(w, i + 7, j + 0, k + 0, this.db);
        this.b(w, i + 7, j + 0, k + 1, this.r, 11);
        this.b(w, i + 7, j + 0, k + 2, this.r, 11);
        this.b(w, i + 7, j + 0, k + 3, this.r, 11);
        this.b(w, i + 7, j + 0, k + 4, this.r, 11);
        this.b(w, i + 7, j + 0, k + 5, this.r, 11);
        this.b(w, i + 7, j + 0, k + 6, this.r, 11);
        this.b(w, i + 7, j + 0, k + 7, this.r, 11);
        this.b(w, i + 7, j + 0, k + 8, this.r, 11);
        this.b(w, i + 7, j + 0, k + 9, this.r, 11);
        this.b(w, i + 7, j + 0, k + 10, this.r, 11);
        this.b(w, i + 7, j + 0, k + 11, this.r, 11);
        this.b(w, i + 7, j + 0, k + 12, this.r, 11);
        this.b(w, i + 7, j + 0, k + 13, this.r, 11);
        this.b(w, i + 7, j + 0, k + 14, this.r, 11);
        this.b(w, i + 7, j + 0, k + 15, this.r, 11);
        this.b(w, i + 7, j + 0, k + 16, this.r, 11);
        this.b(w, i + 7, j + 0, k + 17, this.r, 11);
        this.b(w, i + 7, j + 0, k + 18, this.r, 11);
        this.b(w, i + 7, j + 0, k + 19, this.db);
        this.b(w, i + 7, j + 1, k + 0, this.db);
        this.b(w, i + 7, j + 1, k + 19, this.db);
        this.b(w, i + 7, j + 2, k + 0, this.db);
        this.b(w, i + 7, j + 2, k + 19, this.db);
        this.b(w, i + 7, j + 3, k + 0, this.db);
        this.b(w, i + 7, j + 3, k + 1, this.db);
        this.b(w, i + 7, j + 3, k + 19, this.db);
        this.b(w, i + 7, j + 4, k + 1, this.db);
        this.b(w, i + 7, j + 4, k + 2, this.r, 11);
        this.b(w, i + 7, j + 4, k + 3, this.r, 11);
        this.b(w, i + 7, j + 4, k + 4, this.r, 11);
        this.b(w, i + 7, j + 4, k + 5, this.r, 11);
        this.b(w, i + 7, j + 4, k + 6, this.r, 11);
        this.b(w, i + 7, j + 4, k + 7, this.r, 11);
        this.b(w, i + 7, j + 4, k + 8, this.r, 11);
        this.b(w, i + 7, j + 4, k + 9, this.r, 11);
        this.b(w, i + 7, j + 4, k + 10, this.r, 11);
        this.b(w, i + 7, j + 4, k + 11, this.r, 11);
        this.b(w, i + 7, j + 4, k + 12, this.r, 11);
        this.b(w, i + 7, j + 4, k + 13, this.r, 11);
        this.b(w, i + 7, j + 4, k + 16, this.r, 11);
        this.b(w, i + 7, j + 4, k + 17, this.db);
        this.b(w, i + 7, j + 4, k + 18, this.db);
        this.b(w, i + 7, j + 5, k + 2, this.db);
        this.b(w, i + 7, j + 5, k + 3, this.db);
        this.b(w, i + 7, j + 5, k + 4, this.db);
        this.b(w, i + 7, j + 5, k + 5, this.db);
        this.b(w, i + 7, j + 5, k + 6, this.db);
        this.b(w, i + 7, j + 5, k + 16, this.db);
        this.b(w, i + 7, j + 6, k + 6, this.db);
        this.b(w, i + 7, j + 6, k + 16, this.g, 13);
        this.b(w, i + 7, j + 7, k + 6, this.db);
        this.b(w, i + 7, j + 7, k + 15, this.g, 13);
        this.b(w, i + 7, j + 7, k + 16, this.g, 13);
        this.b(w, i + 7, j + 8, k + 7, this.db);
        this.b(w, i + 7, j + 8, k + 14, this.db);
        this.b(w, i + 7, j + 8, k + 15, this.g, 13);
        this.b(w, i + 7, j + 9, k + 8, this.db);
        this.b(w, i + 7, j + 9, k + 9, this.db);
        this.b(w, i + 7, j + 9, k + 10, this.db);
        this.b(w, i + 7, j + 9, k + 11, this.db);
        this.b(w, i + 7, j + 9, k + 12, this.db);
        this.b(w, i + 7, j + 9, k + 13, this.db);
        this.b(w, i + 8, j + 0, k + 0, this.db);
        this.b(w, i + 8, j + 0, k + 1, this.r, 11);
        this.b(w, i + 8, j + 0, k + 2, this.r, 11);
        this.b(w, i + 8, j + 0, k + 3, this.r, 11);
        this.b(w, i + 8, j + 0, k + 4, this.r, 11);
        this.b(w, i + 8, j + 0, k + 5, this.r, 11);
        this.b(w, i + 8, j + 0, k + 6, this.r, 11);
        this.b(w, i + 8, j + 0, k + 7, this.r, 11);
        this.b(w, i + 8, j + 0, k + 8, this.r, 11);
        this.b(w, i + 8, j + 0, k + 9, this.r, 11);
        this.b(w, i + 8, j + 0, k + 10, this.r, 11);
        this.b(w, i + 8, j + 0, k + 11, this.r, 11);
        this.b(w, i + 8, j + 0, k + 12, this.r, 11);
        this.b(w, i + 8, j + 0, k + 13, this.r, 11);
        this.b(w, i + 8, j + 0, k + 14, this.r, 11);
        this.b(w, i + 8, j + 0, k + 15, this.r, 11);
        this.b(w, i + 8, j + 0, k + 16, this.r, 11);
        this.b(w, i + 8, j + 0, k + 17, this.r, 11);
        this.b(w, i + 8, j + 0, k + 18, this.r, 11);
        this.b(w, i + 8, j + 0, k + 19, this.db);
        this.b(w, i + 8, j + 1, k + 0, this.db);
        this.b(w, i + 8, j + 2, k + 0, this.db);
        this.b(w, i + 8, j + 3, k + 0, this.db);
        this.b(w, i + 8, j + 3, k + 19, this.db);
        this.b(w, i + 8, j + 4, k + 0, this.db);
        this.b(w, i + 8, j + 4, k + 1, this.r, 11);
        this.b(w, i + 8, j + 4, k + 2, this.r, 11);
        this.b(w, i + 8, j + 4, k + 3, this.r, 11);
        this.b(w, i + 8, j + 4, k + 4, this.r, 11);
        this.b(w, i + 8, j + 4, k + 5, this.r, 11);
        this.b(w, i + 8, j + 4, k + 6, this.r, 11);
        this.b(w, i + 8, j + 4, k + 7, this.r, 11);
        this.b(w, i + 8, j + 4, k + 8, this.r, 11);
        this.b(w, i + 8, j + 4, k + 9, this.r, 11);
        this.b(w, i + 8, j + 4, k + 10, this.r, 11);
        this.b(w, i + 8, j + 4, k + 11, this.r, 11);
        this.b(w, i + 8, j + 4, k + 12, this.r, 11);
        this.b(w, i + 8, j + 4, k + 13, this.r, 11);
        this.b(w, i + 8, j + 4, k + 16, this.r, 11);
        this.b(w, i + 8, j + 4, k + 17, this.db);
        this.b(w, i + 8, j + 4, k + 18, this.db);
        this.b(w, i + 8, j + 5, k + 1, this.db);
        this.b(w, i + 8, j + 5, k + 2, this.db);
        this.b(w, i + 8, j + 5, k + 3, this.db);
        this.b(w, i + 8, j + 5, k + 4, this.db);
        this.b(w, i + 8, j + 5, k + 5, this.db);
        this.b(w, i + 8, j + 5, k + 6, this.db);
        this.b(w, i + 8, j + 5, k + 16, this.db);
        this.b(w, i + 8, j + 6, k + 6, this.db);
        this.b(w, i + 8, j + 6, k + 16, this.g, 13);
        this.b(w, i + 8, j + 7, k + 6, this.db);
        this.b(w, i + 8, j + 7, k + 16, this.g, 13);
        this.b(w, i + 8, j + 8, k + 7, this.db);
        this.b(w, i + 8, j + 8, k + 14, this.db);
        this.b(w, i + 8, j + 8, k + 15, this.g, 13);
        this.b(w, i + 8, j + 9, k + 7, this.db);
        this.b(w, i + 8, j + 9, k + 8, this.db);
        this.b(w, i + 8, j + 9, k + 9, this.db);
        this.b(w, i + 8, j + 9, k + 10, this.db);
        this.b(w, i + 8, j + 9, k + 11, this.db);
        this.b(w, i + 8, j + 9, k + 12, this.db);
        this.b(w, i + 8, j + 9, k + 13, this.db);
        this.b(w, i + 9, j + 0, k + 0, this.db);
        this.b(w, i + 9, j + 0, k + 1, this.r, 11);
        this.b(w, i + 9, j + 0, k + 2, this.r, 11);
        this.b(w, i + 9, j + 0, k + 3, this.r, 11);
        this.b(w, i + 9, j + 0, k + 4, this.r, 11);
        this.b(w, i + 9, j + 0, k + 5, this.r, 11);
        this.b(w, i + 9, j + 0, k + 6, this.r, 11);
        this.b(w, i + 9, j + 0, k + 7, this.r, 11);
        this.b(w, i + 9, j + 0, k + 8, this.r, 11);
        this.b(w, i + 9, j + 0, k + 9, this.r, 11);
        this.b(w, i + 9, j + 0, k + 10, this.r, 11);
        this.b(w, i + 9, j + 0, k + 11, this.r, 11);
        this.b(w, i + 9, j + 0, k + 12, this.r, 11);
        this.b(w, i + 9, j + 0, k + 13, this.r, 11);
        this.b(w, i + 9, j + 0, k + 14, this.r, 11);
        this.b(w, i + 9, j + 0, k + 15, this.r, 11);
        this.b(w, i + 9, j + 0, k + 16, this.r, 11);
        this.b(w, i + 9, j + 0, k + 17, this.r, 11);
        this.b(w, i + 9, j + 0, k + 18, this.r, 11);
        this.b(w, i + 9, j + 0, k + 19, this.db);
        this.b(w, i + 9, j + 1, k + 0, this.db);
        this.b(w, i + 9, j + 1, k + 19, this.db);
        this.b(w, i + 9, j + 2, k + 0, this.db);
        this.b(w, i + 9, j + 2, k + 19, this.db);
        this.b(w, i + 9, j + 3, k + 0, this.db);
        this.b(w, i + 9, j + 3, k + 1, this.db);
        this.b(w, i + 9, j + 3, k + 19, this.db);
        this.b(w, i + 9, j + 4, k + 1, this.db);
        this.b(w, i + 9, j + 4, k + 2, this.r, 11);
        this.b(w, i + 9, j + 4, k + 3, this.r, 11);
        this.b(w, i + 9, j + 4, k + 4, this.r, 11);
        this.b(w, i + 9, j + 4, k + 5, this.r, 11);
        this.b(w, i + 9, j + 4, k + 6, this.r, 11);
        this.b(w, i + 9, j + 4, k + 7, this.r, 11);
        this.b(w, i + 9, j + 4, k + 8, this.r, 11);
        this.b(w, i + 9, j + 4, k + 9, this.r, 11);
        this.b(w, i + 9, j + 4, k + 10, this.r, 11);
        this.b(w, i + 9, j + 4, k + 11, this.r, 11);
        this.b(w, i + 9, j + 4, k + 12, this.r, 11);
        this.b(w, i + 9, j + 4, k + 13, this.r, 11);
        this.b(w, i + 9, j + 4, k + 16, this.r, 11);
        this.b(w, i + 9, j + 4, k + 17, this.db);
        this.b(w, i + 9, j + 4, k + 18, this.db);
        this.b(w, i + 9, j + 5, k + 2, this.db);
        this.b(w, i + 9, j + 5, k + 3, this.db);
        this.b(w, i + 9, j + 5, k + 4, this.db);
        this.b(w, i + 9, j + 5, k + 5, this.db);
        this.b(w, i + 9, j + 5, k + 6, this.db);
        this.b(w, i + 9, j + 5, k + 16, this.db);
        this.b(w, i + 9, j + 6, k + 6, this.db);
        this.b(w, i + 9, j + 6, k + 16, this.g, 13);
        this.b(w, i + 9, j + 7, k + 6, this.db);
        this.b(w, i + 9, j + 7, k + 15, this.g, 13);
        this.b(w, i + 9, j + 7, k + 16, this.g, 13);
        this.b(w, i + 9, j + 8, k + 7, this.db);
        this.b(w, i + 9, j + 8, k + 14, this.db);
        this.b(w, i + 9, j + 8, k + 15, this.g, 13);
        this.b(w, i + 9, j + 9, k + 8, this.db);
        this.b(w, i + 9, j + 9, k + 9, this.db);
        this.b(w, i + 9, j + 9, k + 10, this.db);
        this.b(w, i + 9, j + 9, k + 11, this.db);
        this.b(w, i + 9, j + 9, k + 12, this.db);
        this.b(w, i + 9, j + 9, k + 13, this.db);
        this.b(w, i + 10, j + 0, k + 0, this.db);
        this.b(w, i + 10, j + 0, k + 1, this.r, 11);
        this.b(w, i + 10, j + 0, k + 2, this.r, 11);
        this.b(w, i + 10, j + 0, k + 3, this.r, 11);
        this.b(w, i + 10, j + 0, k + 4, this.r, 11);
        this.b(w, i + 10, j + 0, k + 5, this.r, 11);
        this.b(w, i + 10, j + 0, k + 6, this.r, 11);
        this.b(w, i + 10, j + 0, k + 7, this.r, 11);
        this.b(w, i + 10, j + 0, k + 8, this.r, 11);
        this.b(w, i + 10, j + 0, k + 9, this.r, 11);
        this.b(w, i + 10, j + 0, k + 10, this.r, 11);
        this.b(w, i + 10, j + 0, k + 11, this.r, 11);
        this.b(w, i + 10, j + 0, k + 12, this.r, 11);
        this.b(w, i + 10, j + 0, k + 13, this.r, 11);
        this.b(w, i + 10, j + 0, k + 14, this.r, 11);
        this.b(w, i + 10, j + 0, k + 15, this.r, 11);
        this.b(w, i + 10, j + 0, k + 16, this.r, 11);
        this.b(w, i + 10, j + 0, k + 17, this.r, 11);
        this.b(w, i + 10, j + 0, k + 18, this.r, 11);
        this.b(w, i + 10, j + 0, k + 19, this.db);
        this.b(w, i + 10, j + 1, k + 0, this.db);
        this.b(w, i + 10, j + 1, k + 19, this.db);
        this.b(w, i + 10, j + 2, k + 0, this.db);
        this.b(w, i + 10, j + 2, k + 19, this.db);
        this.b(w, i + 10, j + 3, k + 0, this.db);
        this.b(w, i + 10, j + 3, k + 1, this.db);
        this.b(w, i + 10, j + 3, k + 2, this.db);
        this.b(w, i + 10, j + 3, k + 18, this.db);
        this.b(w, i + 10, j + 4, k + 2, this.db);
        this.b(w, i + 10, j + 4, k + 3, this.r, 11);
        this.b(w, i + 10, j + 4, k + 4, this.r, 11);
        this.b(w, i + 10, j + 4, k + 5, this.r, 11);
        this.b(w, i + 10, j + 4, k + 6, this.r, 11);
        this.b(w, i + 10, j + 4, k + 7, this.r, 11);
        this.b(w, i + 10, j + 4, k + 8, this.r, 11);
        this.b(w, i + 10, j + 4, k + 9, this.r, 11);
        this.b(w, i + 10, j + 4, k + 10, this.r, 11);
        this.b(w, i + 10, j + 4, k + 11, this.r, 11);
        this.b(w, i + 10, j + 4, k + 12, this.r, 11);
        this.b(w, i + 10, j + 4, k + 13, this.r, 11);
        this.b(w, i + 10, j + 4, k + 14, this.r, 11);
        this.b(w, i + 10, j + 4, k + 15, this.r, 11);
        this.b(w, i + 10, j + 4, k + 16, this.r, 11);
        this.b(w, i + 10, j + 4, k + 17, this.db);
        this.b(w, i + 10, j + 5, k + 3, this.db);
        this.b(w, i + 10, j + 5, k + 4, this.db);
        this.b(w, i + 10, j + 5, k + 5, this.db);
        this.b(w, i + 10, j + 5, k + 6, this.db);
        this.b(w, i + 10, j + 5, k + 7, this.db);
        this.b(w, i + 10, j + 5, k + 13, this.db);
        this.b(w, i + 10, j + 5, k + 14, this.db);
        this.b(w, i + 10, j + 5, k + 15, this.db);
        this.b(w, i + 10, j + 5, k + 16, this.db);
        this.b(w, i + 10, j + 6, k + 7, this.db);
        this.b(w, i + 10, j + 6, k + 13, this.g, 13);
        this.b(w, i + 10, j + 6, k + 14, this.db);
        this.b(w, i + 10, j + 6, k + 15, this.db);
        this.b(w, i + 10, j + 7, k + 7, this.db);
        this.b(w, i + 10, j + 7, k + 12, this.db);
        this.b(w, i + 10, j + 7, k + 13, this.db);
        this.b(w, i + 10, j + 7, k + 14, this.db);
        this.b(w, i + 10, j + 8, k + 8, this.db);
        this.b(w, i + 10, j + 8, k + 9, this.db);
        this.b(w, i + 10, j + 8, k + 10, this.db);
        this.b(w, i + 10, j + 8, k + 11, this.db);
        this.b(w, i + 10, j + 8, k + 12, this.db);
        this.b(w, i + 10, j + 8, k + 13, this.db);
        this.b(w, i + 11, j + 0, k + 1, this.db);
        this.b(w, i + 11, j + 0, k + 2, this.r, 11);
        this.b(w, i + 11, j + 0, k + 3, this.r, 11);
        this.b(w, i + 11, j + 0, k + 4, this.r, 11);
        this.b(w, i + 11, j + 0, k + 5, this.r, 11);
        this.b(w, i + 11, j + 0, k + 6, this.r, 11);
        this.b(w, i + 11, j + 0, k + 7, this.r, 11);
        this.b(w, i + 11, j + 0, k + 8, this.r, 11);
        this.b(w, i + 11, j + 0, k + 9, this.r, 11);
        this.b(w, i + 11, j + 0, k + 10, this.r, 11);
        this.b(w, i + 11, j + 0, k + 11, this.r, 11);
        this.b(w, i + 11, j + 0, k + 12, this.r, 11);
        this.b(w, i + 11, j + 0, k + 13, this.r, 11);
        this.b(w, i + 11, j + 0, k + 14, this.r, 11);
        this.b(w, i + 11, j + 0, k + 15, this.r, 11);
        this.b(w, i + 11, j + 0, k + 16, this.r, 11);
        this.b(w, i + 11, j + 0, k + 17, this.r, 11);
        this.b(w, i + 11, j + 0, k + 18, this.db);
        this.b(w, i + 11, j + 1, k + 1, this.db);
        this.b(w, i + 11, j + 1, k + 18, this.db);
        this.b(w, i + 11, j + 2, k + 1, this.db);
        this.b(w, i + 11, j + 2, k + 18, this.g, 13);
        this.b(w, i + 11, j + 3, k + 2, this.db);
        this.b(w, i + 11, j + 3, k + 3, this.db);
        this.b(w, i + 11, j + 3, k + 16, this.db);
        this.b(w, i + 11, j + 3, k + 17, this.db);
        this.b(w, i + 11, j + 3, k + 18, this.db);
        this.b(w, i + 11, j + 4, k + 3, this.db);
        this.b(w, i + 11, j + 4, k + 4, this.r, 11);
        this.b(w, i + 11, j + 4, k + 5, this.r, 11);
        this.b(w, i + 11, j + 4, k + 6, this.r, 11);
        this.b(w, i + 11, j + 4, k + 7, this.r, 11);
        this.b(w, i + 11, j + 4, k + 8, this.r, 11);
        this.b(w, i + 11, j + 4, k + 9, this.r, 11);
        this.b(w, i + 11, j + 4, k + 10, this.r, 11);
        this.b(w, i + 11, j + 4, k + 11, this.r, 11);
        this.b(w, i + 11, j + 4, k + 12, this.r, 11);
        this.b(w, i + 11, j + 4, k + 13, this.r, 11);
        this.b(w, i + 11, j + 4, k + 14, this.r, 11);
        this.b(w, i + 11, j + 4, k + 15, this.r, 11);
        this.b(w, i + 11, j + 4, k + 16, this.db);
        this.b(w, i + 11, j + 5, k + 4, this.db);
        this.b(w, i + 11, j + 5, k + 5, this.db);
        this.b(w, i + 11, j + 5, k + 6, this.db);
        this.b(w, i + 11, j + 5, k + 7, this.db);
        this.b(w, i + 11, j + 5, k + 8, this.db);
        this.b(w, i + 11, j + 5, k + 12, this.db);
        this.b(w, i + 11, j + 5, k + 13, this.db);
        this.b(w, i + 11, j + 5, k + 14, this.db);
        this.b(w, i + 11, j + 5, k + 15, this.db);
        this.b(w, i + 11, j + 6, k + 8, this.db);
        this.b(w, i + 11, j + 6, k + 12, this.g, 13);
        this.b(w, i + 11, j + 7, k + 8, this.db);
        this.b(w, i + 11, j + 7, k + 12, this.db);
        this.b(w, i + 11, j + 8, k + 9, this.db);
        this.b(w, i + 11, j + 8, k + 10, this.db);
        this.b(w, i + 11, j + 8, k + 11, this.db);
        this.b(w, i + 11, j + 9, k + 11, this.db);
        this.b(w, i + 12, j + 0, k + 2, this.db);
        this.b(w, i + 12, j + 0, k + 3, this.db);
        this.b(w, i + 12, j + 0, k + 4, this.db);
        this.b(w, i + 12, j + 0, k + 5, this.r, 11);
        this.b(w, i + 12, j + 0, k + 6, this.r, 11);
        this.b(w, i + 12, j + 0, k + 7, this.r, 11);
        this.b(w, i + 12, j + 0, k + 8, this.r, 11);
        this.b(w, i + 12, j + 0, k + 9, this.r, 11);
        this.b(w, i + 12, j + 0, k + 10, this.r, 11);
        this.b(w, i + 12, j + 0, k + 11, this.r, 11);
        this.b(w, i + 12, j + 0, k + 12, this.r, 11);
        this.b(w, i + 12, j + 0, k + 13, this.r, 11);
        this.b(w, i + 12, j + 0, k + 14, this.r, 11);
        this.b(w, i + 12, j + 0, k + 15, this.r, 11);
        this.b(w, i + 12, j + 0, k + 16, this.db);
        this.b(w, i + 12, j + 0, k + 17, this.db);
        this.b(w, i + 12, j + 1, k + 2, this.db);
        this.b(w, i + 12, j + 1, k + 3, this.db);
        this.b(w, i + 12, j + 1, k + 4, this.db);
        this.b(w, i + 12, j + 1, k + 16, this.db);
        this.b(w, i + 12, j + 1, k + 17, this.db);
        this.b(w, i + 12, j + 2, k + 2, this.db);
        this.b(w, i + 12, j + 2, k + 3, this.db);
        this.b(w, i + 12, j + 2, k + 4, this.db);
        this.b(w, i + 12, j + 2, k + 16, this.db);
        this.b(w, i + 12, j + 2, k + 17, this.g, 13);
        this.b(w, i + 12, j + 3, k + 3, this.db);
        this.b(w, i + 12, j + 3, k + 4, this.db);
        this.b(w, i + 12, j + 3, k + 5, this.db);
        this.b(w, i + 12, j + 3, k + 15, this.db);
        this.b(w, i + 12, j + 3, k + 16, this.db);
        this.b(w, i + 12, j + 3, k + 17, this.db);
        this.b(w, i + 12, j + 4, k + 4, this.db);
        this.b(w, i + 12, j + 4, k + 5, this.db);
        this.b(w, i + 12, j + 4, k + 6, this.r, 11);
        this.b(w, i + 12, j + 4, k + 7, this.r, 11);
        this.b(w, i + 12, j + 4, k + 8, this.r, 11);
        this.b(w, i + 12, j + 4, k + 9, this.r, 11);
        this.b(w, i + 12, j + 4, k + 10, this.r, 11);
        this.b(w, i + 12, j + 4, k + 11, this.r, 11);
        this.b(w, i + 12, j + 4, k + 12, this.r, 11);
        this.b(w, i + 12, j + 4, k + 13, this.r, 11);
        this.b(w, i + 12, j + 4, k + 14, this.r, 11);
        this.b(w, i + 12, j + 4, k + 15, this.db);
        this.b(w, i + 12, j + 5, k + 6, this.db);
        this.b(w, i + 12, j + 5, k + 7, this.db);
        this.b(w, i + 12, j + 5, k + 8, this.db);
        this.b(w, i + 12, j + 5, k + 9, this.db);
        this.b(w, i + 12, j + 5, k + 10, this.db);
        this.b(w, i + 12, j + 5, k + 11, this.db);
        this.b(w, i + 12, j + 5, k + 12, this.db);
        this.b(w, i + 12, j + 5, k + 13, this.db);
        this.b(w, i + 12, j + 5, k + 14, this.db);
        this.b(w, i + 12, j + 6, k + 8, this.db);
        this.b(w, i + 12, j + 6, k + 9, this.db);
        this.b(w, i + 12, j + 6, k + 10, this.db);
        this.b(w, i + 12, j + 6, k + 11, this.db);
        this.b(w, i + 12, j + 6, k + 12, this.db);
        this.b(w, i + 12, j + 7, k + 9, this.db);
        this.b(w, i + 12, j + 7, k + 10, this.db);
        this.b(w, i + 12, j + 7, k + 11, this.db);
        this.b(w, i + 12, j + 9, k + 11, this.db);
        this.b(w, i + 12, j + 10, k + 11, this.db);
        this.b(w, i + 12, j + 11, k + 11, this.db);
        this.b(w, i + 13, j + 0, k + 5, this.db);
        this.b(w, i + 13, j + 0, k + 6, this.r, 11);
        this.b(w, i + 13, j + 0, k + 7, this.r, 11);
        this.b(w, i + 13, j + 0, k + 8, this.r, 11);
        this.b(w, i + 13, j + 0, k + 9, this.r, 11);
        this.b(w, i + 13, j + 0, k + 10, this.r, 11);
        this.b(w, i + 13, j + 0, k + 11, this.r, 11);
        this.b(w, i + 13, j + 0, k + 12, this.r, 11);
        this.b(w, i + 13, j + 0, k + 13, this.r, 11);
        this.b(w, i + 13, j + 0, k + 14, this.r, 11);
        this.b(w, i + 13, j + 0, k + 15, this.db);
        this.b(w, i + 13, j + 1, k + 5, this.db);
        this.b(w, i + 13, j + 1, k + 15, this.db);
        this.b(w, i + 13, j + 2, k + 5, this.db);
        this.b(w, i + 13, j + 2, k + 15, this.db);
        this.b(w, i + 13, j + 3, k + 5, this.db);
        this.b(w, i + 13, j + 3, k + 14, this.db);
        this.b(w, i + 13, j + 3, k + 15, this.db);
        this.b(w, i + 13, j + 4, k + 5, this.db);
        this.b(w, i + 13, j + 4, k + 6, this.r, 11);
        this.b(w, i + 13, j + 4, k + 7, this.r, 11);
        this.b(w, i + 13, j + 4, k + 8, this.r, 11);
        this.b(w, i + 13, j + 4, k + 9, this.r, 11);
        this.b(w, i + 13, j + 4, k + 10, this.r, 11);
        this.b(w, i + 13, j + 4, k + 11, this.r, 11);
        this.b(w, i + 13, j + 4, k + 12, this.r, 11);
        this.b(w, i + 13, j + 4, k + 13, this.r, 11);
        this.b(w, i + 13, j + 4, k + 14, this.db);
        this.b(w, i + 13, j + 5, k + 6, this.db);
        this.b(w, i + 13, j + 5, k + 7, this.db);
        this.b(w, i + 13, j + 5, k + 8, this.db);
        this.b(w, i + 13, j + 5, k + 9, this.db);
        this.b(w, i + 13, j + 5, k + 10, this.db);
        this.b(w, i + 13, j + 5, k + 11, this.db);
        this.b(w, i + 13, j + 5, k + 12, this.db);
        this.b(w, i + 13, j + 5, k + 13, this.db);
        this.b(w, i + 14, j + 0, k + 5, this.db);
        this.b(w, i + 14, j + 0, k + 6, this.r, 11);
        this.b(w, i + 14, j + 0, k + 7, this.r, 11);
        this.b(w, i + 14, j + 0, k + 8, this.r, 11);
        this.b(w, i + 14, j + 0, k + 9, this.r, 11);
        this.b(w, i + 14, j + 0, k + 10, this.r, 11);
        this.b(w, i + 14, j + 0, k + 11, this.r, 11);
        this.b(w, i + 14, j + 0, k + 12, this.r, 11);
        this.b(w, i + 14, j + 0, k + 13, this.r, 11);
        this.b(w, i + 14, j + 0, k + 14, this.r, 11);
        this.b(w, i + 14, j + 0, k + 15, this.db);
        this.b(w, i + 14, j + 1, k + 5, this.db);
        this.b(w, i + 14, j + 1, k + 15, this.db);
        this.b(w, i + 14, j + 2, k + 5, this.db);
        this.b(w, i + 14, j + 2, k + 15, this.db);
        this.b(w, i + 14, j + 3, k + 5, this.db);
        this.b(w, i + 14, j + 3, k + 6, this.db);
        this.b(w, i + 14, j + 3, k + 14, this.db);
        this.b(w, i + 14, j + 3, k + 15, this.db);
        this.b(w, i + 14, j + 4, k + 6, this.db);
        this.b(w, i + 14, j + 4, k + 7, this.r, 11);
        this.b(w, i + 14, j + 4, k + 8, this.r, 11);
        this.b(w, i + 14, j + 4, k + 9, this.r, 11);
        this.b(w, i + 14, j + 4, k + 10, this.r, 11);
        this.b(w, i + 14, j + 4, k + 11, this.r, 11);
        this.b(w, i + 14, j + 4, k + 12, this.r, 11);
        this.b(w, i + 14, j + 4, k + 13, this.r, 11);
        this.b(w, i + 14, j + 4, k + 14, this.db);
        this.b(w, i + 14, j + 5, k + 7, this.db);
        this.b(w, i + 14, j + 5, k + 8, this.db);
        this.b(w, i + 14, j + 5, k + 9, this.db);
        this.b(w, i + 14, j + 5, k + 10, this.db);
        this.b(w, i + 14, j + 5, k + 11, this.db);
        this.b(w, i + 14, j + 5, k + 12, this.db);
        this.b(w, i + 14, j + 5, k + 13, this.db);
        this.b(w, i + 15, j + 0, k + 6, this.db);
        this.b(w, i + 15, j + 0, k + 7, this.r, 11);
        this.b(w, i + 15, j + 0, k + 8, this.r, 11);
        this.b(w, i + 15, j + 0, k + 9, this.r, 11);
        this.b(w, i + 15, j + 0, k + 10, this.r, 11);
        this.b(w, i + 15, j + 0, k + 11, this.r, 11);
        this.b(w, i + 15, j + 0, k + 12, this.r, 11);
        this.b(w, i + 15, j + 0, k + 13, this.r, 11);
        this.b(w, i + 15, j + 0, k + 14, this.db);
        this.b(w, i + 15, j + 1, k + 6, this.db);
        this.b(w, i + 15, j + 1, k + 14, this.db);
        this.b(w, i + 15, j + 2, k + 6, this.g, 13);
        this.b(w, i + 15, j + 2, k + 14, this.g, 13);
        this.b(w, i + 15, j + 3, k + 6, this.db);
        this.b(w, i + 15, j + 3, k + 7, this.db);
        this.b(w, i + 15, j + 3, k + 8, this.db);
        this.b(w, i + 15, j + 3, k + 9, this.db);
        this.b(w, i + 15, j + 3, k + 10, this.db);
        this.b(w, i + 15, j + 3, k + 11, this.db);
        this.b(w, i + 15, j + 3, k + 12, this.db);
        this.b(w, i + 15, j + 3, k + 13, this.db);
        this.b(w, i + 15, j + 3, k + 14, this.db);
        this.b(w, i + 15, j + 4, k + 7, this.db);
        this.b(w, i + 15, j + 4, k + 8, this.db);
        this.b(w, i + 15, j + 4, k + 9, this.db);
        this.b(w, i + 15, j + 4, k + 10, this.db);
        this.b(w, i + 15, j + 4, k + 11, this.db);
        this.b(w, i + 15, j + 4, k + 12, this.db);
        this.b(w, i + 15, j + 4, k + 13, this.db);
        this.b(w, i + 16, j + 0, k + 7, this.db);
        this.b(w, i + 16, j + 0, k + 8, this.db);
        this.b(w, i + 16, j + 0, k + 9, this.db);
        this.b(w, i + 16, j + 0, k + 10, this.db);
        this.b(w, i + 16, j + 0, k + 11, this.db);
        this.b(w, i + 16, j + 0, k + 12, this.db);
        this.b(w, i + 16, j + 0, k + 13, this.db);
        this.b(w, i + 16, j + 1, k + 7, this.db);
        this.b(w, i + 16, j + 1, k + 8, this.db);
        this.b(w, i + 16, j + 1, k + 9, this.db);
        this.b(w, i + 16, j + 1, k + 10, this.db);
        this.b(w, i + 16, j + 1, k + 11, this.db);
        this.b(w, i + 16, j + 1, k + 12, this.db);
        this.b(w, i + 16, j + 1, k + 13, this.db);
        this.b(w, i + 16, j + 2, k + 7, this.g, 13);
        this.b(w, i + 16, j + 2, k + 8, this.db);
        this.b(w, i + 16, j + 2, k + 9, this.db);
        this.b(w, i + 16, j + 2, k + 10, this.g, 13);
        this.b(w, i + 16, j + 2, k + 11, this.db);
        this.b(w, i + 16, j + 2, k + 12, this.db);
        this.b(w, i + 16, j + 2, k + 13, this.g, 13);
        this.b(w, i + 16, j + 3, k + 7, this.db);
        this.b(w, i + 16, j + 3, k + 8, this.db);
        this.b(w, i + 16, j + 3, k + 9, this.db);
        this.b(w, i + 16, j + 3, k + 10, this.db);
        this.b(w, i + 16, j + 3, k + 11, this.db);
        this.b(w, i + 16, j + 3, k + 12, this.db);
        this.b(w, i + 16, j + 3, k + 13, this.db);
        double s2 = 50.0;
        AxisAlignedBB ab2 = AxisAlignedBB.getBoundingBox((double)i, (double)j, (double)k, (double)((double)i + s2), (double)((double)j + 1.0), (double)((double)k + s2));
        List list2 = w.func_147461_a(ab2);
        for (int i1 = 0; i1 < list2.size(); ++i1) {
            AxisAlignedBB b = (AxisAlignedBB)list2.get(i1);
            for (int i2 = j; i2 > 60; --i2) {
                if (w.getBlock((int)(b.minX + 0.0), i2, (int)(b.minZ + 0.0)) != Blocks.air && w.getBlock((int)(b.minX + 0.5), i2, (int)(b.minZ + 0.0)) != Blocks.tallgrass) continue;
                w.setBlock((int)(b.minX + 0.0), i2, (int)(b.minZ + 0.0), BlocksDBC.BlockNamekDirt);
            }
        }
        return true;
    }
}

